export const athleticProgram = {
  id: 'athletic-performance',
  name: 'CTC Athlete',
  weeks: 6,
  frequency: '5x / week',
  description: '6-week progressive training for competitive athletes. Power, speed, strength, and conditioning — new exercises each week, peaking in Week 6.',
  category: 'athletic' as const,
  image: '/programs/athletic.jpg',
  days: [
    // ═══════════════════════════════════════
    //  WEEK 1
    // ═══════════════════════════════════════
    {
      day: 'Day 1',
      title: 'W1 · Lower Body',
      warmup: 'Skips for height 2×20 yards · Bounds for distance 2×20 yards · Broad jumps 2×5',
      duration: '70 min',
      exercises: [
        { name: 'Power Clean', sets: 4, reps: '5', rest: '2:00', cues: 'Triple extension — hips, knees, ankles. Catch in a front rack, absorb in a quarter squat.' },
        { name: 'Barbell Front Squat', sets: 4, reps: '12 / 10 / 8 / 6', rest: '2:00', cues: 'Elbows high, chest up. Full depth on every rep. Increase weight each set.' },
        { name: '1a. Dumbbell Walking Lunge', sets: 3, reps: '12 steps', rest: '1:00', cues: 'Long stride, control each step. Keep torso upright.' },
        { name: '1b. Nordic Curl', sets: 3, reps: '5', rest: '1:30', cues: 'Lower as slowly as possible. Use hands to catch yourself at the bottom.' },
        { name: '2a. Reverse Hyper Extension', sets: 3, reps: '12', rest: '0:30', cues: 'Controlled swing, squeeze glutes at the top. No momentum.' },
        { name: '2b. Banded TKE', sets: 3, reps: '15', rest: '0:30', cues: 'Lock the knee fully against the band. Focus on VMO activation.' },
        { name: '2c. Single Leg Calf Raise', sets: 3, reps: '12 each', rest: '1:00', cues: 'Full range — deep stretch at the bottom, full squeeze at the top.' },
        { name: '150-Yard Sprint', sets: 5, reps: '1', rest: '1:00', cues: 'All-out effort. Walk back to start, rest 1 minute, go again.' },
      ],
    },
    {
      day: 'Day 2',
      title: 'W1 · Upper Body',
      warmup: 'Ski erg 3 min, then 2 rounds: ring rows ×15, clapping push-ups ×10, banded 90 & shoot ×12',
      duration: '70 min',
      exercises: [
        { name: 'Dumbbell Hang Snatch', sets: 4, reps: '3 each', rest: '2:00', cues: 'Single arm. Explosive hip drive, punch the dumbbell overhead. Heavy.' },
        { name: '1a. Bench Press', sets: 4, reps: '12 / 10 / 8 / 6', rest: '1:00', cues: 'Shoulder blades pinched, feet flat. Control the descent, explode up.' },
        { name: '1b. Dumbbell External Rotation', sets: 4, reps: '7 each', rest: '1:30', cues: 'Elbow pinned to side, rotate out slowly. Rotator cuff health.' },
        { name: '2a. Pull-Up', sets: 4, reps: '12 / 10 / 8 / 6', rest: '1:00', cues: 'Full dead hang to chin over bar. Add weight as reps decrease.' },
        { name: '2b. Half Kneeling Dumbbell Shoulder Press', sets: 4, reps: '12 / 10 / 8 / 6 each', rest: '1:30', cues: 'Single arm, neutral grip. Brace core hard in the half kneeling position.' },
        { name: '3a. Smith Machine Bent-Over Row', sets: 3, reps: '12', rest: '0:30', cues: 'Pull to lower chest, squeeze shoulder blades together.' },
        { name: '3b. Incline Dumbbell Bench Press', sets: 3, reps: '12', rest: '0:30', cues: 'Control the lowering phase. Full range of motion.' },
        { name: '3c. Smith Machine Shrug', sets: 3, reps: '12', rest: '1:00', cues: 'Pull shoulders straight up to ears. Hold at the top for 1 second.' },
        { name: 'Machine Shoulder Press', sets: 3, reps: '12', rest: '1:00', cues: 'Full lockout overhead. Keep core tight.' },
        { name: 'Lat Pulldown — V-Bar', sets: 3, reps: '12', rest: '1:00', cues: 'Pull to upper chest. Lean back slightly, squeeze lats at the bottom.' },
        { name: 'Cable Chest Fly', sets: 3, reps: '12', rest: '1:00', cues: 'Slight bend in elbows. Squeeze the chest at the center.' },
      ],
    },
    {
      day: 'Day 3',
      title: 'W1 · Core & Arms',
      warmup: 'Jog 5 min',
      duration: '55 min',
      exercises: [
        { name: 'EZ Bar Skull Crusher', sets: 4, reps: '15 / 12 / 10 / 10', rest: '1:30', cues: 'Lower to forehead, keep elbows pointed at the ceiling. Increase weight each set.' },
        { name: '1a. EZ Bar Spider Curl', sets: 4, reps: '10', rest: '0:30', cues: 'Chest on incline bench. Strict form, no swinging.' },
        { name: '1b. Dumbbell Hammer Curl', sets: 4, reps: '12 alternating', rest: '1:00', cues: 'Neutral grip, control the negative. Alternate arms each rep.' },
        { name: 'Barbell Finger Curl', sets: 3, reps: '20', rest: '1:00', cues: 'Let the bar roll to your fingertips, then curl it back. Forearm builder.' },
        { name: '2a. Cable Tricep Extension', sets: 4, reps: '10', rest: '0:30', cues: 'Lock out fully at the bottom. Keep elbows pinned.' },
        { name: '2b. Reverse Barbell Curl', sets: 4, reps: '10', rest: '1:00', cues: 'Overhand grip. Slow and controlled — targets brachioradialis.' },
        { name: '3a. Decline Crunch', sets: 3, reps: '20', rest: '0:30', cues: 'Squeeze abs at the top. Control the descent.' },
        { name: '3b. Half Kneeling Med Ball Throw', sets: 3, reps: '10 each', rest: '1:00', cues: 'Rotate through the core. Explosive throw into the wall.' },
        { name: '4a. Hanging Leg Raise', sets: 3, reps: '10', rest: '0:30', cues: 'Controlled movement — no swinging. Bring knees to chest or toes to bar.' },
        { name: '4b. Russian Twist', sets: 3, reps: '20', rest: '1:00', cues: 'Feet off the ground. Rotate fully side to side with control.' },
        { name: 'EMOM Core Circuit', sets: 3, reps: '9 min total', rest: '-', cues: 'Every minute on the minute — Min 1: Plank :30. Min 2: Supermans :30. Min 3: Side plank :20 each side. Repeat 3 rounds.' },
        { name: 'Easy Run', sets: 1, reps: '15 min', rest: '-', cues: 'Conversational pace. Focus on breathing and form.' },
      ],
    },
    {
      day: 'Day 4',
      title: 'W1 · Lower Body II',
      warmup: 'Lateral shuffle 2×6 (10 yards each direction, stick and hold each cut) · Shuttle run 3× (5-10-5)',
      duration: '70 min',
      exercises: [
        { name: 'Hang Power Clean', sets: 5, reps: '3', rest: '2:00', cues: 'Start at the hip. Aggressive pull, fast elbows. Catch in a quarter squat.' },
        { name: '1a. Barbell Box Squat', sets: 4, reps: '8 / 6 / 4 / 4', rest: '1:00', cues: 'Sit back fully on the box, pause, then drive up explosively.' },
        { name: '1b. Single Leg Box Jump', sets: 4, reps: '2 each', rest: '1:30', cues: 'Explode off one leg, land soft on the box. Step down.' },
        { name: '2a. Barbell Reverse Lunge', sets: 3, reps: '7 each', rest: '1:00', cues: 'Step back, drop the knee. Front knee tracks over toes. Drive through the front heel.' },
        { name: '2b. Single Leg Sliding Hamstring Curl', sets: 3, reps: '7 each', rest: '1:30', cues: 'Slide one heel out slowly, pull it back in. Keep hips up the whole time.' },
        { name: 'Leg Press', sets: 4, reps: '15 / 12 / 10 + burnout', rest: '1:30', cues: 'Increase weight each set. On the last set, drop the weight and rep to failure.' },
        { name: 'Leg Extension', sets: 3, reps: '12', rest: '1:00', cues: 'Squeeze hard at the top. Controlled lowering.' },
        { name: 'Hamstring Curl', sets: 3, reps: '12', rest: '1:00', cues: 'Full range of motion. Squeeze at the bottom of the curl.' },
        { name: 'Conditioning Circuit', sets: 3, reps: 'for time', rest: '2:00', cues: 'Row 15 calories → 20-yard sled push → 10 burpees. 3 rounds as fast as possible.' },
      ],
    },
    {
      day: 'Day 5',
      title: 'W1 · Upper Body II',
      warmup: '2 rounds: banded front raise into pull apart ×10, single arm DB overhead carry 20 yards, scalp push-ups ×10, scalp pull-ups ×10',
      duration: '70 min',
      exercises: [
        { name: 'Landmine Split Jerk', sets: 4, reps: '3 each', rest: '2:00', cues: 'Dip and drive the barbell overhead in a split stance. Explosive and controlled.' },
        { name: '1a. Seated Shoulder Press', sets: 4, reps: '10', rest: '1:00', cues: 'Barbell or Smith machine. Full lockout overhead. Controlled lowering.' },
        { name: '1b. Dumbbell Upright Row', sets: 4, reps: '12 alternating', rest: '1:30', cues: 'Pull to chin height. Lead with the elbows. Alternate arms.' },
        { name: '2a. Cable Low Row', sets: 4, reps: '15 / 12 / 10 / 10', rest: '1:00', cues: 'Sit tall, pull to the belly button. Squeeze the shoulder blades.' },
        { name: '2b. Dumbbell Reverse Fly', sets: 4, reps: '12', rest: '1:30', cues: 'Slight bend in elbows. Squeeze rear delts at the top.' },
        { name: '3a. Decline Bench Press', sets: 4, reps: '10 / 8 / 6 / 6', rest: '1:00', cues: 'Control the bar to lower chest. Drive up explosively.' },
        { name: '3b. Standing Incline Cable Chest Fly', sets: 4, reps: '10', rest: '1:30', cues: 'Cables set low, fly upward. Squeeze chest at the top.' },
        { name: '4a. Cable Tricep Extension — Rope', sets: 3, reps: '15 / 12 / 10', rest: '0:30', cues: 'Split the rope at the bottom, squeeze triceps.' },
        { name: '4b. Dumbbell Zottman Curl', sets: 3, reps: '15 / 12 / 10', rest: '0:30', cues: 'Curl up with palms up, rotate to palms down at the top, lower slowly.' },
        { name: '4c. Cable Tricep Kickback', sets: 3, reps: '15 / 12 / 10', rest: '1:00', cues: 'Hinge forward, extend the arm fully behind you. Squeeze at the top.' },
        { name: '5a. Rower Pike-Up', sets: 3, reps: '15', rest: '0:30', cues: 'Feet on rower seat, pike hips up. Controlled movement.' },
        { name: '5b. Kettlebell Suitcase Carry', sets: 3, reps: '20 yards', rest: '0:30', cues: 'Heavy kettlebell in one hand. Walk tall, fight the lean. Switch sides.' },
        { name: '5c. Ball Crunch', sets: 3, reps: '20', rest: '1:00', cues: 'On a stability ball. Full range — stretch back, crunch up hard.' },
      ],
    },

    // ═══════════════════════════════════════
    //  WEEK 2
    // ═══════════════════════════════════════
    {
      day: 'Day 6',
      title: 'W2 · Lower Body',
      warmup: 'Kneeling starts 2× each leg ×10 yards · Med ball throws: backwards ×5, forwards ×5, vertical ×5',
      duration: '70 min',
      exercises: [
        { name: 'Power Clean', sets: 5, reps: '3', rest: '2:00', cues: 'Heavier than week 1. Aggressive hip extension, fast elbows under the bar.' },
        { name: '1a. Barbell Back Squat — Paused', sets: 4, reps: '5', rest: '1:00', cues: '3-second pause at the bottom. Stay tight in the hole, then drive up.' },
        { name: '1b. Banded TKE', sets: 4, reps: '12 each', rest: '1:30', cues: 'Lock the knee fully against the band. VMO activation.' },
        { name: '2a. Barbell Reverse Lunge', sets: 3, reps: '6 each', rest: '1:00', cues: 'Controlled step back, drive through the front heel.' },
        { name: '2b. Landmine Cossack Squat', sets: 3, reps: '6 each', rest: '1:30', cues: 'Shift weight to one leg, sit deep. Keep the trailing leg straight.' },
        { name: 'Single Leg Hamstring Curl', sets: 3, reps: '12 each', rest: '1:00', cues: 'Slow and controlled. Squeeze at the bottom of each rep.' },
        { name: 'Single Leg Leg Extension', sets: 3, reps: '12 each', rest: '1:00', cues: 'Full lockout at the top. Controlled lowering.' },
        { name: '3a. Seated Calf Raise', sets: 3, reps: '20', rest: '0:30', cues: 'Full range — stretch and squeeze. High reps for the soleus.' },
        { name: '3b. Pogo Jump', sets: 3, reps: '10', rest: '1:00', cues: 'No knee bend — all ankle stiffness. Quick ground contact.' },
        { name: 'Treadmill Sprint', sets: 6, reps: ':30 on / :30 off', rest: '0:30', cues: 'Sprint for 30 seconds, rest for 30 seconds. All-out effort each round.' },
      ],
    },
    {
      day: 'Day 7',
      title: 'W2 · Upper Body',
      warmup: '2 rounds: ski 15/12 cal, banded pass-through + around the world 10+5 each, banded pull-apart ×10, scalp pull-ups ×10',
      duration: '70 min',
      exercises: [
        { name: 'Dumbbell Hang Snatch', sets: 4, reps: '3 each', rest: '2:00', cues: 'Single arm. Heavy. Explosive hip drive, punch overhead.' },
        { name: '1a. Decline Bench Press', sets: 4, reps: '12 / 10 / 8 / 6', rest: '1:00', cues: 'Control to lower chest, drive up. Increase weight each set.' },
        { name: '1b. Cable Face Pull', sets: 4, reps: '12', rest: '1:30', cues: 'Pull to forehead, externally rotate at the end. Squeeze rear delts.' },
        { name: 'Cable Low Row', sets: 4, reps: '10 + drop set', rest: '1:30', cues: '3 sets of 10, then 1 set: 10 reps, drop weight, 10 reps, drop, 10 reps.' },
        { name: 'Dumbbell Alternating Upright Row', sets: 4, reps: '12', rest: '1:30', cues: 'Pull to chin height, lead with the elbows. Alternate arms.' },
        { name: '2a. Dumbbell Flat Bench', sets: 3, reps: '8', rest: '0:30', cues: 'Full range. Squeeze chest at the top.' },
        { name: '2b. Dumbbell Lawnmower Row', sets: 3, reps: '8 each', rest: '0:30', cues: 'One arm, one knee on bench. Pull to the hip, squeeze the lat.' },
        { name: '2c. Dumbbell Chest Fly', sets: 3, reps: '12', rest: '1:00', cues: 'Wide arc, slight bend in elbows. Feel the stretch at the bottom.' },
        { name: 'Machine Lateral Raise', sets: 3, reps: '15', rest: '1:00', cues: 'Controlled movement. Don\'t shrug — lead with the elbows.' },
        { name: 'Lat Pulldown', sets: 3, reps: '12', rest: '1:00', cues: 'Pull to upper chest. Lean back slightly, full stretch at the top.' },
        { name: 'Dip', sets: 3, reps: 'to failure', rest: '1:00', cues: 'Focus on muscle endurance. Full depth, lock out at the top.' },
      ],
    },
    {
      day: 'Day 8',
      title: 'W2 · Core & Arms',
      warmup: 'Jog 5 min',
      duration: '55 min',
      exercises: [
        { name: '1a. Single Arm Cable Curl', sets: 4, reps: '15 / 12 / 10 / 10', rest: '0:30', cues: 'Strict form. Full range of motion, squeeze at the top.' },
        { name: '1b. Single Arm Cable Tricep Extension', sets: 4, reps: '15 / 12 / 10 / 10', rest: '1:00', cues: 'Lock out fully. Keep elbow pinned to your side.' },
        { name: '2a. Drag Curl', sets: 4, reps: '10', rest: '0:30', cues: 'Drag the bar up along your body. Elbows go behind you. Bicep peak builder.' },
        { name: '2b. Cable V-Bar Tricep Extension', sets: 4, reps: '10', rest: '1:00', cues: 'V-bar attachment. Lock out at the bottom, squeeze triceps.' },
        { name: '3a. Seated Dumbbell Hammer Curl', sets: 3, reps: '12', rest: '0:30', cues: 'Seated to eliminate momentum. Neutral grip, slow and controlled.' },
        { name: '3b. Dumbbell French Press', sets: 3, reps: '12', rest: '1:00', cues: 'Single dumbbell overhead. Lower behind head, extend fully.' },
        { name: 'Plate Pinch', sets: 4, reps: ':30', rest: '1:00', cues: 'Pinch two plates together (smooth sides out). Hold for time. Grip strength.' },
        { name: '4a. Cable Crunch', sets: 3, reps: '20', rest: '0:30', cues: 'Kneel facing cable. Crunch down, squeeze abs hard.' },
        { name: '4b. Hanging Leg Raise', sets: 3, reps: '12', rest: '1:00', cues: 'Controlled — no swinging. Bring toes to bar if possible.' },
        { name: '5a. Hollow Hold', sets: 3, reps: ':30', rest: '0:30', cues: 'Lower back pressed into the floor. Arms and legs extended.' },
        { name: '5b. Weighted V-Up', sets: 3, reps: '12', rest: '1:00', cues: 'Hold a plate or med ball. Touch hands to feet at the top.' },
        { name: '6a. Med Ball Slam', sets: 3, reps: '15', rest: '0:30', cues: 'Full extension overhead, slam it into the ground. Explosive.' },
        { name: '6b. Suitcase Carry', sets: 3, reps: '20 yards', rest: '1:00', cues: 'Heavy weight, one side. Walk tall, fight the lean. Switch sides.' },
        { name: 'Zone 2 Run', sets: 1, reps: '20 min', rest: '-', cues: 'Easy pace, stay in zone 2. Build your aerobic base.' },
      ],
    },
    {
      day: 'Day 9',
      title: 'W2 · Lower Body II',
      warmup: 'Ice skaters 3×:15 · Lateral kneeling starts 2× each leg ×10 yards',
      duration: '70 min',
      exercises: [
        { name: 'Hang Power Clean', sets: 5, reps: '3', rest: '2:00', cues: 'Start at the hip, explosive pull. Fast elbows, catch in quarter squat.' },
        { name: '1a. Barbell Back Squat — from Pins', sets: 4, reps: '8 / 6 / 4 / 4', rest: '1:00', cues: 'Start from the pins at parallel. Dead stop each rep, explode up.' },
        { name: '1b. Banded Lunge Jump', sets: 4, reps: '10', rest: '1:30', cues: 'Band around hips for resistance. Explosive alternating lunge jumps.' },
        { name: '2a. Front Rack Barbell Step-Up', sets: 3, reps: '7 each', rest: '1:00', cues: 'Bar in front rack position. Step up, drive the knee. Control down.' },
        { name: '2b. Single Leg Landmine RDL', sets: 3, reps: '7 each', rest: '1:30', cues: 'Hold landmine in one hand. Hinge on opposite leg. Squeeze glute at the top.' },
        { name: '3a. Dumbbell Walking Lunge', sets: 2, reps: '20 yards', rest: '0:30', cues: 'Heavy dumbbells. Long stride, control each step.' },
        { name: '3b. Calf Raise', sets: 2, reps: '20', rest: '0:30', cues: 'Full range — deep stretch, hard squeeze at the top.' },
        { name: '3c. Heavy Sled Push', sets: 2, reps: '20 yards', rest: '1:30', cues: 'Low body angle, short powerful steps. Heavy weight.' },
        { name: 'Conditioning Circuit', sets: 1, reps: 'for time', rest: '-', cues: '400m run → 15 kettlebell swings → 30 wall ball shots → 15 KB swings → 30 wall ball shots → 15 KB swings → 400m run. One round, all-out.' },
      ],
    },
    {
      day: 'Day 10',
      title: 'W2 · Upper Body II',
      warmup: '2 rounds: row 15/12 cal, med ball ground passes ×15 (fast), TRX Y-T-W ×5 each',
      duration: '70 min',
      exercises: [
        { name: 'Landmine Split Jerk', sets: 4, reps: '4 each', rest: '2:00', cues: 'More reps per side than week 1. Explosive dip and drive.' },
        { name: '1a. Seated Dumbbell Arnold Press', sets: 4, reps: '12 / 10 / 8 / 8', rest: '1:00', cues: 'Rotate palms from facing you to facing out as you press. Full lockout.' },
        { name: '1b. Seated Dumbbell Lateral Raise', sets: 4, reps: '12', rest: '1:30', cues: 'Lead with the elbows, not the hands. Controlled throughout.' },
        { name: '2a. Barbell Bent-Over Row', sets: 4, reps: '8', rest: '1:00', cues: '45-degree torso angle. Pull to lower chest, squeeze shoulder blades.' },
        { name: '2b. Cable Straight Arm Pulldown', sets: 4, reps: '12', rest: '1:30', cues: 'Arms straight, pull the bar to your thighs. Squeeze lats hard.' },
        { name: '3a. Cable Incline Bench Press', sets: 4, reps: '12 / 10 / 8 / 8', rest: '1:00', cues: 'Incline angle on the cable press. Squeeze chest at the top.' },
        { name: '3b. Weighted Push-Up', sets: 4, reps: '8', rest: '1:30', cues: 'Plate on your back. Full range of motion. Go heavy.' },
        { name: '4a. EZ Bar Curl', sets: 3, reps: '12', rest: '0:30', cues: 'Strict form. Full range — no swinging.' },
        { name: '4b. Dumbbell Skull Crusher', sets: 3, reps: '12', rest: '0:30', cues: 'Lower to forehead, elbows pointed at ceiling. Lock out at the top.' },
        { name: '4c. Cable Rope Curl', sets: 3, reps: '12', rest: '1:00', cues: 'Rope attachment. Supinate at the top, squeeze hard.' },
        { name: '5a. Toe Touch', sets: 3, reps: '20', rest: '0:30', cues: 'Legs straight up, reach for toes. Crunch the upper abs.' },
        { name: '5b. Oblique Crunch', sets: 3, reps: '15 each', rest: '1:00', cues: 'Side crunch — squeeze the obliques. Both sides.' },
        { name: '6a. Side Plank', sets: 3, reps: ':30 each', rest: '0:30', cues: 'Stack hips, squeeze glutes. Hold steady — no sagging.' },
        { name: '6b. Superman', sets: 3, reps: '20', rest: '1:00', cues: 'Lift arms and legs off the ground. Squeeze lower back at the top.' },
      ],
    },

    // ═══════════════════════════════════════
    //  WEEK 3
    // ═══════════════════════════════════════
    {
      day: 'Day 11',
      title: 'W3 · Lower Body',
      warmup: 'Kneeling starts 2× each leg ×10 yards',
      duration: '70 min',
      exercises: [
        { name: 'Power Clean', sets: 5, reps: '5 / 3 / 3 / 2 / 2', rest: '2:00', cues: 'Building to heavier doubles. Technique stays sharp as the weight goes up.' },
        { name: '1a. Barbell Front Squat', sets: 4, reps: '8 / 6 / 4 / 4', rest: '1:00', cues: 'Elbows high. Increase weight each set. Heavy on the last two.' },
        { name: '1b. Hyper Extension', sets: 4, reps: '10', rest: '1:30', cues: 'Hinge at the hips, squeeze glutes and hamstrings at the top.' },
        { name: '2a. Dumbbell Split Squat', sets: 3, reps: '8 each', rest: '1:00', cues: 'Rear foot elevated. Deep stretch at the bottom. Drive through the front heel.' },
        { name: '2b. Single Leg RDL', sets: 3, reps: '8 each', rest: '1:30', cues: 'Hinge on one leg. Keep the back flat. Squeeze the glute at the top.' },
        { name: '3a. Leg Press', sets: 3, reps: '15 / 12 / 10', rest: '0:30', cues: 'Increase weight each set. Full depth on every rep.' },
        { name: '3b. Leg Extension', sets: 3, reps: '12', rest: '0:30', cues: 'Full lockout, squeeze the quads.' },
        { name: '3c. Calf Raise', sets: 3, reps: '15', rest: '1:00', cues: 'Full range of motion. Controlled tempo.' },
        { name: 'Treadmill Sprint', sets: 6, reps: ':20 on / :40 off', rest: '0:40', cues: 'Top speed work — go fast or be last. Full recovery between rounds.' },
      ],
    },
    {
      day: 'Day 12',
      title: 'W3 · Upper Body',
      warmup: '2 rounds: row 15/12 cal, KB bottoms-up carry 20 yards each arm, scalp pull-up & push-up ×7 each, banded pass-through + around the world 10+5 each',
      duration: '70 min',
      exercises: [
        { name: 'Dumbbell Hang Snatch', sets: 4, reps: '3 each', rest: '2:00', cues: 'Single arm. Heavy. Maintain technique at heavier loads.' },
        { name: '1a. Bench Press', sets: 4, reps: '10 / 8 / 6 / 4', rest: '1:00', cues: 'Heavier progression than week 1. Push for new weight on the heavy sets.' },
        { name: '1b. Dumbbell External Rotation', sets: 4, reps: '7 each', rest: '1:30', cues: 'Elbow pinned to side. Slow rotation out. Shoulder health.' },
        { name: '2a. Lat Pulldown', sets: 4, reps: '12 / 10 / 8 / 8', rest: '1:00', cues: 'Full stretch at the top, pull to upper chest.' },
        { name: '2b. Half Kneeling Dumbbell Shoulder Press', sets: 4, reps: '12 / 10 / 8 / 8 each', rest: '1:30', cues: 'Single arm, neutral grip. Core braced tight.' },
        { name: '3a. Incline Smith Machine Bench Press', sets: 3, reps: '10', rest: '0:30', cues: 'Controlled descent, drive up. Full range of motion.' },
        { name: '3b. Machine Shoulder Press', sets: 3, reps: '12', rest: '0:30', cues: 'Full lockout overhead each rep.' },
        { name: '3c. Pull-Up', sets: 3, reps: 'to failure', rest: '1:00', cues: 'Focus on muscle endurance. Full dead hang to chin over bar.' },
        { name: 'Cable Low Row — Drop Set', sets: 3, reps: '8-10-12 drop set', rest: '1:30', cues: 'Start heavy: 8 reps, drop weight, 10 reps, drop, 12 reps. One round per set.' },
        { name: 'Cable Chest Fly', sets: 3, reps: '15', rest: '1:00', cues: 'High reps, focus on the squeeze at the center.' },
        { name: 'Cable Front Raise — Rope', sets: 3, reps: '15', rest: '1:00', cues: 'Rope attachment. Raise to eye level, control the descent.' },
      ],
    },
    {
      day: 'Day 13',
      title: 'W3 · Core & Arms',
      warmup: 'Jog 7 min',
      duration: '55 min',
      exercises: [
        { name: '1a. Cable Skull Crusher', sets: 4, reps: '20 / 15 / 10 / 10', rest: '0:30', cues: 'Cable attachment. High reps to start, build weight.' },
        { name: '1b. EZ Bar Reverse Grip Curl', sets: 4, reps: '10', rest: '1:00', cues: 'Underhand grip on EZ bar. Strict form, target the long head.' },
        { name: '2a. Dumbbell Hammer Curl', sets: 4, reps: '12 alternating', rest: '0:30', cues: 'Neutral grip. Alternate arms. No swinging.' },
        { name: '2b. Single Arm Cable Tricep Extension', sets: 3, reps: '12', rest: '1:00', cues: 'Lock out fully. Control the return.' },
        { name: '3a. Dumbbell Zottman Curl', sets: 3, reps: '15', rest: '0:30', cues: 'Curl up palms up, rotate to palms down at top, lower slowly.' },
        { name: '3b. Forearm Roller', sets: 4, reps: '2 rolls', rest: '1:00', cues: 'Roll the weight up and down. Forearms should be burning.' },
        { name: '4a. Decline Crunch', sets: 3, reps: '20', rest: '0:30', cues: 'Squeeze abs at the top. Control the descent.' },
        { name: '4b. Rotational Med Ball Throw', sets: 3, reps: '12', rest: '1:00', cues: 'Rotate through the core. Explosive throw into the wall.' },
        { name: '5a. Hanging Leg Raise', sets: 3, reps: '10', rest: '0:30', cues: 'Controlled — no swinging. Toes to bar if possible.' },
        { name: '5b. Russian Twist', sets: 3, reps: '20', rest: '1:00', cues: 'Feet off the ground. Weighted. Full rotation side to side.' },
        { name: 'EMOM Core Circuit', sets: 3, reps: '9 min total', rest: '-', cues: 'Every minute on the minute — Min 1: Hollow hold :30. Min 2: Supermans :30. Min 3: Side plank :20 each side. Repeat 3 rounds.' },
        { name: 'Zone 2 Conditioning', sets: 1, reps: '20 min', rest: '-', cues: 'Run or bike at easy pace. Stay in zone 2. Build your base.' },
      ],
    },
    {
      day: 'Day 14',
      title: 'W3 · Lower Body II',
      warmup: 'Lateral shuffle 2×6 (10 yards each, stick each cut) · 5-10-5 shuttle run ×3',
      duration: '70 min',
      exercises: [
        { name: 'Hang Power Clean', sets: 5, reps: '5 / 3 / 3 / 2 / 2', rest: '2:00', cues: 'Building to heavier doubles. Stay aggressive.' },
        { name: '1a. Barbell Front Squat — Paused', sets: 4, reps: '5', rest: '1:00', cues: '3-second pause at the bottom. Stay tight, drive up hard.' },
        { name: '1b. Banded TKE', sets: 4, reps: '12 each', rest: '1:30', cues: 'Lock the knee fully. VMO activation.' },
        { name: '2a. Dumbbell Split Squat', sets: 3, reps: '7 each', rest: '1:00', cues: 'Rear foot elevated. Deep at the bottom, drive through front heel.' },
        { name: '2b. Front Foot Elevated Alternating Lunge Jump', sets: 3, reps: '12', rest: '1:30', cues: 'Front foot on a low box. Explosive alternating jumps.' },
        { name: '3a. Single Leg Hamstring Curl', sets: 3, reps: '12 each', rest: '0:30', cues: 'Slow and controlled on each leg.' },
        { name: '3b. Copenhagen Hold', sets: 3, reps: ':20 each', rest: '0:30', cues: 'Top leg on a bench, bottom leg hanging. Hold and squeeze the adductors.' },
        { name: '3c. Calf Raise', sets: 3, reps: '15', rest: '1:00', cues: 'Full range of motion. Controlled tempo.' },
        { name: 'Sled Sprint', sets: 8, reps: '20 yards', rest: '0:45', cues: 'Keep the sled light — work on speed. If no sled, treadmill sprints: :20 sprint, :40 rest, ×8.' },
      ],
    },
    {
      day: 'Day 15',
      title: 'W3 · Upper Body II',
      warmup: '2 rounds: jump rope ×60, DB external rotation off knee 10 each, inverted row ×12, single arm sliding push-up ×5 each',
      duration: '70 min',
      exercises: [
        { name: 'Landmine Split Jerk', sets: 4, reps: '5 each', rest: '2:00', cues: 'More reps than last week. Maintain power and technique.' },
        { name: '1a. Barbell Shoulder Press', sets: 4, reps: '10 / 8 / 6 / 4', rest: '1:00', cues: 'Strict press. Full lockout. Push for heavy weight on the last set.' },
        { name: '1b. Cable Face Pull', sets: 4, reps: '10', rest: '1:30', cues: 'Pull to forehead, externally rotate. Squeeze rear delts.' },
        { name: '2a. Chest Supported Dumbbell Row', sets: 4, reps: '8', rest: '1:00', cues: '3-second eccentric (lowering phase). Squeeze hard at the top.' },
        { name: '2b. Dumbbell Flat Bench — Neutral Grip', sets: 4, reps: '8', rest: '1:30', cues: '3-second eccentric. Control the weight down, press up explosively.' },
        { name: '3a. Dumbbell Farmer Carry', sets: 3, reps: '20 yards', rest: '0:30', cues: 'Heavy dumbbells. Walk tall, shoulders packed, core braced.' },
        { name: '3b. Plate Front Raise + Bus Driver', sets: 3, reps: '10', rest: '1:00', cues: 'Raise plate to eye level, rotate it side to side (bus driver), lower.' },
        { name: '4a. Cable Overhead Tricep Extension', sets: 3, reps: '15 / 12 / 10', rest: '0:30', cues: 'Face away from cable. Extend overhead, lock out. Increase weight.' },
        { name: '4b. Dumbbell Cross-Body Curl', sets: 3, reps: '16 alternating', rest: '0:30', cues: 'Curl across the body toward the opposite shoulder. Squeeze the peak.' },
        { name: '4c. Cable Tricep Kickback', sets: 3, reps: '15 / 12 / 10', rest: '1:00', cues: 'Hinge forward, extend arm fully behind you.' },
        { name: '5a. Landmine Rotation', sets: 3, reps: '12', rest: '0:30', cues: 'Controlled rotation. Core engagement throughout.' },
        { name: '5b. Toes to Bar', sets: 3, reps: '12', rest: '1:00', cues: 'Controlled — bring toes to the bar. No kipping.' },
        { name: '6a. Ab Rollout', sets: 3, reps: '10', rest: '0:30', cues: 'Roll out as far as possible. Don\'t let the hips sag.' },
        { name: '6b. Oblique Crunch', sets: 3, reps: '15 each', rest: '1:00', cues: 'Target each side. Full contraction.' },
      ],
    },

    // ═══════════════════════════════════════
    //  WEEK 4
    // ═══════════════════════════════════════
    {
      day: 'Day 16',
      title: 'W4 · Lower Body',
      warmup: 'Kneeling starts 2× each leg ×10 yards · Med ball throws: backwards ×5, forwards ×5, vertical ×5',
      duration: '70 min',
      exercises: [
        { name: 'Power Clean', sets: 5, reps: '3 / 3 / 2 / 2 / 2', rest: '2:00', cues: 'Heavier doubles. Technique under load. Stay aggressive.' },
        { name: '1a. Banded Barbell Back Squat', sets: 4, reps: '8 / 6 / 4 / 4', rest: '1:00', cues: 'Bands add resistance at the top. Explode through the sticking point.' },
        { name: '1b. Death Drop to Vertical Jump', sets: 4, reps: '2', rest: '1:30', cues: 'Step off a box, absorb the landing, immediately jump as high as possible.' },
        { name: '2a. Front Foot Elevated Barbell Reverse Lunge', sets: 3, reps: '6 each', rest: '1:00', cues: 'Front foot on a plate or low platform. Step back, drive through the front heel.' },
        { name: '2b. Kettlebell Crossover Step-Up', sets: 3, reps: '12', rest: '1:30', cues: 'Step across the body onto the box. Kettlebells at sides.' },
        { name: '3a. Leg Press — Drop Set', sets: 3, reps: '10-15-20 drop set', rest: '0:30', cues: 'Start heavy for 10, drop weight for 15, drop again for 20. One round per set.' },
        { name: '3b. Single Leg Leg Extension', sets: 3, reps: '12 each', rest: '0:30', cues: 'Full lockout, squeeze the quad at the top.' },
        { name: '3c. Adduction Machine', sets: 3, reps: '15', rest: '1:00', cues: 'Squeeze the inner thighs. Controlled movement.' },
        { name: '200m Sprint', sets: 5, reps: '1', rest: '1:30', cues: 'All-out 200 meters. Full recovery between rounds.' },
      ],
    },
    {
      day: 'Day 17',
      title: 'W4 · Upper Body',
      warmup: 'Ski erg 3 min, then 2 rounds: ring rows ×15, clapping push-ups ×10, banded 90 & shoot ×12',
      duration: '70 min',
      exercises: [
        { name: 'Dumbbell Hang Snatch', sets: 4, reps: '3 each', rest: '2:00', cues: 'Single arm. Maintain heavy loads from prior weeks.' },
        { name: '1a. Bench Press — Paused', sets: 4, reps: '5', rest: '1:00', cues: '3-second pause at the chest. Stay tight, explode up from the dead stop.' },
        { name: '1b. Med Ball Ground Pass', sets: 4, reps: '10', rest: '1:30', cues: 'Slam the ball into the ground as fast as possible. Explosive.' },
        { name: 'Cable Low Row', sets: 4, reps: '10 + drop set', rest: '1:30', cues: '3 sets of 10, then 1 drop set (10/10/10). Pull to belly, squeeze lats.' },
        { name: 'Dumbbell Alternating Upright Row', sets: 4, reps: '12', rest: '1:30', cues: 'Pull to chin height, lead with elbows. Alternate arms.' },
        { name: '2a. Smith Machine Bent-Over Row', sets: 3, reps: '12', rest: '0:30', cues: 'Pull to lower chest, squeeze shoulder blades together.' },
        { name: '2b. Incline Dumbbell Bench Press', sets: 3, reps: '12', rest: '0:30', cues: 'Control the lowering. Full range of motion.' },
        { name: '2c. Smith Machine Shrug', sets: 3, reps: '12', rest: '1:00', cues: 'Pull shoulders straight to ears. Hold at the top.' },
        { name: 'Machine Lateral Raise', sets: 3, reps: '15', rest: '1:00', cues: 'Controlled movement. No momentum.' },
        { name: 'Lat Pulldown — Single Arm', sets: 3, reps: '10 each', rest: '1:00', cues: 'One arm at a time. Full stretch, squeeze the lat at the bottom.' },
        { name: 'Dip', sets: 3, reps: 'to failure', rest: '1:00', cues: 'Focus on muscle endurance. Full depth, lock out at top.' },
      ],
    },
    {
      day: 'Day 18',
      title: 'W4 · Core & Arms',
      warmup: 'Jog 10 min',
      duration: '55 min',
      exercises: [
        { name: 'EZ Bar Skull Crusher', sets: 4, reps: '15 / 12 / 10 / 10', rest: '1:30', cues: 'Lower to forehead, elbows pointed at ceiling. Increase weight.' },
        { name: '1a. EZ Bar Spider Curl', sets: 4, reps: '10', rest: '0:30', cues: 'Chest on incline bench. Strict form, no swinging.' },
        { name: '1b. Dumbbell Hammer Curl', sets: 4, reps: '12 alternating', rest: '1:00', cues: 'Neutral grip. Control the negative. Alternate arms.' },
        { name: '2a. Barbell Finger Curl', sets: 3, reps: '20', rest: '0:30', cues: 'Let bar roll to fingertips, curl back. Forearm builder.' },
        { name: '2b. Plate Pinch', sets: 3, reps: ':20', rest: '1:00', cues: 'Pinch two plates together. Hold for time.' },
        { name: '3a. Cable Tricep Extension', sets: 4, reps: '10', rest: '0:30', cues: 'Lock out fully at the bottom. Keep elbows pinned.' },
        { name: '3b. Reverse Barbell Curl', sets: 4, reps: '10', rest: '1:00', cues: 'Overhand grip. Slow and controlled.' },
        { name: '4a. Decline Crunch', sets: 3, reps: '20', rest: '0:30', cues: 'Squeeze abs at the top. Control the descent.' },
        { name: '4b. Half Kneeling Med Ball Throw', sets: 3, reps: '10 each', rest: '1:00', cues: 'Rotate through the core. Explosive throw.' },
        { name: '5a. Hanging Leg Raise', sets: 3, reps: '10', rest: '0:30', cues: 'No swinging. Controlled movement.' },
        { name: '5b. Russian Twist', sets: 3, reps: '20', rest: '1:00', cues: 'Feet off ground, rotate fully side to side.' },
        { name: 'Interval Run', sets: 1, reps: '20 min', rest: '-', cues: '5 min easy → 1 min fast → 4 min easy → 1 min fast → 3 min easy → 1 min fast → 5 min easy.' },
      ],
    },
    {
      day: 'Day 19',
      title: 'W4 · Lower Body II',
      warmup: 'Ice skaters 3×:15 · Lateral kneeling starts 2× each leg ×10 yards',
      duration: '70 min',
      exercises: [
        { name: 'Hang Power Clean', sets: 5, reps: '3 / 3 / 2 / 2 / 2', rest: '2:00', cues: 'Heavier doubles. Stay fast and aggressive under the bar.' },
        { name: '1a. Banded Barbell Front Squat', sets: 4, reps: '8 / 6 / 4 / 4', rest: '1:00', cues: 'Bands add resistance at lockout. Elbows high, explode out of the hole.' },
        { name: '1b. Straight Leg Box Jump', sets: 4, reps: '2', rest: '1:30', cues: 'Jump onto the box without bending the knees much. Pure ankle and hip power.' },
        { name: '2a. Dumbbell Step-Up', sets: 3, reps: '7 each', rest: '1:00', cues: 'Step up, drive the knee. Control on the way down.' },
        { name: '2b. Landmine Cossack Squat', sets: 3, reps: '12', rest: '1:30', cues: 'Deep lateral squat. Keep trailing leg straight. Alternate sides.' },
        { name: '3a. Heavy Sled Push & Pull Shuttle', sets: 3, reps: '2×10 yards', rest: '0:30', cues: 'Push 10 yards, pull 10 yards back. Shuttle style.' },
        { name: '3b. Hamstring Curl', sets: 3, reps: '12', rest: '0:30', cues: 'Full range of motion. Squeeze at the bottom.' },
        { name: '3c. Abduction Machine', sets: 3, reps: '15', rest: '1:00', cues: 'Push knees out against the pads. Controlled movement.' },
        { name: 'AMRAP Conditioning', sets: 1, reps: '15 min', rest: '-', cues: 'As many rounds as possible: 40 double unders (or 80 singles) → 8 burpee box jumps → 300m row. Keep moving.' },
      ],
    },
    {
      day: 'Day 20',
      title: 'W4 · Upper Body II',
      warmup: '2 rounds: banded front raise into pull apart ×10, single arm DB overhead carry 20 yards, scalp push-ups ×10, scalp pull-ups ×10',
      duration: '70 min',
      exercises: [
        { name: 'Landmine Split Jerk', sets: 4, reps: '5 each', rest: '2:00', cues: 'Same volume as last week. Push for heavier weight.' },
        { name: '1a. Seated Dumbbell Arnold Press', sets: 4, reps: '12 / 10 / 8 / 8', rest: '1:00', cues: 'Rotate palms as you press. Full lockout overhead.' },
        { name: '1b. Plate Front Raise', sets: 4, reps: '12', rest: '1:30', cues: 'Raise to eye level, control the descent.' },
        { name: '2a. T-Bar Row', sets: 4, reps: '10', rest: '1:00', cues: 'Pull to chest, squeeze the lats and rhomboids.' },
        { name: '2b. Weighted Push-Up', sets: 4, reps: '8', rest: '1:30', cues: 'Plate on your back. Full range. Go heavy.' },
        { name: '3a. Machine Incline Chest Press', sets: 4, reps: '12 / 10 / 8 / 8', rest: '1:00', cues: 'Full lockout, squeeze chest at the top. Increase weight.' },
        { name: '3b. Seated Dumbbell Reverse Fly', sets: 4, reps: '12', rest: '1:30', cues: 'Slight bend in elbows. Squeeze rear delts at the top.' },
        { name: '4a. Dual Cable Curl', sets: 3, reps: '12', rest: '0:30', cues: 'Both arms, cables from low. Squeeze the peak hard.' },
        { name: '4b. Dumbbell Skull Crusher', sets: 3, reps: '15', rest: '0:30', cues: 'Lower to forehead. High reps, feel the burn.' },
        { name: '4c. EZ Bar Reverse Curl', sets: 3, reps: '12', rest: '1:00', cues: 'Overhand grip. Targets the brachioradialis and forearms.' },
        { name: '5a. Rower Pike-Up', sets: 3, reps: '15', rest: '0:30', cues: 'Feet on rower seat, pike hips up. Controlled movement.' },
        { name: '5b. Kettlebell Suitcase Carry', sets: 3, reps: '20 yards', rest: '0:30', cues: 'Heavy kettlebell, one side. Walk tall, fight the lean. Switch sides.' },
        { name: '5c. Ball Crunch', sets: 3, reps: '20', rest: '1:00', cues: 'On a stability ball. Full range — stretch back, crunch up hard.' },
      ],
    },

    // ═══════════════════════════════════════
    //  WEEK 5
    // ═══════════════════════════════════════
    {
      day: 'Day 21',
      title: 'W5 · Lower Body',
      warmup: 'Broad jump to single leg landing 2×4 each · Single leg cycling bounds 2×20 yards · Get-offs 2×20 yards',
      duration: '70 min',
      exercises: [
        { name: 'Barbell Complex — Power Clean + Split Jerk', sets: 5, reps: '2+1', rest: '2:00', cues: '2 power cleans into 1 split jerk. Maintain speed and technique.' },
        { name: '1a. Barbell Split Squat — Slow Eccentric', sets: 4, reps: '5 each', rest: '1:00', cues: '3-second lowering phase. Control every inch of the descent.' },
        { name: '1b. Banded TKE', sets: 4, reps: '12 each', rest: '1:30', cues: 'Lock the knee fully. VMO activation.' },
        { name: '2a. Barbell Hip Thrust', sets: 3, reps: '15', rest: '0:30', cues: 'Drive through heels, squeeze glutes at the top. Full lockout.' },
        { name: '2b. Cable Kickback', sets: 3, reps: '15 each', rest: '1:30', cues: 'Kick straight back, squeeze the glute. Control the return.' },
        { name: '3a. Dumbbell Walking Lunge', sets: 3, reps: '12 steps', rest: '0:30', cues: 'Heavy dumbbells. Long stride, control each step.' },
        { name: '3b. Calf Raise', sets: 3, reps: '15', rest: '0:30', cues: 'Full range — deep stretch, hard squeeze.' },
        { name: '3c. Lateral Sled Pull', sets: 3, reps: '15 yards each way', rest: '1:00', cues: 'Side-facing, pull the sled laterally. Both directions.' },
        { name: 'Sprint Ladder', sets: 1, reps: '9 sprints', rest: '1:00', cues: '10 yd ×2, 20 yd ×2, 30 yd ×2 (90%), 40 yd ×2 (max), 50 yd ×1 (all-out finisher). Walk back to recover.' },
      ],
    },
    {
      day: 'Day 22',
      title: 'W5 · Upper Body',
      warmup: 'Ski erg 3 min, then 2 rounds: DB powell raise 10 each, inverted row ×12, DB hang snatch ×7 each',
      duration: '70 min',
      exercises: [
        { name: 'Barbell Hang Snatch', sets: 5, reps: '2', rest: '2:00', cues: 'Barbell now, not dumbbell. Wide grip, explosive hip drive, catch overhead.' },
        { name: '1a. Decline Bench Press — 1.5 Rep', sets: 4, reps: '8', rest: '1:00', cues: 'Lower all the way, come halfway up, go back down, then press to the top. That\'s 1 rep.' },
        { name: '1b. Cable Face Pull', sets: 4, reps: '12', rest: '1:30', cues: 'Pull to forehead, externally rotate. Squeeze rear delts.' },
        { name: '2a. Weighted Pull-Up', sets: 4, reps: '8 / 6 / 4 / 4', rest: '1:00', cues: 'Belt or DB between legs. Full dead hang to chin over bar.' },
        { name: '2b. Half Kneeling Dumbbell Shoulder Press', sets: 4, reps: '7 each', rest: '1:30', cues: 'Single arm, neutral grip. Core braced.' },
        { name: '3a. Cable Chest Fly', sets: 3, reps: '15', rest: '0:30', cues: 'Slight bend in elbows. Squeeze at center.' },
        { name: '3b. T-Bar Row', sets: 3, reps: '12', rest: '0:30', cues: 'Pull to chest, squeeze the back.' },
        { name: '3c. Decline Kettlebell Push-Up', sets: 3, reps: '12', rest: '1:00', cues: 'Hands on kettlebells, feet elevated. Full depth.' },
        { name: 'Trap Bar Shrug', sets: 3, reps: '20', rest: '1:00', cues: 'High reps, pull shoulders to ears. Hold 1 sec at the top.' },
        { name: 'Close Grip Bench Press', sets: 3, reps: '12', rest: '1:00', cues: 'Hands shoulder-width. Targets triceps. Full lockout.' },
        { name: 'Seated Behind-the-Neck Press', sets: 3, reps: '10', rest: '1:00', cues: 'Light to moderate weight. Lower behind the head to ear level, press up.' },
      ],
    },
    {
      day: 'Day 23',
      title: 'W5 · Core & Arms',
      warmup: 'Jump rope EMOM 10 min — :40 on, :20 off each minute',
      duration: '55 min',
      exercises: [
        { name: 'EZ Bar Curl — Arm Blaster', sets: 4, reps: '10', rest: '1:30', cues: 'Alternate grip each set (wide/narrow). Arm blaster locks elbows in place.' },
        { name: '1a. Cable Overhead Tricep Extension', sets: 4, reps: '12 / 12 / 10 / 10', rest: '0:30', cues: 'Face away from cable. Extend overhead, squeeze triceps.' },
        { name: '1b. Reverse Barbell Curl', sets: 4, reps: '10', rest: '1:00', cues: 'Overhand grip. Slow and controlled. Forearm and brachialis.' },
        { name: '2a. Farmer Carry — Fat Grips', sets: 3, reps: '30 yards', rest: '0:30', cues: 'Fat grips make it harder. Walk tall, grip hard, core braced.' },
        { name: '2b. Dumbbell Wrist Rotation', sets: 3, reps: '20 each', rest: '1:00', cues: 'Rotate the wrists slowly with light dumbbells. Forearm endurance.' },
        { name: '3a. Hanging Leg Raise', sets: 3, reps: '10', rest: '0:30', cues: 'Controlled. No swinging. Full range.' },
        { name: '3b. Med Ball Slam', sets: 3, reps: '10', rest: '1:00', cues: 'Full extension overhead, slam into the ground. Explosive.' },
        { name: '4a. GHD Sit-Up', sets: 3, reps: '12', rest: '0:30', cues: 'Glute-ham developer. Full range of motion. Control the eccentric.' },
        { name: '4b. Hyper Extension', sets: 3, reps: '12', rest: '1:00', cues: 'Hinge at hips, squeeze glutes and hamstrings at top.' },
        { name: 'Bike Intervals', sets: 8, reps: ':20 on / :10 off', rest: '0:10', cues: 'Tabata-style on the bike. All-out for 20 seconds, rest 10 seconds. 8 rounds.' },
      ],
    },
    {
      day: 'Day 24',
      title: 'W5 · Lower Body II',
      warmup: 'Mini hurdle hops (double & single leg) 2× each · Lateral ice skater jump into box jump 3×3 each side',
      duration: '65 min',
      exercises: [
        { name: 'Trap Bar Deadlift', sets: 4, reps: '10 / 8 / 6 / 4', rest: '2:00', cues: 'Drive through the floor. Lock out at the top. Increase weight each set.' },
        { name: 'Seated Box Jump', sets: 4, reps: '2', rest: '1:30', cues: 'Start seated, explode onto the box from a dead stop. No momentum.' },
        { name: '1a. Banded Hamstring Kick', sets: 4, reps: ':10 each', rest: '0:30', cues: 'Band around ankle, kick back rapidly for 10 seconds each leg.' },
        { name: '1b. Front Foot Elevated Smith Machine Reverse Lunge', sets: 4, reps: '7 each', rest: '1:30', cues: 'Front foot on a plate. Step back, deep lunge. Drive through front heel.' },
        { name: '2a. Single Leg Leg Extension', sets: 3, reps: '12 each', rest: '0:30', cues: 'Full lockout, squeeze the quad.' },
        { name: '2b. Single Leg Hamstring Curl', sets: 3, reps: '12 each', rest: '1:30', cues: 'Slow and controlled on each leg. Full range.' },
        { name: '3a. Lateral Sled Pull — Crossover Step', sets: 3, reps: '20 yards', rest: '0:30', cues: 'Side-facing, crossover steps while pulling the sled. Athletic movement.' },
        { name: '3b. Calf Raise', sets: 3, reps: '15', rest: '0:30', cues: 'Full range — stretch and squeeze.' },
        { name: '3c. Copenhagen Plank', sets: 3, reps: ':20 each', rest: '1:00', cues: 'Top leg on bench, bottom hanging. Hold and squeeze adductors.' },
      ],
    },
    {
      day: 'Day 25',
      title: 'W5 · Upper Body II',
      warmup: '2 rounds: row 15 cal, DB external rotation off knee 10 each, inverted row ×12, band pull-apart ×15',
      duration: '70 min',
      exercises: [
        { name: 'Barbell Push Press', sets: 5, reps: '5 / 4 / 3 / 3 / 2', rest: '2:00', cues: 'Quarter dip, drive explosively through the legs. Lock out overhead. Build weight each set.' },
        { name: '1a. Incline Barbell Bench Press', sets: 4, reps: '8 / 6 / 6 / 4', rest: '1:00', cues: '30-degree incline. Control the eccentric. Drive hard off the chest.' },
        { name: '1b. Chest-Supported Dumbbell Row', sets: 4, reps: '10', rest: '1:30', cues: 'Incline bench, chest down. Pull to hip, squeeze the back hard.' },
        { name: '2a. Dumbbell Z-Press', sets: 4, reps: '8 each', rest: '1:00', cues: 'Seated on the floor, legs extended. No back support — pure shoulder and core.' },
        { name: '2b. Landmine Row', sets: 4, reps: '10 each', rest: '1:30', cues: 'Staggered stance, pull the barbell to hip. Squeeze the lat at the top.' },
        { name: '3a. Dumbbell Fly', sets: 3, reps: '12', rest: '0:30', cues: 'Slight bend in elbows. Full stretch, squeeze at the top.' },
        { name: '3b. Straight-Arm Cable Pulldown', sets: 3, reps: '15', rest: '0:30', cues: 'Arms straight, pull to thighs. Squeeze the lats throughout.' },
        { name: '3c. Plate Pinch Carry', sets: 3, reps: '30 yards', rest: '1:00', cues: 'Pinch two plates together in each hand. Walk tall. Grip strength finisher.' },
        { name: '4a. Spider Curl', sets: 3, reps: '12', rest: '0:30', cues: 'Chest against the incline bench. No momentum — strict bicep isolation.' },
        { name: '4b. Cable Rope Tricep Extension', sets: 3, reps: '15', rest: '0:30', cues: 'Split the rope at the bottom. Squeeze the triceps hard.' },
        { name: '4c. Wrist Roller', sets: 3, reps: '2 up + 2 down', rest: '1:00', cues: 'Roll weight up, then down. Forearms should be screaming.' },
      ],
    },

    // ═══════════════════════════════════════
    //  WEEK 6 — PEAK
    // ═══════════════════════════════════════
    {
      day: 'Day 26',
      title: 'W6 · Lower Body',
      warmup: 'Depth drop to broad jump 2×3 · Single leg bounding 2×20 yards · Lateral shuffle to sprint 2×3 each',
      duration: '70 min',
      exercises: [
        { name: 'Barbell Back Squat — Heavy', sets: 5, reps: '5 / 3 / 3 / 2 / 2', rest: '3:00', cues: 'Peak week. Work up to your heaviest double. Brace hard, fight for depth. This is what 6 weeks built to.' },
        { name: 'Box Jump — Max Height', sets: 4, reps: '2', rest: '2:00', cues: 'Highest box you can land safely. Full hip extension at the top. Step down.' },
        { name: '1a. Barbell Front Squat — Pause', sets: 4, reps: '4', rest: '1:00', cues: '2-second pause in the hole. Elbows high, chest up. Drive out with authority.' },
        { name: '1b. Banded TKE', sets: 4, reps: '15 each', rest: '1:30', cues: 'Terminal knee extension. Full lockout, squeeze the VMO.' },
        { name: '2a. Barbell Hip Thrust — Heavy', sets: 4, reps: '8', rest: '1:00', cues: 'Heaviest hip thrust of the program. Full lockout, squeeze 2 seconds at the top.' },
        { name: '2b. Nordic Hamstring Curl', sets: 4, reps: '5', rest: '1:30', cues: 'Slow eccentric. Lower as far as you can control. Use hands to catch if needed.' },
        { name: '3a. Heavy Sled Push', sets: 3, reps: '30 yards', rest: '1:00', cues: 'Load it heavy. Low body angle, short powerful steps. All-out effort.' },
        { name: '3b. Calf Raise — Slow Eccentric', sets: 3, reps: '12', rest: '0:30', cues: '3-second lowering phase. Full stretch at the bottom.' },
        { name: '3c. Hanging Knee Raise', sets: 3, reps: '15', rest: '1:00', cues: 'Controlled. Curl the pelvis under at the top. No swinging.' },
      ],
    },
    {
      day: 'Day 27',
      title: 'W6 · Upper Body',
      warmup: '2 rounds: band pull-apart ×15, push-up walkout ×5, DB hang clean ×8 each, dead hang :30',
      duration: '70 min',
      exercises: [
        { name: 'Barbell Bench Press — Heavy', sets: 5, reps: '5 / 3 / 2 / 2 / 1', rest: '3:00', cues: 'Peak week. Build to your heaviest single. Shoulder blades locked, full-body tension. Make it count.' },
        { name: 'Barbell Hang Clean', sets: 4, reps: '3', rest: '2:00', cues: 'Explosive triple extension. Catch in a solid front rack. Reset every rep.' },
        { name: '1a. Weighted Pull-Up — Heavy', sets: 4, reps: '5 / 4 / 3 / 3', rest: '1:00', cues: 'Heaviest pull-ups of the program. Full dead hang, chest to bar.' },
        { name: '1b. Dumbbell Incline Press', sets: 4, reps: '8', rest: '1:30', cues: '30-degree incline. Heavy dumbbells. Full stretch, explosive press.' },
        { name: '2a. Barbell Bent-Over Row — Heavy', sets: 4, reps: '6', rest: '1:00', cues: 'Heaviest rows of the program. Pull to lower chest. Squeeze for a beat.' },
        { name: '2b. Seated Dumbbell Shoulder Press', sets: 4, reps: '8', rest: '1:30', cues: 'Heavy. Full lockout overhead. Controlled descent.' },
        { name: '3a. Cable Crossover', sets: 3, reps: '12', rest: '0:30', cues: 'Squeeze at the center. Full stretch on the way back.' },
        { name: '3b. Seated Cable Row — Wide Grip', sets: 3, reps: '12', rest: '0:30', cues: 'Wide grip attachment. Pull to upper chest. Squeeze upper back.' },
        { name: '3c. Dumbbell Shrug', sets: 3, reps: '15', rest: '1:00', cues: 'Heavy. Pull shoulders straight up to ears. Hold 1 second.' },
        { name: '4a. Barbell Curl', sets: 3, reps: '10', rest: '0:30', cues: 'Strict. No swinging. Peak squeeze at the top.' },
        { name: '4b. Close-Grip Bench Press', sets: 3, reps: '10', rest: '1:00', cues: 'Hands shoulder-width. Press through the triceps. Full lockout.' },
      ],
    },
    {
      day: 'Day 28',
      title: 'W6 · Core & Arms',
      warmup: 'Jump rope 5 min — mix singles, doubles, crossovers. Then 2 rounds: plank shoulder tap ×10, dead bug ×10 each',
      duration: '55 min',
      exercises: [
        { name: 'EZ Bar Curl — Heavy', sets: 4, reps: '8 / 6 / 6 / 4', rest: '1:30', cues: 'Peak bicep work. Build weight each set. Strict form — no body english.' },
        { name: '1a. Dip — Weighted', sets: 4, reps: '8 / 6 / 6 / 4', rest: '1:00', cues: 'Belt or DB between legs. Full depth. Drive to full lockout.' },
        { name: '1b. Incline Dumbbell Curl', sets: 4, reps: '10', rest: '1:00', cues: '45-degree bench. Full stretch at the bottom. Slow and controlled.' },
        { name: '2a. Farmer Carry — Max Weight', sets: 3, reps: '40 yards', rest: '1:00', cues: 'Heaviest you can carry with good posture. Walk tall, crush the handles.' },
        { name: '2b. Plate Pinch Hold', sets: 3, reps: ':30', rest: '1:00', cues: 'Pinch two plates together. Hold as long as possible. Grip endurance.' },
        { name: '3a. Dragon Flag', sets: 3, reps: '5', rest: '0:30', cues: 'Shoulders on bench, lower body rigid. Lower slowly. The ultimate core test.' },
        { name: '3b. Ab Wheel Rollout — Full Extension', sets: 3, reps: '10', rest: '0:30', cues: 'Full extension from the knees. Don\'t let hips sag. Pull back with the abs.' },
        { name: '3c. Pallof Press — Hold', sets: 3, reps: ':20 each side', rest: '1:00', cues: 'Press out, hold. Resist the rotation. Brace the whole time.' },
        { name: '4a. Rope Hammer Curl', sets: 3, reps: '12', rest: '0:30', cues: 'Cable rope attachment. Neutral grip. Squeeze hard at the top.' },
        { name: '4b. Overhead Tricep Extension — EZ Bar', sets: 3, reps: '12', rest: '0:30', cues: 'Behind the head, elbows forward. Full extension at the top.' },
        { name: 'Assault Bike — Tabata Finisher', sets: 8, reps: ':20 on / :10 off', rest: '0:10', cues: 'Final Tabata of the program. Leave nothing in the tank. 8 rounds of war.' },
      ],
    },
    {
      day: 'Day 29',
      title: 'W6 · Lower Body II',
      warmup: 'Mini hurdle hops (double & single leg) 2× each · Depth jump to sprint 3×2 · A-skips ×20 yards',
      duration: '65 min',
      exercises: [
        { name: 'Trap Bar Deadlift — Heavy', sets: 5, reps: '5 / 3 / 3 / 2 / 1', rest: '3:00', cues: 'Peak week. Build to your heaviest single. Grip hard, drive the floor away. 6 weeks led here.' },
        { name: 'Depth Jump to Box Jump', sets: 4, reps: '3', rest: '2:00', cues: 'Step off a low box, land, immediately explode onto a taller box. Reactive power.' },
        { name: '1a. Barbell Reverse Lunge — Deficit', sets: 4, reps: '6 each', rest: '1:00', cues: 'Front foot on a plate for extra range. Step back, drive through front heel.' },
        { name: '1b. Leg Curl — Slow Eccentric', sets: 4, reps: '8', rest: '1:30', cues: '4-second lowering phase. Squeeze hard at the top. Own every rep.' },
        { name: '2a. Leg Press — Heavy', sets: 4, reps: '10 / 8 / 6 / 6', rest: '1:00', cues: 'Build weight each set. Full depth without lower back rounding.' },
        { name: '2b. Single Leg Calf Raise', sets: 4, reps: '12 each', rest: '1:00', cues: 'Full stretch at the bottom. Hold at the top. No cheating.' },
        { name: '3a. Sled Push Sprint', sets: 3, reps: '25 yards', rest: '1:00', cues: 'Moderate weight, maximum speed. Sprint through the sled.' },
        { name: '3b. GHD Back Extension', sets: 3, reps: '15', rest: '0:30', cues: 'Posterior chain finisher. Squeeze glutes and hamstrings at the top.' },
        { name: '3c. Weighted Plank', sets: 3, reps: ':45', rest: '1:00', cues: 'Plate on your back. Straight line. Brace hard. Final plank of the program — hold it.' },
      ],
    },
    {
      day: 'Day 30',
      title: 'W6 · Upper Body II',
      warmup: '2 rounds: banded face pull ×15, push-up to rotation ×8 each, DB hang snatch ×5 each, dead hang :30',
      duration: '70 min',
      exercises: [
        { name: 'Barbell Overhead Press — Heavy', sets: 5, reps: '5 / 3 / 3 / 2 / 1', rest: '3:00', cues: 'Peak overhead strength. Build to your heaviest single. Strict press — no leg drive. Lock it out.' },
        { name: '1a. Weighted Dip — Heavy', sets: 4, reps: '6 / 5 / 4 / 3', rest: '1:00', cues: 'Heaviest dips of the program. Full depth, powerful press.' },
        { name: '1b. T-Bar Row — Heavy', sets: 4, reps: '8 / 6 / 6 / 4', rest: '1:30', cues: 'Build weight. Pull to chest, squeeze for a full second at the top.' },
        { name: '2a. Dumbbell Flat Bench Press', sets: 4, reps: '8', rest: '1:00', cues: 'Heavy dumbbells. Full stretch at the bottom. Drive hard.' },
        { name: '2b. Barbell Pendlay Row', sets: 4, reps: '6', rest: '1:30', cues: 'Dead stop from the floor every rep. Explosive pull to chest. No cheating.' },
        { name: '3a. Lateral Raise — 21s', sets: 3, reps: '21 (7 bottom half + 7 top half + 7 full)', rest: '1:00', cues: 'The shoulder finisher. 7 partial bottom, 7 partial top, 7 full range. Don\'t drop them.' },
        { name: '3b. Seated Cable Reverse Fly', sets: 3, reps: '15', rest: '0:30', cues: 'Face the cable stack. Pull wide, squeeze rear delts. Control back.' },
        { name: '3c. Heavy Kettlebell Suitcase Carry', sets: 3, reps: '30 yards each', rest: '1:00', cues: 'Heaviest kettlebell you can carry. Walk tall, fight the lean. Core and grip finisher.' },
        { name: '4a. Preacher Curl', sets: 3, reps: '10', rest: '0:30', cues: 'Strict. Full stretch at the bottom. Squeeze the peak.' },
        { name: '4b. Overhead Dumbbell Tricep Extension', sets: 3, reps: '12', rest: '0:30', cues: 'One heavy dumbbell behind the head. Elbows forward. Full extension.' },
        { name: '4c. Wrist Curl + Reverse Wrist Curl', sets: 3, reps: '15 each', rest: '1:00', cues: 'Forearms on thighs, curl the wrists. Both directions. Last arm work of the program — earn it.' },
      ],
    },
  ],
}
