import type { Program } from './programs'

const COOLDOWN =
  'Pitcher Mobility Reset: 90/90 hip breathing, adductor rock-back, couch stretch, ankle mobilization, open-book T-spine rotation, lat stretch. 5-8 min; never force shoulder range.'

const PHASE_1_WARMUP =
  'Phase I — Build the Engine. Quality reps earn explosive reps. Rest enough for speed. Coordinate with throwing workload.'
const PHASE_2_WARMUP =
  'Phase II — Convert to Power. Higher velocity, reactive plyometrics, heavier fast strength. Coordinate with throwing workload.'
const PHASE_3_WARMUP =
  'Phase III — Unleash It. Peak intent, low volume, speed expression. Coordinate with throwing workload.'

export const baseballProgram: Program = {
  id: 'baseball-softball',
  name: 'Baseball / Softball',
  weeks: 6,
  frequency: '3x / week',
  description:
    '6-week sport-specific power program for baseball and softball athletes. Build the Engine → Convert to Power → Unleash It. Rotation, velocity, resilience.',
  category: 'baseball',
  days: [
    // ───────────────────────── Day 1 — W1D1 ─────────────────────────
    {
      day: 'Day 1',
      title: 'W1 · Lower Force + Acceleration',
      warmup: PHASE_1_WARMUP,
      duration: '60-85 min',
      sections: [
        { name: 'Warm-Up + Movement Prep', start: 0 },
        { name: 'Speed + Power', start: 5 },
        { name: 'Primary Strength', start: 10 },
        { name: 'Accessory + Core', start: 11 },
      ],
      exercises: [
        { name: '90/90 Hip Switch', sets: 2, reps: '6/side', rest: '0:30', cues: 'Controlled. Hip rotation' },
        { name: 'Adductor Rock Back', sets: 2, reps: '8/side', rest: '0:30', cues: 'Controlled. Groin/pelvis' },
        { name: 'Knee-to-Wall Ankle Mob', sets: 2, reps: '8/side', rest: '0:30', cues: 'Controlled. Ankle ROM' },
        { name: "World's Greatest Stretch + T-Spine", sets: 1, reps: '5/side', rest: '0:30', cues: 'Controlled. Integrated mobility' },
        { name: 'A-Skip', sets: 2, reps: '15 yd', rest: '0:45', cues: 'Crisp. Sprint rhythm' },
        { name: 'Pogos', sets: 2, reps: '15', rest: '0:45', cues: 'Elastic. Ankle stiffness' },
        { name: 'Countermovement Vertical Jump', sets: 3, reps: '3', rest: '1:00', cues: 'Max intent. Vertical force' },
        { name: 'Broad Jump + Stick', sets: 3, reps: '2', rest: '1:00', cues: 'Max intent. Horizontal force/landing' },
        { name: '10-Yard Acceleration', sets: 4, reps: '1', rest: '2:00', cues: '95-100%. First-step speed' },
        { name: 'Hang Clean', sets: 5, reps: '3', rest: '2:30', cues: 'RPE 6-7. Total-body power' },
        { name: 'Back Squat', sets: 4, reps: '5', rest: '2:30', cues: '70-75%. Lower-body force' },
        { name: 'RFESS', sets: 3, reps: '6/leg', rest: '1:30', cues: 'RPE 7. Unilateral strength' },
        { name: 'Single-Leg DB RDL', sets: 3, reps: '6/leg', rest: '1:30', cues: 'RPE 7. Posterior-chain control' },
        { name: 'Nordic Hamstring', sets: 3, reps: '4', rest: '1:30', cues: 'Controlled eccentric. Hamstring resilience' },
        { name: 'Dead Bug + Pullover', sets: 3, reps: '6/side', rest: '0:45', cues: 'Controlled. Rib/pelvis control' },
        { name: 'Pallof Press', sets: 3, reps: '8/side', rest: '0:45', cues: 'Moderate. Anti-rotation' },
        { name: 'Farmer Carry', sets: 3, reps: '25 yd', rest: '1:00', cues: 'Heavy. Grip + trunk' },
        { name: 'Towel Hang', sets: 2, reps: '20-30s', rest: '1:00', cues: 'Quality hold. Grip endurance' },
      ],
      cooldown: COOLDOWN,
    },

    // ───────────────────────── Day 2 — W1D2 ─────────────────────────
    {
      day: 'Day 2',
      title: 'W1 · Rotational Power + Upper Strength',
      warmup: PHASE_1_WARMUP,
      duration: '60-85 min',
      sections: [
        { name: 'Warm-Up + Arm Prep', start: 0 },
        { name: 'Rotational Power', start: 5 },
        { name: 'Primary Strength', start: 8 },
        { name: 'Accessory + Arm Care', start: 11 },
      ],
      exercises: [
        { name: 'Quadruped T-Spine Rotation', sets: 2, reps: '6/side', rest: '0:30', cues: 'Controlled. T-spine rotation' },
        { name: 'Serratus Wall Slide', sets: 2, reps: '8', rest: '0:30', cues: 'Smooth. Scap upward rotation' },
        { name: 'Band Pull-Apart', sets: 2, reps: '15', rest: '0:30', cues: 'Light. Posterior shoulder' },
        { name: 'Band External Rotation', sets: 2, reps: '10/side', rest: '0:30', cues: 'Light. Rotator cuff' },
        { name: 'Scap Push-Up', sets: 2, reps: '10', rest: '0:30', cues: 'Bodyweight. Serratus control' },
        { name: 'Step-Behind Scoop Toss', sets: 4, reps: '3/side', rest: '1:00', cues: 'Max velocity. Rotational power' },
        { name: 'Med-Ball Shot-Put', sets: 3, reps: '3/side', rest: '1:00', cues: 'Max velocity. Horizontal rotational power' },
        { name: 'Half-Kneeling Rotational Throw', sets: 3, reps: '3/side', rest: '1:00', cues: 'Fast. Hip/trunk separation' },
        { name: 'Bench Press', sets: 4, reps: '5', rest: '2:00', cues: 'RPE 7. Upper strength' },
        { name: 'Neutral-Grip Pull-Up', sets: 4, reps: '5', rest: '1:30', cues: 'RPE 7. Vertical pull' },
        { name: '1-Arm Landmine Press', sets: 3, reps: '6/side', rest: '1:15', cues: 'RPE 7. Scap-friendly press' },
        { name: 'Chest-Supported DB Row', sets: 3, reps: '8', rest: '1:15', cues: 'RPE 7. Posterior shoulder' },
        { name: 'Face Pull + ER', sets: 2, reps: '10', rest: '0:45', cues: 'Light. Scap/cuff' },
        { name: 'Prone Trap-3 Raise', sets: 2, reps: '8/side', rest: '0:45', cues: 'Light. Lower trap' },
        { name: 'Side Plank + Top-Leg Drive', sets: 2, reps: '20s/side', rest: '0:45', cues: 'Quality. Lateral trunk' },
        { name: 'Plate Pinch', sets: 3, reps: '20-30s', rest: '0:45', cues: 'Moderate. Grip' },
        { name: 'Pronation/Supination', sets: 2, reps: '10/side', rest: '0:45', cues: 'Light. Forearm capacity' },
      ],
      cooldown: COOLDOWN,
    },

    // ───────────────────────── Day 3 — W1D3 ─────────────────────────
    {
      day: 'Day 3',
      title: 'W1 · Lateral Power + Total Body',
      warmup: PHASE_1_WARMUP,
      duration: '60-85 min',
      sections: [
        { name: 'Warm-Up', start: 0 },
        { name: 'Speed + Power', start: 5 },
        { name: 'Primary Strength', start: 12 },
        { name: 'Accessory + Core', start: 13 },
      ],
      exercises: [
        { name: 'Assisted Hip Airplane', sets: 2, reps: '4/side', rest: '0:30', cues: 'Controlled. Hip control' },
        { name: 'Lateral Lunge', sets: 2, reps: '6/side', rest: '0:30', cues: 'Easy. Frontal-plane mobility' },
        { name: 'Adductor Rock Back', sets: 2, reps: '8', rest: '0:30', cues: 'Controlled. Groin mobility' },
        { name: 'Pogos', sets: 2, reps: '15', rest: '0:45', cues: 'Elastic. Ankle stiffness' },
        { name: 'Lateral Shuffle', sets: 2, reps: '10 yd', rest: '0:45', cues: 'Crisp. Lateral prep' },
        { name: 'Lateral Bound + Stick', sets: 3, reps: '3/side', rest: '1:00', cues: 'Max intent. Lateral force/decel' },
        { name: 'Pogo → Broad Jump', sets: 3, reps: '2', rest: '1:00', cues: 'Reactive. Elastic to horizontal' },
        { name: 'Split-Stance Jump', sets: 3, reps: '3/side', rest: '1:00', cues: 'Fast. Unilateral power' },
        { name: '5-Yard Lateral Start', sets: 3, reps: '1/side', rest: '1:15', cues: '95-100%. First-step lateral speed' },
        { name: '5-10-5 Technique', sets: 2, reps: '1', rest: '2:00', cues: 'Crisp. COD mechanics' },
        { name: 'Shuffle-to-Scoop Toss', sets: 3, reps: '3/side', rest: '1:00', cues: 'Max velocity. Dynamic rotation' },
        { name: 'Reverse Scoop Toss', sets: 3, reps: '3/side', rest: '1:00', cues: 'Max velocity. Posterior-chain rotation' },
        { name: 'Trap-Bar Deadlift', sets: 4, reps: '5', rest: '2:30', cues: 'RPE 7. Total-body force' },
        { name: 'FFE Reverse Lunge', sets: 3, reps: '6/leg', rest: '1:30', cues: 'RPE 7. Single-leg force' },
        { name: '1-Leg Hip Thrust', sets: 3, reps: '8/side', rest: '1:15', cues: 'RPE 7. Hip extension' },
        { name: 'Copenhagen Plank', sets: 3, reps: '15-20s/side', rest: '0:45', cues: 'Quality. Adductor/pelvis' },
        { name: 'Suitcase Carry', sets: 3, reps: '25 yd/side', rest: '1:00', cues: 'Heavy. Anti-lateral flexion' },
        { name: 'Dead Hang', sets: 2, reps: '20-30s', rest: '1:00', cues: 'Quality. Grip/shoulder decompression' },
      ],
      cooldown: COOLDOWN,
    },

    // ───────────────────────── Day 4 — W2D1 ─────────────────────────
    {
      day: 'Day 4',
      title: 'W2 · Lower Force + Acceleration',
      warmup: PHASE_1_WARMUP,
      duration: '60-85 min',
      sections: [
        { name: 'Warm-Up + Movement Prep', start: 0 },
        { name: 'Speed + Power', start: 5 },
        { name: 'Primary Strength', start: 10 },
        { name: 'Accessory + Core', start: 11 },
      ],
      exercises: [
        { name: '90/90 Hip Switch', sets: 2, reps: '6/side', rest: '0:30', cues: 'Controlled. Hip rotation' },
        { name: 'Adductor Rock Back', sets: 2, reps: '8/side', rest: '0:30', cues: 'Controlled. Groin/pelvis' },
        { name: 'Knee-to-Wall Ankle Mob', sets: 2, reps: '8/side', rest: '0:30', cues: 'Controlled. Ankle ROM' },
        { name: "World's Greatest Stretch + T-Spine", sets: 1, reps: '5/side', rest: '0:30', cues: 'Controlled. Integrated mobility' },
        { name: 'A-Skip', sets: 2, reps: '15 yd', rest: '0:45', cues: 'Crisp. Sprint rhythm' },
        { name: 'Pogos', sets: 2, reps: '15', rest: '0:45', cues: 'Elastic. Ankle stiffness' },
        { name: 'Countermovement Vertical Jump', sets: 3, reps: '3', rest: '1:00', cues: 'Max intent. Vertical force' },
        { name: 'Broad Jump + Stick', sets: 3, reps: '2', rest: '1:00', cues: 'Max intent. Horizontal force/landing' },
        { name: '10-Yard Acceleration', sets: 4, reps: '1', rest: '2:00', cues: '95-100%. First-step speed' },
        { name: 'Hang Clean', sets: 5, reps: '3', rest: '2:30', cues: 'RPE 7-8. Total-body power' },
        { name: 'Back Squat', sets: 4, reps: '5', rest: '2:30', cues: '75-80%. Lower-body force' },
        { name: 'RFESS', sets: 3, reps: '6/leg', rest: '1:30', cues: 'RPE 7. Unilateral strength' },
        { name: 'Single-Leg DB RDL', sets: 3, reps: '6/leg', rest: '1:30', cues: 'RPE 7. Posterior-chain control' },
        { name: 'Nordic Hamstring', sets: 3, reps: '5', rest: '1:30', cues: 'Controlled eccentric. Hamstring resilience' },
        { name: 'Dead Bug + Pullover', sets: 3, reps: '6/side', rest: '0:45', cues: 'Controlled. Rib/pelvis control' },
        { name: 'Pallof Press', sets: 3, reps: '8/side', rest: '0:45', cues: 'Moderate. Anti-rotation' },
        { name: 'Farmer Carry', sets: 3, reps: '25 yd', rest: '1:00', cues: 'Heavy. Grip + trunk' },
        { name: 'Towel Hang', sets: 2, reps: '20-30s', rest: '1:00', cues: 'Quality hold. Grip endurance' },
      ],
      cooldown: COOLDOWN,
    },

    // ───────────────────────── Day 5 — W2D2 ─────────────────────────
    {
      day: 'Day 5',
      title: 'W2 · Rotational Power + Upper Strength',
      warmup: PHASE_1_WARMUP,
      duration: '60-85 min',
      sections: [
        { name: 'Warm-Up + Arm Prep', start: 0 },
        { name: 'Rotational Power', start: 5 },
        { name: 'Primary Strength', start: 8 },
        { name: 'Accessory + Arm Care', start: 11 },
      ],
      exercises: [
        { name: 'Quadruped T-Spine Rotation', sets: 2, reps: '6/side', rest: '0:30', cues: 'Controlled. T-spine rotation' },
        { name: 'Serratus Wall Slide', sets: 2, reps: '8', rest: '0:30', cues: 'Smooth. Scap upward rotation' },
        { name: 'Band Pull-Apart', sets: 2, reps: '15', rest: '0:30', cues: 'Light. Posterior shoulder' },
        { name: 'Band External Rotation', sets: 2, reps: '10/side', rest: '0:30', cues: 'Light. Rotator cuff' },
        { name: 'Scap Push-Up', sets: 2, reps: '10', rest: '0:30', cues: 'Bodyweight. Serratus control' },
        { name: 'Step-Behind Scoop Toss', sets: 4, reps: '3/side', rest: '1:00', cues: 'Max velocity. Rotational power' },
        { name: 'Med-Ball Shot-Put', sets: 3, reps: '3/side', rest: '1:00', cues: 'Max velocity. Horizontal rotational power' },
        { name: 'Half-Kneeling Rotational Throw', sets: 3, reps: '3/side', rest: '1:00', cues: 'Fast. Hip/trunk separation' },
        { name: 'Bench Press', sets: 4, reps: '5', rest: '2:00', cues: 'RPE 7. Upper strength' },
        { name: 'Neutral-Grip Pull-Up', sets: 4, reps: '5', rest: '1:30', cues: 'RPE 7. Vertical pull' },
        { name: '1-Arm Landmine Press', sets: 3, reps: '6/side', rest: '1:15', cues: 'RPE 7. Scap-friendly press' },
        { name: 'Chest-Supported DB Row', sets: 3, reps: '8', rest: '1:15', cues: 'RPE 7. Posterior shoulder' },
        { name: 'Face Pull + ER', sets: 2, reps: '10', rest: '0:45', cues: 'Light. Scap/cuff' },
        { name: 'Prone Trap-3 Raise', sets: 2, reps: '8/side', rest: '0:45', cues: 'Light. Lower trap' },
        { name: 'Side Plank + Top-Leg Drive', sets: 2, reps: '20s/side', rest: '0:45', cues: 'Quality. Lateral trunk' },
        { name: 'Plate Pinch', sets: 3, reps: '20-30s', rest: '0:45', cues: 'Moderate. Grip' },
        { name: 'Pronation/Supination', sets: 2, reps: '10/side', rest: '0:45', cues: 'Light. Forearm capacity' },
      ],
      cooldown: COOLDOWN,
    },

    // ───────────────────────── Day 6 — W2D3 ─────────────────────────
    {
      day: 'Day 6',
      title: 'W2 · Lateral Power + Total Body',
      warmup: PHASE_1_WARMUP,
      duration: '60-85 min',
      sections: [
        { name: 'Warm-Up', start: 0 },
        { name: 'Speed + Power', start: 5 },
        { name: 'Primary Strength', start: 12 },
        { name: 'Accessory + Core', start: 13 },
      ],
      exercises: [
        { name: 'Assisted Hip Airplane', sets: 2, reps: '4/side', rest: '0:30', cues: 'Controlled. Hip control' },
        { name: 'Lateral Lunge', sets: 2, reps: '6/side', rest: '0:30', cues: 'Easy. Frontal-plane mobility' },
        { name: 'Adductor Rock Back', sets: 2, reps: '8', rest: '0:30', cues: 'Controlled. Groin mobility' },
        { name: 'Pogos', sets: 2, reps: '15', rest: '0:45', cues: 'Elastic. Ankle stiffness' },
        { name: 'Lateral Shuffle', sets: 2, reps: '10 yd', rest: '0:45', cues: 'Crisp. Lateral prep' },
        { name: 'Lateral Bound + Stick', sets: 3, reps: '3/side', rest: '1:00', cues: 'Max intent. Lateral force/decel' },
        { name: 'Pogo → Broad Jump', sets: 3, reps: '2', rest: '1:00', cues: 'Reactive. Elastic to horizontal' },
        { name: 'Split-Stance Jump', sets: 3, reps: '3/side', rest: '1:00', cues: 'Fast. Unilateral power' },
        { name: '5-Yard Lateral Start', sets: 3, reps: '1/side', rest: '1:15', cues: '95-100%. First-step lateral speed' },
        { name: '5-10-5 Technique', sets: 2, reps: '1', rest: '2:00', cues: 'Crisp. COD mechanics' },
        { name: 'Shuffle-to-Scoop Toss', sets: 3, reps: '3/side', rest: '1:00', cues: 'Max velocity. Dynamic rotation' },
        { name: 'Reverse Scoop Toss', sets: 3, reps: '3/side', rest: '1:00', cues: 'Max velocity. Posterior-chain rotation' },
        { name: 'Trap-Bar Deadlift', sets: 4, reps: '5', rest: '2:30', cues: 'RPE 7-8. Total-body force' },
        { name: 'FFE Reverse Lunge', sets: 3, reps: '6/leg', rest: '1:30', cues: 'RPE 7. Single-leg force' },
        { name: '1-Leg Hip Thrust', sets: 3, reps: '8/side', rest: '1:15', cues: 'RPE 7. Hip extension' },
        { name: 'Copenhagen Plank', sets: 3, reps: '15-20s/side', rest: '0:45', cues: 'Quality. Adductor/pelvis' },
        { name: 'Suitcase Carry', sets: 3, reps: '25 yd/side', rest: '1:00', cues: 'Heavy. Anti-lateral flexion' },
        { name: 'Dead Hang', sets: 2, reps: '20-30s', rest: '1:00', cues: 'Quality. Grip/shoulder decompression' },
      ],
      cooldown: COOLDOWN,
    },

    // ───────────────────────── Day 7 — W3D1 ─────────────────────────
    {
      day: 'Day 7',
      title: 'W3 · Vertical Power + Lower Strength',
      warmup: PHASE_2_WARMUP,
      duration: '60-85 min',
      sections: [
        { name: 'Warm-Up', start: 0 },
        { name: 'Speed + Power', start: 6 },
        { name: 'Primary Strength', start: 12 },
        { name: 'Accessory + Core', start: 13 },
      ],
      exercises: [
        { name: '90/90 Hip Switch', sets: 2, reps: '6/side', rest: '0:30', cues: 'Controlled. Hip rotation' },
        { name: 'Adductor Rock Back', sets: 2, reps: '8/side', rest: '0:30', cues: 'Controlled. Groin/pelvis' },
        { name: 'Knee-to-Wall Ankle Mob', sets: 2, reps: '8/side', rest: '0:30', cues: 'Controlled. Ankle ROM' },
        { name: "World's Greatest Stretch + T-Spine", sets: 1, reps: '5/side', rest: '0:30', cues: 'Controlled. Integrated mobility' },
        { name: 'A-Skip', sets: 2, reps: '15 yd', rest: '0:45', cues: 'Crisp. Sprint rhythm' },
        { name: 'Pogos', sets: 2, reps: '15', rest: '0:45', cues: 'Elastic. Ankle stiffness' },
        { name: 'Snap Down → Vertical Jump', sets: 3, reps: '3', rest: '1:00', cues: 'Max intent. Decel to vertical power' },
        { name: 'Hurdle Hop → Broad Jump', sets: 4, reps: '2', rest: '1:15', cues: 'Reactive. Elastic power' },
        { name: 'Single-Leg Pogo', sets: 2, reps: '10/side', rest: '0:45', cues: 'Elastic. Unilateral stiffness' },
        { name: 'Falling Start 10 yd', sets: 3, reps: '1', rest: '1:30', cues: '95-100%. Acceleration' },
        { name: '15-Yard Sprint', sets: 3, reps: '1', rest: '2:00', cues: '95-100%. Acceleration' },
        { name: 'Hang Clean', sets: 5, reps: '2', rest: '2:30', cues: 'Fast / RPE 7-8. Power' },
        { name: 'Back Squat', sets: 5, reps: '3', rest: '2:30', cues: '80-85%. Max force' },
        { name: 'RFESS', sets: 3, reps: '5/leg', rest: '1:30', cues: 'RPE 8. Unilateral force' },
        { name: 'Single-Leg RDL', sets: 3, reps: '5/leg', rest: '1:30', cues: 'RPE 7-8. Hip control' },
        { name: 'Nordic Curl', sets: 3, reps: '5', rest: '1:30', cues: 'Controlled. Hamstring' },
        { name: 'Pallof ISO', sets: 3, reps: '20s/side', rest: '0:45', cues: 'Moderate. Anti-rotation' },
        { name: 'Farmer Carry', sets: 4, reps: '20 yd', rest: '1:00', cues: 'Heavy. Grip + trunk' },
      ],
      cooldown: COOLDOWN,
    },

    // ───────────────────────── Day 8 — W3D2 ─────────────────────────
    {
      day: 'Day 8',
      title: 'W3 · High-Velocity Rotational Power',
      warmup: PHASE_2_WARMUP,
      duration: '60-85 min',
      sections: [
        { name: 'Warm-Up + Arm Prep', start: 0 },
        { name: 'Rotational Power', start: 5 },
        { name: 'Primary Strength', start: 9 },
        { name: 'Accessory + Arm Care', start: 12 },
      ],
      exercises: [
        { name: 'Quadruped T-Spine Rotation', sets: 2, reps: '6/side', rest: '0:30', cues: 'Controlled. T-spine rotation' },
        { name: 'Serratus Wall Slide', sets: 2, reps: '8', rest: '0:30', cues: 'Smooth. Scap upward rotation' },
        { name: 'Band Pull-Apart', sets: 2, reps: '15', rest: '0:30', cues: 'Light. Posterior shoulder' },
        { name: 'Band External Rotation', sets: 2, reps: '10/side', rest: '0:30', cues: 'Light. Rotator cuff' },
        { name: 'Scap Push-Up', sets: 2, reps: '10', rest: '0:30', cues: 'Bodyweight. Serratus control' },
        { name: 'Step-Behind Rotational Shot Put', sets: 4, reps: '3/side', rest: '1:00', cues: 'Max velocity. Rotational power' },
        { name: 'Scoop Toss', sets: 4, reps: '3/side', rest: '1:00', cues: 'Max velocity. Rotational power' },
        { name: 'Walk-In Shot Put', sets: 3, reps: '2/side', rest: '1:00', cues: 'Max velocity. Momentum transfer' },
        { name: 'Pivot-Pickoff Rotational Throw', sets: 3, reps: '3/side', rest: '1:00', cues: 'Fast. Quick hip/trunk action' },
        { name: 'Bench Press', sets: 4, reps: '4', rest: '2:00', cues: 'RPE 7-8. Upper strength' },
        { name: 'Weighted Neutral-Grip Pull-Up', sets: 4, reps: '4-5', rest: '1:30', cues: 'RPE 8. Vertical pull' },
        { name: 'Landmine Press', sets: 3, reps: '5/side', rest: '1:15', cues: 'RPE 7. Scap-friendly press' },
        { name: '1-Arm DB Row', sets: 3, reps: '6/side', rest: '1:15', cues: 'RPE 8. Upper-back strength' },
        { name: 'Cable Face Pull', sets: 2, reps: '12', rest: '0:45', cues: 'Light. Scapular control' },
        { name: 'Prone Y', sets: 2, reps: '8', rest: '0:45', cues: 'Light. Lower trap' },
        { name: 'Split-Stance Pallof', sets: 3, reps: '8/side', rest: '0:45', cues: 'Moderate. Anti-rotation' },
        { name: 'Plate Pinch Carry', sets: 3, reps: '20 yd', rest: '0:45', cues: 'Moderate. Grip' },
        { name: 'Finger Extension Band', sets: 2, reps: '20', rest: '0:30', cues: 'Light. Forearm balance' },
      ],
      cooldown: COOLDOWN,
    },

    // ───────────────────────── Day 9 — W3D3 ─────────────────────────
    {
      day: 'Day 9',
      title: 'W3 · Lateral Explosiveness + Total Body',
      warmup: PHASE_2_WARMUP,
      duration: '60-85 min',
      sections: [
        { name: 'Warm-Up', start: 0 },
        { name: 'Speed + Power', start: 5 },
        { name: 'Primary Strength', start: 13 },
        { name: 'Accessory + Core', start: 14 },
      ],
      exercises: [
        { name: 'Assisted Hip Airplane', sets: 2, reps: '4/side', rest: '0:30', cues: 'Controlled. Hip control' },
        { name: 'Lateral Lunge', sets: 2, reps: '6/side', rest: '0:30', cues: 'Easy. Frontal-plane mobility' },
        { name: 'Adductor Rock Back', sets: 2, reps: '8', rest: '0:30', cues: 'Controlled. Groin mobility' },
        { name: 'Pogos', sets: 2, reps: '15', rest: '0:45', cues: 'Elastic. Ankle stiffness' },
        { name: 'Lateral Shuffle', sets: 2, reps: '10 yd', rest: '0:45', cues: 'Crisp. Lateral prep' },
        { name: 'Continuous Lateral Bound', sets: 3, reps: '4/side', rest: '1:00', cues: 'Reactive. Lateral elastic power' },
        { name: 'Lateral Bound → Vertical Jump', sets: 3, reps: '3/side', rest: '1:15', cues: 'Max intent. Force redirection' },
        { name: 'Split Jump', sets: 3, reps: '3/side', rest: '1:00', cues: 'Fast. Unilateral power' },
        { name: 'Crossover Start 10 yd', sets: 3, reps: '1/side', rest: '1:30', cues: '95-100%. Lateral acceleration' },
        { name: 'Pro Agility', sets: 3, reps: '1', rest: '2:30', cues: '95-100%. COD' },
        { name: 'Shuffle Scoop Toss', sets: 4, reps: '3/side', rest: '1:00', cues: 'Max velocity. Dynamic rotation' },
        { name: 'Reverse Scoop Toss', sets: 3, reps: '3/side', rest: '1:00', cues: 'Max velocity. Rotational power' },
        { name: 'Power Clean from Floor', sets: 5, reps: '2', rest: '2:30', cues: 'Fast / RPE 7-8. Total-body power' },
        { name: 'Trap-Bar Deadlift', sets: 4, reps: '3', rest: '2:30', cues: 'RPE 8. Max force' },
        { name: 'Reverse Lunge', sets: 3, reps: '5/side', rest: '1:30', cues: 'RPE 8. Single-leg force' },
        { name: 'Lateral Lunge', sets: 3, reps: '5/side', rest: '1:15', cues: 'RPE 7. Frontal-plane strength' },
        { name: 'Copenhagen Plank', sets: 3, reps: '20-25s/side', rest: '0:45', cues: 'Quality. Adductor/pelvis' },
        { name: 'Suitcase Carry', sets: 3, reps: '25 yd/side', rest: '1:00', cues: 'Heavy. Grip + trunk' },
      ],
      cooldown: COOLDOWN,
    },

    // ───────────────────────── Day 10 — W4D1 ─────────────────────────
    {
      day: 'Day 10',
      title: 'W4 · Vertical Power + Lower Strength',
      warmup: PHASE_2_WARMUP,
      duration: '60-85 min',
      sections: [
        { name: 'Warm-Up', start: 0 },
        { name: 'Speed + Power', start: 6 },
        { name: 'Primary Strength', start: 12 },
        { name: 'Accessory + Core', start: 13 },
      ],
      exercises: [
        { name: '90/90 Hip Switch', sets: 2, reps: '6/side', rest: '0:30', cues: 'Controlled. Hip rotation' },
        { name: 'Adductor Rock Back', sets: 2, reps: '8/side', rest: '0:30', cues: 'Controlled. Groin/pelvis' },
        { name: 'Knee-to-Wall Ankle Mob', sets: 2, reps: '8/side', rest: '0:30', cues: 'Controlled. Ankle ROM' },
        { name: "World's Greatest Stretch + T-Spine", sets: 1, reps: '5/side', rest: '0:30', cues: 'Controlled. Integrated mobility' },
        { name: 'A-Skip', sets: 2, reps: '15 yd', rest: '0:45', cues: 'Crisp. Sprint rhythm' },
        { name: 'Pogos', sets: 2, reps: '15', rest: '0:45', cues: 'Elastic. Ankle stiffness' },
        { name: 'Snap Down → Vertical Jump', sets: 3, reps: '3', rest: '1:00', cues: 'Max intent. Decel to vertical power' },
        { name: 'Hurdle Hop → Broad Jump', sets: 4, reps: '2', rest: '1:15', cues: 'Reactive. Elastic power' },
        { name: 'Single-Leg Pogo', sets: 2, reps: '10/side', rest: '0:45', cues: 'Elastic. Unilateral stiffness' },
        { name: 'Falling Start 10 yd', sets: 3, reps: '1', rest: '1:30', cues: '95-100%. Acceleration' },
        { name: '15-Yard Sprint', sets: 3, reps: '1', rest: '2:00', cues: '95-100%. Acceleration' },
        { name: 'Hang Clean', sets: 5, reps: '2', rest: '2:30', cues: 'Fast / RPE 8. Power' },
        { name: 'Back Squat', sets: 5, reps: '3', rest: '2:30', cues: '82-87%. Max force' },
        { name: 'RFESS', sets: 3, reps: '5/leg', rest: '1:30', cues: 'RPE 8. Unilateral force' },
        { name: 'Single-Leg RDL', sets: 3, reps: '5/leg', rest: '1:30', cues: 'RPE 7-8. Hip control' },
        { name: 'Nordic Curl', sets: 3, reps: '5', rest: '1:30', cues: 'Controlled. Hamstring' },
        { name: 'Pallof ISO', sets: 3, reps: '20s/side', rest: '0:45', cues: 'Moderate. Anti-rotation' },
        { name: 'Farmer Carry', sets: 4, reps: '20 yd', rest: '1:00', cues: 'Heavy. Grip + trunk' },
      ],
      cooldown: COOLDOWN,
    },

    // ───────────────────────── Day 11 — W4D2 ─────────────────────────
    {
      day: 'Day 11',
      title: 'W4 · High-Velocity Rotational Power',
      warmup: PHASE_2_WARMUP,
      duration: '60-85 min',
      sections: [
        { name: 'Warm-Up + Arm Prep', start: 0 },
        { name: 'Rotational Power', start: 5 },
        { name: 'Primary Strength', start: 9 },
        { name: 'Accessory + Arm Care', start: 12 },
      ],
      exercises: [
        { name: 'Quadruped T-Spine Rotation', sets: 2, reps: '6/side', rest: '0:30', cues: 'Controlled. T-spine rotation' },
        { name: 'Serratus Wall Slide', sets: 2, reps: '8', rest: '0:30', cues: 'Smooth. Scap upward rotation' },
        { name: 'Band Pull-Apart', sets: 2, reps: '15', rest: '0:30', cues: 'Light. Posterior shoulder' },
        { name: 'Band External Rotation', sets: 2, reps: '10/side', rest: '0:30', cues: 'Light. Rotator cuff' },
        { name: 'Scap Push-Up', sets: 2, reps: '10', rest: '0:30', cues: 'Bodyweight. Serratus control' },
        { name: 'Step-Behind Rotational Shot Put', sets: 4, reps: '3/side', rest: '1:00', cues: 'Max velocity. Rotational power' },
        { name: 'Scoop Toss', sets: 4, reps: '3/side', rest: '1:00', cues: 'Max velocity. Rotational power' },
        { name: 'Walk-In Shot Put', sets: 3, reps: '2/side', rest: '1:00', cues: 'Max velocity. Momentum transfer' },
        { name: 'Pivot-Pickoff Rotational Throw', sets: 3, reps: '3/side', rest: '1:00', cues: 'Fast. Quick hip/trunk action' },
        { name: 'Bench Press', sets: 4, reps: '4', rest: '2:00', cues: 'RPE 7-8. Upper strength' },
        { name: 'Weighted Neutral-Grip Pull-Up', sets: 4, reps: '4-5', rest: '1:30', cues: 'RPE 8. Vertical pull' },
        { name: 'Landmine Press', sets: 3, reps: '5/side', rest: '1:15', cues: 'RPE 7. Scap-friendly press' },
        { name: '1-Arm DB Row', sets: 3, reps: '6/side', rest: '1:15', cues: 'RPE 8. Upper-back strength' },
        { name: 'Cable Face Pull', sets: 2, reps: '12', rest: '0:45', cues: 'Light. Scapular control' },
        { name: 'Prone Y', sets: 2, reps: '8', rest: '0:45', cues: 'Light. Lower trap' },
        { name: 'Split-Stance Pallof', sets: 3, reps: '8/side', rest: '0:45', cues: 'Moderate. Anti-rotation' },
        { name: 'Plate Pinch Carry', sets: 3, reps: '20 yd', rest: '0:45', cues: 'Moderate. Grip' },
        { name: 'Finger Extension Band', sets: 2, reps: '20', rest: '0:30', cues: 'Light. Forearm balance' },
      ],
      cooldown: COOLDOWN,
    },

    // ───────────────────────── Day 12 — W4D3 ─────────────────────────
    {
      day: 'Day 12',
      title: 'W4 · Lateral Explosiveness + Total Body',
      warmup: PHASE_2_WARMUP,
      duration: '60-85 min',
      sections: [
        { name: 'Warm-Up', start: 0 },
        { name: 'Speed + Power', start: 5 },
        { name: 'Primary Strength', start: 13 },
        { name: 'Accessory + Core', start: 14 },
      ],
      exercises: [
        { name: 'Assisted Hip Airplane', sets: 2, reps: '4/side', rest: '0:30', cues: 'Controlled. Hip control' },
        { name: 'Lateral Lunge', sets: 2, reps: '6/side', rest: '0:30', cues: 'Easy. Frontal-plane mobility' },
        { name: 'Adductor Rock Back', sets: 2, reps: '8', rest: '0:30', cues: 'Controlled. Groin mobility' },
        { name: 'Pogos', sets: 2, reps: '15', rest: '0:45', cues: 'Elastic. Ankle stiffness' },
        { name: 'Lateral Shuffle', sets: 2, reps: '10 yd', rest: '0:45', cues: 'Crisp. Lateral prep' },
        { name: 'Continuous Lateral Bound', sets: 3, reps: '4/side', rest: '1:00', cues: 'Reactive. Lateral elastic power' },
        { name: 'Lateral Bound → Vertical Jump', sets: 3, reps: '3/side', rest: '1:15', cues: 'Max intent. Force redirection' },
        { name: 'Split Jump', sets: 3, reps: '3/side', rest: '1:00', cues: 'Fast. Unilateral power' },
        { name: 'Crossover Start 10 yd', sets: 3, reps: '1/side', rest: '1:30', cues: '95-100%. Lateral acceleration' },
        { name: 'Pro Agility', sets: 3, reps: '1', rest: '2:30', cues: '95-100%. COD' },
        { name: 'Shuffle Scoop Toss', sets: 4, reps: '3/side', rest: '1:00', cues: 'Max velocity. Dynamic rotation' },
        { name: 'Reverse Scoop Toss', sets: 3, reps: '3/side', rest: '1:00', cues: 'Max velocity. Rotational power' },
        { name: 'Power Clean from Floor', sets: 5, reps: '2', rest: '2:30', cues: 'Fast / RPE 7-8. Total-body power' },
        { name: 'Trap-Bar Deadlift', sets: 4, reps: '3', rest: '2:30', cues: 'RPE 8-8.5. Max force' },
        { name: 'Reverse Lunge', sets: 3, reps: '5/side', rest: '1:30', cues: 'RPE 8. Single-leg force' },
        { name: 'Lateral Lunge', sets: 3, reps: '5/side', rest: '1:15', cues: 'RPE 7. Frontal-plane strength' },
        { name: 'Copenhagen Plank', sets: 3, reps: '20-25s/side', rest: '0:45', cues: 'Quality. Adductor/pelvis' },
        { name: 'Suitcase Carry', sets: 3, reps: '25 yd/side', rest: '1:00', cues: 'Heavy. Grip + trunk' },
      ],
      cooldown: COOLDOWN,
    },

    // ───────────────────────── Day 13 — W5D1 ─────────────────────────
    {
      day: 'Day 13',
      title: 'W5 · Force Into Speed',
      warmup: PHASE_3_WARMUP,
      duration: '60-85 min',
      sections: [
        { name: 'Warm-Up', start: 0 },
        { name: 'Speed + Power', start: 5 },
        { name: 'Primary Strength', start: 9 },
        { name: 'Accessory + Core', start: 10 },
      ],
      exercises: [
        { name: '90/90 Hip Switch', sets: 2, reps: '6/side', rest: '0:30', cues: 'Controlled. Hip rotation' },
        { name: 'Adductor Rock Back', sets: 2, reps: '8/side', rest: '0:30', cues: 'Controlled. Groin/pelvis' },
        { name: 'Knee-to-Wall Ankle Mob', sets: 2, reps: '8/side', rest: '0:30', cues: 'Controlled. Ankle ROM' },
        { name: "World's Greatest Stretch + T-Spine", sets: 1, reps: '5/side', rest: '0:30', cues: 'Controlled. Integrated mobility' },
        { name: 'Pogos', sets: 2, reps: '10', rest: '0:45', cues: 'Elastic. Ankle stiffness' },
        { name: 'Depth Drop → Vertical Jump', sets: 3, reps: '2', rest: '1:15', cues: 'Max intent. Reactive vertical power' },
        { name: 'Broad Jump', sets: 4, reps: '2', rest: '1:15', cues: 'Max intent. Horizontal power' },
        { name: '10-Yard Sprint', sets: 4, reps: '1', rest: '2:00', cues: '100%. Acceleration' },
        { name: 'Hang Clean', sets: 6, reps: '2', rest: '2:30', cues: 'Fast / RPE 7-9. Power' },
        { name: 'Back Squat', sets: 4, reps: '3', rest: '2:30', cues: '82-88%. Force expression' },
        { name: 'RFESS', sets: 2, reps: '5/side', rest: '1:30', cues: 'RPE 8. Unilateral force' },
        { name: 'Nordic Curl', sets: 2, reps: '4', rest: '1:30', cues: 'Controlled. Hamstring' },
        { name: 'Dead Bug + Pullover', sets: 2, reps: '6/side', rest: '0:45', cues: 'Controlled. Trunk' },
        { name: 'Farmer Carry', sets: 3, reps: '20 yd', rest: '1:00', cues: 'Heavy. Grip + trunk' },
      ],
      cooldown: COOLDOWN,
    },

    // ───────────────────────── Day 14 — W5D2 ─────────────────────────
    {
      day: 'Day 14',
      title: 'W5 · Rotational Velocity',
      warmup: PHASE_3_WARMUP,
      duration: '60-85 min',
      sections: [
        { name: 'Warm-Up + Arm Prep', start: 0 },
        { name: 'Rotational Power', start: 5 },
        { name: 'Primary Strength', start: 9 },
        { name: 'Accessory + Arm Care', start: 12 },
      ],
      exercises: [
        { name: 'Quadruped T-Spine Rotation', sets: 2, reps: '6/side', rest: '0:30', cues: 'Controlled. T-spine rotation' },
        { name: 'Serratus Wall Slide', sets: 2, reps: '8', rest: '0:30', cues: 'Smooth. Scap upward rotation' },
        { name: 'Band Pull-Apart', sets: 2, reps: '15', rest: '0:30', cues: 'Light. Posterior shoulder' },
        { name: 'Band External Rotation', sets: 2, reps: '10/side', rest: '0:30', cues: 'Light. Rotator cuff' },
        { name: 'Scap Push-Up', sets: 2, reps: '10', rest: '0:30', cues: 'Bodyweight. Serratus control' },
        { name: 'Step-Behind Scoop Toss', sets: 4, reps: '2/side', rest: '1:15', cues: 'MAX velocity. Rotational power' },
        { name: 'Walk-In Shot Put', sets: 4, reps: '2/side', rest: '1:15', cues: 'MAX velocity. Momentum transfer' },
        { name: 'Shuffle Shot Put', sets: 3, reps: '2/side', rest: '1:15', cues: 'MAX velocity. Dynamic rotation' },
        { name: 'Pivot-Pickoff Throw', sets: 3, reps: '2/side', rest: '1:00', cues: 'MAX velocity. Quick rotation' },
        { name: 'Bench Press', sets: 3, reps: '3-4', rest: '2:00', cues: 'RPE 7-8. Strength maintenance' },
        { name: 'Weighted Pull-Up', sets: 3, reps: '4', rest: '1:30', cues: 'RPE 8. Pull strength' },
        { name: 'Landmine Press', sets: 2, reps: '5/side', rest: '1:15', cues: 'RPE 7. Scap-friendly press' },
        { name: 'Chest-Supported Row', sets: 2, reps: '6', rest: '1:15', cues: 'RPE 8. Upper back' },
        { name: 'Serratus Wall Slide', sets: 2, reps: '8', rest: '0:30', cues: 'Smooth. Scap control' },
        { name: 'Prone Trap-3', sets: 2, reps: '8', rest: '0:45', cues: 'Light. Lower trap' },
        { name: 'Cable Lift', sets: 2, reps: '6/side', rest: '0:45', cues: 'Fast-control. Trunk transfer' },
        { name: 'Plate Pinch', sets: 2, reps: '25s', rest: '0:45', cues: 'Moderate. Grip' },
      ],
      cooldown: COOLDOWN,
    },

    // ───────────────────────── Day 15 — W5D3 ─────────────────────────
    {
      day: 'Day 15',
      title: 'W5 · Athletic Power',
      warmup: PHASE_3_WARMUP,
      duration: '60-85 min',
      sections: [
        { name: 'Warm-Up', start: 0 },
        { name: 'Speed + Power', start: 5 },
        { name: 'Primary Strength', start: 12 },
        { name: 'Accessory + Core', start: 13 },
      ],
      exercises: [
        { name: 'Assisted Hip Airplane', sets: 2, reps: '4/side', rest: '0:30', cues: 'Controlled. Hip control' },
        { name: 'Lateral Lunge', sets: 2, reps: '6/side', rest: '0:30', cues: 'Easy. Frontal-plane mobility' },
        { name: 'Adductor Rock Back', sets: 2, reps: '8', rest: '0:30', cues: 'Controlled. Groin mobility' },
        { name: 'Pogos', sets: 2, reps: '15', rest: '0:45', cues: 'Elastic. Ankle stiffness' },
        { name: 'Lateral Pogo', sets: 2, reps: '10/side', rest: '0:45', cues: 'Elastic. Lateral stiffness' },
        { name: 'Lateral Bound → Broad Jump', sets: 3, reps: '2/side', rest: '1:15', cues: 'Max intent. Force redirection' },
        { name: 'Reactive Lateral Bound', sets: 3, reps: '3/side', rest: '1:00', cues: 'Reactive. Lateral power' },
        { name: 'Crossover Start', sets: 3, reps: '10 yd/side', rest: '1:30', cues: '100%. Acceleration' },
        { name: '5-10-5', sets: 3, reps: '1', rest: '2:30', cues: '95-100%. COD' },
        { name: 'Shuffle Scoop Toss', sets: 3, reps: '2/side', rest: '1:15', cues: 'MAX velocity. Rotation' },
        { name: 'Reverse Scoop Toss', sets: 3, reps: '2/side', rest: '1:15', cues: 'MAX velocity. Rotation' },
        { name: 'Power Clean', sets: 5, reps: '2', rest: '2:30', cues: 'Fast. Total-body power' },
        { name: 'Trap-Bar Deadlift', sets: 3, reps: '3', rest: '2:30', cues: 'RPE 8. Force maintenance' },
        { name: 'Reverse Lunge', sets: 2, reps: '5/side', rest: '1:30', cues: 'RPE 7-8. Single-leg force' },
        { name: 'Copenhagen Plank', sets: 2, reps: '20s/side', rest: '0:45', cues: 'Quality. Adductor/pelvis' },
        { name: 'Suitcase Carry', sets: 3, reps: '20 yd/side', rest: '1:00', cues: 'Heavy. Grip + trunk' },
      ],
      cooldown: COOLDOWN,
    },

    // ───────────────────────── Day 16 — W6D1 ─────────────────────────
    {
      day: 'Day 16',
      title: 'W6 · Explosive Lower',
      warmup: PHASE_3_WARMUP,
      duration: '50-70 min',
      sections: [
        { name: 'Warm-Up', start: 0 },
        { name: 'Speed + Power', start: 5 },
        { name: 'Primary Strength', start: 9 },
        { name: 'Accessory + Core', start: 10 },
      ],
      exercises: [
        { name: '90/90 Hip Switch', sets: 2, reps: '6/side', rest: '0:30', cues: 'Controlled. Hip rotation' },
        { name: 'Adductor Rock Back', sets: 2, reps: '8/side', rest: '0:30', cues: 'Controlled. Groin/pelvis' },
        { name: 'Knee-to-Wall Ankle Mob', sets: 2, reps: '8/side', rest: '0:30', cues: 'Controlled. Ankle ROM' },
        { name: "World's Greatest Stretch + T-Spine", sets: 1, reps: '5/side', rest: '0:30', cues: 'Controlled. Integrated mobility' },
        { name: 'Pogos', sets: 2, reps: '10', rest: '0:45', cues: 'Elastic. Ankle stiffness' },
        { name: 'Vertical Jump', sets: 3, reps: '2', rest: '1:15', cues: 'MAX intent. Vertical power' },
        { name: 'Broad Jump', sets: 3, reps: '2', rest: '1:15', cues: 'MAX intent. Horizontal power' },
        { name: '10-Yard Sprint', sets: 3, reps: '1', rest: '2:00', cues: '100%. Acceleration' },
        { name: 'Hang Clean', sets: 4, reps: '2', rest: '2:30', cues: 'Fast. Power' },
        { name: 'Back Squat', sets: 3, reps: '3', rest: '2:30', cues: '75-82%. Strength primer' },
        { name: 'RFESS', sets: 2, reps: '4/side', rest: '1:15', cues: 'RPE 7. Unilateral strength' },
        { name: 'Nordic Curl', sets: 2, reps: '3-4', rest: '1:15', cues: 'Controlled. Hamstring' },
        { name: 'Farmer Carry', sets: 2, reps: '20 yd', rest: '1:00', cues: 'Heavy. Grip + trunk' },
      ],
      cooldown: COOLDOWN,
    },

    // ───────────────────────── Day 17 — W6D2 ─────────────────────────
    {
      day: 'Day 17',
      title: 'W6 · Pitcher Power',
      warmup: PHASE_3_WARMUP,
      duration: '50-70 min',
      sections: [
        { name: 'Warm-Up + Arm Prep', start: 0 },
        { name: 'Rotational Power', start: 5 },
        { name: 'Primary Strength', start: 8 },
        { name: 'Accessory + Arm Care', start: 11 },
      ],
      exercises: [
        { name: 'Quadruped T-Spine Rotation', sets: 2, reps: '6/side', rest: '0:30', cues: 'Controlled. T-spine rotation' },
        { name: 'Serratus Wall Slide', sets: 2, reps: '8', rest: '0:30', cues: 'Smooth. Scap upward rotation' },
        { name: 'Band Pull-Apart', sets: 2, reps: '15', rest: '0:30', cues: 'Light. Posterior shoulder' },
        { name: 'Band External Rotation', sets: 2, reps: '10/side', rest: '0:30', cues: 'Light. Rotator cuff' },
        { name: 'Scap Push-Up', sets: 2, reps: '10', rest: '0:30', cues: 'Bodyweight. Serratus control' },
        { name: 'Step-Behind Scoop Toss', sets: 3, reps: '2/side', rest: '1:15', cues: 'MAX velocity. Rotation' },
        { name: 'Walk-In Shot Put', sets: 3, reps: '2/side', rest: '1:15', cues: 'MAX velocity. Momentum transfer' },
        { name: 'Shuffle Shot Put', sets: 2, reps: '2/side', rest: '1:15', cues: 'MAX velocity. Dynamic rotation' },
        { name: 'Bench Press', sets: 3, reps: '3', rest: '2:00', cues: 'Moderate/fast. Strength primer' },
        { name: 'Neutral-Grip Pull-Up', sets: 3, reps: '4', rest: '1:30', cues: 'RPE 7. Pull strength' },
        { name: 'Landmine Press', sets: 2, reps: '4/side', rest: '1:00', cues: 'RPE 6-7. Scap-friendly press' },
        { name: 'Chest-Supported Row', sets: 2, reps: '6', rest: '1:00', cues: 'RPE 7. Upper back' },
        { name: 'Serratus Wall Slide', sets: 2, reps: '8', rest: '0:30', cues: 'Smooth. Scap control' },
        { name: 'Band External Rotation', sets: 2, reps: '10', rest: '0:30', cues: 'Light. Cuff' },
        { name: 'Prone Trap-3', sets: 2, reps: '8', rest: '0:30', cues: 'Light. Lower trap' },
        { name: 'Pallof Press', sets: 2, reps: '6/side', rest: '0:45', cues: 'Moderate. Anti-rotation' },
        { name: 'Plate Pinch', sets: 2, reps: '20s', rest: '0:45', cues: 'Easy-moderate. Grip' },
      ],
      cooldown: COOLDOWN,
    },
  ],
}
