import type { Program } from './programs'

export const executiveProgram: Program = {
  id: 'executive-performance',
  name: 'Executive Performance Protocol',
  weeks: 6,
  frequency: '4x / week',
  description: 'Efficient training for busy professionals who refuse to let the body slide.',
  category: 'functional',
  image: '/programs/executive.jpg',
  days: [
    // ═══════════════════════════════════════
    //  WEEK 1 — Foundation (RPE 6-7)
    // ═══════════════════════════════════════
    {
      day: 'Day 1',
      title: 'W1 · Strength Foundations',
      warmup: '5 min: bodyweight squats, arm circles, cat-cow, hip hinges',
      duration: '45 min',
      exercises: [
        {
          name: 'Goblet Squat',
          sets: 3,
          reps: '10',
          tempo: '3-1-1-0',
          rest: '1:30',
          cues: 'Elbows inside knees at the bottom. Chest up, weight in heels.',
        },
        {
          name: '1a. Dumbbell Bench Press',
          sets: 3,
          reps: '10',
          tempo: '3-1-1-0',
          rest: '1:30',
          cues: 'Control the descent. Press to full lockout. Shoulder blades pinched.',
        },
        {
          name: '1b. Single-Arm Dumbbell Row',
          sets: 3,
          reps: '10 each',
          rest: '1:15',
          cues: 'Pull to hip. Squeeze the lat at the top. Don\'t rotate the torso.',
        },
        {
          name: 'Kettlebell Deadlift',
          sets: 3,
          reps: '12',
          rest: '1:30',
          cues: 'Push hips back, flat back. Drive through heels to stand.',
        },
        {
          name: 'Plank Hold',
          sets: 3,
          reps: '45 sec',
          rest: '1:00',
          cues: 'Straight line head to heels. Squeeze glutes, brace core. Breathe.',
        },
      ],
      cooldown: '5 min: chest stretch, hip flexor stretch, child\'s pose',
    },
    {
      day: 'Day 2',
      title: 'W1 · Conditioning + Breathwork',
      warmup: '5 min: light jog, arm swings, leg swings',
      duration: '40 min',
      exercises: [
        {
          name: 'Kettlebell Swing',
          sets: 4,
          reps: '15',
          rest: '1:00',
          cues: 'Hip hinge — not a squat. Snap hips forward, float the bell to chest height.',
        },
        {
          name: 'Rowing Machine Intervals',
          sets: 5,
          reps: '250m',
          rest: '1:00',
          cues: 'Legs-back-arms on the drive, arms-back-legs on recovery. Aim for consistent split.',
        },
        {
          name: 'Push-Up to Rotation',
          sets: 3,
          reps: '8 each side',
          rest: '1:00',
          cues: 'Full push-up, rotate to side plank at the top. Open the chest.',
        },
        {
          name: 'Med Ball Slam',
          sets: 3,
          reps: '12',
          rest: '1:00',
          cues: 'Reach overhead, slam with your whole body. Pick up and reset each rep.',
        },
        {
          name: 'Box Breathing',
          sets: 1,
          reps: '5 min',
          rest: '-',
          cues: '4 seconds inhale, 4 hold, 4 exhale, 4 hold. Focus on complete stillness.',
        },
        {
          name: 'Wim Hof Breathing',
          sets: 3,
          reps: '30 breaths + hold',
          rest: '1:00',
          cues: 'Deep belly breaths in, passive exhale out. After 30, exhale and hold as long as comfortable.',
        },
      ],
      cooldown: '5 min: standing forward fold, doorway chest stretch',
    },
    {
      day: 'Day 3',
      title: 'W1 · Focus & Power',
      warmup: '5 min: jump rope, mobility flow',
      duration: '50 min',
      exercises: [
        {
          name: 'Trap Bar Deadlift',
          sets: 4,
          reps: '6',
          rest: '2:30',
          cues: 'Neutral spine, grip hard. Drive the floor away from you.',
        },
        {
          name: '1a. Dumbbell Push Press',
          sets: 3,
          reps: '8',
          rest: '1:30',
          cues: 'Quarter dip, drive explosively. Lock out overhead.',
        },
        {
          name: '1b. TRX Row',
          sets: 3,
          reps: '12',
          rest: '1:15',
          cues: 'Body straight as a plank. Pull chest to handles, squeeze at the top.',
        },
        {
          name: '2a. Dumbbell Walking Lunge',
          sets: 3,
          reps: '10 each',
          rest: '1:30',
          cues: 'Long stride, back knee kisses the floor. Stay tall and controlled.',
        },
        {
          name: '2b. Pallof Press',
          sets: 3,
          reps: '10 each side',
          rest: '1:00',
          cues: 'Resist the rotation. Press out slowly, hold for a beat, bring it back.',
        },
      ],
      cooldown: '5 min: pigeon stretch, thoracic spine rotation, deep breathing',
    },
    {
      day: 'Day 4',
      title: 'W1 · Recovery & Mobility',
      warmup: '5 min easy walk',
      duration: '30 min',
      exercises: [
        {
          name: 'Foam Roll — Full Body',
          sets: 1,
          reps: '60 sec each area',
          rest: '-',
          cues: 'Upper back, lats, quads, hamstrings, calves. Slow and controlled.',
        },
        {
          name: 'Hip 90/90 Flow',
          sets: 2,
          reps: '8 transitions',
          rest: '-',
          cues: 'Smooth transitions between sides. Sit tall throughout.',
        },
        {
          name: 'Thoracic Spine Rotation',
          sets: 2,
          reps: '8 each side',
          rest: '-',
          cues: 'Side-lying position. Follow the hand with your eyes. Open up fully.',
        },
        {
          name: 'Banded Pull-Apart',
          sets: 2,
          reps: '15',
          rest: '-',
          cues: 'Light band, slow reps. Focus on squeezing the upper back.',
        },
        {
          name: 'Yoga Flow',
          sets: 1,
          reps: '5 min',
          rest: '-',
          cues: 'Sun salutation A. Breathe with each movement. Move with intention.',
        },
        {
          name: 'Guided Visualization',
          sets: 1,
          reps: '5 min',
          rest: '-',
          cues: 'Close your eyes. See your biggest goal. Walk through each step to get there.',
        },
        {
          name: 'Gratitude Journaling',
          sets: 1,
          reps: '5 min',
          rest: '-',
          cues: 'Write 3 things you\'re grateful for. Be specific — not just \'family\' but why, today.',
        },
      ],
      cooldown: 'Hydrate. Refuel with protein + carbs within 30 min. Prioritize 7-8 hours of sleep tonight.',
    },

    // ═══════════════════════════════════════
    //  WEEK 2 — Foundation+ (RPE 6-7)
    //  Add 1 set on key lifts, +2 reps on accessories
    // ═══════════════════════════════════════
    {
      day: 'Day 5',
      title: 'W2 · Strength Foundations',
      warmup: '5 min: bodyweight squats, arm circles, cat-cow, hip hinges',
      duration: '50 min',
      exercises: [
        {
          name: 'Goblet Squat',
          sets: 4,
          reps: '12',
          tempo: '3-1-1-0',
          rest: '1:30',
          cues: 'Heavier than last week. Elbows inside knees, chest proud. Own every rep.',
        },
        {
          name: '1a. Dumbbell Bench Press',
          sets: 4,
          reps: '12',
          tempo: '3-1-1-0',
          rest: '1:30',
          cues: 'Slow on the way down, explode up. Shoulder blades pinched the entire time.',
        },
        {
          name: '1b. Single-Arm Dumbbell Row',
          sets: 4,
          reps: '12 each',
          rest: '1:15',
          cues: 'Pull to hip, squeeze for a full second at the top. No torso rotation.',
        },
        {
          name: 'Kettlebell Deadlift',
          sets: 4,
          reps: '12',
          rest: '1:30',
          cues: 'Heavier bell this week. Hips back, flat back, drive through heels.',
        },
        {
          name: 'Plank Hold',
          sets: 3,
          reps: '60 sec',
          rest: '1:00',
          cues: 'Added time. Straight line head to heels. If you shake, you\'re growing.',
        },
        {
          name: 'Dead Bug',
          sets: 3,
          reps: '10 each side',
          rest: '1:00',
          cues: 'Lower back pressed into the floor. Opposite arm and leg extend slowly. Breathe out as you extend.',
        },
      ],
      cooldown: '5 min: chest stretch, hip flexor stretch, child\'s pose',
    },
    {
      day: 'Day 6',
      title: 'W2 · Conditioning + Breathwork',
      warmup: '5 min: light jog, arm swings, leg swings, high knees',
      duration: '40 min',
      exercises: [
        {
          name: 'Kettlebell Swing',
          sets: 5,
          reps: '15',
          rest: '0:45',
          cues: 'One more set than last week, less rest. Snap the hips. Bell should float.',
        },
        {
          name: 'Rowing Machine Intervals',
          sets: 6,
          reps: '250m',
          rest: '0:50',
          cues: 'One more round, tighter rest. Hold your pace from last week or beat it.',
        },
        {
          name: 'Push-Up to Rotation',
          sets: 3,
          reps: '10 each side',
          rest: '1:00',
          cues: 'Two more reps per side. Full push-up, controlled rotation to side plank.',
        },
        {
          name: 'Med Ball Slam',
          sets: 4,
          reps: '12',
          rest: '0:45',
          cues: 'Extra set, less rest. Slam with intent — every rep like it owes you money.',
        },
        {
          name: 'Box Breathing',
          sets: 1,
          reps: '5 min',
          rest: '-',
          cues: 'Extend to 5-5-5-5 if the 4-count felt manageable last week.',
        },
        {
          name: 'Wim Hof Breathing',
          sets: 3,
          reps: '35 breaths + hold',
          rest: '1:00',
          cues: 'Five more breaths per round. Try to extend the hold by 10 seconds.',
        },
      ],
      cooldown: '5 min: standing forward fold, doorway chest stretch, neck rolls',
    },
    {
      day: 'Day 7',
      title: 'W2 · Focus & Power',
      warmup: '5 min: jump rope, mobility flow, glute bridges',
      duration: '50 min',
      exercises: [
        {
          name: 'Trap Bar Deadlift',
          sets: 4,
          reps: '8',
          rest: '2:30',
          cues: 'Two more reps at the same weight. Focus on speed off the floor.',
        },
        {
          name: '1a. Dumbbell Push Press',
          sets: 4,
          reps: '8',
          rest: '1:30',
          cues: 'Extra set. Quarter dip, drive explosively. Lock out overhead every rep.',
        },
        {
          name: '1b. TRX Row',
          sets: 4,
          reps: '12',
          rest: '1:15',
          cues: 'Step feet closer to the anchor for a harder angle. Squeeze at the top.',
        },
        {
          name: '2a. Dumbbell Walking Lunge',
          sets: 3,
          reps: '12 each',
          rest: '1:30',
          cues: 'Two more steps per leg. Long stride, back knee kisses the floor.',
        },
        {
          name: '2b. Pallof Press',
          sets: 3,
          reps: '12 each side',
          rest: '1:00',
          cues: 'Two more reps. Slow press out, hold 2 seconds at full extension.',
        },
        {
          name: 'Farmer Carry',
          sets: 3,
          reps: '40 yards',
          rest: '1:00',
          cues: 'Heavy dumbbells at your sides. Tall posture, packed shoulders, crush the handles.',
        },
      ],
      cooldown: '5 min: pigeon stretch, thoracic spine rotation, deep breathing',
    },
    {
      day: 'Day 8',
      title: 'W2 · Recovery & Mobility',
      warmup: '5 min easy walk',
      duration: '35 min',
      exercises: [
        {
          name: 'Foam Roll — Full Body',
          sets: 1,
          reps: '90 sec each area',
          rest: '-',
          cues: 'Spend extra time on any area that felt tight this week. Breathe into the pressure.',
        },
        {
          name: 'Hip 90/90 Flow',
          sets: 3,
          reps: '8 transitions',
          rest: '-',
          cues: 'One more set. Try to sit taller and rotate further than last week.',
        },
        {
          name: 'Thoracic Spine Rotation',
          sets: 3,
          reps: '8 each side',
          rest: '-',
          cues: 'Extra set. Breathe out as you open up. Reach further each rep.',
        },
        {
          name: 'Banded Pull-Apart',
          sets: 3,
          reps: '15',
          rest: '-',
          cues: 'Added set. Slow and controlled — 2 seconds out, 2 seconds back.',
        },
        {
          name: 'Yoga Flow',
          sets: 1,
          reps: '7 min',
          rest: '-',
          cues: 'Sun salutation A into Warrior I and II. Flow with your breath.',
        },
        {
          name: 'Guided Visualization',
          sets: 1,
          reps: '5 min',
          rest: '-',
          cues: 'Visualize your best training session. Feel the weight, hear the gym, see yourself executing.',
        },
        {
          name: 'Gratitude Journaling',
          sets: 1,
          reps: '5 min',
          rest: '-',
          cues: 'Write 3 wins from this week. What did you show up for? What moved the needle?',
        },
      ],
      cooldown: 'Hydrate. Refuel with protein + carbs within 30 min. You earned this rest.',
    },

    // ═══════════════════════════════════════
    //  WEEK 3 — Build (RPE 7-8)
    //  4 sets on compounds, 8-10 reps, new variations
    // ═══════════════════════════════════════
    {
      day: 'Day 9',
      title: 'W3 · Strength Foundations',
      warmup: '5 min: bodyweight squats, hip circles, band pull-aparts, cat-cow',
      duration: '50 min',
      exercises: [
        {
          name: 'Barbell Front Squat',
          sets: 4,
          reps: '10',
          tempo: '2-1-1-0',
          rest: '2:00',
          cues: 'Upgrade from goblet. Elbows high, chest up, full depth. This is your new standard.',
        },
        {
          name: '1a. Dumbbell Bench Press',
          sets: 4,
          reps: '10',
          tempo: '2-1-1-0',
          rest: '1:30',
          cues: 'Heavier than Week 2. Control the negative for 2 full seconds.',
        },
        {
          name: '1b. Cable Face Pull',
          sets: 4,
          reps: '12',
          rest: '1:15',
          cues: 'Pull to the forehead, elbows high and wide. Squeeze upper back at the finish.',
        },
        {
          name: 'Romanian Deadlift',
          sets: 4,
          reps: '10',
          rest: '1:30',
          cues: 'Barbell in front of shins. Hinge at the hips, slight knee bend. Feel the hamstrings load.',
        },
        {
          name: '2a. Plank Hold',
          sets: 3,
          reps: '60 sec',
          rest: '0:30',
          cues: 'Straight line head to heels. Squeeze everything. If it\'s easy, add a weight plate on your back.',
        },
        {
          name: '2b. Dead Bug',
          sets: 3,
          reps: '12 each side',
          rest: '1:00',
          cues: 'Lower back glued to the floor. Slow and controlled — no rushing.',
        },
      ],
      cooldown: '5 min: quad stretch, hamstring stretch, child\'s pose',
    },
    {
      day: 'Day 10',
      title: 'W3 · Conditioning + Breathwork',
      warmup: '5 min: jump rope, arm swings, leg swings, high knees',
      duration: '45 min',
      exercises: [
        {
          name: 'Kettlebell Swing',
          sets: 5,
          reps: '20',
          rest: '0:45',
          cues: 'Heavier bell, more reps. Hips snap hard. This is where conditioning gets real.',
        },
        {
          name: 'Assault Bike Intervals',
          sets: 6,
          reps: '30 sec all-out / 30 sec easy',
          rest: '-',
          cues: 'New tool. Max effort on the work intervals. Spin easy on recovery. No coasting.',
        },
        {
          name: 'Med Ball Slam',
          sets: 4,
          reps: '15',
          rest: '0:45',
          cues: 'More reps. Slam with full-body aggression. Reset completely between reps.',
        },
        {
          name: 'TRX Row',
          sets: 4,
          reps: '15',
          rest: '1:00',
          cues: 'Feet close to the anchor for max difficulty. Pull chest to handles, hold at the top.',
        },
        {
          name: 'Box Breathing',
          sets: 1,
          reps: '5 min',
          rest: '-',
          cues: '5-5-5-5 count this week. Slower and longer. Find total stillness.',
        },
        {
          name: 'Wim Hof Breathing',
          sets: 4,
          reps: '35 breaths + hold',
          rest: '1:00',
          cues: 'Four rounds now. Push the breath hold further. Trust your body.',
        },
      ],
      cooldown: '5 min: standing forward fold, doorway chest stretch, deep breathing',
    },
    {
      day: 'Day 11',
      title: 'W3 · Focus & Power',
      warmup: '5 min: jump rope, glute bridges, leg swings, arm circles',
      duration: '55 min',
      exercises: [
        {
          name: 'Trap Bar Deadlift',
          sets: 4,
          reps: '6',
          rest: '2:30',
          cues: 'Heavier than Week 2. Grip hard, brace deep. Explode off the floor.',
        },
        {
          name: 'Barbell Shoulder Press',
          sets: 4,
          reps: '8',
          rest: '2:00',
          cues: 'Upgrade from dumbbell push press. Strict press — no leg drive. Brace the core hard.',
        },
        {
          name: '1a. Dumbbell Walking Lunge',
          sets: 4,
          reps: '10 each',
          rest: '1:30',
          cues: 'Heavier dumbbells. Long stride, control the descent. Drive through the front heel.',
        },
        {
          name: '1b. Cable Face Pull',
          sets: 4,
          reps: '12',
          rest: '1:00',
          cues: 'External rotate at the top — thumbs point behind you. Posture builder.',
        },
        {
          name: '2a. Pallof Press',
          sets: 3,
          reps: '12 each side',
          rest: '0:30',
          cues: 'Heavier cable setting. Press out, hold 3 seconds. Resist the pull.',
        },
        {
          name: '2b. Farmer Carry',
          sets: 3,
          reps: '50 yards',
          rest: '1:00',
          cues: 'Heavy dumbbells. Tall posture, shoulders packed. Grip is the limiter — fight for it.',
        },
      ],
      cooldown: '5 min: pigeon stretch, thoracic opener, 90/90 flow',
    },
    {
      day: 'Day 12',
      title: 'W3 · Recovery & Mobility',
      warmup: '5 min easy walk',
      duration: '35 min',
      exercises: [
        {
          name: 'Foam Roll — Full Body',
          sets: 1,
          reps: '90 sec each area',
          rest: '-',
          cues: 'Add IT band and glutes this week. Breathe into the tight spots.',
        },
        {
          name: 'Hip 90/90 Flow',
          sets: 3,
          reps: '10 transitions',
          rest: '-',
          cues: 'More transitions, smoother flow. Own each position before moving on.',
        },
        {
          name: 'Thoracic Spine Rotation',
          sets: 3,
          reps: '10 each side',
          rest: '-',
          cues: 'More reps. Exhale as you open. Try to touch the opposite hand to the floor.',
        },
        {
          name: 'Banded Pull-Apart',
          sets: 3,
          reps: '20',
          rest: '-',
          cues: 'More reps, same control. Shoulder blades together, hold for a beat each rep.',
        },
        {
          name: 'Yoga Flow',
          sets: 1,
          reps: '8 min',
          rest: '-',
          cues: 'Sun salutation A + B. Add Warrior III for balance. Hold each pose for 3 full breaths.',
        },
        {
          name: 'Guided Visualization',
          sets: 1,
          reps: '5 min',
          rest: '-',
          cues: 'Visualize yourself 6 months from now. What does the stronger version of you look like?',
        },
        {
          name: 'Gratitude Journaling',
          sets: 1,
          reps: '5 min',
          rest: '-',
          cues: 'Write about one hard moment this week and what it taught you. Growth lives in discomfort.',
        },
      ],
      cooldown: 'Hydrate. Protein + carbs within 30 min. You\'re halfway through — the real work starts now.',
    },

    // ═══════════════════════════════════════
    //  WEEK 4 — Build+ (RPE 7-8)
    //  Heavier loads, more volume, new challenges
    // ═══════════════════════════════════════
    {
      day: 'Day 13',
      title: 'W4 · Strength Foundations',
      warmup: '5 min: bodyweight squats, band pull-aparts, hip circles, inchworms',
      duration: '55 min',
      exercises: [
        {
          name: 'Barbell Front Squat',
          sets: 4,
          reps: '8',
          tempo: '2-1-1-0',
          rest: '2:00',
          cues: 'Heavier than Week 3. Fewer reps, more load. Elbows high, depth is non-negotiable.',
        },
        {
          name: '1a. Incline Dumbbell Bench Press',
          sets: 4,
          reps: '10',
          tempo: '2-1-1-0',
          rest: '1:30',
          cues: 'New angle for chest development. 30-degree incline. Control down, press up with power.',
        },
        {
          name: '1b. Cable Face Pull',
          sets: 4,
          reps: '15',
          rest: '1:15',
          cues: 'More reps, lighter weight. External rotate at the finish. Posture insurance.',
        },
        {
          name: 'Romanian Deadlift',
          sets: 4,
          reps: '8',
          rest: '2:00',
          cues: 'Heavier barbell. Hinge deep, feel the stretch in the hamstrings. Squeeze glutes to stand.',
        },
        {
          name: '2a. Dumbbell Lateral Raise',
          sets: 3,
          reps: '12',
          rest: '0:30',
          cues: 'Control the lift — no swinging. Raise to shoulder height, pause, lower slowly.',
        },
        {
          name: '2b. Dead Bug',
          sets: 3,
          reps: '12 each side',
          rest: '1:00',
          cues: 'Add a light dumbbell in the working hand. Lower back stays pressed flat.',
        },
      ],
      cooldown: '5 min: quad stretch, hamstring stretch, lat stretch, child\'s pose',
    },
    {
      day: 'Day 14',
      title: 'W4 · Conditioning + Breathwork',
      warmup: '5 min: jump rope, arm swings, high knees, butt kicks',
      duration: '45 min',
      exercises: [
        {
          name: 'Kettlebell Swing',
          sets: 6,
          reps: '20',
          rest: '0:40',
          cues: 'Six sets, 40 seconds rest. Heavier bell if you can. This is a cardio war.',
        },
        {
          name: 'Assault Bike Intervals',
          sets: 8,
          reps: '20 sec all-out / 40 sec easy',
          rest: '-',
          cues: 'More rounds. Tabata style. Empty the tank on every work interval.',
        },
        {
          name: 'Rowing Machine Intervals',
          sets: 4,
          reps: '500m',
          rest: '1:30',
          cues: 'Longer intervals now — 500m pieces. Hold a pace you can sustain across all 4.',
        },
        {
          name: 'Med Ball Slam',
          sets: 4,
          reps: '15',
          rest: '0:30',
          cues: 'Heavier ball. Less rest. Every slam is a statement.',
        },
        {
          name: 'Box Breathing',
          sets: 1,
          reps: '5 min',
          rest: '-',
          cues: '6-6-6-6 count. Your nervous system is getting stronger. Prove it.',
        },
        {
          name: 'Wim Hof Breathing',
          sets: 4,
          reps: '40 breaths + hold',
          rest: '1:00',
          cues: 'Forty breaths per round. Push the hold past 90 seconds if you can.',
        },
      ],
      cooldown: '5 min: standing forward fold, quad stretch, deep breathing',
    },
    {
      day: 'Day 15',
      title: 'W4 · Focus & Power',
      warmup: '5 min: jump rope, hip circles, glute bridges, arm circles',
      duration: '55 min',
      exercises: [
        {
          name: 'Trap Bar Deadlift',
          sets: 5,
          reps: '5',
          rest: '2:30',
          cues: 'Five sets of five. Add weight from Week 3. Controlled descent, explosive drive.',
        },
        {
          name: 'Barbell Shoulder Press',
          sets: 4,
          reps: '6',
          rest: '2:00',
          cues: 'Heavier than Week 3. Fewer reps, more intent. Lock out fully, control back down.',
        },
        {
          name: '1a. Barbell Reverse Lunge',
          sets: 4,
          reps: '8 each',
          rest: '1:30',
          cues: 'Upgrade from dumbbell. Bar on upper back. Step back, drop knee, drive through front heel.',
        },
        {
          name: '1b. Pallof Press',
          sets: 4,
          reps: '10 each side',
          rest: '1:00',
          cues: 'Heavier band or cable. Press out, hold 3 seconds. Your core is the anchor.',
        },
        {
          name: '2a. Med Ball Slam',
          sets: 3,
          reps: '8',
          rest: '0:30',
          cues: 'Heavy ball, explosive. Full overhead reach, slam through the floor.',
        },
        {
          name: '2b. Farmer Carry',
          sets: 3,
          reps: '60 yards',
          rest: '1:00',
          cues: 'Heavier and longer than Week 3. Grip, posture, and grit all tested here.',
        },
      ],
      cooldown: '5 min: pigeon stretch, scorpion stretch, deep breathing',
    },
    {
      day: 'Day 16',
      title: 'W4 · Recovery & Mobility',
      warmup: '5 min easy walk',
      duration: '35 min',
      exercises: [
        {
          name: 'Foam Roll — Full Body',
          sets: 1,
          reps: '2 min each area',
          rest: '-',
          cues: 'Spend more time on problem areas. Quads, hip flexors, and upper back get extra attention.',
        },
        {
          name: 'Hip 90/90 Flow',
          sets: 3,
          reps: '10 transitions',
          rest: '-',
          cues: 'Add a forward lean in each position. You should feel a deep stretch in the hip.',
        },
        {
          name: 'Thoracic Spine Rotation',
          sets: 3,
          reps: '10 each side',
          rest: '-',
          cues: 'Use a foam roller under the knees for support. Reach further each rep.',
        },
        {
          name: 'Banded Pull-Apart',
          sets: 3,
          reps: '20',
          rest: '-',
          cues: 'Add an overhead variation — arms at 45 degrees. Posture corrector.',
        },
        {
          name: 'Yoga Flow',
          sets: 1,
          reps: '10 min',
          rest: '-',
          cues: 'Full sun salutation sequence with Warrior I, II, and III. Hold each pose for 5 breaths.',
        },
        {
          name: 'Guided Visualization',
          sets: 1,
          reps: '5 min',
          rest: '-',
          cues: 'Visualize your peak week. See yourself hitting every lift, every interval. Own it mentally first.',
        },
        {
          name: 'Gratitude Journaling',
          sets: 1,
          reps: '5 min',
          rest: '-',
          cues: 'Reflect on your progression. Compare Week 1 you to Week 4 you. Write what changed.',
        },
      ],
      cooldown: 'Hydrate. Quality nutrition tonight. Tomorrow the intensity goes up — prepare your mind.',
    },

    // ═══════════════════════════════════════
    //  WEEK 5 — Peak (RPE 8-9)
    //  Heavy compounds 5-6 reps, 4-5 sets, explosive power
    // ═══════════════════════════════════════
    {
      day: 'Day 17',
      title: 'W5 · Strength Foundations',
      warmup: '5 min: bodyweight squats, hip circles, band pull-aparts, inchworms, glute bridges',
      duration: '55 min',
      exercises: [
        {
          name: 'Barbell Front Squat',
          sets: 5,
          reps: '6',
          rest: '2:30',
          cues: 'Peak loading. Five sets of six. Elbows up, brace hard. This is what you\'ve been building to.',
        },
        {
          name: '1a. Dumbbell Bench Press',
          sets: 4,
          reps: '8',
          tempo: '2-0-1-0',
          rest: '1:30',
          cues: 'Heavy dumbbells. Controlled negative, powerful press. Shoulder blades locked in.',
        },
        {
          name: '1b. Single-Arm Dumbbell Row',
          sets: 4,
          reps: '8 each',
          rest: '1:15',
          cues: 'Heavy. Pull explosively to the hip, control back down. No body English.',
        },
        {
          name: 'Romanian Deadlift',
          sets: 4,
          reps: '6',
          rest: '2:00',
          cues: 'Heaviest barbell yet. Deep hinge, hamstrings loaded. Slow descent, powerful drive.',
        },
        {
          name: '2a. Dumbbell Lateral Raise',
          sets: 4,
          reps: '10',
          rest: '0:30',
          cues: 'Controlled raises to shoulder height. Pause at the top. Build the shoulders.',
        },
        {
          name: '2b. Hollow Hold',
          sets: 3,
          reps: '45 sec',
          rest: '1:00',
          cues: 'Lower back pressed flat. Arms overhead, legs extended. If it burns, it\'s working.',
        },
      ],
      cooldown: '5 min: quad stretch, hamstring stretch, lat stretch, child\'s pose',
    },
    {
      day: 'Day 18',
      title: 'W5 · Conditioning + Breathwork',
      warmup: '5 min: jump rope, arm swings, high knees, butt kicks, leg swings',
      duration: '45 min',
      exercises: [
        {
          name: 'Kettlebell Swing',
          sets: 5,
          reps: '25',
          rest: '0:45',
          cues: 'Heaviest bell you can handle with good form. Twenty-five reps. No half reps.',
        },
        {
          name: 'Assault Bike Intervals',
          sets: 10,
          reps: '20 sec all-out / 20 sec easy',
          rest: '-',
          cues: 'Ten rounds. Work-to-rest ratio goes 1:1. This is peak conditioning. Embrace the suffering.',
        },
        {
          name: 'Rowing Machine Intervals',
          sets: 4,
          reps: '500m',
          rest: '1:00',
          cues: 'Same distance, less rest. Beat your Week 4 split time or match it with less recovery.',
        },
        {
          name: 'Med Ball Slam',
          sets: 5,
          reps: '12',
          rest: '0:30',
          cues: 'Five sets. Heaviest ball. Full aggression on every single slam.',
        },
        {
          name: 'Box Breathing',
          sets: 1,
          reps: '5 min',
          rest: '-',
          cues: '6-6-6-6 count. Complete calm after complete chaos. Master the switch.',
        },
        {
          name: 'Wim Hof Breathing',
          sets: 4,
          reps: '40 breaths + hold',
          rest: '1:00',
          cues: 'Push past 2 minutes on the hold if you can. Your body can do more than your mind believes.',
        },
      ],
      cooldown: '5 min: standing forward fold, doorway chest stretch, deep breathing',
    },
    {
      day: 'Day 19',
      title: 'W5 · Focus & Power',
      warmup: '5 min: jump rope, hip circles, glute bridges, scapular push-ups',
      duration: '55 min',
      exercises: [
        {
          name: 'Trap Bar Deadlift',
          sets: 5,
          reps: '5',
          rest: '3:00',
          cues: 'Heaviest of the program. Five heavy singles of five. Grip the bar like you mean it.',
        },
        {
          name: 'Barbell Shoulder Press',
          sets: 4,
          reps: '6',
          rest: '2:00',
          cues: 'Heavy strict press. No leg drive. Lock out overhead, own every inch.',
        },
        {
          name: '1a. Barbell Reverse Lunge',
          sets: 4,
          reps: '6 each',
          rest: '1:30',
          cues: 'Heavier bar. Fewer reps, more load. Controlled step back, explosive drive up.',
        },
        {
          name: '1b. Cable Face Pull',
          sets: 4,
          reps: '15',
          rest: '1:00',
          cues: 'High volume for posture and shoulder health. Pull, rotate, squeeze. Every rep.',
        },
        {
          name: '2a. Med Ball Slam',
          sets: 4,
          reps: '8',
          rest: '0:30',
          cues: 'Explosive. Heaviest ball. Full overhead reach, slam through the floor.',
        },
        {
          name: '2b. Farmer Carry',
          sets: 4,
          reps: '60 yards',
          rest: '1:00',
          cues: 'Heaviest dumbbells you can carry. Grip endurance and total-body tension. Don\'t drop them.',
        },
      ],
      cooldown: '5 min: pigeon stretch, scorpion stretch, thoracic opener',
    },
    {
      day: 'Day 20',
      title: 'W5 · Recovery & Mobility',
      warmup: '5 min easy walk',
      duration: '40 min',
      exercises: [
        {
          name: 'Foam Roll — Full Body',
          sets: 1,
          reps: '2 min each area',
          rest: '-',
          cues: 'Take your time. Hit quads, hamstrings, glutes, upper back, lats, and calves. Breathe deeply.',
        },
        {
          name: 'Hip 90/90 Flow',
          sets: 3,
          reps: '12 transitions',
          rest: '-',
          cues: 'Most transitions yet. You should feel more mobile than Week 1. Prove it.',
        },
        {
          name: 'Thoracic Spine Rotation',
          sets: 3,
          reps: '12 each side',
          rest: '-',
          cues: 'Most reps yet. Full range of motion. Exhale deeply as you open.',
        },
        {
          name: 'Banded Pull-Apart',
          sets: 3,
          reps: '20',
          rest: '-',
          cues: 'Mix overhand and underhand grip sets. Feel the upper back light up.',
        },
        {
          name: 'Yoga Flow',
          sets: 1,
          reps: '10 min',
          rest: '-',
          cues: 'Full flow: sun salutation A + B, Warrior I-II-III, triangle pose, extended side angle. Breathe.',
        },
        {
          name: 'Guided Visualization',
          sets: 1,
          reps: '5 min',
          rest: '-',
          cues: 'Visualize your final week. Every lift, every interval, every breath. You\'re walking in prepared.',
        },
        {
          name: 'Gratitude Journaling',
          sets: 1,
          reps: '5 min',
          rest: '-',
          cues: 'Write a letter to Week 1 you. What would you tell yourself knowing what you know now?',
        },
      ],
      cooldown: 'Hydrate. Clean nutrition. Sleep 8 hours. Final week incoming — finish what you started.',
    },

    // ═══════════════════════════════════════
    //  WEEK 6 — Peak Performance (RPE 8-9)
    //  Maintain intensity, reduce volume slightly for peak output
    // ═══════════════════════════════════════
    {
      day: 'Day 21',
      title: 'W6 · Strength Foundations',
      warmup: '5 min: bodyweight squats, hip circles, band pull-aparts, glute bridges, inchworms',
      duration: '50 min',
      exercises: [
        {
          name: 'Barbell Front Squat',
          sets: 4,
          reps: '5',
          rest: '2:30',
          cues: 'Heaviest front squats of the program. Four sets of five. Quality over quantity. Own every rep.',
        },
        {
          name: '1a. Incline Dumbbell Bench Press',
          sets: 4,
          reps: '8',
          tempo: '2-0-1-0',
          rest: '1:30',
          cues: 'Heavy dumbbells. Controlled negative, explosive press. Shoulder blades pinched tight.',
        },
        {
          name: '1b. Single-Arm Dumbbell Row',
          sets: 4,
          reps: '8 each',
          rest: '1:15',
          cues: 'Heaviest rows yet. Pull with intent, squeeze the lat hard at the top.',
        },
        {
          name: 'Romanian Deadlift',
          sets: 4,
          reps: '6',
          rest: '2:00',
          cues: 'Match or beat your Week 5 weight. Deep hinge, heavy hamstring load. You know the movement — trust it.',
        },
        {
          name: 'Hollow Hold',
          sets: 3,
          reps: '60 sec',
          rest: '1:00',
          cues: 'Full minute. Lower back flat, arms overhead. Show your core what six weeks of work looks like.',
        },
      ],
      cooldown: '5 min: quad stretch, hamstring stretch, lat stretch, deep breathing',
    },
    {
      day: 'Day 22',
      title: 'W6 · Conditioning + Breathwork',
      warmup: '5 min: jump rope, arm swings, high knees, butt kicks',
      duration: '45 min',
      exercises: [
        {
          name: 'Kettlebell Swing',
          sets: 5,
          reps: '20',
          rest: '0:40',
          cues: 'Same heavy bell from Week 5. Slightly less volume but same intensity. Make every rep count.',
        },
        {
          name: 'Assault Bike Intervals',
          sets: 8,
          reps: '30 sec all-out / 30 sec easy',
          rest: '-',
          cues: 'Slightly fewer rounds than Week 5 but longer work intervals. Beat your max calories per round.',
        },
        {
          name: 'Rowing Machine Intervals',
          sets: 3,
          reps: '500m',
          rest: '1:30',
          cues: 'Three all-out pieces. Your fastest splits of the program. Leave nothing in the tank.',
        },
        {
          name: 'Med Ball Slam',
          sets: 4,
          reps: '10',
          rest: '0:30',
          cues: 'Same heavy ball. Slightly less total volume. Maximum power on each slam.',
        },
        {
          name: 'Box Breathing',
          sets: 1,
          reps: '5 min',
          rest: '-',
          cues: '7-7-7-7 count. Your longest holds yet. Calm is a skill you\'ve trained for six weeks.',
        },
        {
          name: 'Wim Hof Breathing',
          sets: 4,
          reps: '40 breaths + hold',
          rest: '1:00',
          cues: 'Final session. Push for your longest hold ever. You have six weeks of practice behind you.',
        },
      ],
      cooldown: '5 min: standing forward fold, doorway chest stretch, neck rolls, deep breathing',
    },
    {
      day: 'Day 23',
      title: 'W6 · Focus & Power',
      warmup: '5 min: jump rope, hip circles, glute bridges, scapular push-ups, arm circles',
      duration: '55 min',
      exercises: [
        {
          name: 'Trap Bar Deadlift',
          sets: 4,
          reps: '5',
          rest: '3:00',
          cues: 'Match your Week 5 weight or add 5 lbs. Four sets, full recovery. Peak performance.',
        },
        {
          name: 'Barbell Shoulder Press',
          sets: 4,
          reps: '5',
          rest: '2:00',
          cues: 'Heaviest strict press of the program. Five reps, four sets. Full lockout, no ego lean-back.',
        },
        {
          name: '1a. Barbell Reverse Lunge',
          sets: 4,
          reps: '6 each',
          rest: '1:30',
          cues: 'Heavy bar. Controlled step back, explosive drive. Your legs are stronger than they were six weeks ago.',
        },
        {
          name: '1b. Pallof Press',
          sets: 4,
          reps: '10 each side',
          rest: '1:00',
          cues: 'Heaviest cable yet. Press and hold for 3 full seconds. Your core doesn\'t flinch.',
        },
        {
          name: 'Farmer Carry',
          sets: 4,
          reps: '60 yards',
          rest: '1:00',
          cues: 'Heaviest carries of the program. Crush the handles. Tall posture. Don\'t you dare put them down early.',
        },
      ],
      cooldown: '5 min: pigeon stretch, scorpion stretch, thoracic opener, deep breathing',
    },
    {
      day: 'Day 24',
      title: 'W6 · Recovery & Mobility',
      warmup: '5 min easy walk',
      duration: '40 min',
      exercises: [
        {
          name: 'Foam Roll — Full Body',
          sets: 1,
          reps: '2 min each area',
          rest: '-',
          cues: 'Final session. Give every area the attention it deserves. Breathe and release.',
        },
        {
          name: 'Hip 90/90 Flow',
          sets: 3,
          reps: '12 transitions',
          rest: '-',
          cues: 'Notice how much easier this is than Week 1. That\'s six weeks of work showing.',
        },
        {
          name: 'Thoracic Spine Rotation',
          sets: 3,
          reps: '12 each side',
          rest: '-',
          cues: 'Full range, deep breath on each opening. Your mobility is a weapon now.',
        },
        {
          name: 'Banded Pull-Apart',
          sets: 3,
          reps: '20',
          rest: '-',
          cues: 'Slow and controlled. Three-second holds at full extension. Upper back finisher.',
        },
        {
          name: 'Yoga Flow',
          sets: 1,
          reps: '12 min',
          rest: '-',
          cues: 'Longest flow of the program. Full sun salutation sequence, warrior series, tree pose, seated forward fold. Breathe with every movement.',
        },
        {
          name: 'Guided Visualization',
          sets: 1,
          reps: '5 min',
          rest: '-',
          cues: 'See the person you\'ve become. Stronger. More disciplined. More focused. This is who you are now.',
        },
        {
          name: 'Gratitude Journaling',
          sets: 1,
          reps: '5 min',
          rest: '-',
          cues: 'Write about what you accomplished in 6 weeks. What will you carry forward? What\'s next?',
        },
      ],
      cooldown: 'Protocol complete. Hydrate. Refuel. Rest. You didn\'t just survive this — you competed. Now go build on it.',
    },
  ],
}
