import type { Program } from './programs'

export const foundationsProgram: Program = {
  id: 'functional-fitness',
  name: 'CTC Foundations',
  weeks: 8,
  frequency: '3x / week',
  description: '8-week periodized program. Strength, volume, and power — your starting point to compete.',
  category: 'functional',
  image: '/programs/functional.jpg',
  days: [
    // =====================================================================
    // PHASE 1: FOUNDATION (Weeks 1–2)
    // Establish baselines. Learn the movements. Build work capacity.
    // Main lifts: 4×8 @ 65-68%. Accessories: 3×10-15.
    // =====================================================================

    // ---- W1 Day 1: Strength ----
    {
      day: 'Day 1',
      title: 'W1 · Strength',
      warmup: '10 min: Start with 2 minutes on the stationary bike at an easy pace to get your blood flowing and your joints warm. Then monster walks — put a resistance band around your ankles, get into a quarter-squat position, and take small steps sideways, keeping tension on the band the whole time (this wakes up your hips and glutes). Next, single-arm dumbbell external rotations — hold a light dumbbell, elbow bent at 90 degrees and pinned to your side, and rotate your forearm outward away from your body (this warms up your shoulder joint for pressing and pulling). Then banded hip hinges — loop a band around a rack at hip height, step back until there\'s tension, then hinge at your hips (push your butt back, soft knees, flat back) until you feel a stretch in your hamstrings, then stand tall and squeeze your glutes. Finish with bodyweight squats — feet shoulder-width apart, sit your hips back and down like you\'re sitting in a chair, chest up, then stand back up.',
      duration: '60 min',
      sections: [{ name: 'Strength', start: 0 }],
      exercises: [
        {
          name: 'Barbell Back Squat',
          sets: 4,
          reps: '8 @ 65%',
          rest: '2:30',
          cues: 'This week you\'re establishing your baseline — pick a weight you can complete all 4 sets of 8 with good form. Set the bar across your upper back (not your neck), grip it wide, and stand tall. Keep your chest up and eyes forward the whole time. Push your hips back first, then bend your knees, and sit down until your hip crease drops below your knee — that\'s "full depth." Drive through your heels to stand back up. Record this weight — you\'ll add to it every week.',
        },
        {
          name: 'Barbell Deadlift',
          sets: 4,
          reps: '8 @ 65%',
          rest: '2:30',
          cues: 'Same as the squat — find your baseline weight for sets of 8 with perfect form. Stand with the bar over your shoelaces, feet hip-width apart. Bend down and grip the bar just outside your legs, keeping your back flat and your chest up. Take a big breath, brace your core like you\'re about to take a punch, then push the floor away with your legs while keeping the bar close against your shins. Finish by squeezing your glutes and standing tall. Record your weight.',
        },
        {
          name: 'Bench Press',
          sets: 4,
          reps: '8 @ 65%',
          rest: '2:30',
          cues: 'Establish your bench baseline. Lie back, feet flat on the floor, and pinch your shoulder blades together and down — this protects your shoulders and gives you a stable base. Lower the bar under control until it lightly touches your chest, then press it back up explosively. Keep your wrists stacked directly over your elbows. Pick a weight you can handle for all 4 sets of 8 without form breakdown.',
        },
        {
          name: 'Barbell Bent-Over Row',
          sets: 3,
          reps: '10',
          rest: '1:30',
          cues: 'This works your entire back — the opposite motion of the bench press. Hold the bar with an overhand grip, hinge forward at your hips until your torso is at about a 45-degree angle, knees soft, back flat. Pull the bar up toward your lower chest, squeezing your shoulder blades together at the top like you\'re pinching a pencil between them. Lower it back down with control.',
        },
        {
          name: 'Pull-Ups',
          sets: 3,
          reps: '8',
          rest: '1:30',
          cues: 'Grip a pull-up bar with palms facing away, hands just outside shoulder width. Start from a full dead hang and pull your body up until your chin clears the bar, driving your elbows down toward your hips. Lower yourself back down slowly — don\'t just drop. No swinging or kicking. If you can\'t do a full pull-up yet, use a band for assistance or do slow negatives (jump up, lower yourself down as slowly as possible).',
        },
        {
          name: 'Walking Lunge',
          sets: 3,
          reps: '10 each leg',
          rest: '1:30',
          cues: 'Holding a dumbbell in each hand, take a long step forward and lower your body straight down until your back knee lightly taps the floor — both knees should be bent around 90 degrees. Push off your front foot to step through into the next lunge, alternating legs. Keep your torso tall and chest up the whole time.',
        },
        {
          name: 'Plank',
          sets: 3,
          reps: '30 sec',
          rest: '0:45',
          cues: 'Get into a push-up position but rest on your forearms, elbows directly under your shoulders. Your body should form one straight line from head to heels — no sagging hips, no butt in the air. Squeeze your glutes and brace your core. Keep breathing normally.',
        },
        {
          name: 'Ab Rollouts',
          sets: 3,
          reps: '8',
          rest: '1:00',
          cues: 'Kneeling on the floor holding an ab wheel, brace your core tight and slowly roll forward, extending your body as far as you can while keeping control — don\'t let your lower back sag. Use your abs to pull yourself back to the starting position. Go slow — this is about control, not speed.',
        },
      ],
      cooldown: '5 min: Foam roll quads, hamstrings, and glutes — pause on any tight spots for a few seconds. Then standing quad stretch (30 sec each), seated hamstring reach (30 sec each), and cross-body shoulder stretch (30 sec each).',
    },

    // ---- W1 Day 2: Volume & Bodybuilding ----
    {
      day: 'Day 2',
      title: 'W1 · Volume & Bodybuilding',
      warmup: '10 min: Start with 2 minutes on the ski erg at an easy pace. Then banded pull-aparts — hold a resistance band in front of you with both hands, arms straight, and pull it apart until it touches your chest, squeezing your shoulder blades together (15 reps). Next, single-arm dumbbell overhead carry — hold a light dumbbell straight overhead with one arm locked out, and walk a short distance keeping your core tight. Finish with lunge jumps — start in a lunge, jump up and switch legs in the air, landing softly on the other side.',
      duration: '55 min',
      sections: [{ name: 'Accessories', start: 0 }, { name: 'Core', start: 8 }],
      exercises: [
        {
          name: '1a. Incline Dumbbell Bench Press',
          sets: 3,
          reps: '12',
          rest: '1:30',
          cues: 'Set an adjustable bench to about 30-45 degrees. Press two dumbbells up until your arms are extended, then lower them slowly until you feel a full stretch across your chest. Squeeze your chest together at the top. This targets your upper chest more than a flat bench.',
        },
        {
          name: '1b. Seated Low Row',
          sets: 3,
          reps: '12',
          rest: '1:15',
          cues: 'Sit at the cable row machine, knees slightly bent, feet on the platform. Pull the handle toward your belly button, driving your elbows behind you and squeezing your shoulder blades together. Return slowly with control.',
        },
        {
          name: '2a. Arnold Press',
          sets: 3,
          reps: '10',
          rest: '1:15',
          cues: 'Hold dumbbells at shoulder height with palms facing you. As you press overhead, rotate your wrists so palms face forward at the top. Reverse the rotation as you lower. This hits your shoulders from multiple angles.',
        },
        {
          name: '2b. Cable Tricep Pushdown',
          sets: 3,
          reps: '12',
          rest: '1:00',
          cues: 'Stand facing a cable machine with the attachment at head height. Pin your elbows to your sides — they shouldn\'t move the whole set. Push down until your arms are fully straight, squeeze hard at the bottom, then let it rise with control.',
        },
        {
          name: '3a. Reverse Cable Crossover',
          sets: 3,
          reps: '15',
          rest: '1:00',
          cues: 'Set two cables at chest height, cross the handles. With a slight bend in your elbows, pull your arms out and back in a wide arc. Squeeze the back of your shoulders hard at the end of every rep.',
        },
        {
          name: '3b. Farmer Carry + Shrugs',
          sets: 3,
          reps: '20 yd carry + 10 shrugs',
          rest: '1:30',
          cues: 'Pick up a heavy dumbbell in each hand and walk 20 yards with tall posture — shoulders back, core tight. As soon as you finish, do 10 shrugs with the same dumbbells — lift your shoulders toward your ears, then lower. Your grip will be screaming. That\'s the point.',
        },
        {
          name: 'Dumbbell Split Squat',
          sets: 3,
          reps: '10 each',
          rest: '1:15',
          cues: 'Stand in front of a bench, holding a dumbbell in each hand. Place the top of your back foot on the bench behind you. Lower your body straight down by bending your front knee — don\'t lean forward. Push through your front heel to stand back up.',
        },
        {
          name: 'Barbell Hip Thrust',
          sets: 2,
          reps: '10 + 10 sec hold + 10',
          rest: '1:30',
          cues: 'Sit on the ground with your upper back against a bench, barbell over your hips. Drive through your heels to push your hips up until your body forms a straight line from shoulders to knees, squeezing your glutes hard at the top. After each block of reps, hold the top for 10 seconds.',
        },
        {
          name: 'Cable Crunches',
          sets: 2,
          reps: '20',
          rest: '0:45',
          cues: 'Kneel facing a cable machine with a rope attachment at the top. Hold the rope by your head and crunch down, rounding your upper back and bringing elbows toward knees. Exhale hard as you crunch. Hips stay still — all movement from your abs.',
        },
        {
          name: 'Dumbbell Oblique Crunch',
          sets: 2,
          reps: '15 each side',
          rest: '0:45',
          cues: 'Stand tall holding a dumbbell at your side. Without leaning forward, crunch sideways bringing your ribcage toward your hip. Return to standing with control. Finish all reps on one side before switching.',
        },
      ],
      cooldown: '5 min: Chest stretch in a doorway (20-30 sec each side), lat stretch on a rack (20-30 sec each side), shoulder stretch across your chest (20-30 sec each side).',
    },

    // ---- W1 Day 3: Power & Speed ----
    {
      day: 'Day 3',
      title: 'W1 · Power & Speed',
      warmup: '15 min: 5 min easy jog at conversational pace. Then line hops — hop forward and back over a line on the ground, quick and light. Lateral hops — side to side over the line. High knees — jog in place driving knees up as fast as you can. A-skips — drive one knee up sharply while hopping on the opposite foot, then switch. Finish with build-up sprints — jog into a gradual sprint up to about 70% speed over 20-30 yards, walk back and repeat.',
      duration: '55 min',
      sections: [{ name: 'Speed', start: 0 }, { name: 'Power', start: 3 }, { name: 'Conditioning', start: 7 }],
      exercises: [
        {
          name: 'Double Leg Line Hops',
          sets: 2,
          reps: '15 sec',
          rest: '0:30',
          cues: 'Stand next to a line on the ground. Hop side to side with both feet together, as quick and light as possible. Land softly on the balls of your feet — think "quiet feet."',
        },
        {
          name: 'Double Leg Lateral Line Hops',
          sets: 2,
          reps: '15 sec',
          rest: '0:30',
          cues: 'Same setup but hopping forward and back over the line. Stay light and fast, bend your knees slightly on each landing.',
        },
        {
          name: 'Single Leg Line Hops',
          sets: 2,
          reps: '10 sec each',
          rest: '0:30',
          cues: 'Balance on one foot and hop side to side over the line, landing soft and controlled. This trains balance and ankle stability. Do all reps on one leg, then switch.',
        },
        {
          name: '1a. Power Clean',
          sets: 4,
          reps: '5-4-3-3',
          rest: '2:30',
          cues: 'This is an advanced lift — Coach Tyler will walk you through it hands-on. Start with the bar on the floor, pull it up explosively by extending your hips, knees, and ankles all at once. As the bar rises, pull yourself underneath it and catch it across the front of your shoulders with elbows up. Technique first, weight later. This week is about nailing the movement pattern.',
        },
        {
          name: '1b. Box Jumps',
          sets: 4,
          reps: '3',
          rest: '1:30',
          cues: 'Stand facing a sturdy box. Bend your knees, swing your arms back, then explode upward and land softly on top with both feet, knees bent. Stand up fully at the top. Always step back down — never jump down.',
        },
        {
          name: '2a. Explosive Sled Rows',
          sets: 3,
          reps: '8',
          rest: '1:15',
          cues: 'Attach a rope to a loaded sled and face it. Pull the sled toward you explosively, driving with your back and arms. Keep your whole body tight — brace your core. Drive the movement from your back, not just your arms.',
        },
        {
          name: '2b. Explosive Push-Ups',
          sets: 3,
          reps: '8',
          rest: '1:00',
          cues: 'Start in push-up position. Lower yourself down, then push up so explosively your hands leave the ground. Land softly with slightly bent elbows, then immediately go into the next rep.',
        },
        {
          name: '3a. Heavy Sled Pushes',
          sets: 3,
          reps: '25 yards',
          rest: '2:00',
          cues: 'Load up a sled, get behind it with arms locked straight. Lean your whole body forward at a low angle and take short, powerful driving steps. This builds explosive leg drive and full-body conditioning.',
        },
        {
          name: '3b. Kettlebell Swing',
          sets: 3,
          reps: '12',
          rest: '1:00',
          cues: 'Stand with feet shoulder-width, kettlebell on the ground. Hinge at your hips, grab the bell, hike it back between your legs, then explosively snap your hips forward to send the bell to chest height. Power comes entirely from your hip snap, not your arms.',
        },
        {
          name: 'Finisher: Run + Thrusters',
          sets: 1,
          reps: 'Max rounds in 8 min',
          rest: '-',
          cues: 'Run 200 meters, then immediately do 10 dumbbell thrusters — hold dumbbells at your shoulders, squat down, stand up explosively and press overhead in one motion. That\'s one round. Repeat for max rounds in 8 minutes. Keep moving — this tests your conditioning after a hard day.',
        },
      ],
      cooldown: '5 min: Foam roll quads, hamstrings, glutes, and upper back — extra time on tight spots. Standing quad stretch (20 sec each), seated hamstring reach (20 sec each), cross-body shoulder stretch (20 sec each).',
    },

    // =====================================================================
    // WEEK 2: FOUNDATION — PROGRESSIVE
    // Same movements, add 5-10 lbs to main lifts. +2 reps on accessories.
    // =====================================================================

    // ---- W2 Day 1: Strength ----
    {
      day: 'Day 4',
      title: 'W2 · Strength',
      warmup: '10 min: 2 minutes on the bike. Monster walks with band (15 each direction). Single-arm dumbbell external rotations (15 each arm). Banded hip hinges (10 reps). Bodyweight squats (10 reps).',
      duration: '60 min',
      sections: [{ name: 'Strength', start: 0 }],
      exercises: [
        {
          name: 'Barbell Back Squat',
          sets: 4,
          reps: '8 @ 68%',
          rest: '2:30',
          cues: 'Add 5-10 lbs to last week\'s weight. Same perfect form — chest up, hips back first, full depth, drive through your heels. The weight should feel slightly heavier but completely manageable for all 4 sets.',
        },
        {
          name: 'Barbell Deadlift',
          sets: 4,
          reps: '8 @ 68%',
          rest: '2:30',
          cues: 'Add 5-10 lbs from week 1. Keep your back flat, chest up, brace your core before every rep. Push the floor away with your legs, finish by squeezing your glutes at the top.',
        },
        {
          name: 'Bench Press',
          sets: 4,
          reps: '8 @ 68%',
          rest: '2:30',
          cues: 'Add 5 lbs from week 1. Shoulder blades pinched together and down, lower the bar with control, press up explosively. Every rep should look the same — that\'s the standard.',
        },
        {
          name: 'Barbell Bent-Over Row',
          sets: 3,
          reps: '12',
          rest: '1:30',
          cues: 'Same weight as last week but push for 12 reps — 2 more than week 1. Hinge forward, pull the bar to your lower chest, squeeze at the top. Control the weight down.',
        },
        {
          name: 'Pull-Ups',
          sets: 3,
          reps: '10',
          rest: '1:30',
          cues: 'Push for 10 reps — 2 more than last week. Same strict form: dead hang, pull chin over bar, slow lower. If you need the band, use a lighter one than last week.',
        },
        {
          name: 'Walking Lunge',
          sets: 3,
          reps: '12 each leg',
          rest: '1:30',
          cues: 'Same weight, 2 more reps per leg than week 1. Chest tall, back knee taps the floor, push through your front heel.',
        },
        {
          name: 'Plank',
          sets: 3,
          reps: '40 sec',
          rest: '0:45',
          cues: 'Ten seconds longer than last week. Same tight position — straight line from head to heels. Breathe normally.',
        },
        {
          name: 'Ab Rollouts',
          sets: 3,
          reps: '10',
          rest: '1:00',
          cues: 'Two more reps than last week. Try to roll out a little further this time while keeping full control.',
        },
      ],
      cooldown: '5 min: Foam roll quads, hamstrings, glutes. Standing quad stretch, seated hamstring reach, cross-body shoulder stretch — 30 sec each.',
    },

    // ---- W2 Day 2: Volume & Bodybuilding ----
    {
      day: 'Day 5',
      title: 'W2 · Volume & Bodybuilding',
      warmup: '10 min: 2 minutes ski erg. Banded pull-aparts (15 reps). Single-arm overhead carry (20 yards each). Lunge jumps (10 total).',
      duration: '55 min',
      sections: [{ name: 'Accessories', start: 0 }, { name: 'Core', start: 8 }],
      exercises: [
        {
          name: '1a. Incline Dumbbell Bench Press',
          sets: 4,
          reps: '12',
          rest: '1:30',
          cues: 'One more set than last week — 4 sets of 12. Same weight, just more total work. Full stretch at the bottom, squeeze at the top.',
        },
        {
          name: '1b. Seated Low Row',
          sets: 4,
          reps: '12',
          rest: '1:15',
          cues: 'Four sets this week. Pull the handle to your belly button, elbows behind you, squeeze your shoulder blades together. Return slowly.',
        },
        {
          name: '2a. Arnold Press',
          sets: 3,
          reps: '12',
          rest: '1:15',
          cues: 'Two more reps than last week. Same rotation — palms in at the bottom, palms out at the top. Control the weight.',
        },
        {
          name: '2b. Cable Tricep Pushdown',
          sets: 3,
          reps: '15',
          rest: '1:00',
          cues: 'Push for 15 reps. Elbows glued to your sides, full lockout at the bottom, controlled return.',
        },
        {
          name: '3a. Reverse Cable Crossover',
          sets: 3,
          reps: '15',
          rest: '1:00',
          cues: 'Same as last week. Focus on squeezing the back of your shoulders harder at the end of each rep.',
        },
        {
          name: '3b. Farmer Carry + Shrugs',
          sets: 3,
          reps: '20 yd carry + 12 shrugs',
          rest: '1:30',
          cues: 'Same weight, 2 more shrugs. Tall posture on the carry, full range on the shrugs.',
        },
        {
          name: 'Dumbbell Split Squat',
          sets: 3,
          reps: '12 each',
          rest: '1:15',
          cues: 'Two more reps per leg. Keep your torso upright, front knee tracking over your toes.',
        },
        {
          name: 'Barbell Hip Thrust',
          sets: 3,
          reps: '10 + 10 sec hold + 10',
          rest: '1:30',
          cues: 'One more set than last week. Same setup — drive hips up, squeeze glutes hard, hold 10 sec between blocks.',
        },
        {
          name: 'Cable Crunches',
          sets: 3,
          reps: '20',
          rest: '0:45',
          cues: 'One more set this week. Same strict form — crunch from your abs, not your hips.',
        },
        {
          name: 'Dumbbell Oblique Crunch',
          sets: 3,
          reps: '15 each side',
          rest: '0:45',
          cues: 'One more set. Controlled squeeze, no rushing.',
        },
      ],
      cooldown: '5 min: Chest stretch in doorway (30 sec each), lat stretch (30 sec each), shoulder stretch (30 sec each).',
    },

    // ---- W2 Day 3: Power & Speed ----
    {
      day: 'Day 6',
      title: 'W2 · Power & Speed',
      warmup: '15 min: 5 min easy jog. Line hops, lateral hops, high knees, A-skips. Build-up sprints to 75% speed over 30 yards.',
      duration: '55 min',
      sections: [{ name: 'Speed', start: 0 }, { name: 'Power', start: 3 }, { name: 'Conditioning', start: 7 }],
      exercises: [
        {
          name: 'Double Leg Line Hops',
          sets: 3,
          reps: '15 sec',
          rest: '0:30',
          cues: 'One more set than last week. Stay quick, stay light. Faster feet than week 1.',
        },
        {
          name: 'Double Leg Lateral Line Hops',
          sets: 3,
          reps: '15 sec',
          rest: '0:30',
          cues: 'Three sets this week. Soft landings, quick turnover.',
        },
        {
          name: 'Single Leg Line Hops',
          sets: 2,
          reps: '15 sec each',
          rest: '0:30',
          cues: 'Five more seconds per leg than last week. Focus on sticking each landing.',
        },
        {
          name: '1a. Power Clean',
          sets: 4,
          reps: '5',
          rest: '2:30',
          cues: 'Add 5-10 lbs from last week. Straight sets of 5 this time — your technique should feel smoother. Explosive hip drive, catch with high elbows.',
        },
        {
          name: '1b. Box Jumps',
          sets: 4,
          reps: '4',
          rest: '1:30',
          cues: 'One more rep per set than last week. Same height — focus on landing softer and standing up faster at the top. Step down.',
        },
        {
          name: '2a. Explosive Sled Rows',
          sets: 4,
          reps: '10',
          rest: '1:15',
          cues: 'More reps this week — 10 instead of 8. One extra set too. Pull harder and faster each rep.',
        },
        {
          name: '2b. Explosive Push-Ups',
          sets: 4,
          reps: '10',
          rest: '1:00',
          cues: 'Four sets this week, 10 reps. Get your hands higher off the ground than last week.',
        },
        {
          name: '3a. Heavy Sled Pushes',
          sets: 3,
          reps: '30 yards',
          rest: '2:00',
          cues: 'Five more yards than last week, or add weight to the sled. Short, powerful steps — lean into it.',
        },
        {
          name: '3b. Kettlebell Swing',
          sets: 3,
          reps: '15',
          rest: '1:00',
          cues: 'Three more reps per set. Snap your hips harder — the bell should float to chest height effortlessly.',
        },
        {
          name: 'Finisher: Run + Thrusters',
          sets: 1,
          reps: 'Max rounds in 10 min',
          rest: '-',
          cues: 'Two more minutes than last week. Same format: 200m run + 10 thrusters per round. Beat your week 1 round count.',
        },
      ],
      cooldown: '5 min: Foam roll quads, hamstrings, glutes, upper back. Full-body stretches — 20-30 sec each.',
    },

    // =====================================================================
    // PHASE 2: BUILD (Weeks 3–4)
    // Increase load, introduce variations, build muscle.
    // Main lifts: 4×6 @ 72-75%. New accessory exercises.
    // =====================================================================

    // ---- W3 Day 1: Strength ----
    {
      day: 'Day 7',
      title: 'W3 · Strength',
      warmup: '10 min: 2 minutes bike. Monster walks (15 each direction). Band pull-aparts (15 reps). Banded hip hinges (10 reps). Goblet squat — hold a dumbbell vertically against your chest, squat to full depth, 10 reps.',
      duration: '65 min',
      sections: [{ name: 'Strength', start: 0 }],
      exercises: [
        {
          name: 'Barbell Back Squat',
          sets: 4,
          reps: '6 @ 72%',
          rest: '2:30',
          cues: 'Fewer reps, heavier weight. You should feel the difference from weeks 1-2 — this is real strength work now. Same form: chest up, full depth, drive through heels. Each rep should be powerful and controlled.',
        },
        {
          name: 'Sumo Deadlift',
          sets: 4,
          reps: '6 @ 72%',
          rest: '2:30',
          cues: 'New stance this phase — feet wide (toes touching the plates), toes pointed out at 45 degrees, grip inside your knees. This shifts more work to your inner thighs and glutes. Keep your chest tall, push the floor apart with your feet, and lock out by driving your hips forward. Use about the same weight as your conventional deadlift.',
        },
        {
          name: 'Bench Press',
          sets: 4,
          reps: '6 @ 72%',
          rest: '2:30',
          cues: 'Heavier than weeks 1-2. Shoulder blades locked, controlled lower to chest, explosive press. Every rep should be crisp — no grinding or shaking.',
        },
        {
          name: 'Pendlay Row',
          sets: 4,
          reps: '8',
          rest: '2:00',
          cues: 'A stricter version of the bent-over row. Bend forward until your back is parallel to the floor, let the bar touch the ground between every rep — dead stop, no bounce. Pull explosively from the floor to your chest, squeeze your back, then lower it back to the ground with control. This builds real pulling power.',
        },
        {
          name: 'Weighted Pull-Ups',
          sets: 4,
          reps: '6',
          rest: '2:00',
          cues: 'Time to add weight. Use a dip belt, hold a dumbbell between your feet, or wear a weighted vest. Even 5-10 lbs makes a difference. Full dead hang to chin over bar, 3-second lower. If bodyweight pull-ups are still challenging, stay with bodyweight and aim for 6 perfect reps.',
        },
        {
          name: 'Reverse Lunge — Dumbbell',
          sets: 3,
          reps: '8 each leg',
          rest: '1:30',
          cues: 'New variation — step backward instead of forward. Hold dumbbells at your sides, step back into a lunge, lower until your back knee taps the floor, then drive through your front heel to return to standing. This puts more emphasis on your glutes and is easier on your knees.',
        },
        {
          name: 'Ab Wheel Rollout',
          sets: 3,
          reps: '10',
          rest: '1:00',
          cues: 'Try to roll out farther than weeks 1-2. Keep your core braced the entire time — the moment your lower back starts to sag, you\'ve gone too far. Pull back with your abs, not your hips.',
        },
      ],
      cooldown: '5 min: Foam roll quads, hamstrings, glutes. Hip flexor stretch (30 sec each), pigeon stretch (30 sec each), chest doorway stretch (30 sec each).',
    },

    // ---- W3 Day 2: Volume & Bodybuilding ----
    {
      day: 'Day 8',
      title: 'W3 · Volume & Bodybuilding',
      warmup: '10 min: 2 minutes ski erg. Banded pull-aparts (15). Light dumbbell overhead carry (20 yards each arm). 10 push-ups + 10 bodyweight squats.',
      duration: '60 min',
      sections: [{ name: 'Accessories', start: 0 }, { name: 'Core', start: 8 }],
      exercises: [
        {
          name: '1a. Dumbbell Bench Press',
          sets: 4,
          reps: '10',
          rest: '1:30',
          cues: 'New pressing variation — flat bench with dumbbells instead of incline. This gives you a deeper stretch at the bottom than a barbell. Lower the dumbbells until they\'re level with your chest, pause for a beat, then press up and squeeze your chest at the top.',
        },
        {
          name: '1b. Chest-Supported Dumbbell Row',
          sets: 4,
          reps: '10',
          rest: '1:15',
          cues: 'Lie face-down on an incline bench set to about 30 degrees, a dumbbell in each hand hanging straight down. Row both dumbbells up toward your hips, squeezing your shoulder blades together hard at the top. Because the bench supports your chest, you can\'t cheat with momentum — pure back work.',
        },
        {
          name: '2a. Seated Dumbbell Shoulder Press',
          sets: 3,
          reps: '10',
          rest: '1:15',
          cues: 'Sit on a bench set to 90 degrees, dumbbells at shoulder height, palms forward. Press straight up until your arms lock out, then lower with control. Keep your back against the pad — no arching.',
        },
        {
          name: '2b. Skull Crushers',
          sets: 3,
          reps: '10',
          rest: '1:00',
          cues: 'Lie on a flat bench holding an EZ bar or dumbbells with arms straight over your chest. Bend only at the elbows to lower the weight toward your forehead — keep your upper arms perfectly still, pointing at the ceiling. Press back up by straightening your elbows. You\'ll feel this deep in your triceps.',
        },
        {
          name: '3a. Cable Fly — Low to High',
          sets: 3,
          reps: '12',
          rest: '1:00',
          cues: 'Set the cables at the bottom position. Grab a handle in each hand and pull them up and together in an arc, like you\'re scooping something and lifting it to eye level. Squeeze your upper chest hard at the top.',
        },
        {
          name: '3b. Cable Face Pull',
          sets: 3,
          reps: '15',
          rest: '1:00',
          cues: 'Set a rope attachment at face height. Pull the rope toward your face, splitting your hands apart so your elbows flare wide and your hands end up beside your ears. This protects your shoulders — never skip it.',
        },
        {
          name: 'Bulgarian Split Squat',
          sets: 3,
          reps: '10 each',
          rest: '1:15',
          cues: 'Rear foot elevated on a bench, dumbbell in each hand. Lower straight down until your back knee nearly touches the floor, then drive up through your front heel. Keep your torso upright. This is harder than a regular lunge — embrace it.',
        },
        {
          name: 'Barbell Hip Thrust',
          sets: 3,
          reps: '10',
          rest: '1:30',
          cues: 'Heavier than weeks 1-2. Full hip extension at the top, hard glute squeeze, controlled lower. No holds this week — just straight sets of 10 with more weight.',
        },
        {
          name: 'Hanging Knee Raise',
          sets: 3,
          reps: '12',
          rest: '0:45',
          cues: 'Hang from a pull-up bar, arms straight. Bring your knees up toward your chest by curling your pelvis up — don\'t just swing your legs. Lower them back down slowly. If you swing, you\'re using momentum instead of abs.',
        },
        {
          name: 'Farmer Carry',
          sets: 3,
          reps: '40 yards',
          rest: '1:00',
          cues: 'Heavier dumbbells than weeks 1-2, double the distance. Tall posture, tight core, steady walk. Your grip and traps will work overtime.',
        },
      ],
      cooldown: '5 min: Chest stretch (30 sec each), lat stretch (30 sec each), hip flexor stretch (30 sec each).',
    },

    // ---- W3 Day 3: Power & Speed ----
    {
      day: 'Day 9',
      title: 'W3 · Power & Speed',
      warmup: '15 min: 5 min easy jog. Broad jumps — 3 reps for distance. Lateral bounds — hop side to side on one leg, 3 each way. A-skips and high knees. Build-up sprints to 80% over 30 yards.',
      duration: '55 min',
      sections: [{ name: 'Speed', start: 0 }, { name: 'Power', start: 2 }, { name: 'Conditioning', start: 6 }],
      exercises: [
        {
          name: 'Broad Jump',
          sets: 3,
          reps: '5',
          rest: '1:00',
          cues: 'New explosive movement. Stand with feet hip-width, swing your arms back and bend your knees, then explode forward as far as you can. Land with soft knees, absorb the impact, stand up fully. Mark your distance — you\'ll try to beat it in the coming weeks.',
        },
        {
          name: 'Lateral Bound',
          sets: 3,
          reps: '5 each',
          rest: '1:00',
          cues: 'Stand on one leg, push off explosively to the side, and land softly on the other leg. Stick the landing for a full second before bounding back. This builds the lateral explosiveness you need for cutting and changing direction.',
        },
        {
          name: '1a. Power Clean',
          sets: 4,
          reps: '4-3-3-2',
          rest: '2:30',
          cues: 'Heavier than weeks 1-2 — fewer reps, more weight. Your technique should be dialed in by now. Explosive triple extension, fast elbows, solid catch. Add 10-15 lbs from last phase.',
        },
        {
          name: '1b. Depth Jump',
          sets: 4,
          reps: '3',
          rest: '1:30',
          cues: 'Stand on a box (12-18 inches). Step off — don\'t jump off. The moment your feet hit the ground, immediately jump straight up as high as you can. Spend as little time on the ground as possible — this trains your body to absorb and redirect force instantly.',
        },
        {
          name: '2a. Medicine Ball Slam',
          sets: 4,
          reps: '10',
          rest: '1:15',
          cues: 'Hold a medicine ball overhead, rise up on your toes, then slam it into the ground as hard as humanly possible. Hinge at your hips as you slam. Pick it up and repeat. This builds explosive power and aggression — don\'t hold back.',
        },
        {
          name: '2b. Explosive Push-Ups',
          sets: 4,
          reps: '10',
          rest: '1:00',
          cues: 'Push up hard enough for your hands to leave the ground. Land soft, go right into the next rep. Each push-up should be more explosive than the last.',
        },
        {
          name: '3a. Heavy Sled Pushes',
          sets: 4,
          reps: '30 yards',
          rest: '2:00',
          cues: 'One more set and heavier sled than weeks 1-2. Lean into it, short powerful steps, stay low.',
        },
        {
          name: '3b. Kettlebell Swing',
          sets: 4,
          reps: '12',
          rest: '1:00',
          cues: 'One more set. Heavier kettlebell if week 2 felt easy. Violent hip snap, let the bell float.',
        },
        {
          name: 'Finisher: Run + Thrusters',
          sets: 1,
          reps: 'Max rounds in 10 min',
          rest: '-',
          cues: 'Use heavier dumbbells on the thrusters than weeks 1-2. Same format: 200m run + 10 thrusters. Push the pace.',
        },
      ],
      cooldown: '5 min: Foam roll everything. Full-body stretches — 20-30 sec holds.',
    },

    // ---- W4 Day 1: Strength ----
    {
      day: 'Day 10',
      title: 'W4 · Strength',
      warmup: '10 min: 2 minutes bike. Monster walks (15 each). Band pull-aparts (15). Goblet squats (10). Banded hip hinges (10).',
      duration: '65 min',
      sections: [{ name: 'Strength', start: 0 }],
      exercises: [
        {
          name: 'Barbell Back Squat',
          sets: 4,
          reps: '6 @ 75%',
          rest: '2:30',
          cues: 'Add 5-10 lbs from week 3. Same 6 reps, heavier bar. By now your squat should feel dialed — you own this movement. Stay disciplined: full depth, chest up, powerful drive.',
        },
        {
          name: 'Sumo Deadlift',
          sets: 4,
          reps: '6 @ 75%',
          rest: '2:30',
          cues: 'Add 5-10 lbs from week 3. Wide stance, chest tall, push the floor apart. The sumo should feel more natural this week than last.',
        },
        {
          name: 'Bench Press',
          sets: 4,
          reps: '6 @ 75%',
          rest: '2:30',
          cues: 'Heavier again. At 75%, these should be challenging but clean. No bouncing off the chest, no butt coming off the bench. Controlled lower, explosive press.',
        },
        {
          name: 'Pendlay Row',
          sets: 4,
          reps: '6',
          rest: '2:00',
          cues: 'Heavier than week 3, fewer reps. Every rep starts from a dead stop on the floor. Explosive pull to your chest, squeeze your back, controlled lower to the ground.',
        },
        {
          name: 'Weighted Pull-Ups',
          sets: 4,
          reps: '5',
          rest: '2:00',
          cues: 'Add 5 lbs from week 3. One fewer rep per set but heavier. Full range: dead hang to chin over bar. If 5 reps is too easy, add more weight.',
        },
        {
          name: 'Reverse Lunge — Dumbbell',
          sets: 3,
          reps: '8 each leg',
          rest: '1:30',
          cues: 'Heavier dumbbells than week 3. Step back, lower to a tap, drive through the front heel. Glutes should be on fire by the third set.',
        },
        {
          name: 'Ab Wheel Rollout',
          sets: 3,
          reps: '12',
          rest: '1:00',
          cues: 'Two more reps than week 3. Roll out as far as you can while keeping your core solid. If you can do these from your toes instead of your knees, go for it.',
        },
      ],
      cooldown: '5 min: Foam roll and stretch — quads, hamstrings, hips, chest. 30 sec each.',
    },

    // ---- W4 Day 2: Volume & Bodybuilding ----
    {
      day: 'Day 11',
      title: 'W4 · Volume & Bodybuilding',
      warmup: '10 min: 2 minutes ski erg. Banded pull-aparts (15). Overhead carry (20 yards each). Push-ups (10) + bodyweight squats (10).',
      duration: '60 min',
      sections: [{ name: 'Accessories', start: 0 }, { name: 'Core', start: 8 }],
      exercises: [
        {
          name: '1a. Dumbbell Bench Press',
          sets: 4,
          reps: '10',
          rest: '1:30',
          cues: 'Heavier dumbbells than week 3 — same 10 reps but more weight. Deep stretch at the bottom, strong squeeze at the top.',
        },
        {
          name: '1b. Chest-Supported Dumbbell Row',
          sets: 4,
          reps: '10',
          rest: '1:15',
          cues: 'Heavier dumbbells. Row up toward your hips, squeeze hard at the top. The bench keeps you honest — no cheating.',
        },
        {
          name: '2a. Seated Dumbbell Shoulder Press',
          sets: 4,
          reps: '10',
          rest: '1:15',
          cues: 'One more set than week 3. Press overhead, lock out fully, lower with a 2-second count.',
        },
        {
          name: '2b. Skull Crushers',
          sets: 4,
          reps: '10',
          rest: '1:00',
          cues: 'One more set this week. Upper arms vertical, bend only at the elbows, lower toward forehead, press up. Keep the burn going.',
        },
        {
          name: '3a. Cable Fly — High to Low',
          sets: 3,
          reps: '12',
          rest: '1:00',
          cues: 'New angle — cables set at the top position. Pull the handles down and together in front of your hips, like you\'re doing a double karate chop. This targets the lower chest fibers you haven\'t hit yet.',
        },
        {
          name: '3b. Cable Face Pull',
          sets: 4,
          reps: '15',
          rest: '1:00',
          cues: 'One more set than week 3. Pull the rope to your face, split your hands wide, squeeze the back of your shoulders. This keeps your shoulders healthy as the weights get heavier.',
        },
        {
          name: 'Bulgarian Split Squat',
          sets: 3,
          reps: '10 each',
          rest: '1:15',
          cues: 'Heavier dumbbells than week 3. Rear foot on the bench, lower straight down, drive up through the front heel. These should burn.',
        },
        {
          name: 'Barbell Hip Thrust',
          sets: 4,
          reps: '10',
          rest: '1:30',
          cues: 'One more set and heavier bar than week 3. Full hip extension, squeeze your glutes at the top like you\'re trying to crack a walnut.',
        },
        {
          name: 'Hanging Knee Raise',
          sets: 3,
          reps: '15',
          rest: '0:45',
          cues: 'Three more reps than week 3. Curl your pelvis up, knees to chest, slow lower. No swinging.',
        },
        {
          name: 'Farmer Carry',
          sets: 4,
          reps: '40 yards',
          rest: '1:00',
          cues: 'One more set, heavier weight. Tall posture, white-knuckle grip, don\'t stop walking.',
        },
      ],
      cooldown: '5 min: Chest stretch, lat stretch, hip flexor stretch — 30 sec each.',
    },

    // ---- W4 Day 3: Power & Speed ----
    {
      day: 'Day 12',
      title: 'W4 · Power & Speed',
      warmup: '15 min: 5 min jog. Broad jumps (3 reps). Lateral bounds (3 each). A-skips, high knees. Build-up sprints to 85% over 30 yards.',
      duration: '55 min',
      sections: [{ name: 'Speed', start: 0 }, { name: 'Power', start: 2 }, { name: 'Conditioning', start: 6 }],
      exercises: [
        {
          name: 'Broad Jump',
          sets: 4,
          reps: '5',
          rest: '1:00',
          cues: 'One more set than week 3. Try to beat your week 3 distance. Aggressive arm swing, full hip extension on takeoff, soft landing.',
        },
        {
          name: 'Lateral Bound',
          sets: 4,
          reps: '5 each',
          rest: '1:00',
          cues: 'One more set. Push off harder and cover more distance. Stick the landing — hold for a full second.',
        },
        {
          name: '1a. Power Clean',
          sets: 5,
          reps: '3',
          rest: '2:30',
          cues: 'Heavier than week 3 — straight sets of 3 with 5 sets. Your technique is there, now load it up. Aggressive hip drive, fast elbows, solid catch.',
        },
        {
          name: '1b. Box Jumps',
          sets: 5,
          reps: '3',
          rest: '1:30',
          cues: 'Higher box than weeks 1-2 if you\'re landing clean. Soft landing, full stand at the top, step down.',
        },
        {
          name: '2a. Medicine Ball Slam',
          sets: 4,
          reps: '12',
          rest: '1:15',
          cues: 'Heavier ball or more reps — 12 instead of 10. Slam it like it owes you money.',
        },
        {
          name: '2b. Clapping Push-Ups',
          sets: 4,
          reps: '8',
          rest: '1:00',
          cues: 'Upgrade from explosive push-ups — now you clap at the top. Push up so hard your hands leave the ground, clap quickly, and land with soft elbows. If clapping isn\'t there yet, stick with regular explosive push-ups but push for maximum height.',
        },
        {
          name: '3a. Heavy Sled Pushes',
          sets: 4,
          reps: '30 yards',
          rest: '2:00',
          cues: 'Heaviest sled yet. Same form — stay low, drive hard with each step.',
        },
        {
          name: '3b. Kettlebell Swing',
          sets: 4,
          reps: '15',
          rest: '1:00',
          cues: 'Heavier kettlebell and more reps. Powerful hip snap, bell to chest height.',
        },
        {
          name: 'Finisher: Run + Thrusters',
          sets: 1,
          reps: 'Max rounds in 10 min',
          rest: '-',
          cues: 'Heavier thrusters than week 3. Push hard — you should beat your week 3 round count even with more weight.',
        },
      ],
      cooldown: '5 min: Full body foam roll and stretch.',
    },

    // =====================================================================
    // PHASE 3: STRENGTH (Weeks 5–6)
    // Heavy compound work. Lower reps, heavier loads.
    // Main lifts: 5×5 @ 78% → 5×3 @ 82%. Grit work.
    // =====================================================================

    // ---- W5 Day 1: Strength ----
    {
      day: 'Day 13',
      title: 'W5 · Strength',
      warmup: '10 min: 2 minutes bike. Monster walks (15 each). Banded hip hinges (10). Bodyweight squats (10). Empty bar squats (5), empty bar bench press (5) — groove the pattern before loading up.',
      duration: '65 min',
      sections: [{ name: 'Strength', start: 0 }],
      exercises: [
        {
          name: 'Barbell Back Squat',
          sets: 5,
          reps: '5 @ 78%',
          rest: '3:00',
          cues: 'Welcome to the strength phase — 5×5 with real weight. These should feel heavy but doable. Every rep same depth, same speed, same tightness. Take a full 3 minutes rest between sets — you need it. This is where the foundation you built in weeks 1-4 pays off.',
        },
        {
          name: 'Barbell Deadlift',
          sets: 5,
          reps: '5 @ 78%',
          rest: '3:00',
          cues: 'Back to conventional stance with serious weight. Brace hard on every rep — big breath, core tight. Pull with authority. Reset your feet and grip between every rep if you need to. No touch-and-go — dead stop, reset, pull.',
        },
        {
          name: 'Bench Press',
          sets: 5,
          reps: '5 @ 78%',
          rest: '3:00',
          cues: 'Five sets of five at 78%. Shoulder blades locked, controlled lower, explosive press. Every rep should look identical. If rep 5 looks different from rep 1, the weight is too heavy.',
        },
        {
          name: 'Barbell Bent-Over Row',
          sets: 4,
          reps: '6',
          rest: '2:00',
          cues: 'Heavy rows — 6 reps with real weight. Hinge forward, flat back, pull the bar to your lower chest. Squeeze hard at the top. Don\'t use your hips to jerk the weight up.',
        },
        {
          name: 'Weighted Pull-Ups',
          sets: 4,
          reps: '5',
          rest: '2:00',
          cues: 'Heavier than phase 2. Full dead hang, pull chin over bar, 3-second lower on every rep. If you need to rest 10 seconds mid-set to finish your reps, that\'s fine.',
        },
        {
          name: 'Walking Lunge — Heavier',
          sets: 3,
          reps: '8 each leg',
          rest: '1:30',
          cues: 'Heavier dumbbells than phase 2 — these should feel like work. Chest up, full depth, controlled steps.',
        },
        {
          name: 'Plank',
          sets: 3,
          reps: '60 sec',
          rest: '1:00',
          cues: 'Double what you started with in week 1. Straight line from head to heels. If 60 seconds is easy, add weight on your back.',
        },
      ],
      cooldown: '5 min: Foam roll quads, hamstrings, glutes, back. Deep hip flexor stretch (45 sec each), pigeon stretch (45 sec each).',
    },

    // ---- W5 Day 2: Volume & Bodybuilding ----
    {
      day: 'Day 14',
      title: 'W5 · Volume & Bodybuilding',
      warmup: '10 min: 2 minutes ski erg. Banded pull-aparts (15). Push-ups (10). Empty bar overhead press (10).',
      duration: '60 min',
      sections: [{ name: 'Accessories', start: 0 }, { name: 'Core', start: 8 }],
      exercises: [
        {
          name: '1a. Incline Barbell Bench Press',
          sets: 4,
          reps: '8',
          rest: '1:30',
          cues: 'Barbell on the incline bench — heavier than dumbbells allowed. Set the bench to 30 degrees, unrack, lower to your upper chest, press up. Keep your butt on the bench.',
        },
        {
          name: '1b. Seated Cable Row',
          sets: 4,
          reps: '8',
          rest: '1:15',
          cues: 'Heavier than phase 2. Pull the handle to your belly button, elbows behind you, squeeze for a full second at peak contraction.',
        },
        {
          name: '2a. Push Press',
          sets: 3,
          reps: '8',
          rest: '2:00',
          cues: 'New overhead variation — you get to use your legs. Hold the bar at your shoulders, dip your knees slightly (2-3 inches), then drive up explosively through your legs and press the bar overhead in one fluid motion. This lets you handle heavier weight overhead than a strict press. Lock out at the top.',
        },
        {
          name: '2b. Weighted Dips',
          sets: 3,
          reps: '8',
          rest: '1:30',
          cues: 'Add weight with a dip belt or hold a dumbbell between your feet. Lean slightly forward (chest dips), lower until your elbows are at 90 degrees, then press up. If bodyweight is still challenging, do bodyweight and aim for a full 8 clean reps.',
        },
        {
          name: '3a. Dumbbell Lateral Raise',
          sets: 3,
          reps: '12',
          rest: '1:00',
          cues: 'Lead with your elbows, raise arms to shoulder height, lower over 2 seconds. Light weight, perfect form.',
        },
        {
          name: '3b. Dumbbell Hammer Curl',
          sets: 3,
          reps: '10',
          rest: '1:00',
          cues: 'Thumbs up, curl to shoulders, 2-second lower. Elbows glued to your sides.',
        },
        {
          name: 'Leg Press',
          sets: 4,
          reps: '10',
          rest: '1:30',
          cues: 'Feet shoulder-width on the platform, toes slightly out. Lower the sled until your knees are near 90 degrees, then drive up — don\'t lock your knees fully at the top. This builds quad size to complement your squat strength.',
        },
        {
          name: 'Barbell Hip Thrust',
          sets: 4,
          reps: '8',
          rest: '1:30',
          cues: 'Heavier bar than phase 2. Full hip extension, 2-second hold at the top of every rep. Squeeze your glutes like your life depends on it.',
        },
        {
          name: 'Cable Crunches',
          sets: 3,
          reps: '20',
          rest: '0:45',
          cues: 'Heavier weight on the cable. Crunch with your abs, not your hips. Exhale hard at the bottom.',
        },
        {
          name: 'Pallof Press',
          sets: 3,
          reps: '10 each side',
          rest: '0:45',
          cues: 'Stand sideways to a cable machine, handle at chest height. Hold the handle against your chest, then press your arms straight out in front of you — the cable will try to rotate you, resist it with your core. Hold for a beat with arms extended, then bring it back. This builds anti-rotation core strength.',
        },
      ],
      cooldown: '5 min: Chest stretch, lat stretch, shoulder stretch, hip flexor stretch — 30 sec each.',
    },

    // ---- W5 Day 3: Power & Speed ----
    {
      day: 'Day 15',
      title: 'W5 · Power & Speed',
      warmup: '15 min: 5 min easy jog. Broad jumps (3). Single-leg hops (5 each). A-skips, high knees, butt kicks. Build-up sprints to 85% over 40 yards.',
      duration: '55 min',
      sections: [{ name: 'Speed', start: 0 }, { name: 'Power', start: 2 }, { name: 'Conditioning', start: 6 }],
      exercises: [
        {
          name: 'Broad Jump',
          sets: 4,
          reps: '5',
          rest: '1:00',
          cues: 'Beat your phase 2 distance. Aggressive arm swing, full triple extension at takeoff, stick the landing.',
        },
        {
          name: 'Single Leg Hop',
          sets: 3,
          reps: '5 each',
          rest: '1:00',
          cues: 'New movement — hop forward on one leg for distance. Drive your knee up and forward, land softly, stabilize, then hop again. This builds single-leg power you can\'t get from bilateral jumps.',
        },
        {
          name: '1a. Hang Clean',
          sets: 5,
          reps: '3',
          rest: '2:30',
          cues: 'New variation — start with the bar at your hips instead of the floor. Dip your knees slightly, then explode with your hips and catch the bar at your shoulders. Starting from the hang position isolates the most explosive part of the clean. Heavier than your power clean.',
        },
        {
          name: '1b. Box Jumps',
          sets: 5,
          reps: '3',
          rest: '1:30',
          cues: 'Higher box than phase 2. Land soft, stand tall, step down. Quality over quantity.',
        },
        {
          name: '2a. Medicine Ball Rotational Throw',
          sets: 4,
          reps: '6 each side',
          rest: '1:15',
          cues: 'Stand sideways to a wall, feet shoulder-width. Hold a med ball at your hip, rotate your torso explosively and slam the ball into the wall. Catch it and repeat. This builds rotational power — the kind that makes you dangerous in any sport.',
        },
        {
          name: '2b. Explosive Push-Ups',
          sets: 4,
          reps: '8',
          rest: '1:00',
          cues: 'Maximum height on every rep. Push the ground away like it\'s on fire.',
        },
        {
          name: 'Sprint Intervals',
          sets: 4,
          reps: '40 yards',
          rest: '2:00',
          cues: 'All-out sprints — 95% effort. Explode out of your stance, pump your arms, drive your knees. Walk back to the start and fully recover before the next one. Speed, not endurance.',
        },
        {
          name: 'Finisher: Run + Thrusters',
          sets: 1,
          reps: 'Max rounds in 10 min',
          rest: '-',
          cues: 'Heaviest thrusters yet. Push hard — your conditioning should be noticeably better than week 1.',
        },
      ],
      cooldown: '5 min: Full body foam roll and stretch. Extra time on hip flexors and calves.',
    },

    // ---- W6 Day 1: Strength ----
    {
      day: 'Day 16',
      title: 'W6 · Strength',
      warmup: '10 min: 2 minutes bike. Monster walks (15 each). Band pull-aparts (15). Empty bar squats (5), empty bar bench (5). Build to 50% for 3 reps on your first exercise to prime the nervous system.',
      duration: '70 min',
      sections: [{ name: 'Strength', start: 0 }],
      exercises: [
        {
          name: 'Barbell Back Squat',
          sets: 5,
          reps: '3 @ 82%',
          rest: '3:00',
          cues: 'Heavy triples — fewer reps, more weight than week 5. Each rep should feel like a statement. Take your time between sets, breathe, reset, and attack. Full depth, chest up, drive through your heels. You are stronger than you were 5 weeks ago. Prove it.',
        },
        {
          name: 'Barbell Deadlift',
          sets: 5,
          reps: '3 @ 82%',
          rest: '3:00',
          cues: 'Heavy triples. Dead stop between every rep — reset your position completely. Flat back, tight core, explosive pull. This is the heaviest you\'ve pulled in this program so far.',
        },
        {
          name: 'Bench Press',
          sets: 5,
          reps: '3 @ 82%',
          rest: '3:00',
          cues: 'Heavy triples. Shoulder blades locked, controlled lower, explosive press. Every rep should be clean. If your form breaks down on rep 3, the weight is too heavy — drop 5 lbs.',
        },
        {
          name: 'Pendlay Row',
          sets: 4,
          reps: '5',
          rest: '2:00',
          cues: 'Heavier than phase 2. Dead stop on the floor, explosive pull to your chest. Five heavy reps per set.',
        },
        {
          name: 'Weighted Pull-Ups',
          sets: 4,
          reps: '4',
          rest: '2:00',
          cues: 'Heaviest pull-ups yet. Add weight — every rep is a full dead hang to chin over bar. Quality over quantity.',
        },
        {
          name: 'Reverse Lunge — Barbell',
          sets: 3,
          reps: '6 each leg',
          rest: '1:30',
          cues: 'Upgrade — bar on your back instead of dumbbells. Step back, lower to a tap, drive through the front heel. Heavier and more stable than the dumbbell version.',
        },
        {
          name: 'Ab Wheel Rollout',
          sets: 3,
          reps: '12',
          rest: '1:00',
          cues: 'Full extension if you can. From your toes if possible. Control the entire range.',
        },
      ],
      cooldown: '5 min: Foam roll and deep stretch — quads, hamstrings, hips, chest, back. Hold each stretch 45 sec.',
    },

    // ---- W6 Day 2: Volume & Bodybuilding ----
    {
      day: 'Day 17',
      title: 'W6 · Volume & Bodybuilding',
      warmup: '10 min: 2 minutes ski erg. Banded pull-aparts (15). Push-ups (15). Empty bar overhead press (10).',
      duration: '60 min',
      sections: [{ name: 'Accessories', start: 0 }, { name: 'Core', start: 8 }],
      exercises: [
        {
          name: '1a. Incline Barbell Bench Press',
          sets: 4,
          reps: '6',
          rest: '1:30',
          cues: 'Heavier than week 5 — fewer reps, more weight. Lower to your upper chest with control, press up with force.',
        },
        {
          name: '1b. Chest-Supported Dumbbell Row',
          sets: 4,
          reps: '6',
          rest: '1:15',
          cues: 'Heaviest rows yet. Lie on the incline bench, row heavy dumbbells to your hips, squeeze your back hard.',
        },
        {
          name: '2a. Push Press',
          sets: 4,
          reps: '6',
          rest: '2:00',
          cues: 'One more set and heavier than week 5. Dip, drive, press, lock out. Use your legs to move more weight overhead.',
        },
        {
          name: '2b. Weighted Dips',
          sets: 4,
          reps: '6',
          rest: '1:30',
          cues: 'Heavier than week 5. Lower to 90 degrees, press up with force. Add weight if bodyweight is too easy.',
        },
        {
          name: '3a. Cable Lateral Raise',
          sets: 4,
          reps: '10',
          rest: '1:00',
          cues: 'Cable version — constant tension through the whole range. Stand next to the cable machine, pull the handle out to the side until your arm is at shoulder height.',
        },
        {
          name: '3b. Barbell Curl',
          sets: 3,
          reps: '8',
          rest: '1:00',
          cues: 'Stand with the bar, underhand grip. Curl up by bending your elbows only — no swinging. Squeeze at the top, lower over 2 seconds.',
        },
        {
          name: 'Leg Press',
          sets: 4,
          reps: '8',
          rest: '1:30',
          cues: 'Heavier than week 5 — fewer reps, more plates. Full range, don\'t lock knees at the top.',
        },
        {
          name: 'Barbell Hip Thrust',
          sets: 4,
          reps: '6',
          rest: '1:30',
          cues: 'Heaviest hip thrusts yet. Full lockout, 3-second hold at the top of every rep. Your glutes are getting seriously strong.',
        },
        {
          name: 'Hanging Leg Raise',
          sets: 3,
          reps: '12',
          rest: '0:45',
          cues: 'Straight legs this time — hang from the bar, raise your straight legs up toward the bar. Go as high as you can while keeping control. Much harder than knee raises.',
        },
        {
          name: 'Farmer Carry — Heavy',
          sets: 4,
          reps: '40 yards',
          rest: '1:00',
          cues: 'Heaviest carry yet. Your grip is being forged. Tall posture, don\'t stop walking.',
        },
      ],
      cooldown: '5 min: Chest stretch, lat stretch, hip flexor stretch, shoulder stretch — 30 sec each.',
    },

    // ---- W6 Day 3: Power & Speed ----
    {
      day: 'Day 18',
      title: 'W6 · Power & Speed',
      warmup: '15 min: 5 min jog. Depth jumps from a low box (3 reps). Lateral bounds (3 each). A-skips, high knees. Build-up sprints to 90% over 40 yards.',
      duration: '55 min',
      sections: [{ name: 'Speed', start: 0 }, { name: 'Power', start: 2 }, { name: 'Conditioning', start: 6 }],
      exercises: [
        {
          name: 'Depth Jump',
          sets: 4,
          reps: '3',
          rest: '1:30',
          cues: 'Higher box than week 3. Step off, the instant your feet hit, jump as high as possible. Minimum ground contact time.',
        },
        {
          name: 'Lateral Bound',
          sets: 4,
          reps: '5 each',
          rest: '1:00',
          cues: 'Cover more ground than any week before. Explode laterally, stick the landing, hold for a second.',
        },
        {
          name: '1a. Hang Clean',
          sets: 5,
          reps: '2',
          rest: '2:30',
          cues: 'Heavy doubles — add weight from week 5. Two explosive reps per set. Violent hip extension, fast elbows.',
        },
        {
          name: '1b. Box Jumps',
          sets: 5,
          reps: '3',
          rest: '1:30',
          cues: 'Highest box yet. If you can\'t land clean, go back to a box you can own. Quality matters more than height.',
        },
        {
          name: '2a. Medicine Ball Chest Pass',
          sets: 4,
          reps: '8',
          rest: '1:15',
          cues: 'Stand facing a wall with a med ball at your chest. Explosively push it into the wall like a chest pass in basketball. Catch it and immediately throw again. This builds explosive pushing power.',
        },
        {
          name: '2b. Clapping Push-Ups',
          sets: 4,
          reps: '6',
          rest: '1:00',
          cues: 'Push up, clap, land soft. Six quality reps — each one explosive.',
        },
        {
          name: 'Sprint Intervals',
          sets: 5,
          reps: '40 yards',
          rest: '2:00',
          cues: 'One more sprint than week 5. All-out effort — 95%. Walk back, fully recover, go again.',
        },
        {
          name: 'Finisher: Run + Thrusters',
          sets: 1,
          reps: 'Max rounds in 8 min',
          rest: '-',
          cues: 'Heavy thrusters, shorter time cap. Fewer minutes means you push harder. Leave nothing in the tank.',
        },
      ],
      cooldown: '5 min: Full body foam roll and stretch. Take extra time — you\'ve earned it.',
    },

    // =====================================================================
    // PHASE 4: PEAK & TEST (Weeks 7–8)
    // Week 7: Heavy doubles, peak performance.
    // Week 8: Test new maxes. Prove the gains. Reduced accessories.
    // =====================================================================

    // ---- W7 Day 1: Strength — Peak ----
    {
      day: 'Day 19',
      title: 'W7 · Strength — Peak',
      warmup: '12 min: 2 minutes bike. Monster walks (15 each). Band pull-aparts (15). Empty bar work — squat, bench, deadlift — 5 reps each. Then ramp up: hit 50% × 3, 60% × 2, 70% × 1 on your first lift before starting your working sets.',
      duration: '70 min',
      sections: [{ name: 'Peak Strength', start: 0 }],
      exercises: [
        {
          name: 'Barbell Back Squat',
          sets: 6,
          reps: '3-2-2-1-2-2 @ 85-90%',
          rest: '3:30',
          cues: 'This is what you\'ve been building toward. Warm up to about 85%, hit a set of 3, then push up to 88-90% for doubles and a single. After the heavy work, drop back to 85% for two backoff doubles. Full depth on every rep — no cutting it short when the weight is heavy. Trust your body — it\'s ready.',
        },
        {
          name: 'Bench Press',
          sets: 6,
          reps: '3-2-2-1-2-2 @ 85-90%',
          rest: '3:30',
          cues: 'Same scheme as squats. Build to a heavy single at 88-90%, then backoff doubles at 85%. Shoulder blades locked, controlled lower, maximum drive off the chest. You\'re close to your new max — respect the weight.',
        },
        {
          name: 'Barbell Deadlift',
          sets: 5,
          reps: '2-2-1-1-2 @ 85-90%',
          rest: '3:30',
          cues: 'Heavy doubles and singles. Reset completely between every rep. Flat back, big breath, explosive pull. After the heavy singles, do a backoff set of 2 at 85%.',
        },
        {
          name: 'Barbell Bent-Over Row',
          sets: 3,
          reps: '5',
          rest: '2:00',
          cues: 'Heavy but reduced volume — 3 sets only. Your back is already fatigued from deadlifts. Pull with authority.',
        },
        {
          name: 'Pull-Ups',
          sets: 3,
          reps: '5',
          rest: '2:00',
          cues: 'Moderate weight or bodyweight — 3 sets of 5 to finish. Full range, strict form. Keep it clean.',
        },
        {
          name: 'Plank',
          sets: 3,
          reps: '60 sec',
          rest: '1:00',
          cues: 'Light core work to finish. Hold it solid.',
        },
      ],
      cooldown: '5 min: Full body foam roll. Deep stretching — hold each position 45-60 sec. Your body worked hard today.',
    },

    // ---- W7 Day 2: Volume — Recovery Focused ----
    {
      day: 'Day 20',
      title: 'W7 · Volume — Recovery',
      warmup: '10 min: 2 minutes ski erg. Banded pull-aparts (15). Light push-ups (10). Bodyweight squats (10). This is a lighter day — no need to fire up the nervous system.',
      duration: '50 min',
      sections: [{ name: 'Accessories', start: 0 }, { name: 'Core', start: 6 }],
      exercises: [
        {
          name: '1a. Dumbbell Bench Press',
          sets: 3,
          reps: '8',
          rest: '1:30',
          cues: 'Moderate weight — this is a recovery session, not a max effort. Good stretch, good squeeze, clean reps.',
        },
        {
          name: '1b. Seated Cable Row',
          sets: 3,
          reps: '8',
          rest: '1:15',
          cues: 'Moderate weight. Pull to your belly, squeeze, return. Smooth and controlled.',
        },
        {
          name: '2a. Arnold Press',
          sets: 3,
          reps: '8',
          rest: '1:15',
          cues: 'Light to moderate. Full rotation, full lockout. Keep it moving.',
        },
        {
          name: '2b. Cable Tricep Pushdown',
          sets: 3,
          reps: '10',
          rest: '1:00',
          cues: 'Light pump work. Elbows pinned, full extension, steady pace.',
        },
        {
          name: 'Dumbbell Split Squat',
          sets: 3,
          reps: '8 each',
          rest: '1:15',
          cues: 'Moderate weight. Keeping your legs fresh for test week while still moving.',
        },
        {
          name: 'Barbell Hip Thrust',
          sets: 3,
          reps: '8',
          rest: '1:30',
          cues: 'Moderate weight. Full extension, good squeeze. Nothing maximal this week.',
        },
        {
          name: 'Cable Crunches',
          sets: 2,
          reps: '15',
          rest: '0:45',
          cues: 'Light core work. Keep the movement controlled.',
        },
        {
          name: 'Pallof Press',
          sets: 2,
          reps: '10 each side',
          rest: '0:45',
          cues: 'Light anti-rotation work. Press out, hold, return. Stay tight.',
        },
      ],
      cooldown: '5 min: Light stretching and foam rolling. Take it easy — test week is coming.',
    },

    // ---- W7 Day 3: Power — Maintenance ----
    {
      day: 'Day 21',
      title: 'W7 · Power — Maintenance',
      warmup: '15 min: 5 min easy jog. Light plyometrics — line hops (2×10 sec), lateral hops (2×10 sec). A-skips, high knees. Build-up sprints to 85% over 30 yards.',
      duration: '45 min',
      sections: [{ name: 'Speed', start: 0 }, { name: 'Power', start: 1 }, { name: 'Conditioning', start: 4 }],
      exercises: [
        {
          name: 'Box Jumps',
          sets: 4,
          reps: '3',
          rest: '1:30',
          cues: 'Moderate height — not your max box. Focus on landing quality and explosiveness. Keep your nervous system sharp without beating it up.',
        },
        {
          name: 'Power Clean',
          sets: 4,
          reps: '2',
          rest: '2:30',
          cues: 'Moderate weight — about 80% of your best. Fast and crisp. Stay explosive without going to max effort. Save your max for test week.',
        },
        {
          name: 'Medicine Ball Slam',
          sets: 3,
          reps: '8',
          rest: '1:15',
          cues: 'Moderate ball. Slam hard but don\'t exhaust yourself. Stay powerful.',
        },
        {
          name: 'Kettlebell Swing',
          sets: 3,
          reps: '12',
          rest: '1:00',
          cues: 'Moderate weight. Clean hip snap, let it float. Keep the movement sharp.',
        },
        {
          name: 'Sprint Intervals',
          sets: 3,
          reps: '30 yards',
          rest: '2:00',
          cues: 'Three sprints at 90% — just enough to keep your speed sharp without draining your tank. Full recovery between.',
        },
      ],
      cooldown: '5 min: Full body stretch and foam roll. Rest up — test week starts next.',
    },

    // ---- W8 Day 1: Strength — TEST DAY ----
    {
      day: 'Day 22',
      title: 'W8 · TEST DAY — Big Three',
      warmup: '15 min: This is the most important warmup of the program. 3 minutes easy bike. Monster walks (10 each). Band pull-aparts (15). Then build up to your test weight with: empty bar × 5, 40% × 5, 50% × 3, 60% × 2, 70% × 1, 80% × 1. Rest 2-3 minutes between warmup sets as you get heavier. You should feel strong and sharp, not tired.',
      duration: '75 min',
      sections: [{ name: 'Test — Squat', start: 0 }, { name: 'Test — Bench', start: 1 }, { name: 'Test — Deadlift', start: 2 }],
      exercises: [
        {
          name: 'Barbell Back Squat — Test',
          sets: 5,
          reps: 'Work to new 1-3RM',
          rest: '4:00',
          cues: 'This is it. After your warmup sets, take 3-5 attempts to find your max for the day. Start at about 85% for a triple, add 5-10 lbs per attempt. If a triple felt strong, go for a double. If the double was clean, try a single with 5-10 more. Stop when form starts to break down — a clean new PR beats a sloppy heavier one every time. Record your best lift. Compare it to your week 1 baseline. That gap is your progress.',
        },
        {
          name: 'Bench Press — Test',
          sets: 5,
          reps: 'Work to new 1-3RM',
          rest: '4:00',
          cues: 'Same approach. Start around 85%, take 3-5 attempts working up. Shoulder blades locked, controlled lower, max drive. Have a spotter for anything above 90%. Go for a PR but never sacrifice form — a clean heavy rep is worth more than a shaky max.',
        },
        {
          name: 'Barbell Deadlift — Test',
          sets: 5,
          reps: 'Work to new 1-3RM',
          rest: '4:00',
          cues: 'Final test. Build up to your max. Flat back, tight core, explosive pull. Every rep resets from a dead stop. When the weight gets truly heavy, use a mixed grip (one hand over, one under) if you need to — or hook grip if you can handle it. Record your number. You\'ve earned whatever is on that bar.',
        },
      ],
      cooldown: '10 min: Extended foam rolling and stretching. You just tested your maxes — treat your body right. Quads, hamstrings, glutes, back, chest — 45-60 sec each. Drink water. Eat protein within the hour.',
    },

    // ---- W8 Day 2: Accessory Tests + Volume ----
    {
      day: 'Day 23',
      title: 'W8 · Accessory Tests',
      warmup: '10 min: 2 minutes ski erg. Banded pull-aparts (15). Light overhead press (10). Pull-up bar hang (30 sec).',
      duration: '55 min',
      sections: [{ name: 'Tests', start: 0 }, { name: 'Light Pump', start: 3 }],
      exercises: [
        {
          name: 'Weighted Pull-Ups — Test',
          sets: 4,
          reps: 'Work to max weight × 3',
          rest: '3:00',
          cues: 'Find your heaviest pull-up for 3 clean reps. Start with bodyweight × 5, then add weight: +10 × 3, +20 × 3, keep going until you can\'t get 3 clean reps. Record the heaviest weight you hit for a triple. Compare to week 1 when pull-ups were bodyweight.',
        },
        {
          name: 'Overhead Press — Test',
          sets: 4,
          reps: 'Work to new 3-5RM',
          rest: '3:00',
          cues: 'Strict press — no leg drive. Build up to your heaviest set of 3-5. Start light, add 5 lbs per set. Squeeze your glutes and brace your core on every rep. Record your best.',
        },
        {
          name: 'Barbell Bent-Over Row — Test',
          sets: 4,
          reps: 'Work to new 5RM',
          rest: '2:30',
          cues: 'Find your heaviest row for 5 clean reps — no jerking or using your legs. Hinge forward, flat back, pull to your chest. Compare to your week 1 rows.',
        },
        {
          name: 'Dumbbell Bench Press',
          sets: 3,
          reps: '12',
          rest: '1:15',
          cues: 'Light pump work — moderate weight, get some blood flowing. Your body is recovering from test day yesterday.',
        },
        {
          name: 'Seated Cable Row',
          sets: 3,
          reps: '12',
          rest: '1:15',
          cues: 'Light pump. Smooth reps, good squeeze.',
        },
        {
          name: 'Arnold Press',
          sets: 3,
          reps: '12',
          rest: '1:00',
          cues: 'Light weight, full rotation, clean reps. Recovery work.',
        },
        {
          name: 'Barbell Hip Thrust',
          sets: 3,
          reps: '10',
          rest: '1:15',
          cues: 'Moderate weight. Full extension, good squeeze.',
        },
        {
          name: 'Cable Crunches',
          sets: 3,
          reps: '15',
          rest: '0:45',
          cues: 'Light core work to finish.',
        },
      ],
      cooldown: '5 min: Full body stretch — 30 sec each position.',
    },

    // ---- W8 Day 3: Power Test + Celebration ----
    {
      day: 'Day 24',
      title: 'W8 · Power Test + Celebration',
      warmup: '15 min: 5 min easy jog. Broad jumps (3). Line hops (2×10 sec). A-skips, high knees. Build-up sprints to 85% over 30 yards.',
      duration: '50 min',
      sections: [{ name: 'Power Tests', start: 0 }, { name: 'Final Conditioning', start: 3 }],
      exercises: [
        {
          name: 'Power Clean — Test',
          sets: 5,
          reps: 'Work to new 3RM',
          rest: '3:00',
          cues: 'Find your heaviest clean for 3 reps. Build up from 50% in sets of 3, adding weight each time. Stop when form breaks. Compare to your week 1 technique work — you should be moving significantly more weight with better form.',
        },
        {
          name: 'Box Jump — Max Height Test',
          sets: 5,
          reps: '1',
          rest: '2:00',
          cues: 'Start at a comfortable height and keep adding. One jump per set. Land clean, stand tall. Keep going until you find your max height for a safe, controlled landing. This is your vertical power test.',
        },
        {
          name: 'Broad Jump — Max Distance Test',
          sets: 3,
          reps: '3',
          rest: '1:30',
          cues: 'Three attempts to find your max distance. Measure your best. Compare to week 3 when you first started broad jumps.',
        },
        {
          name: '40-Yard Sprint — Time Trial',
          sets: 3,
          reps: '1',
          rest: '3:00',
          cues: 'Three all-out sprints. Have someone time you or use a stopwatch. Full recovery between each. Record your best time. This is your speed test.',
        },
        {
          name: 'Final Finisher: Run + Thrusters',
          sets: 1,
          reps: 'Max rounds in 10 min',
          rest: '-',
          cues: 'Same weight and format as week 5. This is your conditioning retest — you should crush your earlier number. 200m run + 10 thrusters per round. Leave absolutely everything on the floor. This is the last workout of the program. Make it count.',
        },
      ],
      cooldown: '10 min: Extended cool-down — you just finished an 8-week program. Full body foam roll, every major muscle group. Deep stretching: quads, hamstrings, hip flexors, glutes, chest, lats, shoulders — hold each for 60 sec. Take stock of how far you\'ve come. You showed up, you put in the work, and you got stronger. That\'s what it means to compete.',
    },
  ],
}
