import type { Program } from './programs'

export const hybridProgram: Program = {
  id: 'hybrid-training',
  name: 'Hybrid Training',
  weeks: 6,
  frequency: '6x / week',
  description: 'The best of both worlds — build muscle, build engine. No weakness.',
  category: 'hybrid',
  image: '/programs/hybrid.jpg',
  days: [
    // =============================================
    // WEEK 1 — FOUNDATION
    // =============================================
    {
      day: 'Day 1',
      title: 'W1 · Upper Push + Conditioning',
      warmup: '5 min: band pull-aparts, arm circles, push-up walkouts, jumping jacks',
      duration: '55 min',
      exercises: [
        {
          name: 'Bench Press',
          sets: 4,
          reps: '6',
          tempo: '3-1-1-0',
          rest: '2:30',
          cues: 'Shoulder blades pinched, feet flat. Controlled descent, explosive press.',
        },
        {
          name: '1a. Dumbbell Incline Press',
          sets: 3,
          reps: '10',
          rest: '1:30',
          cues: '30-degree angle. Full stretch at the bottom, squeeze at the top.',
        },
        {
          name: '1b. Dumbbell Lateral Raise',
          sets: 3,
          reps: '12',
          rest: '1:00',
          cues: 'Slight bend in elbows. Raise to shoulder height. Control the negative — don\'t swing.',
        },
        {
          name: 'Tricep Dips',
          sets: 3,
          reps: '10-12',
          rest: '1:30',
          cues: 'Full depth — upper arm parallel. Drive up to full lockout. Lean forward slightly.',
        },
        {
          name: 'Assault Bike Intervals',
          sets: 6,
          reps: '30 sec on / 30 sec off',
          rest: '0:30',
          cues: 'Max effort on work intervals. Full body — push and pull with the arms.',
        },
        {
          name: 'Push-Up — Burnout',
          sets: 2,
          reps: 'Max reps',
          rest: '1:00',
          cues: 'Chest to floor every rep. When you can\'t do full, drop to knees. Empty the tank.',
        },
      ],
      cooldown: '5 min: chest doorway stretch, tricep stretch, shoulder stretch',
    },
    {
      day: 'Day 2',
      title: 'W1 · Lower Body Strength',
      warmup: '5 min: hip circles, leg swings, bodyweight squats, glute bridges',
      duration: '55 min',
      exercises: [
        {
          name: 'Barbell Back Squat',
          sets: 5,
          reps: '5',
          rest: '2:30',
          cues: 'Brace hard. Break at hips and knees together. Drive heels through the floor.',
        },
        {
          name: 'Romanian Deadlift',
          sets: 4,
          reps: '8',
          tempo: '3-1-1-0',
          rest: '2:00',
          cues: 'Hips back, bar tracks down the thighs. Hamstring stretch, then glute squeeze at top.',
        },
        {
          name: '1a. Walking Lunge',
          sets: 3,
          reps: '10 each',
          rest: '1:30',
          cues: 'Long stride, knee tracks over toes. Back knee kisses the floor. Stay upright.',
        },
        {
          name: '1b. Leg Curl',
          sets: 3,
          reps: '12',
          rest: '1:15',
          cues: 'Slow negative. Squeeze at the top. Full range of motion.',
        },
        {
          name: '2a. Calf Raise',
          sets: 3,
          reps: '15',
          rest: '1:00',
          cues: 'Full stretch at the bottom, pause at the top. Slow and controlled.',
        },
        {
          name: '2b. Hanging Leg Raise',
          sets: 3,
          reps: '10',
          rest: '1:00',
          cues: 'No swinging. Curl the hips under as you raise. Control the descent.',
        },
      ],
      cooldown: '5 min: quad stretch, hamstring stretch, calf stretch',
    },
    {
      day: 'Day 3',
      title: 'W1 · Engine Builder',
      warmup: '5 min: light jog, arm swings, high knees, butt kicks',
      duration: '40 min',
      exercises: [
        {
          name: 'Rowing Machine',
          sets: 4,
          reps: '500m',
          rest: '1:30',
          cues: 'Legs-back-arms sequence. Strong leg drive. Maintain a consistent pace.',
        },
        {
          name: 'Kettlebell Swing',
          sets: 4,
          reps: '20',
          rest: '1:00',
          cues: 'Hinge hard, snap the hips. Bell floats to chest height. Arms are along for the ride.',
        },
        {
          name: 'Burpee',
          sets: 4,
          reps: '10',
          rest: '1:00',
          cues: 'Chest to floor, pop up, jump and clap. Speed matters — keep moving.',
        },
        {
          name: 'Battle Rope Alternating Waves',
          sets: 4,
          reps: '30 sec',
          rest: '0:45',
          cues: 'Small, fast movements from the shoulders. Stay low in an athletic stance.',
        },
        {
          name: 'Box Step-Up',
          sets: 3,
          reps: '12 each',
          rest: '1:00',
          cues: 'Drive through the lead leg. Don\'t push off the back foot. Full extension at the top.',
        },
      ],
      cooldown: '5 min: full body stretch',
    },
    {
      day: 'Day 4',
      title: 'W1 · Upper Pull + Power',
      warmup: '5 min: band pull-aparts, cat-cow, scapular push-ups, face pulls',
      duration: '55 min',
      exercises: [
        {
          name: 'Weighted Pull-Ups',
          sets: 4,
          reps: '6',
          rest: '2:30',
          cues: 'Full dead hang. Chest to bar. Slow negative — fight the way down.',
        },
        {
          name: 'Barbell Bent-Over Row',
          sets: 4,
          reps: '8',
          rest: '2:00',
          cues: '45-degree torso. Pull to lower chest. Squeeze the shoulder blades for a beat.',
        },
        {
          name: '1a. Dumbbell Hammer Curl',
          sets: 3,
          reps: '12',
          rest: '1:00',
          cues: 'Neutral grip, elbows pinned. No swinging — controlled reps.',
        },
        {
          name: '1b. Face Pull',
          sets: 3,
          reps: '15',
          rest: '1:00',
          cues: 'Pull to forehead. External rotate at the end. Squeeze rear delts hard.',
        },
        {
          name: 'Power Clean',
          sets: 4,
          reps: '4',
          rest: '2:30',
          cues: 'Triple extension — ankles, knees, hips. Catch in the front rack. Absorb in a quarter squat.',
        },
        {
          name: 'Med Ball Rotational Throw',
          sets: 3,
          reps: '8 each side',
          rest: '1:00',
          cues: 'Rotate from the hips, not the arms. Throw through the wall. Reset every rep.',
        },
      ],
      cooldown: '5 min: lat stretch, bicep stretch, thoracic extension over foam roller',
    },
    {
      day: 'Day 5',
      title: 'W1 · Lower Body Hypertrophy',
      warmup: '5 min: foam roll quads/glutes, hip circles, walking lunges, leg swings',
      duration: '50 min',
      exercises: [
        {
          name: 'Front Squat',
          sets: 4,
          reps: '8',
          rest: '2:00',
          cues: 'Elbows high. Sit between the hips. Drive up with authority.',
        },
        {
          name: 'Bulgarian Split Squat',
          sets: 3,
          reps: '10 each',
          rest: '1:30',
          cues: 'Rear foot on bench. Front knee over toes. Stay tall through the torso.',
        },
        {
          name: 'Hip Thrust',
          sets: 4,
          reps: '12',
          rest: '1:30',
          cues: 'Upper back on bench, feet flat. Drive through heels. Full hip extension, squeeze at top.',
        },
        {
          name: '1a. Leg Extension',
          sets: 3,
          reps: '15',
          rest: '1:00',
          cues: 'Full lockout at the top. 2 second hold. Slow negative.',
        },
        {
          name: '1b. Goblet Squat — 1.5 Reps',
          sets: 3,
          reps: '8',
          rest: '1:30',
          cues: 'Go all the way down, come halfway up, go back down, then stand. That\'s one rep.',
        },
        {
          name: 'Suitcase Carry',
          sets: 3,
          reps: '30 yards each hand',
          rest: '1:00',
          cues: 'One heavy dumbbell, stay perfectly upright. Don\'t lean. Core fights the offset.',
        },
      ],
      cooldown: '5 min: pigeon stretch, quad stretch, hamstring stretch',
    },
    {
      day: 'Day 6',
      title: 'W1 · Full Body Blast',
      warmup: '5 min: jump rope, inchworms, mountain climbers, high knees',
      duration: '45 min',
      exercises: [
        {
          name: 'Dumbbell Complex',
          sets: 4,
          reps: '6 each move',
          rest: '2:00',
          cues: 'Deadlift → Row → Clean → Press → Squat. No rest between moves. That\'s one set.',
        },
        {
          name: 'Assault Bike Sprint',
          sets: 5,
          reps: '20 sec max / 40 sec easy',
          rest: '-',
          cues: 'All-out for 20 seconds. True max effort. Recover at easy pace.',
        },
        {
          name: 'Wall Ball',
          sets: 4,
          reps: '15',
          rest: '1:00',
          cues: 'Deep squat, throw to target on the way up. Catch and squat in one motion.',
        },
        {
          name: 'Sled Push',
          sets: 3,
          reps: '40 yards',
          rest: '1:30',
          cues: 'Low body angle. Short, powerful steps. Arms locked out.',
        },
        {
          name: 'Plank to Push-Up',
          sets: 3,
          reps: '8 each arm lead',
          rest: '1:00',
          cues: 'Start on forearms, press up to hands one arm at a time. Keep hips level.',
        },
      ],
      cooldown: '10 min: full body stretch and foam roll. You earned it.',
    },

    // =============================================
    // WEEK 2 — FOUNDATION+ (add volume)
    // =============================================
    {
      day: 'Day 7',
      title: 'W2 · Upper Push + Conditioning',
      warmup: '5 min: band pull-aparts, arm circles, push-up walkouts, jumping jacks',
      duration: '60 min',
      exercises: [
        {
          name: 'Bench Press',
          sets: 5,
          reps: '6',
          tempo: '3-1-1-0',
          rest: '2:30',
          cues: 'Added a set this week. Same weight, same control. Earn the volume.',
        },
        {
          name: '1a. Dumbbell Incline Press',
          sets: 3,
          reps: '12',
          rest: '1:30',
          cues: '30-degree angle. Two extra reps — make them count. Full stretch, full squeeze.',
        },
        {
          name: '1b. Dumbbell Lateral Raise',
          sets: 3,
          reps: '14',
          rest: '1:00',
          cues: 'Slight bend in elbows. Two extra reps over last week. Don\'t speed up — own each one.',
        },
        {
          name: 'Tricep Dips',
          sets: 4,
          reps: '10-12',
          rest: '1:30',
          cues: 'Extra set this week. Full depth, full lockout. If bodyweight is easy, add a dumbbell between your feet.',
        },
        {
          name: 'Assault Bike Intervals',
          sets: 7,
          reps: '30 sec on / 30 sec off',
          rest: '0:30',
          cues: 'One more round than last week. Don\'t let the pace drop — same intensity, more rounds.',
        },
        {
          name: 'Push-Up — Burnout',
          sets: 3,
          reps: 'Max reps',
          rest: '1:00',
          cues: 'Three sets this week. Beat your total from Week 1. Chest to floor every rep.',
        },
      ],
      cooldown: '5 min: chest doorway stretch, tricep stretch, shoulder stretch',
    },
    {
      day: 'Day 8',
      title: 'W2 · Lower Body Strength',
      warmup: '5 min: hip circles, leg swings, bodyweight squats, glute bridges',
      duration: '60 min',
      exercises: [
        {
          name: 'Barbell Back Squat',
          sets: 5,
          reps: '5',
          rest: '2:30',
          cues: 'Same sets and reps — add 5-10 lbs over last week. Brace harder, move better.',
        },
        {
          name: 'Romanian Deadlift',
          sets: 4,
          reps: '10',
          tempo: '3-1-1-0',
          rest: '2:00',
          cues: 'Two extra reps. Same weight. Feel the hamstrings load deep in the stretch.',
        },
        {
          name: '1a. Walking Lunge',
          sets: 3,
          reps: '12 each',
          rest: '1:30',
          cues: 'Two more per leg. Longer set, same quality. Back knee brushes the floor every rep.',
        },
        {
          name: '1b. Leg Curl',
          sets: 3,
          reps: '14',
          rest: '1:15',
          cues: 'Extra reps — slow the negative even more. Feel the hamstring fight on the way down.',
        },
        {
          name: '2a. Calf Raise',
          sets: 4,
          reps: '15',
          rest: '1:00',
          cues: 'Added a set. Full stretch at the bottom, 2-second hold at the top.',
        },
        {
          name: '2b. Hanging Leg Raise',
          sets: 4,
          reps: '10',
          rest: '1:00',
          cues: 'Extra set. No swinging. If you start kipping, the set is over — start clean.',
        },
      ],
      cooldown: '5 min: quad stretch, hamstring stretch, calf stretch',
    },
    {
      day: 'Day 9',
      title: 'W2 · Engine Builder',
      warmup: '5 min: light jog, arm swings, high knees, butt kicks',
      duration: '42 min',
      exercises: [
        {
          name: 'Rowing Machine',
          sets: 5,
          reps: '500m',
          rest: '1:15',
          cues: 'One more round, 15 seconds less rest. Your pace should be faster than Week 1.',
        },
        {
          name: 'Kettlebell Swing',
          sets: 5,
          reps: '20',
          rest: '0:45',
          cues: 'Extra set, shorter rest. The bell should pop to chest height every rep. Hips do the work.',
        },
        {
          name: 'Burpee',
          sets: 4,
          reps: '12',
          rest: '1:00',
          cues: 'Two extra reps. Don\'t let form get sloppy — chest to floor, full jump at the top.',
        },
        {
          name: 'Battle Rope Alternating Waves',
          sets: 5,
          reps: '30 sec',
          rest: '0:30',
          cues: 'Extra round, shorter rest. Keep the wave amplitude consistent — don\'t let them die.',
        },
        {
          name: 'Box Step-Up',
          sets: 4,
          reps: '12 each',
          rest: '1:00',
          cues: 'Added a set. Drive through the heel of the top foot. Stand all the way up.',
        },
      ],
      cooldown: '5 min: full body stretch',
    },
    {
      day: 'Day 10',
      title: 'W2 · Upper Pull + Power',
      warmup: '5 min: band pull-aparts, cat-cow, scapular push-ups, face pulls',
      duration: '60 min',
      exercises: [
        {
          name: 'Weighted Pull-Ups',
          sets: 5,
          reps: '6',
          rest: '2:30',
          cues: 'Extra set. Same weight. Full dead hang at the bottom, chest to bar at the top.',
        },
        {
          name: 'Barbell Bent-Over Row',
          sets: 4,
          reps: '10',
          rest: '2:00',
          cues: 'Two more reps. Keep the torso at 45 degrees — don\'t cheat with momentum.',
        },
        {
          name: '1a. Dumbbell Hammer Curl',
          sets: 3,
          reps: '14',
          rest: '1:00',
          cues: 'Two extra reps. Elbows don\'t move. Make the bicep do all the work.',
        },
        {
          name: '1b. Face Pull',
          sets: 4,
          reps: '15',
          rest: '1:00',
          cues: 'Added a set. External rotate at the end — show the ceiling your palms.',
        },
        {
          name: 'Power Clean',
          sets: 5,
          reps: '4',
          rest: '2:30',
          cues: 'Extra set. Focus on the catch — elbows whip through fast. Absorb in the quarter squat.',
        },
        {
          name: 'Med Ball Rotational Throw',
          sets: 3,
          reps: '10 each side',
          rest: '1:00',
          cues: 'Two more reps each side. Hip rotation powers the throw. Reset fully between reps.',
        },
      ],
      cooldown: '5 min: lat stretch, bicep stretch, thoracic extension over foam roller',
    },
    {
      day: 'Day 11',
      title: 'W2 · Lower Body Hypertrophy',
      warmup: '5 min: foam roll quads/glutes, hip circles, walking lunges, leg swings',
      duration: '55 min',
      exercises: [
        {
          name: 'Front Squat',
          sets: 4,
          reps: '10',
          rest: '2:00',
          cues: 'Two more reps — same weight. Elbows stay high the entire set. Don\'t let them drop.',
        },
        {
          name: 'Bulgarian Split Squat',
          sets: 4,
          reps: '10 each',
          rest: '1:30',
          cues: 'Extra set this week. The back leg is just for balance — the front leg does the work.',
        },
        {
          name: 'Hip Thrust',
          sets: 4,
          reps: '14',
          rest: '1:30',
          cues: 'Two extra reps. Full hip extension every rep — squeeze the glutes like you\'re cracking a walnut.',
        },
        {
          name: '1a. Leg Extension',
          sets: 3,
          reps: '15',
          rest: '1:00',
          cues: 'Same reps, add 5 lbs. Full lockout, 2-second hold. Make the quads burn.',
        },
        {
          name: '1b. Goblet Squat — 1.5 Reps',
          sets: 3,
          reps: '10',
          rest: '1:30',
          cues: 'Two more reps of the 1.5 pattern. Stay in the hole — the half rep is where the growth is.',
        },
        {
          name: 'Suitcase Carry',
          sets: 4,
          reps: '30 yards each hand',
          rest: '1:00',
          cues: 'Extra set. Use a heavier dumbbell if last week felt easy. No leaning.',
        },
      ],
      cooldown: '5 min: pigeon stretch, quad stretch, hamstring stretch',
    },
    {
      day: 'Day 12',
      title: 'W2 · Full Body Blast',
      warmup: '5 min: jump rope, inchworms, mountain climbers, high knees',
      duration: '48 min',
      exercises: [
        {
          name: 'Dumbbell Complex',
          sets: 5,
          reps: '6 each move',
          rest: '1:45',
          cues: 'Extra set, less rest. Deadlift → Row → Clean → Press → Squat. Don\'t put the dumbbells down.',
        },
        {
          name: 'Assault Bike Sprint',
          sets: 6,
          reps: '20 sec max / 40 sec easy',
          rest: '-',
          cues: 'One more round than Week 1. Keep the RPM the same across all sets.',
        },
        {
          name: 'Wall Ball',
          sets: 4,
          reps: '18',
          rest: '1:00',
          cues: 'Three extra reps. Deeper squat, harder throw. Catch the ball and go — no pause.',
        },
        {
          name: 'Sled Push',
          sets: 4,
          reps: '40 yards',
          rest: '1:15',
          cues: 'Added a set. Low body angle. Attack the ground with your feet.',
        },
        {
          name: 'Plank to Push-Up',
          sets: 4,
          reps: '8 each arm lead',
          rest: '1:00',
          cues: 'Extra set. Hips stay level — if they twist, slow down. Alternate which arm leads.',
        },
      ],
      cooldown: '10 min: full body stretch and foam roll',
    },

    // =============================================
    // WEEK 3 — BUILD (heavier loads, variations)
    // =============================================
    {
      day: 'Day 13',
      title: 'W3 · Upper Push + Conditioning',
      warmup: '5 min: band pull-aparts, arm circles, push-up walkouts, light dumbbell press x10',
      duration: '60 min',
      exercises: [
        {
          name: 'Bench Press',
          sets: 5,
          reps: '5',
          tempo: '2-1-1-0',
          rest: '2:30',
          cues: 'Heavier than Weeks 1-2. One less rep — add weight. Every rep is a max effort press.',
        },
        {
          name: '1a. Dumbbell Incline Press',
          sets: 4,
          reps: '8',
          rest: '1:30',
          cues: 'Heavier dumbbells, fewer reps. Feel the stretch at the bottom, explode up.',
        },
        {
          name: '1b. Cable Lateral Raise',
          sets: 4,
          reps: '12',
          rest: '1:00',
          cues: 'Cable gives constant tension. Raise to shoulder height, 1-second hold at the top.',
        },
        {
          name: '1c. Overhead Tricep Extension',
          sets: 4,
          reps: '12',
          rest: '1:00',
          cues: 'Tri-set this week. Rope or dumbbell overhead. Full stretch, full squeeze. Elbows stay tight.',
        },
        {
          name: 'Assault Bike — Ladder',
          sets: 1,
          reps: '10-20-30-40-30-20-10 cal',
          rest: '1:00 between rounds',
          cues: 'New format — work up then work down. Rest 1 minute between each round. Don\'t pace — attack.',
        },
        {
          name: 'Weighted Push-Up — Burnout',
          sets: 2,
          reps: 'Max reps',
          rest: '1:00',
          cues: 'Plate on your back. When you fail, ditch the plate and keep going bodyweight.',
        },
      ],
      cooldown: '5 min: chest doorway stretch, tricep stretch, shoulder stretch',
    },
    {
      day: 'Day 14',
      title: 'W3 · Lower Body Strength',
      warmup: '5 min: hip circles, leg swings, bodyweight squats, banded glute walks',
      duration: '60 min',
      exercises: [
        {
          name: 'Barbell Back Squat',
          sets: 5,
          reps: '4',
          rest: '3:00',
          cues: 'Heavier weight, fewer reps. Add 10-15 lbs over Week 2. Brace like you mean it.',
        },
        {
          name: 'Pause Deadlift',
          sets: 4,
          reps: '5',
          rest: '2:30',
          cues: 'New variation — 2-second pause at the knee. No bounce. Build strength off the floor.',
        },
        {
          name: '1a. Reverse Lunge',
          sets: 4,
          reps: '10 each',
          rest: '1:30',
          cues: 'Step back, not forward. Decelerate with the front leg. Keep the torso vertical.',
        },
        {
          name: '1b. Nordic Hamstring Curl',
          sets: 3,
          reps: '5-6',
          rest: '1:30',
          cues: 'Anchor your feet. Lower as slowly as possible. Use hands to catch yourself at the bottom.',
        },
        {
          name: '2a. Single-Leg Calf Raise',
          sets: 3,
          reps: '12 each',
          rest: '1:00',
          cues: 'One leg at a time. Full range. The balance challenge is part of the exercise.',
        },
        {
          name: '2b. Ab Wheel Rollout',
          sets: 3,
          reps: '10',
          rest: '1:00',
          cues: 'Squeeze the glutes, tuck the ribs. Extend as far as you can control. No back sag.',
        },
      ],
      cooldown: '5 min: quad stretch, hamstring stretch, hip flexor stretch',
    },
    {
      day: 'Day 15',
      title: 'W3 · Engine Builder',
      warmup: '5 min: light jog, arm swings, high knees, butt kicks',
      duration: '42 min',
      exercises: [
        {
          name: 'Rowing Machine — Intervals',
          sets: 6,
          reps: '350m',
          rest: '1:00',
          cues: 'Shorter distance, faster pace, less rest. Push the damper up one setting from Week 2.',
        },
        {
          name: 'Kettlebell Clean & Press',
          sets: 4,
          reps: '8 each arm',
          rest: '1:00',
          cues: 'New movement. Clean to rack, press overhead, control back down. Alternate arms each set.',
        },
        {
          name: 'Burpee Box Jump',
          sets: 4,
          reps: '8',
          rest: '1:00',
          cues: 'Burpee into a box jump — don\'t step up. Land soft on the box, step down.',
        },
        {
          name: 'Battle Rope Slam',
          sets: 5,
          reps: '20',
          rest: '0:30',
          cues: 'Both arms together — slam the ropes to the ground. Full hip hinge on every slam.',
        },
        {
          name: '1a. Box Jump',
          sets: 3,
          reps: '8',
          rest: '0:45',
          cues: 'Explode up, land soft. Step down — don\'t jump down. Reset between each rep.',
        },
        {
          name: '1b. Broad Jump',
          sets: 3,
          reps: '6',
          rest: '1:00',
          cues: 'Swing your arms and launch forward. Stick the landing. Measure against yourself each set.',
        },
      ],
      cooldown: '5 min: full body stretch, hamstring focus',
    },
    {
      day: 'Day 16',
      title: 'W3 · Upper Pull + Power',
      warmup: '5 min: band pull-aparts, cat-cow, scapular push-ups, light dumbbell rows x10',
      duration: '60 min',
      exercises: [
        {
          name: 'Weighted Pull-Ups',
          sets: 5,
          reps: '5',
          rest: '2:30',
          cues: 'Add weight. One fewer rep but heavier. Full range — dead hang to chest to bar.',
        },
        {
          name: 'Pendlay Row',
          sets: 4,
          reps: '6',
          rest: '2:00',
          cues: 'Bar starts on the floor each rep. Explosive pull to the chest. No body English.',
        },
        {
          name: '1a. Barbell Curl',
          sets: 3,
          reps: '10',
          rest: '1:00',
          cues: 'Straight bar, shoulder-width grip. Strict form — no swinging. Squeeze at the top.',
        },
        {
          name: '1b. Face Pull',
          sets: 4,
          reps: '15',
          rest: '1:00',
          cues: 'High pull to forehead. External rotate hard. Hold the squeeze for a full second.',
        },
        {
          name: '1c. Band Pull-Apart',
          sets: 4,
          reps: '20',
          rest: '0:45',
          cues: 'Tri-set finisher. Squeeze the shoulder blades. Constant tension — don\'t let the band go slack.',
        },
        {
          name: 'Hang Power Clean',
          sets: 5,
          reps: '3',
          rest: '2:30',
          cues: 'Start from the hang position at mid-thigh. Violent hip extension. Fast elbows in the catch.',
        },
      ],
      cooldown: '5 min: lat stretch, bicep stretch, thoracic extension over foam roller',
    },
    {
      day: 'Day 17',
      title: 'W3 · Lower Body Hypertrophy',
      warmup: '5 min: foam roll quads/glutes, hip circles, bodyweight lunges, banded squats',
      duration: '55 min',
      exercises: [
        {
          name: 'Front Squat',
          sets: 5,
          reps: '6',
          rest: '2:00',
          cues: 'Heavier this week. Fewer reps, more weight. Elbows high, chest up, sit deep.',
        },
        {
          name: 'Bulgarian Split Squat',
          sets: 4,
          reps: '8 each',
          rest: '1:30',
          cues: 'Hold dumbbells this week. Controlled descent — 2 seconds down, explode up.',
        },
        {
          name: 'Barbell Hip Thrust',
          sets: 4,
          reps: '10',
          rest: '1:30',
          cues: 'Barbell now, not dumbbells. Pad the bar. Full extension, hard glute squeeze.',
        },
        {
          name: '1a. Leg Press',
          sets: 3,
          reps: '12',
          rest: '1:00',
          cues: 'Feet high on the platform. Deep range of motion. Don\'t lock the knees at the top.',
        },
        {
          name: '1b. Dumbbell Stiff-Leg Deadlift',
          sets: 3,
          reps: '12',
          rest: '1:15',
          cues: 'Dumbbells track down the shins. Deep hamstring stretch. Squeeze the glutes to stand.',
        },
        {
          name: 'Farmer Carry',
          sets: 3,
          reps: '40 yards',
          rest: '1:00',
          cues: 'Heavy dumbbells, both hands. Tall posture. Grip hard, walk with purpose.',
        },
      ],
      cooldown: '5 min: pigeon stretch, quad stretch, hamstring stretch',
    },
    {
      day: 'Day 18',
      title: 'W3 · Full Body Blast',
      warmup: '5 min: jump rope, inchworms, mountain climbers, broad jumps x5',
      duration: '48 min',
      exercises: [
        {
          name: 'Barbell Complex',
          sets: 4,
          reps: '5 each move',
          rest: '2:00',
          cues: 'Deadlift → Hang Clean → Front Squat → Push Press → Back Squat. Barbell never leaves your hands.',
        },
        {
          name: 'Assault Bike Sprint',
          sets: 8,
          reps: '15 sec max / 45 sec easy',
          rest: '-',
          cues: 'Shorter sprints, more rounds. Absolute max effort every 15 seconds.',
        },
        {
          name: 'Wall Ball',
          sets: 5,
          reps: '15',
          rest: '0:45',
          cues: 'Extra set, less rest. Deeper squat, higher throw. No pausing between reps.',
        },
        {
          name: 'Sled Push + Pull',
          sets: 4,
          reps: '40 yards each',
          rest: '1:30',
          cues: 'Push down, rope-pull it back. No walking rest between the push and the pull.',
        },
        {
          name: 'Renegade Row',
          sets: 3,
          reps: '8 each arm',
          rest: '1:00',
          cues: 'Push-up position, row one dumbbell at a time. Hips stay square. Core is on fire — good.',
        },
      ],
      cooldown: '10 min: full body stretch and foam roll',
    },

    // =============================================
    // WEEK 4 — BUILD+ (advanced variations, tri-sets)
    // =============================================
    {
      day: 'Day 19',
      title: 'W4 · Upper Push + Conditioning',
      warmup: '5 min: band pull-aparts, arm circles, light dumbbell press x10, push-up walkouts',
      duration: '60 min',
      exercises: [
        {
          name: 'Close-Grip Bench Press',
          sets: 5,
          reps: '5',
          rest: '2:30',
          cues: 'New grip — hands inside shoulder width. This builds lockout power and tricep mass.',
        },
        {
          name: '1a. Dumbbell Floor Press',
          sets: 4,
          reps: '10',
          rest: '1:30',
          cues: 'Lie on the floor. Triceps touch the ground, then press. This eliminates bounce and builds raw strength.',
        },
        {
          name: '1b. Arnold Press',
          sets: 4,
          reps: '10',
          rest: '1:00',
          cues: 'Start palms facing you, rotate as you press overhead. Full rotation, full press.',
        },
        {
          name: '1c. Tricep Rope Pushdown',
          sets: 4,
          reps: '15',
          rest: '1:00',
          cues: 'Tri-set finisher. Spread the rope at the bottom. Lock out every rep. Elbows stay pinned.',
        },
        {
          name: 'Assault Bike — EMOM',
          sets: 10,
          reps: '15 cal every minute on the minute',
          rest: '-',
          cues: 'Set a timer for 10 minutes. Hit 15 calories at the top of each minute. Rest is whatever\'s left.',
        },
        {
          name: 'Deficit Push-Up — Burnout',
          sets: 2,
          reps: 'Max reps',
          rest: '1:00',
          cues: 'Hands on dumbbells or plates for extra range. Chest below hand level. Deeper equals harder.',
        },
      ],
      cooldown: '5 min: chest doorway stretch, tricep stretch, lat stretch',
    },
    {
      day: 'Day 20',
      title: 'W4 · Lower Body Strength',
      warmup: '5 min: hip circles, leg swings, banded walks, bodyweight pause squats',
      duration: '60 min',
      exercises: [
        {
          name: 'Barbell Back Squat — Pause',
          sets: 5,
          reps: '3',
          rest: '3:00',
          cues: '2-second pause in the hole. Heaviest squat week. Stay tight at the bottom — no relaxing.',
        },
        {
          name: 'Trap Bar Deadlift',
          sets: 4,
          reps: '6',
          rest: '2:30',
          cues: 'New variation. Neutral grip, drive through the floor. Chest up, hips and shoulders rise together.',
        },
        {
          name: '1a. Barbell Reverse Lunge',
          sets: 4,
          reps: '8 each',
          rest: '1:30',
          cues: 'Bar on your back. Step back with control. Front knee stays stacked over the ankle.',
        },
        {
          name: '1b. Glute-Ham Raise',
          sets: 3,
          reps: '8',
          rest: '1:30',
          cues: 'Control the descent. Use a slight push off the pad if needed. Build to bodyweight only.',
        },
        {
          name: '2a. Seated Calf Raise',
          sets: 4,
          reps: '15',
          rest: '1:00',
          cues: 'Seated targets the soleus. Full stretch at bottom, 3-second hold at top.',
        },
        {
          name: '2b. Pallof Press',
          sets: 3,
          reps: '10 each side',
          rest: '1:00',
          cues: 'Cable at chest height. Press out and resist the rotation. Core stays locked.',
        },
      ],
      cooldown: '5 min: quad stretch, hamstring stretch, hip flexor stretch',
    },
    {
      day: 'Day 21',
      title: 'W4 · Engine Builder',
      warmup: '5 min: light jog, arm swings, high knees, broad jumps x5',
      duration: '45 min',
      exercises: [
        {
          name: 'Rowing Machine — Sprint',
          sets: 8,
          reps: '250m',
          rest: '0:45',
          cues: 'Shorter distance, faster pace, less rest. Your stroke rate should be 28+ on every set.',
        },
        {
          name: 'Kettlebell Snatch',
          sets: 4,
          reps: '8 each arm',
          rest: '1:00',
          cues: 'New movement. Swing to overhead in one motion. Lock out at the top, punch through the bell.',
        },
        {
          name: 'Burpee Pull-Up',
          sets: 4,
          reps: '8',
          rest: '1:15',
          cues: 'Burpee under the bar, jump into a pull-up. Two movements, one beast of an exercise.',
        },
        {
          name: 'Battle Rope — Alternating Waves + Slam Combo',
          sets: 5,
          reps: '20 sec waves / 10 sec slams',
          rest: '0:30',
          cues: 'Alternate waves for 20 seconds, then slam for 10. No rest between the switch.',
        },
        {
          name: 'Box Jump — Higher Box',
          sets: 4,
          reps: '6',
          rest: '1:00',
          cues: 'Raise the box height. Explode from a dead stop. Land soft, step down every time.',
        },
      ],
      cooldown: '5 min: full body stretch, hip flexor focus',
    },
    {
      day: 'Day 22',
      title: 'W4 · Upper Pull + Power',
      warmup: '5 min: band pull-aparts, cat-cow, scapular pull-ups, light dumbbell rows x10',
      duration: '60 min',
      exercises: [
        {
          name: 'Chest-to-Bar Pull-Ups',
          sets: 5,
          reps: '5',
          rest: '2:30',
          cues: 'Strict pull-ups — chest touches the bar every rep. Full dead hang between reps.',
        },
        {
          name: 'Meadows Row',
          sets: 4,
          reps: '8 each',
          rest: '1:30',
          cues: 'Barbell in landmine. Stagger your stance. Pull to the hip, squeeze the lat hard.',
        },
        {
          name: '1a. Incline Dumbbell Curl',
          sets: 3,
          reps: '10',
          rest: '1:00',
          cues: 'Incline bench, arms hang straight down. Big stretch at the bottom. Curl with control.',
        },
        {
          name: '1b. Rear Delt Fly',
          sets: 4,
          reps: '12',
          rest: '1:00',
          cues: 'Bent over or chest-supported. Squeeze the rear delts. Controlled negative.',
        },
        {
          name: '1c. Plate Pinch Hold',
          sets: 3,
          reps: '30 sec',
          rest: '0:45',
          cues: 'Tri-set finisher. Pinch two plates smooth-side-out. Grip hard — if you drop them, rest and go again.',
        },
        {
          name: 'Hang Power Clean + Push Press',
          sets: 5,
          reps: '3+3',
          rest: '2:30',
          cues: 'Clean from the hang, catch in front rack, then push press three times. Power combo.',
        },
      ],
      cooldown: '5 min: lat stretch, bicep stretch, thoracic spine foam roll',
    },
    {
      day: 'Day 23',
      title: 'W4 · Lower Body Hypertrophy',
      warmup: '5 min: foam roll quads/glutes, hip circles, banded squats, walking lunges',
      duration: '55 min',
      exercises: [
        {
          name: 'Front Squat — Tempo',
          sets: 4,
          reps: '6',
          tempo: '4-1-1-0',
          rest: '2:00',
          cues: '4-second descent. Control every inch. This is where real muscle gets built.',
        },
        {
          name: 'Rear Foot Elevated Split Squat — Barbell',
          sets: 4,
          reps: '8 each',
          rest: '1:30',
          cues: 'Bar on your back, rear foot on bench. Step out far enough that the front shin stays vertical.',
        },
        {
          name: 'Single-Leg Hip Thrust',
          sets: 3,
          reps: '10 each',
          rest: '1:30',
          cues: 'One leg at a time. Full extension, hard squeeze. Don\'t let the hips rotate.',
        },
        {
          name: '1a. Leg Press — Narrow Stance',
          sets: 4,
          reps: '12',
          rest: '1:00',
          cues: 'Feet close together, low on the platform. Targets the quads. Deep range of motion.',
        },
        {
          name: '1b. Seated Leg Curl',
          sets: 4,
          reps: '12',
          rest: '1:00',
          cues: 'Squeeze at the bottom. 2-second hold. Let the hamstrings do the work — no momentum.',
        },
        {
          name: 'Zercher Carry',
          sets: 3,
          reps: '40 yards',
          rest: '1:00',
          cues: 'Barbell in the crook of your elbows. Stay upright. This builds total body toughness.',
        },
      ],
      cooldown: '5 min: pigeon stretch, quad stretch, hamstring stretch',
    },
    {
      day: 'Day 24',
      title: 'W4 · Full Body Blast',
      warmup: '5 min: jump rope, inchworms, mountain climbers, med ball slams x10',
      duration: '50 min',
      exercises: [
        {
          name: 'Barbell Complex',
          sets: 5,
          reps: '4 each move',
          rest: '2:00',
          cues: 'Heavier bar. Deadlift → Hang Clean → Front Squat → Push Press → Back Squat. Don\'t let go.',
        },
        {
          name: 'Assault Bike — Tabata',
          sets: 8,
          reps: '20 sec max / 10 sec rest',
          rest: '-',
          cues: 'True Tabata — 20 on, 10 off, 8 rounds. This is 4 minutes of suffering. Earn it.',
        },
        {
          name: 'Thrusters',
          sets: 4,
          reps: '12',
          rest: '1:00',
          cues: 'Front squat into push press in one fluid motion. Use dumbbells or a barbell. No pausing at the top.',
        },
        {
          name: 'Sled Push — Heavy',
          sets: 4,
          reps: '30 yards',
          rest: '1:30',
          cues: 'More weight, shorter distance. Low and slow — grind it out. Every yard counts.',
        },
        {
          name: 'Turkish Get-Up',
          sets: 3,
          reps: '3 each side',
          rest: '1:00',
          cues: 'Kettlebell or dumbbell. Every step is deliberate. This is strength, stability, and focus in one move.',
        },
      ],
      cooldown: '10 min: full body stretch and foam roll',
    },

    // =============================================
    // WEEK 5 — PEAK (heavy, high intensity)
    // =============================================
    {
      day: 'Day 25',
      title: 'W5 · Upper Push + Conditioning',
      warmup: '5 min: band pull-aparts, arm circles, barbell warm-up — empty bar x10 press',
      duration: '60 min',
      exercises: [
        {
          name: 'Bench Press — Heavy Singles',
          sets: 6,
          reps: '2',
          rest: '3:00',
          cues: 'Work up to your heaviest double. Full setup every rep — retract, arch, feet planted. This is your peak.',
        },
        {
          name: '1a. Dumbbell Incline Press — Heavy',
          sets: 4,
          reps: '6',
          rest: '1:30',
          cues: 'Heaviest dumbbells you can control. Full stretch, controlled press. No bouncing.',
        },
        {
          name: '1b. Dumbbell Lateral Raise — Drop Set',
          sets: 3,
          reps: '8 heavy + 12 light',
          rest: '1:00',
          cues: 'Start heavy for 8, immediately drop weight and hit 12 more. Shoulders should be on fire.',
        },
        {
          name: 'Weighted Dips',
          sets: 4,
          reps: '6-8',
          rest: '2:00',
          cues: 'Belt with plates or dumbbell between feet. Full depth, explosive lockout.',
        },
        {
          name: 'Assault Bike — Death by Calories',
          sets: 1,
          reps: '1 cal min 1, 2 cal min 2, 3 cal min 3... until failure',
          rest: '-',
          cues: 'Add a calorie each minute until you can\'t finish within the minute. Record your score.',
        },
        {
          name: 'Plyometric Push-Up',
          sets: 3,
          reps: '8',
          rest: '1:00',
          cues: 'Explode off the floor. Hands leave the ground. Land soft, reset, repeat. Power output matters.',
        },
      ],
      cooldown: '5 min: chest doorway stretch, tricep stretch, shoulder stretch',
    },
    {
      day: 'Day 26',
      title: 'W5 · Lower Body Strength',
      warmup: '5 min: hip circles, leg swings, banded walks, empty bar squat x10',
      duration: '65 min',
      exercises: [
        {
          name: 'Barbell Back Squat — Heavy Triples',
          sets: 6,
          reps: '3',
          rest: '3:00',
          cues: 'Work up to your heaviest triple. Belt up. Brace like your spine depends on it — because it does.',
        },
        {
          name: 'Conventional Deadlift',
          sets: 5,
          reps: '3',
          rest: '3:00',
          cues: 'Heavy triples. Bar over mid-foot. Pull the slack out before you lift. Lockout hard.',
        },
        {
          name: '1a. Barbell Walking Lunge',
          sets: 3,
          reps: '8 each',
          rest: '1:30',
          cues: 'Bar on your back. Long strides, controlled tempo. This is strength, not cardio.',
        },
        {
          name: '1b. GHD Raise',
          sets: 3,
          reps: '8',
          rest: '1:30',
          cues: 'Controlled descent, hamstrings fire to pull you back up. Hug a plate if bodyweight is easy.',
        },
        {
          name: 'Heavy Farmer Carry',
          sets: 3,
          reps: '50 yards',
          rest: '1:30',
          cues: 'Heaviest dumbbells you can hold. Walk with purpose. Grip gives out first — fight it.',
        },
        {
          name: 'Hanging Knee Raise — Weighted',
          sets: 3,
          reps: '12',
          rest: '1:00',
          cues: 'Dumbbell between feet. Curl the hips under. No kipping — pure core strength.',
        },
      ],
      cooldown: '5 min: quad stretch, hamstring stretch, hip flexor stretch',
    },
    {
      day: 'Day 27',
      title: 'W5 · Engine Builder',
      warmup: '5 min: light jog, dynamic stretches, high knees, butt kicks',
      duration: '45 min',
      exercises: [
        {
          name: 'Rowing Machine — 2K Test',
          sets: 1,
          reps: '2000m for time',
          rest: '3:00',
          cues: 'All-out effort. Start strong but don\'t blow up in the first 500m. Negative split if you can.',
        },
        {
          name: 'Kettlebell Swing — Heavy',
          sets: 5,
          reps: '15',
          rest: '0:45',
          cues: 'Heaviest bell you can swing with good form. Hips snap, bell floats. Grip hard.',
        },
        {
          name: 'Man Maker',
          sets: 4,
          reps: '6',
          rest: '1:30',
          cues: 'Push-up → Row left → Row right → Clean → Thruster. One rep. The ultimate hybrid movement.',
        },
        {
          name: 'Battle Rope — 3-Minute Round',
          sets: 3,
          reps: '3 min continuous',
          rest: '1:00',
          cues: 'Alternate between waves, slams, and circles. Don\'t stop for 3 minutes. Switch styles when you fatigue.',
        },
        {
          name: 'Assault Bike — Recovery Pace',
          sets: 1,
          reps: '5 min easy',
          rest: '-',
          cues: 'Easy spin to cool the heart rate. This is earned rest — but keep the legs moving.',
        },
      ],
      cooldown: '5 min: full body stretch, extra time on whatever\'s tight',
    },
    {
      day: 'Day 28',
      title: 'W5 · Upper Pull + Power',
      warmup: '5 min: band pull-aparts, thoracic rotations, scapular pull-ups, light rows x10',
      duration: '60 min',
      exercises: [
        {
          name: 'Weighted Pull-Ups — Heavy',
          sets: 5,
          reps: '3',
          rest: '2:30',
          cues: 'Add serious weight. Three perfect reps. Dead hang, chest to bar, controlled negative.',
        },
        {
          name: 'T-Bar Row',
          sets: 4,
          reps: '6',
          rest: '2:00',
          cues: 'New rowing variation. Chest supported or bent over. Squeeze the back hard at the top.',
        },
        {
          name: '1a. Barbell Curl — Heavy',
          sets: 4,
          reps: '6',
          rest: '1:00',
          cues: 'Heavy barbell curl. Strict form — no lean-back. If you can\'t stay upright, it\'s too heavy.',
        },
        {
          name: '1b. Cable Face Pull — Pause',
          sets: 4,
          reps: '12',
          rest: '1:00',
          cues: '2-second hold at peak contraction. External rotate fully. Rear delts and rotator cuff on fire.',
        },
        {
          name: 'Power Clean — Heavy',
          sets: 5,
          reps: '2',
          rest: '3:00',
          cues: 'Heaviest doubles you can catch clean. Triple extension, fast elbows. This is peak power.',
        },
        {
          name: 'Med Ball Slam',
          sets: 4,
          reps: '10',
          rest: '0:45',
          cues: 'Overhead to the floor with everything you\'ve got. Use the whole body. Pick it up and repeat.',
        },
      ],
      cooldown: '5 min: lat stretch, bicep stretch, thoracic extension over foam roller',
    },
    {
      day: 'Day 29',
      title: 'W5 · Lower Body Hypertrophy',
      warmup: '5 min: foam roll quads/glutes, hip circles, banded squats, walking lunges',
      duration: '55 min',
      exercises: [
        {
          name: 'Front Squat — Heavy',
          sets: 5,
          reps: '4',
          rest: '2:30',
          cues: 'Heaviest front squat week. Elbows high, brace hard. Four clean reps — no grinding.',
        },
        {
          name: 'Walking Lunge — Heavy',
          sets: 4,
          reps: '8 each',
          rest: '1:30',
          cues: 'Heavy dumbbells. Long stride, controlled descent. Each step is a single-leg squat.',
        },
        {
          name: 'Barbell Hip Thrust — Heavy',
          sets: 5,
          reps: '6',
          rest: '1:30',
          cues: 'Heaviest hip thrust week. Full lockout, hard squeeze. The glutes drive everything.',
        },
        {
          name: '1a. Leg Extension — Pause',
          sets: 3,
          reps: '10',
          rest: '1:00',
          cues: '3-second hold at the top of each rep. Quads should be screaming. That\'s the point.',
        },
        {
          name: '1b. Leg Curl — Pause',
          sets: 3,
          reps: '10',
          rest: '1:00',
          cues: '3-second hold at peak contraction. Slow negative. Make every rep count.',
        },
        {
          name: 'Sled Drag — Backward',
          sets: 3,
          reps: '40 yards',
          rest: '1:00',
          cues: 'Walk backward dragging the sled. Quads and calves do the work. Stay low.',
        },
      ],
      cooldown: '5 min: pigeon stretch, quad stretch, hamstring stretch',
    },
    {
      day: 'Day 30',
      title: 'W5 · Full Body Blast',
      warmup: '5 min: jump rope, inchworms, med ball slams x10, mountain climbers',
      duration: '50 min',
      exercises: [
        {
          name: 'Barbell Complex — Heavy',
          sets: 5,
          reps: '3 each move',
          rest: '2:30',
          cues: 'Deadlift → Hang Clean → Front Squat → Push Press → Back Squat. Heaviest bar yet. 3 reps each — make them perfect.',
        },
        {
          name: 'Assault Bike — 3 Min Max Calories',
          sets: 3,
          reps: '3 min max effort',
          rest: '2:00',
          cues: 'Three rounds of 3-minute all-out efforts. Record your calories each round. Don\'t let them drop.',
        },
        {
          name: 'Thrusters — Heavy',
          sets: 4,
          reps: '8',
          rest: '1:15',
          cues: 'Heavy dumbbells or barbell. Deep squat, explosive press. This is the ultimate hybrid move.',
        },
        {
          name: 'Sled Push — Sprint',
          sets: 5,
          reps: '30 yards',
          rest: '1:00',
          cues: 'Moderate weight, max speed. Sprint the sled. Walk back as your rest.',
        },
        {
          name: 'Plank Hold — Weighted',
          sets: 3,
          reps: '45 sec',
          rest: '1:00',
          cues: 'Plate on your back. Glutes tight, ribs tucked. If your hips sag, the set is over.',
        },
      ],
      cooldown: '10 min: full body stretch and foam roll. Take your time — big week.',
    },

    // =============================================
    // WEEK 6 — PEAK (max intensity, reduced volume)
    // =============================================
    {
      day: 'Day 31',
      title: 'W6 · Upper Push + Conditioning',
      warmup: '5 min: band pull-aparts, arm circles, barbell warm-up — work up in triples',
      duration: '55 min',
      exercises: [
        {
          name: 'Bench Press — Heavy Doubles',
          sets: 5,
          reps: '2',
          rest: '3:00',
          cues: 'Peak week. Work up to your heaviest double. One less set than last week — quality over quantity.',
        },
        {
          name: '1a. Dumbbell Incline Press',
          sets: 3,
          reps: '8',
          rest: '1:30',
          cues: 'Heavy but fewer sets. Every rep is perfect. Full stretch, controlled press.',
        },
        {
          name: '1b. Lateral Raise — 21s',
          sets: 3,
          reps: '7 bottom half + 7 top half + 7 full',
          rest: '1:00',
          cues: 'Three ranges in one set. Bottom half first, top half next, full range to finish. No rest between.',
        },
        {
          name: 'Weighted Dips — Heavy',
          sets: 3,
          reps: '5',
          rest: '2:00',
          cues: 'Heavy doubles from last week, now triples. Full depth, powerful lockout.',
        },
        {
          name: 'Assault Bike — 1 Min On / 1 Min Off',
          sets: 6,
          reps: '1 min max calories',
          rest: '1:00',
          cues: 'Longer intervals, equal rest. Push harder than any other week. Record your calorie total.',
        },
        {
          name: 'Diamond Push-Up — Burnout',
          sets: 2,
          reps: 'Max reps',
          rest: '1:00',
          cues: 'Hands together under the chest. When you fail, switch to regular push-ups and keep going.',
        },
      ],
      cooldown: '5 min: chest doorway stretch, tricep stretch, shoulder stretch',
    },
    {
      day: 'Day 32',
      title: 'W6 · Lower Body Strength',
      warmup: '5 min: hip circles, leg swings, banded walks, empty bar squat x10',
      duration: '60 min',
      exercises: [
        {
          name: 'Barbell Back Squat — Heavy Doubles',
          sets: 5,
          reps: '2',
          rest: '3:00',
          cues: 'Peak squat week. Work up to your absolute heaviest double. Belt, bracing, full focus.',
        },
        {
          name: 'Conventional Deadlift — Heavy',
          sets: 4,
          reps: '2',
          rest: '3:00',
          cues: 'Heavy doubles. Pull the slack out. Brace, wedge, pull. Lockout with authority.',
        },
        {
          name: '1a. Step-Up — Heavy',
          sets: 3,
          reps: '6 each',
          rest: '1:30',
          cues: 'High box, heavy dumbbells. Drive through the lead foot. Full extension at the top.',
        },
        {
          name: '1b. Nordic Hamstring Curl',
          sets: 3,
          reps: '6',
          rest: '1:30',
          cues: 'Slowest negative you can manage. You should be stronger here than Week 3.',
        },
        {
          name: 'Heavy Suitcase Carry',
          sets: 3,
          reps: '40 yards each hand',
          rest: '1:00',
          cues: 'Heaviest dumbbell you can carry without leaning. Tall posture. Crush the grip.',
        },
        {
          name: 'Hanging Leg Raise — Toes to Bar',
          sets: 3,
          reps: '8',
          rest: '1:00',
          cues: 'Full range — toes touch the bar. If you can\'t reach, go as high as possible. Control the descent.',
        },
      ],
      cooldown: '5 min: quad stretch, hamstring stretch, hip flexor stretch',
    },
    {
      day: 'Day 33',
      title: 'W6 · Engine Builder',
      warmup: '5 min: light jog, dynamic stretches, high knees, butt kicks',
      duration: '45 min',
      exercises: [
        {
          name: 'Rowing Machine — 500m Test',
          sets: 3,
          reps: '500m for time',
          rest: '2:00',
          cues: 'Three all-out 500m sprints. Record each time. Your first should be your fastest — don\'t hold back.',
        },
        {
          name: 'Kettlebell Swing — EMOM',
          sets: 10,
          reps: '15 swings every minute on the minute',
          rest: '-',
          cues: '10 minutes. 15 heavy swings at the top of each minute. Rest is whatever remains. Hips snap every rep.',
        },
        {
          name: 'Man Maker',
          sets: 3,
          reps: '8',
          rest: '1:30',
          cues: 'More reps than Week 5. Push-up, row, row, clean, thruster. No shortcuts — full range on everything.',
        },
        {
          name: 'Battle Rope — Finisher',
          sets: 1,
          reps: '5 min continuous',
          rest: '-',
          cues: 'One set, five minutes, don\'t stop. Alternate waves, slams, circles, whatever keeps you moving. Mental toughness round.',
        },
        {
          name: 'Assault Bike — Cool Down',
          sets: 1,
          reps: '5 min easy',
          rest: '-',
          cues: 'Easy spin. Bring the heart rate down. You just finished the hardest conditioning week of the program.',
        },
      ],
      cooldown: '5 min: full body stretch',
    },
    {
      day: 'Day 34',
      title: 'W6 · Upper Pull + Power',
      warmup: '5 min: band pull-aparts, thoracic rotations, scapular pull-ups, face pulls',
      duration: '55 min',
      exercises: [
        {
          name: 'Weighted Pull-Ups — Max Effort',
          sets: 5,
          reps: '2',
          rest: '3:00',
          cues: 'Heaviest pull-ups of the program. Two perfect reps. Dead hang, chest to bar, slow negative.',
        },
        {
          name: 'Barbell Bent-Over Row — Heavy',
          sets: 4,
          reps: '5',
          rest: '2:00',
          cues: 'Heavy weight, strict form. No heaving. 45-degree torso, pull to lower chest, squeeze.',
        },
        {
          name: '1a. Dumbbell Curl — Heavy',
          sets: 3,
          reps: '6',
          rest: '1:00',
          cues: 'Heaviest curls of the program. Strict form only — one ugly rep undoes the set.',
        },
        {
          name: '1b. Face Pull — Heavy',
          sets: 3,
          reps: '12',
          rest: '1:00',
          cues: 'Heavier cable. External rotate fully. Hold for 2 seconds at peak.',
        },
        {
          name: 'Power Clean — Max Effort Doubles',
          sets: 5,
          reps: '2',
          rest: '3:00',
          cues: 'Peak power clean week. Work up to your absolute heaviest double. Explosive extension, fast catch.',
        },
        {
          name: 'Med Ball Overhead Slam',
          sets: 3,
          reps: '10',
          rest: '0:45',
          cues: 'Full extension overhead, slam with everything. Leave nothing in the tank.',
        },
      ],
      cooldown: '5 min: lat stretch, bicep stretch, thoracic extension over foam roller',
    },
    {
      day: 'Day 35',
      title: 'W6 · Lower Body Hypertrophy',
      warmup: '5 min: foam roll quads/glutes, hip circles, banded squats, bodyweight lunges',
      duration: '50 min',
      exercises: [
        {
          name: 'Front Squat — Heavy Triples',
          sets: 4,
          reps: '3',
          rest: '2:30',
          cues: 'Heaviest front squat of the program. Fewer reps, fewer sets, max weight. Elbows up, chest proud.',
        },
        {
          name: 'Bulgarian Split Squat — Heavy',
          sets: 3,
          reps: '6 each',
          rest: '1:30',
          cues: 'Heavy dumbbells. Six controlled reps per leg. This is your peak single-leg strength.',
        },
        {
          name: 'Barbell Hip Thrust — Heavy',
          sets: 4,
          reps: '5',
          rest: '1:30',
          cues: 'Max weight. Full lockout, 2-second squeeze. Five perfect reps.',
        },
        {
          name: '1a. Leg Extension — Drop Set',
          sets: 2,
          reps: '8 heavy + 12 light',
          rest: '1:00',
          cues: 'Start heavy for 8, drop the pin and hit 12 more. Two sets total — make them brutal.',
        },
        {
          name: '1b. Leg Curl — Drop Set',
          sets: 2,
          reps: '8 heavy + 12 light',
          rest: '1:00',
          cues: 'Same idea. Heavy for 8, drop for 12. Hamstrings should be completely cooked.',
        },
        {
          name: 'Sled Push + Backward Drag',
          sets: 3,
          reps: '30 yards each direction',
          rest: '1:00',
          cues: 'Push it down, drag it back. No rest between directions. Legs are done when this is done.',
        },
      ],
      cooldown: '5 min: pigeon stretch, quad stretch, hamstring stretch',
    },
    {
      day: 'Day 36',
      title: 'W6 · Full Body Blast',
      warmup: '5 min: jump rope, inchworms, med ball slams x10, bodyweight squats',
      duration: '50 min',
      exercises: [
        {
          name: 'Barbell Complex — Final Test',
          sets: 4,
          reps: '3 each move',
          rest: '2:30',
          cues: 'Deadlift → Hang Clean → Front Squat → Push Press → Back Squat. Heaviest complex of the program. This is your final exam.',
        },
        {
          name: 'Assault Bike — Max Calorie Challenge',
          sets: 1,
          reps: '5 min max calories',
          rest: '-',
          cues: 'One set, five minutes, everything you have. Record your total. Beat everyone — including yourself.',
        },
        {
          name: 'Thruster — Heavy',
          sets: 3,
          reps: '8',
          rest: '1:15',
          cues: 'Heaviest thrusters yet. Deep squat, explosive press. Three sets — give each one everything.',
        },
        {
          name: 'Sled Push — All-Out Sprint',
          sets: 3,
          reps: '40 yards',
          rest: '1:30',
          cues: 'Moderate weight, maximum speed. Sprint like the program depends on it — because this is the last one.',
        },
        {
          name: 'Plank Hold — Max Time',
          sets: 1,
          reps: 'Max hold',
          rest: '-',
          cues: 'One set. Hold until failure. Glutes tight, ribs tucked, breathe steady. This is how we finish.',
        },
      ],
      cooldown: '10 min: full body stretch and foam roll. Six weeks complete. You\'re not the same athlete who started.',
    },
  ],
}
