export type Exercise = {
  name: string
  sets: number
  reps: string
  tempo?: string
  rest: string
  cues: string
  videoUrl?: string
}

export type TrainingDay = {
  day: string
  title: string
  warmup?: string
  exercises: Exercise[]
  cooldown?: string
  duration: string
}

export type Program = {
  id: string
  name: string
  weeks: number
  days: TrainingDay[]
  frequency: string
  description: string
  category: 'strength' | 'hybrid' | 'conditioning' | 'functional' | 'running'
  image?: string
}

import { athleticProgram } from './athlete-program'
export { athleticProgram }

export const executiveProgram: Program = {
  id: 'executive-performance',
  name: 'Executive Performance Protocol',
  weeks: 4,
  frequency: '4x / week',
  description: 'Efficient training for busy professionals who refuse to let the body slide.',
  category: 'functional',
  image: '/programs/executive.jpg',
  days: [
    {
      day: 'Day 1',
      title: 'Strength Foundations',
      warmup: '5 min: bodyweight squats, arm circles, cat-cow, hip hinges',
      duration: '45 min',
      exercises: [
        {
          name: 'Goblet Squat',
          sets: 3,
          reps: '10',
          tempo: '3-1-1-0',
          rest: '1:30',
          cues: 'Elbows inside knees at the bottom. Chest up, weight in heels.',
        },
        {
          name: '1a. Dumbbell Bench Press',
          sets: 3,
          reps: '10',
          tempo: '3-1-1-0',
          rest: '1:30',
          cues: 'Control the descent. Press to full lockout. Shoulder blades pinched.',
        },
        {
          name: '1b. Single-Arm Dumbbell Row',
          sets: 3,
          reps: '10 each',
          rest: '1:15',
          cues: 'Pull to hip. Squeeze the lat at the top. Don\'t rotate the torso.',
        },
        {
          name: 'Kettlebell Deadlift',
          sets: 3,
          reps: '12',
          rest: '1:30',
          cues: 'Push hips back, flat back. Drive through heels to stand.',
        },
        {
          name: 'Plank Hold',
          sets: 3,
          reps: '45 sec',
          rest: '1:00',
          cues: 'Straight line head to heels. Squeeze glutes, brace core. Breathe.',
        },
      ],
      cooldown: '5 min: chest stretch, hip flexor stretch, child\'s pose',
    },
    {
      day: 'Day 2',
      title: 'Conditioning + Breathwork',
      warmup: '5 min: light jog, arm swings, leg swings',
      duration: '40 min',
      exercises: [
        {
          name: 'Kettlebell Swing',
          sets: 4,
          reps: '15',
          rest: '1:00',
          cues: 'Hip hinge — not a squat. Snap hips forward, float the bell to chest height.',
        },
        {
          name: 'Rowing Machine Intervals',
          sets: 5,
          reps: '250m',
          rest: '1:00',
          cues: 'Legs-back-arms on the drive, arms-back-legs on recovery. Aim for consistent split.',
        },
        {
          name: 'Push-Up to Rotation',
          sets: 3,
          reps: '8 each side',
          rest: '1:00',
          cues: 'Full push-up, rotate to side plank at the top. Open the chest.',
        },
        {
          name: 'Med Ball Slam',
          sets: 3,
          reps: '12',
          rest: '1:00',
          cues: 'Reach overhead, slam with your whole body. Pick up and reset each rep.',
        },
        {
          name: 'Box Breathing',
          sets: 1,
          reps: '5 min',
          rest: '-',
          cues: '4 seconds inhale, 4 hold, 4 exhale, 4 hold. Focus on complete stillness.',
        },
        {
          name: 'Wim Hof Breathing',
          sets: 3,
          reps: '30 breaths + hold',
          rest: '1:00',
          cues: 'Deep belly breaths in, passive exhale out. After 30, exhale and hold as long as comfortable.',
        },
      ],
      cooldown: '5 min: standing forward fold, doorway chest stretch',
    },
    {
      day: 'Day 3',
      title: 'Focus & Power',
      warmup: '5 min: jump rope, mobility flow',
      duration: '50 min',
      exercises: [
        {
          name: 'Trap Bar Deadlift',
          sets: 4,
          reps: '6',
          rest: '2:30',
          cues: 'Neutral spine, grip hard. Drive the floor away from you.',
        },
        {
          name: '1a. Dumbbell Push Press',
          sets: 3,
          reps: '8',
          rest: '1:30',
          cues: 'Quarter dip, drive explosively. Lock out overhead.',
        },
        {
          name: '1b. TRX Row',
          sets: 3,
          reps: '12',
          rest: '1:15',
          cues: 'Body straight as a plank. Pull chest to handles, squeeze at the top.',
        },
        {
          name: '2a. Dumbbell Walking Lunge',
          sets: 3,
          reps: '10 each',
          rest: '1:30',
          cues: 'Long stride, back knee kisses the floor. Stay tall and controlled.',
        },
        {
          name: '2b. Pallof Press',
          sets: 3,
          reps: '10 each side',
          rest: '1:00',
          cues: 'Resist the rotation. Press out slowly, hold for a beat, bring it back.',
        },
      ],
      cooldown: '5 min: pigeon stretch, thoracic spine rotation, deep breathing',
    },
    {
      day: 'Day 4',
      title: 'Recovery & Mobility',
      warmup: '5 min easy walk',
      duration: '30 min',
      exercises: [
        {
          name: 'Foam Roll — Full Body',
          sets: 1,
          reps: '60 sec each area',
          rest: '-',
          cues: 'Upper back, lats, quads, hamstrings, calves. Slow and controlled.',
        },
        {
          name: 'Hip 90/90 Flow',
          sets: 2,
          reps: '8 transitions',
          rest: '-',
          cues: 'Smooth transitions between sides. Sit tall throughout.',
        },
        {
          name: 'Thoracic Spine Rotation',
          sets: 2,
          reps: '8 each side',
          rest: '-',
          cues: 'Side-lying position. Follow the hand with your eyes. Open up fully.',
        },
        {
          name: 'Banded Pull-Apart',
          sets: 2,
          reps: '15',
          rest: '-',
          cues: 'Light band, slow reps. Focus on squeezing the upper back.',
        },
        {
          name: 'Yoga Flow',
          sets: 1,
          reps: '5 min',
          rest: '-',
          cues: 'Sun salutation A. Breathe with each movement. Move with intention.',
        },
        {
          name: 'Guided Visualization',
          sets: 1,
          reps: '5 min',
          rest: '-',
          cues: 'Close your eyes. See your biggest goal. Walk through each step to get there.',
        },
        {
          name: 'Gratitude Journaling',
          sets: 1,
          reps: '5 min',
          rest: '-',
          cues: 'Write 3 things you\'re grateful for. Be specific — not just "family" but why, today.',
        },
      ],
      cooldown: 'Hydrate. Refuel with protein + carbs within 30 min. Prioritize 7-8 hours of sleep tonight.',
    },
  ],
}

export const functionalFitnessProgram: Program = {
  id: 'functional-fitness',
  name: 'Functional Fitness',
  weeks: 8,
  frequency: '3x / week',
  description: 'Adult Performance Class — 8-week periodized strength, volume, and power program.',
  category: 'functional',
  image: '/programs/functional.jpg',
  days: [
    {
      day: 'Day 1',
      title: 'Strength',
      warmup: '10 min: stationary bike 2 min, monster walks, single-arm dumbbell external rotations, banded hip hinges, bodyweight squats',
      duration: '60 min',
      exercises: [
        {
          name: 'Barbell Back Squat',
          sets: 4,
          reps: '8-6-4-4',
          rest: '2:30',
          cues: 'Progressive loading across 8 weeks — Coach Tyler will guide your weights each session. Chest up, drive through heels, full depth. Hip crease below the knee on every rep.',
        },
        {
          name: 'Barbell Deadlift',
          sets: 4,
          reps: '8-6-4-4',
          rest: '2:30',
          cues: 'Same loading progression as the squat. Flat back, bar tight against shins. Push the floor away. Lock hips and knees at the top.',
        },
        {
          name: 'Bench Press',
          sets: 4,
          reps: '8-6-4-4',
          rest: '2:30',
          cues: 'Same loading progression as the squat. Shoulder blades pinched, feet flat. Controlled descent, explosive press.',
        },
        {
          name: 'Barbell Bent-Over Row',
          sets: 3,
          reps: '10',
          rest: '1:30',
          cues: '45-degree torso angle. Pull to lower chest, squeeze the shoulder blades together. Lower with control.',
        },
        {
          name: 'Walking Lunge',
          sets: 3,
          reps: '12',
          rest: '1:30',
          cues: 'Long stride, back knee kisses the floor. Stay tall, chest up. Dumbbells at your sides.',
        },
        {
          name: 'Pull-Ups',
          sets: 3,
          reps: '8',
          rest: '1:30',
          cues: 'Full dead hang to chin over the bar. Control the negative on the way down. No kipping.',
        },
        {
          name: 'Plank',
          sets: 3,
          reps: '30 sec',
          rest: '0:45',
          cues: 'Straight line from head to heels. Squeeze glutes, brace core. Breathe — don\'t hold your breath.',
        },
        {
          name: 'Ab Rollouts',
          sets: 3,
          reps: '8',
          rest: '1:00',
          cues: 'Core tight, don\'t let the hips sag. Roll out as far as you can control, then pull back with your abs.',
        },
      ],
      cooldown: '5 min: foam roll quads, hamstrings, glutes',
    },
    {
      day: 'Day 2',
      title: 'Volume & Bodybuilding',
      warmup: '10 min: ski erg 2 min, banded pull-aparts, single-arm dumbbell overhead carry, lunge jumps',
      duration: '55 min',
      exercises: [
        {
          name: '1a. Incline Dumbbell Bench Press',
          sets: 4,
          reps: '15-12-10-8',
          rest: '1:30',
          cues: 'Increase weight each set. Full stretch at the bottom, squeeze the chest together at the top.',
        },
        {
          name: '1b. Seated Low Row',
          sets: 4,
          reps: '10',
          rest: '1:15',
          cues: 'Pull to belly button, squeeze shoulder blades together. Chest tall, no rounding forward.',
        },
        {
          name: '2a. Arnold Press',
          sets: 3,
          reps: '10',
          rest: '1:15',
          cues: 'Start palms facing you, rotate as you press overhead. Full lockout at the top.',
        },
        {
          name: '2b. Cable Tricep Extensions',
          sets: 3,
          reps: '12',
          rest: '1:00',
          cues: 'Elbows pinned to your sides, full extension at the bottom. Squeeze the triceps hard.',
        },
        {
          name: '3a. Reverse Cable Crossover',
          sets: 3,
          reps: '15',
          rest: '1:00',
          cues: 'Slight bend in elbows. Squeeze the rear delts at the end of every rep.',
        },
        {
          name: '3b. Farmer Carry + Shrugs',
          sets: 3,
          reps: '20 yd carry + 10 shrugs',
          rest: '1:30',
          cues: 'Heavy dumbbells, tall posture. Carry 20 yards then immediately hit 10 shrugs. Grip strength is earned here.',
        },
        {
          name: 'Dumbbell Split Squat',
          sets: 3,
          reps: '10 each',
          rest: '1:15',
          cues: 'Rear foot elevated on a bench. Front knee tracks over toes. Stay upright — don\'t lean forward.',
        },
        {
          name: 'Barbell Hip Thrust',
          sets: 2,
          reps: '10 + 10 sec hold + 10',
          rest: '1:30',
          cues: 'Upper back on bench. Drive through heels. Full hip extension — squeeze glutes at the top. Hold 10 seconds between rep blocks.',
        },
        {
          name: 'Cable Crunches',
          sets: 2,
          reps: '20',
          rest: '0:45',
          cues: 'Kneel at the cable, crunch down hard. Exhale on every rep. Feel the abs contract.',
        },
        {
          name: 'Dumbbell Oblique Crunch',
          sets: 2,
          reps: '15 each side',
          rest: '0:45',
          cues: 'Side crunch with a dumbbell for resistance. Controlled movement — don\'t rush.',
        },
      ],
      cooldown: '5 min: chest stretch, lat stretch, shoulder stretch',
    },
    {
      day: 'Day 3',
      title: 'Power & Speed',
      warmup: '10 min: line hops, lateral hops, high knees, A-skips, build-up sprints',
      duration: '55 min',
      exercises: [
        {
          name: 'Double Leg Line Hops',
          sets: 2,
          reps: '15 sec',
          rest: '0:30',
          cues: 'Warm up the nervous system — quick feet, soft landings. Stay light on your toes.',
        },
        {
          name: 'Double Leg Lateral Line Hops',
          sets: 2,
          reps: '15 sec',
          rest: '0:30',
          cues: 'Side to side over the line. Stay light, stay fast. Absorb each landing.',
        },
        {
          name: 'Single Leg Line Hops',
          sets: 2,
          reps: '10 sec each',
          rest: '0:30',
          cues: 'Balance and speed. Land soft on each hop. Control your body.',
        },
        {
          name: '1a. Power Clean',
          sets: 4,
          reps: '5-4-3-3',
          rest: '2:30',
          cues: 'Triple extension — hips, knees, ankles. Catch in front rack position. Weight builds across the 8-week cycle.',
        },
        {
          name: '1b. Box Jumps',
          sets: 4,
          reps: '2',
          rest: '1:30',
          cues: 'Explosive — max height you can land safely. Step down every rep. Full hip extension at the top.',
        },
        {
          name: '2a. Explosive Sled Rows',
          sets: 4,
          reps: '8',
          rest: '1:15',
          cues: 'Explosive pull, controlled return. Full body tension — brace your core, drive with your back.',
        },
        {
          name: '2b. Explosive Push-Ups',
          sets: 4,
          reps: '10',
          rest: '1:00',
          cues: 'Hands leave the ground on every rep. Land soft, absorb, then explode back up.',
        },
        {
          name: '3a. Heavy Sled Pushes',
          sets: 3,
          reps: '30 yards',
          rest: '2:00',
          cues: 'Low body angle, arms locked out. Short, powerful steps. Drive through the ground.',
        },
        {
          name: '3b. Kettlebell Swing',
          sets: 3,
          reps: '12',
          rest: '1:00',
          cues: 'Hip hinge, snap the hips forward. Bell floats to chest height. Power comes from the hips, not the arms.',
        },
        {
          name: 'Finisher',
          sets: 1,
          reps: 'Max rounds in 8-10 min',
          rest: '-',
          cues: '200m run + 10 dumbbell thrusters. Keep moving — rest only when you have to. Push the pace.',
        },
      ],
      cooldown: '5 min: full body foam roll and stretch',
    },
  ],
}

export const hybridProgram: Program = {
  id: 'hybrid-training',
  name: 'Hybrid Training',
  weeks: 4,
  frequency: '6x / week',
  description: 'The best of both worlds — build muscle, build engine. No weakness.',
  category: 'hybrid',
  image: '/programs/hybrid.jpg',
  days: [
    {
      day: 'Day 1',
      title: 'Upper Push + Conditioning',
      warmup: '5 min: band pull-aparts, arm circles, push-up walkouts, jumping jacks',
      duration: '55 min',
      exercises: [
        {
          name: 'Bench Press',
          sets: 4,
          reps: '6',
          tempo: '3-1-1-0',
          rest: '2:30',
          cues: 'Shoulder blades pinched, feet flat. Controlled descent, explosive press.',
        },
        {
          name: '1a. Dumbbell Incline Press',
          sets: 3,
          reps: '10',
          rest: '1:30',
          cues: '30-degree angle. Full stretch at the bottom, squeeze at the top.',
        },
        {
          name: '1b. Dumbbell Lateral Raise',
          sets: 3,
          reps: '12',
          rest: '1:00',
          cues: 'Slight bend in elbows. Raise to shoulder height. Control the negative — don\'t swing.',
        },
        {
          name: 'Tricep Dips',
          sets: 3,
          reps: '10-12',
          rest: '1:30',
          cues: 'Full depth — upper arm parallel. Drive up to full lockout. Lean forward slightly.',
        },
        {
          name: 'Assault Bike Intervals',
          sets: 6,
          reps: '30 sec on / 30 sec off',
          rest: '0:30',
          cues: 'Max effort on work intervals. Full body — push and pull with the arms.',
        },
        {
          name: 'Push-Up — Burnout',
          sets: 2,
          reps: 'Max reps',
          rest: '1:00',
          cues: 'Chest to floor every rep. When you can\'t do full, drop to knees. Empty the tank.',
        },
      ],
      cooldown: '5 min: chest doorway stretch, tricep stretch, shoulder stretch',
    },
    {
      day: 'Day 2',
      title: 'Lower Body Strength',
      warmup: '5 min: hip circles, leg swings, bodyweight squats, glute bridges',
      duration: '55 min',
      exercises: [
        {
          name: 'Barbell Back Squat',
          sets: 5,
          reps: '5',
          rest: '2:30',
          cues: 'Brace hard. Break at hips and knees together. Drive heels through the floor.',
        },
        {
          name: 'Romanian Deadlift',
          sets: 4,
          reps: '8',
          tempo: '3-1-1-0',
          rest: '2:00',
          cues: 'Hips back, bar tracks down the thighs. Hamstring stretch, then glute squeeze at top.',
        },
        {
          name: '1a. Walking Lunge',
          sets: 3,
          reps: '10 each',
          rest: '1:30',
          cues: 'Long stride, knee tracks over toes. Back knee kisses the floor. Stay upright.',
        },
        {
          name: '1b. Leg Curl',
          sets: 3,
          reps: '12',
          rest: '1:15',
          cues: 'Slow negative. Squeeze at the top. Full range of motion.',
        },
        {
          name: '2a. Calf Raise',
          sets: 3,
          reps: '15',
          rest: '1:00',
          cues: 'Full stretch at the bottom, pause at the top. Slow and controlled.',
        },
        {
          name: '2b. Hanging Leg Raise',
          sets: 3,
          reps: '10',
          rest: '1:00',
          cues: 'No swinging. Curl the hips under as you raise. Control the descent.',
        },
      ],
      cooldown: '5 min: quad stretch, hamstring stretch, calf stretch',
    },
    {
      day: 'Day 3',
      title: 'Engine Builder',
      warmup: '5 min: light jog, arm swings, high knees, butt kicks',
      duration: '40 min',
      exercises: [
        {
          name: 'Rowing Machine',
          sets: 4,
          reps: '500m',
          rest: '1:30',
          cues: 'Legs-back-arms sequence. Strong leg drive. Maintain a consistent pace.',
        },
        {
          name: 'Kettlebell Swing',
          sets: 4,
          reps: '20',
          rest: '1:00',
          cues: 'Hinge hard, snap the hips. Bell floats to chest height. Arms are along for the ride.',
        },
        {
          name: 'Burpee',
          sets: 4,
          reps: '10',
          rest: '1:00',
          cues: 'Chest to floor, pop up, jump and clap. Speed matters — keep moving.',
        },
        {
          name: 'Battle Rope Alternating Waves',
          sets: 4,
          reps: '30 sec',
          rest: '0:45',
          cues: 'Small, fast movements from the shoulders. Stay low in an athletic stance.',
        },
        {
          name: 'Box Step-Up',
          sets: 3,
          reps: '12 each',
          rest: '1:00',
          cues: 'Drive through the lead leg. Don\'t push off the back foot. Full extension at the top.',
        },
      ],
      cooldown: '5 min: full body stretch',
    },
    {
      day: 'Day 4',
      title: 'Upper Pull + Power',
      warmup: '5 min: band pull-aparts, cat-cow, scapular push-ups, face pulls',
      duration: '55 min',
      exercises: [
        {
          name: 'Weighted Pull-Ups',
          sets: 4,
          reps: '6',
          rest: '2:30',
          cues: 'Full dead hang. Chest to bar. Slow negative — fight the way down.',
        },
        {
          name: 'Barbell Bent-Over Row',
          sets: 4,
          reps: '8',
          rest: '2:00',
          cues: '45-degree torso. Pull to lower chest. Squeeze the shoulder blades for a beat.',
        },
        {
          name: '1a. Dumbbell Hammer Curl',
          sets: 3,
          reps: '12',
          rest: '1:00',
          cues: 'Neutral grip, elbows pinned. No swinging — controlled reps.',
        },
        {
          name: '1b. Face Pull',
          sets: 3,
          reps: '15',
          rest: '1:00',
          cues: 'Pull to forehead. External rotate at the end. Squeeze rear delts hard.',
        },
        {
          name: 'Power Clean',
          sets: 4,
          reps: '4',
          rest: '2:30',
          cues: 'Triple extension — ankles, knees, hips. Catch in the front rack. Absorb in a quarter squat.',
        },
        {
          name: 'Med Ball Rotational Throw',
          sets: 3,
          reps: '8 each side',
          rest: '1:00',
          cues: 'Rotate from the hips, not the arms. Throw through the wall. Reset every rep.',
        },
      ],
      cooldown: '5 min: lat stretch, bicep stretch, thoracic extension over foam roller',
    },
    {
      day: 'Day 5',
      title: 'Lower Body Hypertrophy',
      warmup: '5 min: foam roll quads/glutes, hip circles, walking lunges, leg swings',
      duration: '50 min',
      exercises: [
        {
          name: 'Front Squat',
          sets: 4,
          reps: '8',
          rest: '2:00',
          cues: 'Elbows high. Sit between the hips. Drive up with authority.',
        },
        {
          name: 'Bulgarian Split Squat',
          sets: 3,
          reps: '10 each',
          rest: '1:30',
          cues: 'Rear foot on bench. Front knee over toes. Stay tall through the torso.',
        },
        {
          name: 'Hip Thrust',
          sets: 4,
          reps: '12',
          rest: '1:30',
          cues: 'Upper back on bench, feet flat. Drive through heels. Full hip extension, squeeze at top.',
        },
        {
          name: '1a. Leg Extension',
          sets: 3,
          reps: '15',
          rest: '1:00',
          cues: 'Full lockout at the top. 2 second hold. Slow negative.',
        },
        {
          name: '1b. Goblet Squat — 1.5 Reps',
          sets: 3,
          reps: '8',
          rest: '1:30',
          cues: 'Go all the way down, come halfway up, go back down, then stand. That\'s one rep.',
        },
        {
          name: 'Suitcase Carry',
          sets: 3,
          reps: '30 yards each hand',
          rest: '1:00',
          cues: 'One heavy dumbbell, stay perfectly upright. Don\'t lean. Core fights the offset.',
        },
      ],
      cooldown: '5 min: pigeon stretch, quad stretch, hamstring stretch',
    },
    {
      day: 'Day 6',
      title: 'Full Body Blast',
      warmup: '5 min: jump rope, inchworms, mountain climbers, high knees',
      duration: '45 min',
      exercises: [
        {
          name: 'Dumbbell Complex',
          sets: 4,
          reps: '6 each move',
          rest: '2:00',
          cues: 'Deadlift → Row → Clean → Press → Squat. No rest between moves. That\'s one set.',
        },
        {
          name: 'Assault Bike Sprint',
          sets: 5,
          reps: '20 sec max / 40 sec easy',
          rest: '-',
          cues: 'All-out for 20 seconds. True max effort. Recover at easy pace.',
        },
        {
          name: 'Wall Ball',
          sets: 4,
          reps: '15',
          rest: '1:00',
          cues: 'Deep squat, throw to target on the way up. Catch and squat in one motion.',
        },
        {
          name: 'Sled Push',
          sets: 3,
          reps: '40 yards',
          rest: '1:30',
          cues: 'Low body angle. Short, powerful steps. Arms locked out.',
        },
        {
          name: 'Plank to Push-Up',
          sets: 3,
          reps: '8 each arm lead',
          rest: '1:00',
          cues: 'Start on forearms, press up to hands one arm at a time. Keep hips level.',
        },
      ],
      cooldown: '10 min: full body stretch and foam roll. You earned it.',
    },
  ],
}

export const strengthProgram: Program = {
  id: 'strength',
  name: 'Strength',
  weeks: 4,
  frequency: '6x / week',
  description: 'Push. Pull. Legs. Repeat. Build serious strength and size.',
  category: 'strength',
  image: '/programs/strength.jpg',
  days: [
    {
      day: 'Day 1',
      title: 'Push — Strength',
      warmup: '5 min: band pull-aparts, arm circles, push-up walkouts, rotator cuff work',
      duration: '60 min',
      exercises: [
        {
          name: 'Bench Press',
          sets: 5,
          reps: '5',
          rest: '3:00',
          cues: 'Arch the upper back, not the lower. Bar touches mid-chest. Explode off the chest.',
        },
        {
          name: 'Overhead Press',
          sets: 4,
          reps: '6',
          rest: '2:30',
          cues: 'Strict press — no leg drive. Bar starts at chin, lock out overhead. Squeeze glutes.',
        },
        {
          name: 'Incline Dumbbell Bench Press',
          sets: 3,
          reps: '10',
          rest: '1:30',
          cues: '30-degree bench. Full stretch at the bottom. Squeeze the chest at the top.',
        },
        {
          name: 'Dumbbell Lateral Raise',
          sets: 4,
          reps: '12',
          rest: '1:00',
          cues: 'Lead with the elbows. Raise to shoulder height. Controlled negative every rep.',
        },
        {
          name: 'Cable Tricep Pushdown',
          sets: 3,
          reps: '12',
          rest: '1:00',
          cues: 'Elbows pinned to sides. Full extension. Squeeze at the bottom.',
        },
        {
          name: 'Close-Grip Bench Press',
          sets: 3,
          reps: '8',
          rest: '1:30',
          cues: 'Hands shoulder-width. Elbows tucked close. Press through the triceps.',
        },
      ],
      cooldown: '5 min: chest stretch, shoulder stretch, tricep stretch',
    },
    {
      day: 'Day 2',
      title: 'Pull — Strength',
      warmup: '5 min: band pull-aparts, cat-cow, dead hangs, scap retractions',
      duration: '55 min',
      exercises: [
        {
          name: 'Barbell Deadlift',
          sets: 5,
          reps: '5',
          rest: '3:00',
          cues: 'Flat back, bar against shins. Drive through the floor. Lock hips and knees at the same time.',
        },
        {
          name: 'Weighted Pull-Ups',
          sets: 4,
          reps: '6',
          rest: '2:30',
          cues: 'Full hang to chest at bar. Slow negative. Add weight when you hit all reps.',
        },
        {
          name: 'Barbell Bent-Over Row',
          sets: 4,
          reps: '8',
          rest: '2:00',
          cues: '45-degree torso. Pull to lower chest. Squeeze for a beat at the top.',
        },
        {
          name: 'Cable Face Pull',
          sets: 3,
          reps: '15',
          rest: '1:00',
          cues: 'Pull to forehead, external rotate. Rear delts and upper back should be on fire.',
        },
        {
          name: 'Barbell Curl',
          sets: 3,
          reps: '10',
          rest: '1:00',
          cues: 'Strict form. No swinging the body. Squeeze at the top, slow negative.',
        },
        {
          name: 'Dumbbell Hammer Curl',
          sets: 3,
          reps: '12',
          rest: '1:00',
          cues: 'Neutral grip. Elbows locked. Work the brachialis — builds arm thickness.',
        },
      ],
      cooldown: '5 min: lat stretch, bicep stretch, lower back stretch',
    },
    {
      day: 'Day 3',
      title: 'Legs — Strength',
      warmup: '5 min: bodyweight squats, leg swings, hip circles, glute bridges, foam roll quads',
      duration: '60 min',
      exercises: [
        {
          name: 'Barbell Back Squat',
          sets: 5,
          reps: '5',
          rest: '3:00',
          cues: 'Big breath, brace hard. Break hips and knees together. Fight to keep the chest up.',
        },
        {
          name: 'Front Squat',
          sets: 3,
          reps: '6',
          rest: '2:30',
          cues: 'Elbows high, upper back tight. Sit straight down. Drive up through the heels.',
        },
        {
          name: 'Barbell Hip Thrust',
          sets: 4,
          reps: '10',
          rest: '1:30',
          cues: 'Upper back on bench. Drive through heels. Full hip extension — squeeze glutes at top.',
        },
        {
          name: 'Walking Lunge',
          sets: 3,
          reps: '10 each',
          rest: '1:30',
          cues: 'Dumbbells at sides. Long stride, back knee to floor. Controlled and upright.',
        },
        {
          name: 'Leg Curl',
          sets: 3,
          reps: '12',
          rest: '1:15',
          cues: 'Squeeze hard at the top. 3-second negative on every rep.',
        },
        {
          name: 'Standing Calf Raise',
          sets: 4,
          reps: '15',
          rest: '1:00',
          cues: 'Full stretch at the bottom. Pause at the top. Don\'t rush.',
        },
      ],
      cooldown: '5 min: pigeon stretch, quad stretch, hamstring stretch',
    },
    {
      day: 'Day 4',
      title: 'Push — Volume',
      warmup: '5 min: band pull-aparts, arm circles, light push-ups',
      duration: '55 min',
      exercises: [
        {
          name: 'Dumbbell Bench Press',
          sets: 4,
          reps: '10',
          tempo: '3-1-1-0',
          rest: '1:30',
          cues: 'Full stretch at the bottom. Squeeze the chest together at the top.',
        },
        {
          name: 'Dumbbell Arnold Press',
          sets: 4,
          reps: '10',
          rest: '1:30',
          cues: 'Start palms in, rotate as you press. Full lockout overhead.',
        },
        {
          name: '1a. Cable Fly',
          sets: 3,
          reps: '12',
          rest: '1:00',
          cues: 'Slight bend in elbows. Bring hands together at chest height. Squeeze the chest.',
        },
        {
          name: '1b. Dumbbell Front Raise',
          sets: 3,
          reps: '12',
          rest: '1:00',
          cues: 'Thumbs up, raise to eye level. Control the weight — don\'t swing.',
        },
        {
          name: 'Overhead Tricep Extension',
          sets: 3,
          reps: '12',
          rest: '1:00',
          cues: 'Dumbbell behind head, elbows forward. Extend fully. Feel the stretch.',
        },
        {
          name: 'Push-Up — Burnout',
          sets: 2,
          reps: 'Max reps',
          rest: '1:00',
          cues: 'Chest to the floor every rep. Drop to knees when you have to. Empty the tank.',
        },
      ],
      cooldown: '5 min: chest and shoulder stretching',
    },
    {
      day: 'Day 5',
      title: 'Pull — Volume',
      warmup: '5 min: band pull-aparts, scap push-ups, cat-cow, light rows',
      duration: '55 min',
      exercises: [
        {
          name: 'Chest-Supported Dumbbell Row',
          sets: 4,
          reps: '10',
          rest: '1:30',
          cues: 'Incline bench, chest down. Pull to hip, squeeze the back. No momentum.',
        },
        {
          name: 'Lat Pulldown',
          sets: 4,
          reps: '10',
          rest: '1:30',
          cues: 'Pull to upper chest. Lean back slightly. Squeeze the lats at the bottom.',
        },
        {
          name: '1a. Seated Cable Row',
          sets: 3,
          reps: '12',
          rest: '1:15',
          cues: 'Pull to belly button. Chest tall. Squeeze the shoulder blades together.',
        },
        {
          name: '1b. Reverse Fly',
          sets: 3,
          reps: '15',
          rest: '1:00',
          cues: 'Bent over, slight bend in elbows. Raise to shoulder height. Feel the rear delts.',
        },
        {
          name: '2a. Incline Dumbbell Curl',
          sets: 3,
          reps: '10',
          rest: '1:00',
          cues: 'Bench at 45 degrees. Full stretch at the bottom. Curl with intention.',
        },
        {
          name: '2b. Concentration Curl',
          sets: 3,
          reps: '10 each',
          rest: '1:00',
          cues: 'Elbow on inner thigh. Squeeze at the top. Slow negative.',
        },
      ],
      cooldown: '5 min: lat stretch, bicep stretch, foam roll upper back',
    },
    {
      day: 'Day 6',
      title: 'Legs — Power',
      warmup: '5 min: foam roll, leg swings, bodyweight squats, box jumps (low)',
      duration: '60 min',
      exercises: [
        {
          name: 'Box Squat',
          sets: 4,
          reps: '5',
          rest: '2:30',
          cues: 'Sit back to the box, pause, then explode up. Focus on power out of the hole.',
        },
        {
          name: 'Trap Bar Deadlift',
          sets: 4,
          reps: '5',
          rest: '2:30',
          cues: 'Neutral grip, push the floor away. Lock out hard. Reset every rep.',
        },
        {
          name: 'Leg Press',
          sets: 4,
          reps: '12',
          rest: '1:30',
          cues: 'Feet shoulder-width. Full depth without the lower back coming off the pad.',
        },
        {
          name: 'Bulgarian Split Squat',
          sets: 3,
          reps: '10 each',
          rest: '1:30',
          cues: 'Rear foot on bench. Drop straight down. Drive through the front heel.',
        },
        {
          name: 'Seated Calf Raise',
          sets: 4,
          reps: '15',
          rest: '1:00',
          cues: 'Full stretch, full squeeze. Slow reps build the soleus.',
        },
        {
          name: 'Ab Wheel Rollout',
          sets: 3,
          reps: '10',
          rest: '1:00',
          cues: 'Core tight, don\'t let the hips sag. Roll out as far as you can control.',
        },
      ],
      cooldown: '5 min: quad stretch, hamstring stretch, hip flexor stretch',
    },
  ],
}

export const runningProgram: Program = {
  id: 'running',
  name: 'Running — Half Marathon',
  weeks: 4,
  frequency: '3x / week',
  description: '1km repeats, threshold work, and progressive long runs. Built to race.',
  category: 'running',
  image: '/programs/running.jpg',
  days: [
    {
      day: 'Day 1',
      title: 'Intervals + Race Pace',
      warmup: '15 min: easy jog (1 mile), A-skips, B-skips, high knees, butt kicks, 4 × 100m strides building to 85%',
      duration: '55 min',
      exercises: [
        {
          name: '1km Repeat at Race Pace',
          sets: 5,
          reps: '1km',
          rest: '2:00',
          cues: 'Run at your target race split. Jog the recovery, don\'t walk. Keep your form locked in when you\'re tired. Weeks 1-2: 4 reps. Weeks 3-4: 5 reps.',
        },
        {
          name: '800m at Half Marathon Goal Pace',
          sets: 4,
          reps: '800m',
          rest: '1:30',
          cues: 'Dial in your half marathon goal pace. This should feel fast but controlled — you could hold a few words, not a sentence. Stay relaxed through the shoulders. Weeks 1-2: 3 reps. Weeks 3-4: 4 reps.',
        },
        {
          name: '400m Fast Finish',
          sets: 3,
          reps: '400m',
          rest: '1:00',
          cues: 'Faster than race pace — about 5K effort. This builds your finishing kick. Drive the arms, stay tall, quick turnover. These should hurt a little.',
        },
        {
          name: '200m Build-Up Sprint',
          sets: 4,
          reps: '200m',
          rest: '1:30',
          cues: 'Start at jog pace and accelerate through the full 200m — hit 90-95% by the last 50m. Builds leg power and turnover speed without needing a hill. Walk back to start for recovery. Focus on smooth acceleration, not jerky effort.',
        },
      ],
      cooldown: '10 min: easy jog (0.5 mile), calf stretch, hip flexor stretch, hamstring stretch, quad stretch (30 sec each side)',
    },
    {
      day: 'Day 2',
      title: 'Threshold + Tempo',
      warmup: '15 min: easy jog (1 mile), leg swings, hip circles, 4 × 100m strides at tempo effort',
      duration: '50 min',
      exercises: [
        {
          name: 'Tempo Run',
          sets: 1,
          reps: '25 min',
          rest: '-',
          cues: 'Comfortably hard — you can speak in short phrases but not sentences. This is your lactate threshold pace, roughly your 1-hour race effort. Don\'t start too fast. Lock in and hold steady. Weeks 1-2: 20 min. Weeks 3-4: 25 min.',
        },
        {
          name: 'Race Simulation Fartlek',
          sets: 1,
          reps: '16 min',
          rest: '-',
          cues: 'Alternate 2 min hard / 2 min easy jog for 16 minutes total (4 rounds). Simulates race-day surges on tired legs. The easy portions are active recovery — keep moving, don\'t stop.',
        },
        {
          name: 'Easy Jog Recovery',
          sets: 1,
          reps: '10 min',
          rest: '-',
          cues: 'Slow it down to conversational pace. Let your heart rate drop. This is active recovery — flush the legs out and finish the session right.',
        },
      ],
      cooldown: '5 min walk, then foam roll calves, quads, and IT band. Pigeon stretch and standing hamstring stretch (30 sec each side).',
    },
    {
      day: 'Day 3',
      title: 'Long Run',
      warmup: 'No formal warmup — start with a walk, then easy jog. Let the first mile be your warmup. Don\'t stretch cold.',
      duration: '60-80 min',
      exercises: [
        {
          name: 'Long Run — Steady',
          sets: 1,
          reps: 'See cues for distance',
          rest: '-',
          cues: 'Week 1: 5 miles. Week 2: 6 miles. Week 3: 7 miles. Week 4: 8 miles. Run at easy conversational pace — you should be able to hold a full conversation. This is your aerobic base. Don\'t chase pace. If you can\'t talk, slow down.',
        },
        {
          name: 'Progression Finish — Last Mile',
          sets: 1,
          reps: '1 mile',
          rest: '-',
          cues: 'Pick it up for the final mile. Drop to half marathon effort and close hard — simulate the end of a race. This trains your body to push when it\'s already tired.',
        },
        {
          name: 'Cooldown Walk + Stretch',
          sets: 1,
          reps: '10 min',
          rest: '-',
          cues: '5 min walk, then calves, hip flexors, hamstrings, quads (30 sec each side), pigeon stretch (45 sec each side). Hold every stretch — don\'t bounce. Start hydrating now.',
        },
      ],
      cooldown: '5 min walk, then calves, hip flexors, hamstrings, quads (30 sec each side). Refuel within 30 min — protein + carbs.',
    },
  ],
}

export const allPrograms: Program[] = [
  functionalFitnessProgram,
  runningProgram,
  hybridProgram,
  athleticProgram,
  strengthProgram,
  executiveProgram,
]

export function getProgram(identity: string): Program {
  return identity === 'athlete' ? athleticProgram : executiveProgram
}

export function getProgramById(id: string): Program | undefined {
  return allPrograms.find((p) => p.id === id)
}

