export type Exercise = {
  name: string
  sets: number
  reps: string
  tempo?: string
  rest: string
  cues: string
  videoUrl?: string
}

export type TrainingDay = {
  day: string
  title: string
  warmup?: string
  exercises: Exercise[]
  cooldown?: string
  duration: string
}

export type Program = {
  id: string
  name: string
  weeks: number
  days: TrainingDay[]
  frequency: string
  description: string
  category: 'strength' | 'hybrid' | 'conditioning' | 'functional' | 'running'
}

export const athleticProgram: Program = {
  id: 'athletic-performance',
  name: 'Athletic Performance',
  weeks: 4,
  frequency: '5x / week',
  description: 'Sport-ready power, speed, and conditioning for competitive athletes.',
  category: 'hybrid',
  days: [
    {
      day: 'Day 1',
      title: 'Lower Body Power',
      warmup: '5 min dynamic stretching: leg swings, hip circles, walking lunges, high knees',
      duration: '55 min',
      exercises: [
        {
          name: 'Barbell Back Squat',
          sets: 4,
          reps: '6',
          tempo: '3-1-1-0',
          rest: '2:30',
          cues: 'Chest up, drive through heels. Full depth — hip crease below knee.',
        },
        {
          name: 'Romanian Deadlift',
          sets: 3,
          reps: '8',
          tempo: '3-1-1-0',
          rest: '2:00',
          cues: 'Hinge at hips, slight knee bend. Feel the stretch in hamstrings before driving up.',
        },
        {
          name: 'Bulgarian Split Squat',
          sets: 3,
          reps: '10 each',
          rest: '1:30',
          cues: 'Rear foot elevated. Front knee tracks over toes. Stay upright.',
        },
        {
          name: 'Box Jumps',
          sets: 4,
          reps: '5',
          rest: '1:30',
          cues: 'Explode up, land soft. Step down — don\'t jump down. Full hip extension at the top.',
        },
        {
          name: 'Sled Push',
          sets: 3,
          reps: '40 yards',
          rest: '2:00',
          cues: 'Low body angle, drive through the ground. Short powerful steps.',
        },
      ],
      cooldown: '5 min foam rolling: quads, hamstrings, glutes, calves',
    },
    {
      day: 'Day 2',
      title: 'Upper Body Strength',
      warmup: '5 min: band pull-aparts, arm circles, push-up to downward dog',
      duration: '50 min',
      exercises: [
        {
          name: 'Bench Press',
          sets: 4,
          reps: '6',
          tempo: '3-1-1-0',
          rest: '2:30',
          cues: 'Shoulder blades pinched, feet flat. Control the descent — explode up.',
        },
        {
          name: 'Bent-Over Barbell Row',
          sets: 4,
          reps: '8',
          tempo: '2-1-1-0',
          rest: '2:00',
          cues: '45-degree torso angle. Pull to lower chest, squeeze shoulder blades.',
        },
        {
          name: 'Dumbbell Shoulder Press',
          sets: 3,
          reps: '10',
          rest: '1:30',
          cues: 'Full range of motion. Don\'t arch the back. Lock out at the top.',
        },
        {
          name: 'Weighted Chin-Ups',
          sets: 3,
          reps: '6-8',
          rest: '2:00',
          cues: 'Full dead hang to chin over bar. Control the negative.',
        },
        {
          name: 'Face Pulls',
          sets: 3,
          reps: '15',
          rest: '1:00',
          cues: 'Pull to forehead level, external rotate at the end. Squeeze rear delts.',
        },
        {
          name: 'Farmer\'s Carry',
          sets: 3,
          reps: '40 yards',
          rest: '1:30',
          cues: 'Heavy weight, tall posture. Shoulders packed, core braced.',
        },
      ],
      cooldown: '5 min stretching: chest, lats, shoulders',
    },
    {
      day: 'Day 3',
      title: 'Speed & Agility',
      warmup: '10 min: A-skips, B-skips, lateral shuffles, karaoke, build-up sprints',
      duration: '45 min',
      exercises: [
        {
          name: '10-Yard Sprint',
          sets: 6,
          reps: '1',
          rest: '1:30',
          cues: 'Explosive start. Drive phase — 45-degree body angle for first 5 steps.',
        },
        {
          name: '5-10-5 Pro Agility',
          sets: 4,
          reps: '1',
          rest: '2:00',
          cues: 'Low center of gravity on cuts. Plant outside foot hard, drive opposite direction.',
        },
        {
          name: 'Lateral Bound',
          sets: 3,
          reps: '8 each',
          rest: '1:30',
          cues: 'Stick each landing for 1 second. Absorb with a soft knee.',
        },
        {
          name: 'Cone Drill — L-Drill',
          sets: 4,
          reps: '1',
          rest: '2:00',
          cues: 'Tight turns around cones. Stay low through transitions.',
        },
        {
          name: 'Broad Jump',
          sets: 4,
          reps: '3',
          rest: '1:30',
          cues: 'Load the hips, swing arms, explode forward. Stick the landing.',
        },
        {
          name: 'Sprint Intervals',
          sets: 6,
          reps: '100 yards',
          rest: '1:00',
          cues: '85% effort. Focus on mechanics — high knees, arm drive, relaxed face.',
        },
        {
          name: 'Ladder Drills',
          sets: 3,
          reps: '2 patterns',
          rest: '1:00',
          cues: 'Quick feet, light contact. Ickey shuffle + in-in-out-out.',
        },
      ],
      cooldown: '5 min: hip flexor stretch, hamstring stretch, calf stretch',
    },
    {
      day: 'Day 4',
      title: 'Total Body Conditioning',
      warmup: '5 min: jump rope, mountain climbers, inchworms',
      duration: '60 min',
      exercises: [
        {
          name: 'Power Clean',
          sets: 4,
          reps: '5',
          rest: '2:30',
          cues: 'Triple extension — hips, knees, ankles. Catch in a front rack, absorb in a quarter squat.',
        },
        {
          name: 'Dumbbell Thruster',
          sets: 3,
          reps: '12',
          rest: '1:30',
          cues: 'Squat deep, drive overhead in one motion. Lock out at the top.',
        },
        {
          name: 'Pull-Ups',
          sets: 4,
          reps: '8-10',
          rest: '1:30',
          cues: 'Full range. Dead hang to chin over bar. No kipping.',
        },
        {
          name: 'Battle Rope Slams',
          sets: 4,
          reps: '30 sec',
          rest: '1:00',
          cues: 'Full body — use your hips, not just arms. Controlled aggression.',
        },
        {
          name: 'Prowler Push + Pull',
          sets: 3,
          reps: '40 yards each',
          rest: '2:00',
          cues: 'Push: low angle, short steps. Pull: hand over hand, drive with legs.',
        },
      ],
      cooldown: '10 min: full body stretch and foam roll',
    },
    {
      day: 'Day 5',
      title: 'Recovery & Mobility',
      warmup: '5 min easy walk or light bike',
      duration: '35 min',
      exercises: [
        {
          name: 'Foam Roll — Full Body',
          sets: 1,
          reps: '60 sec each area',
          rest: '-',
          cues: 'Quads, hamstrings, glutes, IT band, lats, upper back. Slow passes.',
        },
        {
          name: '90/90 Hip Stretch',
          sets: 2,
          reps: '60 sec each side',
          rest: '-',
          cues: 'Sit tall, lean forward into the stretch. Breathe deep.',
        },
        {
          name: 'Cat-Cow',
          sets: 2,
          reps: '10',
          rest: '-',
          cues: 'Controlled movement. Full flexion and extension of the spine.',
        },
        {
          name: 'World\'s Greatest Stretch',
          sets: 2,
          reps: '5 each side',
          rest: '-',
          cues: 'Lunge, rotate, reach. Open up the hips and thoracic spine.',
        },
        {
          name: 'Banded Shoulder Distraction',
          sets: 2,
          reps: '45 sec each side',
          rest: '-',
          cues: 'Face away from anchor. Let the band pull the shoulder forward, rotate slowly.',
        },
        {
          name: 'Supine Spinal Twist',
          sets: 2,
          reps: '60 sec each side',
          rest: '-',
          cues: 'Knees stacked, arms out. Let gravity do the work. Breathe.',
        },
        {
          name: 'Diaphragmatic Breathing',
          sets: 1,
          reps: '3 min',
          rest: '-',
          cues: '4 seconds in through the nose, 6 seconds out through the mouth. Belly rises first.',
        },
        {
          name: 'Meditation / Visualization',
          sets: 1,
          reps: '5 min',
          rest: '-',
          cues: 'Eyes closed. Visualize tomorrow\'s training session. See yourself executing perfectly.',
        },
      ],
    },
  ],
}

export const executiveProgram: Program = {
  id: 'executive-performance',
  name: 'Executive Performance Protocol',
  weeks: 4,
  frequency: '4x / week',
  description: 'Efficient training for busy professionals who refuse to let the body slide.',
  category: 'functional',
  days: [
    {
      day: 'Day 1',
      title: 'Strength Foundations',
      warmup: '5 min: bodyweight squats, arm circles, cat-cow, hip hinges',
      duration: '45 min',
      exercises: [
        {
          name: 'Goblet Squat',
          sets: 3,
          reps: '10',
          tempo: '3-1-1-0',
          rest: '1:30',
          cues: 'Elbows inside knees at the bottom. Chest up, weight in heels.',
        },
        {
          name: 'Dumbbell Bench Press',
          sets: 3,
          reps: '10',
          tempo: '3-1-1-0',
          rest: '1:30',
          cues: 'Control the descent. Press to full lockout. Shoulder blades pinched.',
        },
        {
          name: 'Single-Arm Dumbbell Row',
          sets: 3,
          reps: '10 each',
          rest: '1:15',
          cues: 'Pull to hip. Squeeze the lat at the top. Don\'t rotate the torso.',
        },
        {
          name: 'Kettlebell Deadlift',
          sets: 3,
          reps: '12',
          rest: '1:30',
          cues: 'Push hips back, flat back. Drive through heels to stand.',
        },
        {
          name: 'Plank Hold',
          sets: 3,
          reps: '45 sec',
          rest: '1:00',
          cues: 'Straight line head to heels. Squeeze glutes, brace core. Breathe.',
        },
      ],
      cooldown: '5 min: chest stretch, hip flexor stretch, child\'s pose',
    },
    {
      day: 'Day 2',
      title: 'Conditioning + Breathwork',
      warmup: '5 min: light jog, arm swings, leg swings',
      duration: '40 min',
      exercises: [
        {
          name: 'Kettlebell Swing',
          sets: 4,
          reps: '15',
          rest: '1:00',
          cues: 'Hip hinge — not a squat. Snap hips forward, float the bell to chest height.',
        },
        {
          name: 'Rowing Machine Intervals',
          sets: 5,
          reps: '250m',
          rest: '1:00',
          cues: 'Legs-back-arms on the drive, arms-back-legs on recovery. Aim for consistent split.',
        },
        {
          name: 'Push-Up to Rotation',
          sets: 3,
          reps: '8 each side',
          rest: '1:00',
          cues: 'Full push-up, rotate to side plank at the top. Open the chest.',
        },
        {
          name: 'Med Ball Slam',
          sets: 3,
          reps: '12',
          rest: '1:00',
          cues: 'Reach overhead, slam with your whole body. Pick up and reset each rep.',
        },
        {
          name: 'Box Breathing',
          sets: 1,
          reps: '5 min',
          rest: '-',
          cues: '4 seconds inhale, 4 hold, 4 exhale, 4 hold. Focus on complete stillness.',
        },
        {
          name: 'Wim Hof Breathing',
          sets: 3,
          reps: '30 breaths + hold',
          rest: '1:00',
          cues: 'Deep belly breaths in, passive exhale out. After 30, exhale and hold as long as comfortable.',
        },
      ],
      cooldown: '5 min: standing forward fold, doorway chest stretch',
    },
    {
      day: 'Day 3',
      title: 'Focus & Power',
      warmup: '5 min: jump rope, mobility flow',
      duration: '50 min',
      exercises: [
        {
          name: 'Trap Bar Deadlift',
          sets: 4,
          reps: '6',
          rest: '2:30',
          cues: 'Neutral spine, grip hard. Drive the floor away from you.',
        },
        {
          name: 'Dumbbell Push Press',
          sets: 3,
          reps: '8',
          rest: '1:30',
          cues: 'Quarter dip, drive explosively. Lock out overhead.',
        },
        {
          name: 'TRX Row',
          sets: 3,
          reps: '12',
          rest: '1:15',
          cues: 'Body straight as a plank. Pull chest to handles, squeeze at the top.',
        },
        {
          name: 'Dumbbell Walking Lunge',
          sets: 3,
          reps: '10 each',
          rest: '1:30',
          cues: 'Long stride, back knee kisses the floor. Stay tall and controlled.',
        },
        {
          name: 'Pallof Press',
          sets: 3,
          reps: '10 each side',
          rest: '1:00',
          cues: 'Resist the rotation. Press out slowly, hold for a beat, bring it back.',
        },
      ],
      cooldown: '5 min: pigeon stretch, thoracic spine rotation, deep breathing',
    },
    {
      day: 'Day 4',
      title: 'Recovery & Mobility',
      warmup: '5 min easy walk',
      duration: '30 min',
      exercises: [
        {
          name: 'Foam Roll — Full Body',
          sets: 1,
          reps: '60 sec each area',
          rest: '-',
          cues: 'Upper back, lats, quads, hamstrings, calves. Slow and controlled.',
        },
        {
          name: 'Hip 90/90 Flow',
          sets: 2,
          reps: '8 transitions',
          rest: '-',
          cues: 'Smooth transitions between sides. Sit tall throughout.',
        },
        {
          name: 'Thoracic Spine Rotation',
          sets: 2,
          reps: '8 each side',
          rest: '-',
          cues: 'Side-lying position. Follow the hand with your eyes. Open up fully.',
        },
        {
          name: 'Banded Pull-Apart',
          sets: 2,
          reps: '15',
          rest: '-',
          cues: 'Light band, slow reps. Focus on squeezing the upper back.',
        },
        {
          name: 'Yoga Flow',
          sets: 1,
          reps: '5 min',
          rest: '-',
          cues: 'Sun salutation A. Breathe with each movement. Move with intention.',
        },
        {
          name: 'Guided Visualization',
          sets: 1,
          reps: '5 min',
          rest: '-',
          cues: 'Close your eyes. See your biggest goal. Walk through each step to get there.',
        },
        {
          name: 'Gratitude Journaling',
          sets: 1,
          reps: '5 min',
          rest: '-',
          cues: 'Write 3 things you\'re grateful for. Be specific — not just "family" but why, today.',
        },
      ],
    },
  ],
}

export const functionalFitnessProgram: Program = {
  id: 'functional-fitness',
  name: 'Functional Fitness',
  weeks: 4,
  frequency: '3x / week',
  description: 'Full-body training 3 days a week. Maximum results, minimum time commitment.',
  category: 'functional',
  days: [
    {
      day: 'Day 1',
      title: 'Strength + Movement',
      warmup: '5 min: world\'s greatest stretch, inchworms, bodyweight squats, band pull-aparts',
      duration: '50 min',
      exercises: [
        {
          name: 'Trap Bar Deadlift',
          sets: 4,
          reps: '6',
          rest: '2:30',
          cues: 'Neutral grip, chest up. Push the floor away. Lock out hips at the top.',
        },
        {
          name: 'Dumbbell Bench Press',
          sets: 4,
          reps: '8',
          tempo: '3-1-1-0',
          rest: '2:00',
          cues: 'Control the lower. Touch chest, press to full lockout. Shoulder blades glued to bench.',
        },
        {
          name: 'Goblet Squat',
          sets: 3,
          reps: '12',
          rest: '1:30',
          cues: 'Elbows inside knees at the bottom. Full depth. Drive up through the heels.',
        },
        {
          name: 'Single-Arm Dumbbell Row',
          sets: 3,
          reps: '10 each',
          rest: '1:15',
          cues: 'Pull to hip, squeeze the lat. Keep your torso still — no rotation.',
        },
        {
          name: 'Farmer\'s Carry',
          sets: 3,
          reps: '40 yards',
          rest: '1:30',
          cues: 'Heavy dumbbells, tall posture. Shoulders down, core tight, walk with purpose.',
        },
        {
          name: 'Dead Bug',
          sets: 3,
          reps: '8 each side',
          rest: '1:00',
          cues: 'Low back pressed into the floor the entire time. Slow and controlled.',
        },
      ],
      cooldown: '5 min: hip flexor stretch, chest stretch, hamstring stretch',
    },
    {
      day: 'Day 2',
      title: 'Conditioning + Core',
      warmup: '5 min: jump rope, arm circles, leg swings, A-skips',
      duration: '45 min',
      exercises: [
        {
          name: 'Kettlebell Swing',
          sets: 5,
          reps: '15',
          rest: '1:00',
          cues: 'Hip hinge — not a squat. Snap the hips, float the bell. Arms are just hooks.',
        },
        {
          name: 'Dumbbell Thruster',
          sets: 4,
          reps: '10',
          rest: '1:30',
          cues: 'Squat deep, then drive through the heels and press overhead in one motion.',
        },
        {
          name: 'Renegade Row',
          sets: 3,
          reps: '8 each',
          rest: '1:15',
          cues: 'Wide feet for balance. Row one dumbbell, keep hips square to the floor.',
        },
        {
          name: 'Box Jump',
          sets: 4,
          reps: '6',
          rest: '1:30',
          cues: 'Load the hips, swing the arms, explode. Land soft. Step down every rep.',
        },
        {
          name: 'Med Ball Slam',
          sets: 3,
          reps: '12',
          rest: '1:00',
          cues: 'Full reach overhead, slam it like you mean it. Reset every rep.',
        },
        {
          name: 'Plank Shoulder Tap',
          sets: 3,
          reps: '10 each',
          rest: '1:00',
          cues: 'Hips stay level. Don\'t rock side to side. Slow and controlled.',
        },
      ],
      cooldown: '5 min: pigeon stretch, child\'s pose, deep breathing',
    },
    {
      day: 'Day 3',
      title: 'Power + Recovery',
      warmup: '5 min: foam roll, hip circles, high knees, butt kicks',
      duration: '50 min',
      exercises: [
        {
          name: 'Barbell Front Squat',
          sets: 4,
          reps: '6',
          rest: '2:30',
          cues: 'Elbows high, core tight. Sit straight down between the hips. Drive up with authority.',
        },
        {
          name: 'Dumbbell Push Press',
          sets: 3,
          reps: '8',
          rest: '1:30',
          cues: 'Quick dip, explosive drive. Lock out overhead. Use the legs.',
        },
        {
          name: 'Pull-Ups',
          sets: 4,
          reps: '6-8',
          rest: '2:00',
          cues: 'Full dead hang to chin over bar. No kipping. Control the way down.',
        },
        {
          name: 'Dumbbell Romanian Deadlift',
          sets: 3,
          reps: '10',
          tempo: '3-1-1-0',
          rest: '1:30',
          cues: 'Hinge until dumbbells reach mid-shin. Feel the hamstrings load, then squeeze glutes to stand.',
        },
        {
          name: 'Turkish Get-Up',
          sets: 2,
          reps: '3 each side',
          rest: '1:30',
          cues: 'Eyes on the weight the entire time. Slow, deliberate movement through every position.',
        },
        {
          name: '90/90 Hip Stretch',
          sets: 2,
          reps: '60 sec each side',
          rest: '-',
          cues: 'Sit tall, lean forward. Breathe into the stretch. Don\'t force it.',
        },
        {
          name: 'Diaphragmatic Breathing',
          sets: 1,
          reps: '3 min',
          rest: '-',
          cues: '4 in, 6 out. Belly rises first. Calm the nervous system.',
        },
      ],
      cooldown: '5 min: full body foam roll',
    },
  ],
}

export const hybridProgram: Program = {
  id: 'hybrid-training',
  name: 'Hybrid Training',
  weeks: 4,
  frequency: '6x / week',
  description: 'The best of both worlds — build muscle, build engine. No weakness.',
  category: 'hybrid',
  days: [
    {
      day: 'Day 1',
      title: 'Upper Push + Conditioning',
      warmup: '5 min: band pull-aparts, arm circles, push-up walkouts, jumping jacks',
      duration: '55 min',
      exercises: [
        {
          name: 'Barbell Bench Press',
          sets: 4,
          reps: '6',
          tempo: '3-1-1-0',
          rest: '2:30',
          cues: 'Shoulder blades pinched, feet flat. Controlled descent, explosive press.',
        },
        {
          name: 'Dumbbell Incline Press',
          sets: 3,
          reps: '10',
          rest: '1:30',
          cues: '30-degree angle. Full stretch at the bottom, squeeze at the top.',
        },
        {
          name: 'Dumbbell Lateral Raise',
          sets: 3,
          reps: '12',
          rest: '1:00',
          cues: 'Slight bend in elbows. Raise to shoulder height. Control the negative — don\'t swing.',
        },
        {
          name: 'Tricep Dips',
          sets: 3,
          reps: '10-12',
          rest: '1:30',
          cues: 'Full depth — upper arm parallel. Drive up to full lockout. Lean forward slightly.',
        },
        {
          name: 'Assault Bike Intervals',
          sets: 6,
          reps: '30 sec on / 30 sec off',
          rest: '0:30',
          cues: 'Max effort on work intervals. Full body — push and pull with the arms.',
        },
        {
          name: 'Push-Up Burnout',
          sets: 2,
          reps: 'Max reps',
          rest: '1:00',
          cues: 'Chest to floor every rep. When you can\'t do full, drop to knees. Empty the tank.',
        },
      ],
      cooldown: '5 min: chest doorway stretch, tricep stretch, shoulder stretch',
    },
    {
      day: 'Day 2',
      title: 'Lower Body Strength',
      warmup: '5 min: hip circles, leg swings, bodyweight squats, glute bridges',
      duration: '55 min',
      exercises: [
        {
          name: 'Barbell Back Squat',
          sets: 5,
          reps: '5',
          rest: '2:30',
          cues: 'Brace hard. Break at hips and knees together. Drive heels through the floor.',
        },
        {
          name: 'Romanian Deadlift',
          sets: 4,
          reps: '8',
          tempo: '3-1-1-0',
          rest: '2:00',
          cues: 'Hips back, bar tracks down the thighs. Hamstring stretch, then glute squeeze at top.',
        },
        {
          name: 'Walking Lunge',
          sets: 3,
          reps: '10 each',
          rest: '1:30',
          cues: 'Long stride, knee tracks over toes. Back knee kisses the floor. Stay upright.',
        },
        {
          name: 'Leg Curl',
          sets: 3,
          reps: '12',
          rest: '1:15',
          cues: 'Slow negative. Squeeze at the top. Full range of motion.',
        },
        {
          name: 'Calf Raise',
          sets: 4,
          reps: '15',
          rest: '1:00',
          cues: 'Full stretch at the bottom, pause at the top. Slow and controlled.',
        },
        {
          name: 'Hanging Leg Raise',
          sets: 3,
          reps: '10',
          rest: '1:00',
          cues: 'No swinging. Curl the hips under as you raise. Control the descent.',
        },
      ],
      cooldown: '5 min: quad stretch, hamstring stretch, calf stretch',
    },
    {
      day: 'Day 3',
      title: 'Engine Builder',
      warmup: '5 min: light jog, arm swings, high knees, butt kicks',
      duration: '40 min',
      exercises: [
        {
          name: 'Rowing Machine',
          sets: 4,
          reps: '500m',
          rest: '1:30',
          cues: 'Legs-back-arms sequence. Strong leg drive. Maintain a consistent pace.',
        },
        {
          name: 'Kettlebell Swing',
          sets: 4,
          reps: '20',
          rest: '1:00',
          cues: 'Hinge hard, snap the hips. Bell floats to chest height. Arms are along for the ride.',
        },
        {
          name: 'Burpee',
          sets: 4,
          reps: '10',
          rest: '1:00',
          cues: 'Chest to floor, pop up, jump and clap. Speed matters — keep moving.',
        },
        {
          name: 'Battle Rope Alternating Waves',
          sets: 4,
          reps: '30 sec',
          rest: '0:45',
          cues: 'Small, fast movements from the shoulders. Stay low in an athletic stance.',
        },
        {
          name: 'Box Step-Up',
          sets: 3,
          reps: '12 each',
          rest: '1:00',
          cues: 'Drive through the lead leg. Don\'t push off the back foot. Full extension at the top.',
        },
      ],
      cooldown: '5 min: full body stretch',
    },
    {
      day: 'Day 4',
      title: 'Upper Pull + Power',
      warmup: '5 min: band pull-aparts, cat-cow, scapular push-ups, face pulls',
      duration: '55 min',
      exercises: [
        {
          name: 'Weighted Pull-Ups',
          sets: 4,
          reps: '6',
          rest: '2:30',
          cues: 'Full dead hang. Chest to bar. Slow negative — fight the way down.',
        },
        {
          name: 'Barbell Bent-Over Row',
          sets: 4,
          reps: '8',
          rest: '2:00',
          cues: '45-degree torso. Pull to lower chest. Squeeze the shoulder blades for a beat.',
        },
        {
          name: 'Dumbbell Hammer Curl',
          sets: 3,
          reps: '12',
          rest: '1:00',
          cues: 'Neutral grip, elbows pinned. No swinging — controlled reps.',
        },
        {
          name: 'Face Pull',
          sets: 3,
          reps: '15',
          rest: '1:00',
          cues: 'Pull to forehead. External rotate at the end. Squeeze rear delts hard.',
        },
        {
          name: 'Power Clean',
          sets: 4,
          reps: '4',
          rest: '2:30',
          cues: 'Triple extension — ankles, knees, hips. Catch in the front rack. Absorb in a quarter squat.',
        },
        {
          name: 'Med Ball Rotational Throw',
          sets: 3,
          reps: '8 each side',
          rest: '1:00',
          cues: 'Rotate from the hips, not the arms. Throw through the wall. Reset every rep.',
        },
      ],
      cooldown: '5 min: lat stretch, bicep stretch, thoracic extension over foam roller',
    },
    {
      day: 'Day 5',
      title: 'Lower Body Hypertrophy',
      warmup: '5 min: foam roll quads/glutes, hip circles, walking lunges, leg swings',
      duration: '50 min',
      exercises: [
        {
          name: 'Front Squat',
          sets: 4,
          reps: '8',
          rest: '2:00',
          cues: 'Elbows high. Sit between the hips. Drive up with authority.',
        },
        {
          name: 'Bulgarian Split Squat',
          sets: 3,
          reps: '10 each',
          rest: '1:30',
          cues: 'Rear foot on bench. Front knee over toes. Stay tall through the torso.',
        },
        {
          name: 'Hip Thrust',
          sets: 4,
          reps: '12',
          rest: '1:30',
          cues: 'Upper back on bench, feet flat. Drive through heels. Full hip extension, squeeze at top.',
        },
        {
          name: 'Leg Extension',
          sets: 3,
          reps: '15',
          rest: '1:00',
          cues: 'Full lockout at the top. 2 second hold. Slow negative.',
        },
        {
          name: 'Goblet Squat — 1.5 Reps',
          sets: 3,
          reps: '8',
          rest: '1:30',
          cues: 'Go all the way down, come halfway up, go back down, then stand. That\'s one rep.',
        },
        {
          name: 'Suitcase Carry',
          sets: 3,
          reps: '30 yards each hand',
          rest: '1:00',
          cues: 'One heavy dumbbell, stay perfectly upright. Don\'t lean. Core fights the offset.',
        },
      ],
      cooldown: '5 min: pigeon stretch, quad stretch, hamstring stretch',
    },
    {
      day: 'Day 6',
      title: 'Full Body Blast',
      warmup: '5 min: jump rope, inchworms, mountain climbers, high knees',
      duration: '45 min',
      exercises: [
        {
          name: 'Dumbbell Complex',
          sets: 4,
          reps: '6 each move',
          rest: '2:00',
          cues: 'Deadlift → Row → Clean → Press → Squat. No rest between moves. That\'s one set.',
        },
        {
          name: 'Assault Bike Sprint',
          sets: 5,
          reps: '20 sec max / 40 sec easy',
          rest: '0:00',
          cues: 'All-out for 20 seconds. True max effort. Recover at easy pace.',
        },
        {
          name: 'Wall Ball',
          sets: 4,
          reps: '15',
          rest: '1:00',
          cues: 'Deep squat, throw to target on the way up. Catch and squat in one motion.',
        },
        {
          name: 'Sled Push',
          sets: 3,
          reps: '40 yards',
          rest: '1:30',
          cues: 'Low body angle. Short, powerful steps. Arms locked out.',
        },
        {
          name: 'Plank to Push-Up',
          sets: 3,
          reps: '8 each arm lead',
          rest: '1:00',
          cues: 'Start on forearms, press up to hands one arm at a time. Keep hips level.',
        },
      ],
      cooldown: '10 min: full body stretch and foam roll. You earned it.',
    },
  ],
}

export const strengthProgram: Program = {
  id: 'strength',
  name: 'Strength',
  weeks: 4,
  frequency: '6x / week',
  description: 'Push. Pull. Legs. Repeat. Build serious strength and size.',
  category: 'strength',
  days: [
    {
      day: 'Day 1',
      title: 'Push — Strength',
      warmup: '5 min: band pull-aparts, arm circles, push-up walkouts, rotator cuff work',
      duration: '60 min',
      exercises: [
        {
          name: 'Barbell Bench Press',
          sets: 5,
          reps: '5',
          rest: '3:00',
          cues: 'Arch the upper back, not the lower. Bar touches mid-chest. Explode off the chest.',
        },
        {
          name: 'Overhead Press',
          sets: 4,
          reps: '6',
          rest: '2:30',
          cues: 'Strict press — no leg drive. Bar starts at chin, lock out overhead. Squeeze glutes.',
        },
        {
          name: 'Incline Dumbbell Press',
          sets: 3,
          reps: '10',
          rest: '1:30',
          cues: '30-degree bench. Full stretch at the bottom. Squeeze the chest at the top.',
        },
        {
          name: 'Dumbbell Lateral Raise',
          sets: 4,
          reps: '12',
          rest: '1:00',
          cues: 'Lead with the elbows. Raise to shoulder height. Controlled negative every rep.',
        },
        {
          name: 'Cable Tricep Pushdown',
          sets: 3,
          reps: '12',
          rest: '1:00',
          cues: 'Elbows pinned to sides. Full extension. Squeeze at the bottom.',
        },
        {
          name: 'Close-Grip Bench Press',
          sets: 3,
          reps: '8',
          rest: '1:30',
          cues: 'Hands shoulder-width. Elbows tucked close. Press through the triceps.',
        },
      ],
      cooldown: '5 min: chest stretch, shoulder stretch, tricep stretch',
    },
    {
      day: 'Day 2',
      title: 'Pull — Strength',
      warmup: '5 min: band pull-aparts, cat-cow, dead hangs, scap retractions',
      duration: '55 min',
      exercises: [
        {
          name: 'Barbell Deadlift',
          sets: 5,
          reps: '5',
          rest: '3:00',
          cues: 'Flat back, bar against shins. Drive through the floor. Lock hips and knees at the same time.',
        },
        {
          name: 'Weighted Pull-Ups',
          sets: 4,
          reps: '6',
          rest: '2:30',
          cues: 'Full hang to chest at bar. Slow negative. Add weight when you hit all reps.',
        },
        {
          name: 'Barbell Bent-Over Row',
          sets: 4,
          reps: '8',
          rest: '2:00',
          cues: '45-degree torso. Pull to lower chest. Squeeze for a beat at the top.',
        },
        {
          name: 'Cable Face Pull',
          sets: 3,
          reps: '15',
          rest: '1:00',
          cues: 'Pull to forehead, external rotate. Rear delts and upper back should be on fire.',
        },
        {
          name: 'Barbell Curl',
          sets: 3,
          reps: '10',
          rest: '1:00',
          cues: 'Strict form. No swinging the body. Squeeze at the top, slow negative.',
        },
        {
          name: 'Hammer Curl',
          sets: 3,
          reps: '12',
          rest: '1:00',
          cues: 'Neutral grip. Elbows locked. Work the brachialis — builds arm thickness.',
        },
      ],
      cooldown: '5 min: lat stretch, bicep stretch, lower back stretch',
    },
    {
      day: 'Day 3',
      title: 'Legs — Strength',
      warmup: '5 min: bodyweight squats, leg swings, hip circles, glute bridges, foam roll quads',
      duration: '60 min',
      exercises: [
        {
          name: 'Barbell Back Squat',
          sets: 5,
          reps: '5',
          rest: '3:00',
          cues: 'Big breath, brace hard. Break hips and knees together. Fight to keep the chest up.',
        },
        {
          name: 'Front Squat',
          sets: 3,
          reps: '6',
          rest: '2:30',
          cues: 'Elbows high, upper back tight. Sit straight down. Drive up through the heels.',
        },
        {
          name: 'Barbell Hip Thrust',
          sets: 4,
          reps: '10',
          rest: '1:30',
          cues: 'Upper back on bench. Drive through heels. Full hip extension — squeeze glutes at top.',
        },
        {
          name: 'Walking Lunge',
          sets: 3,
          reps: '10 each',
          rest: '1:30',
          cues: 'Dumbbells at sides. Long stride, back knee to floor. Controlled and upright.',
        },
        {
          name: 'Leg Curl',
          sets: 3,
          reps: '12',
          rest: '1:15',
          cues: 'Squeeze hard at the top. 3-second negative on every rep.',
        },
        {
          name: 'Standing Calf Raise',
          sets: 4,
          reps: '15',
          rest: '1:00',
          cues: 'Full stretch at the bottom. Pause at the top. Don\'t rush.',
        },
      ],
      cooldown: '5 min: pigeon stretch, quad stretch, hamstring stretch',
    },
    {
      day: 'Day 4',
      title: 'Push — Volume',
      warmup: '5 min: band pull-aparts, arm circles, light push-ups',
      duration: '55 min',
      exercises: [
        {
          name: 'Dumbbell Bench Press',
          sets: 4,
          reps: '10',
          tempo: '3-1-1-0',
          rest: '1:30',
          cues: 'Full stretch at the bottom. Squeeze the chest together at the top.',
        },
        {
          name: 'Dumbbell Arnold Press',
          sets: 4,
          reps: '10',
          rest: '1:30',
          cues: 'Start palms in, rotate as you press. Full lockout overhead.',
        },
        {
          name: 'Cable Fly',
          sets: 3,
          reps: '12',
          rest: '1:00',
          cues: 'Slight bend in elbows. Bring hands together at chest height. Squeeze the chest.',
        },
        {
          name: 'Dumbbell Front Raise',
          sets: 3,
          reps: '12',
          rest: '1:00',
          cues: 'Thumbs up, raise to eye level. Control the weight — don\'t swing.',
        },
        {
          name: 'Overhead Tricep Extension',
          sets: 3,
          reps: '12',
          rest: '1:00',
          cues: 'Dumbbell behind head, elbows forward. Extend fully. Feel the stretch.',
        },
        {
          name: 'Push-Up — Burnout',
          sets: 2,
          reps: 'Max reps',
          rest: '1:00',
          cues: 'Chest to the floor every rep. Drop to knees when you have to. Empty the tank.',
        },
      ],
      cooldown: '5 min: chest and shoulder stretching',
    },
    {
      day: 'Day 5',
      title: 'Pull — Volume',
      warmup: '5 min: band pull-aparts, scap push-ups, cat-cow, light rows',
      duration: '55 min',
      exercises: [
        {
          name: 'Chest-Supported Dumbbell Row',
          sets: 4,
          reps: '10',
          rest: '1:30',
          cues: 'Incline bench, chest down. Pull to hip, squeeze the back. No momentum.',
        },
        {
          name: 'Lat Pulldown',
          sets: 4,
          reps: '10',
          rest: '1:30',
          cues: 'Pull to upper chest. Lean back slightly. Squeeze the lats at the bottom.',
        },
        {
          name: 'Seated Cable Row',
          sets: 3,
          reps: '12',
          rest: '1:15',
          cues: 'Pull to belly button. Chest tall. Squeeze the shoulder blades together.',
        },
        {
          name: 'Reverse Fly',
          sets: 3,
          reps: '15',
          rest: '1:00',
          cues: 'Bent over, slight bend in elbows. Raise to shoulder height. Feel the rear delts.',
        },
        {
          name: 'Incline Dumbbell Curl',
          sets: 3,
          reps: '10',
          rest: '1:00',
          cues: 'Bench at 45 degrees. Full stretch at the bottom. Curl with intention.',
        },
        {
          name: 'Concentration Curl',
          sets: 3,
          reps: '10 each',
          rest: '1:00',
          cues: 'Elbow on inner thigh. Squeeze at the top. Slow negative.',
        },
      ],
      cooldown: '5 min: lat stretch, bicep stretch, foam roll upper back',
    },
    {
      day: 'Day 6',
      title: 'Legs — Power',
      warmup: '5 min: foam roll, leg swings, bodyweight squats, box jumps (low)',
      duration: '60 min',
      exercises: [
        {
          name: 'Box Squat',
          sets: 4,
          reps: '5',
          rest: '2:30',
          cues: 'Sit back to the box, pause, then explode up. Focus on power out of the hole.',
        },
        {
          name: 'Trap Bar Deadlift',
          sets: 4,
          reps: '5',
          rest: '2:30',
          cues: 'Neutral grip, push the floor away. Lock out hard. Reset every rep.',
        },
        {
          name: 'Leg Press',
          sets: 4,
          reps: '12',
          rest: '1:30',
          cues: 'Feet shoulder-width. Full depth without the lower back coming off the pad.',
        },
        {
          name: 'Bulgarian Split Squat',
          sets: 3,
          reps: '10 each',
          rest: '1:30',
          cues: 'Rear foot on bench. Drop straight down. Drive through the front heel.',
        },
        {
          name: 'Seated Calf Raise',
          sets: 4,
          reps: '15',
          rest: '1:00',
          cues: 'Full stretch, full squeeze. Slow reps build the soleus.',
        },
        {
          name: 'Ab Wheel Rollout',
          sets: 3,
          reps: '10',
          rest: '1:00',
          cues: 'Core tight, don\'t let the hips sag. Roll out as far as you can control.',
        },
      ],
      cooldown: '5 min: quad stretch, hamstring stretch, hip flexor stretch',
    },
  ],
}

export const hyroxProgram: Program = {
  id: 'hyrox',
  name: 'Hyrox',
  weeks: 4,
  frequency: '6x / week',
  description: 'Train for Hyrox. Running, rowing, sled, wall balls — race-ready conditioning.',
  category: 'conditioning',
  days: [
    {
      day: 'Day 1',
      title: 'Run + Sled Work',
      warmup: '10 min: easy jog, dynamic stretches, A-skips, high knees',
      duration: '50 min',
      exercises: [
        {
          name: '1km Run',
          sets: 1,
          reps: '1',
          rest: '2:00',
          cues: 'Race pace. Settle into your rhythm early. Breathe through the nose if you can.',
        },
        {
          name: 'Sled Push',
          sets: 4,
          reps: '50m',
          rest: '2:00',
          cues: 'Low angle, arms locked. Short, powerful steps. Don\'t stand up tall.',
        },
        {
          name: 'Sled Pull',
          sets: 4,
          reps: '50m',
          rest: '2:00',
          cues: 'Face the sled, pull hand over hand. Stay low, drive with the legs.',
        },
        {
          name: '800m Run',
          sets: 2,
          reps: '1',
          rest: '1:30',
          cues: 'Slightly faster than 1km pace. Practice running on tired legs.',
        },
        {
          name: 'Farmer\'s Carry',
          sets: 3,
          reps: '50m',
          rest: '1:30',
          cues: 'Heavy dumbbells. Tall posture, shoulders down. Grip training is race training.',
        },
      ],
      cooldown: '5 min: walk, calf stretch, quad stretch',
    },
    {
      day: 'Day 2',
      title: 'Upper Body Strength',
      warmup: '5 min: band pull-aparts, arm circles, push-up walkouts',
      duration: '50 min',
      exercises: [
        {
          name: 'Bench Press',
          sets: 4,
          reps: '8',
          rest: '2:00',
          cues: 'Controlled descent, explosive press. Shoulder blades tight, feet flat.',
        },
        {
          name: 'Barbell Bent-Over Row',
          sets: 4,
          reps: '8',
          rest: '2:00',
          cues: 'Pull to lower chest. Squeeze. Lower with control.',
        },
        {
          name: 'Dumbbell Shoulder Press',
          sets: 3,
          reps: '10',
          rest: '1:30',
          cues: 'Full lockout. Don\'t arch the back. Strong core.',
        },
        {
          name: 'Pull-Ups',
          sets: 4,
          reps: '8-10',
          rest: '1:30',
          cues: 'Full range. Dead hang to chin over bar. Build the engine that moves you.',
        },
        {
          name: 'Push-Up — Close Grip',
          sets: 3,
          reps: '15',
          rest: '1:00',
          cues: 'Hands under shoulders. Elbows stay tight. Tricep and chest endurance.',
        },
        {
          name: 'Plank Hold',
          sets: 3,
          reps: '60 sec',
          rest: '0:45',
          cues: 'Head to heels in a line. Breathe. Core doesn\'t quit.',
        },
      ],
      cooldown: '5 min: chest stretch, lat stretch, shoulder stretch',
    },
    {
      day: 'Day 3',
      title: 'Run + Row',
      warmup: '10 min: easy jog, leg swings, hip circles, build-up strides',
      duration: '50 min',
      exercises: [
        {
          name: '1km Run',
          sets: 3,
          reps: '1',
          rest: '1:30',
          cues: 'Consistent pace across all 3. Don\'t go out too hot. Negative split if possible.',
        },
        {
          name: 'Rowing Machine',
          sets: 4,
          reps: '1000m',
          rest: '2:00',
          cues: 'Legs-back-arms. Strong leg drive. Aim for a consistent split across all rounds.',
        },
        {
          name: 'Wall Ball',
          sets: 3,
          reps: '20',
          rest: '1:30',
          cues: 'Deep squat, throw on the way up. Catch and squat in one motion. Find a rhythm.',
        },
      ],
      cooldown: '5 min: hip flexor stretch, hamstring stretch, calf stretch',
    },
    {
      day: 'Day 4',
      title: 'Lower Body + Lunges',
      warmup: '5 min: foam roll, hip circles, bodyweight squats, glute bridges',
      duration: '55 min',
      exercises: [
        {
          name: 'Barbell Back Squat',
          sets: 4,
          reps: '8',
          rest: '2:00',
          cues: 'Full depth, controlled. Build the legs that carry you through the race.',
        },
        {
          name: 'Dumbbell Walking Lunge',
          sets: 4,
          reps: '20 each',
          rest: '2:00',
          cues: 'Hyrox lunge standard: long stride, back knee to floor. This is race practice.',
        },
        {
          name: 'Romanian Deadlift',
          sets: 3,
          reps: '10',
          rest: '1:30',
          cues: 'Hamstring stretch, glute squeeze. Protect the back — hinge, don\'t round.',
        },
        {
          name: 'Step-Up',
          sets: 3,
          reps: '12 each',
          rest: '1:15',
          cues: 'Drive through the lead leg. No push from the back foot. Full extension at top.',
        },
        {
          name: 'Calf Raise',
          sets: 3,
          reps: '20',
          rest: '1:00',
          cues: 'High reps for endurance. Full range. These save you in the last 2km.',
        },
        {
          name: 'Reverse Lunge — Tempo',
          sets: 3,
          reps: '8 each',
          tempo: '3-1-1-0',
          rest: '1:30',
          cues: 'Slow down, controlled up. Build stability and strength through the range.',
        },
      ],
      cooldown: '5 min: pigeon stretch, quad stretch, hip flexor stretch',
    },
    {
      day: 'Day 5',
      title: 'Race Simulation',
      warmup: '10 min: easy jog, dynamic stretches, practice transitions',
      duration: '60 min',
      exercises: [
        {
          name: '1km Run',
          sets: 1,
          reps: '1',
          rest: '0:30',
          cues: 'Race pace. This is the start — settle in fast.',
        },
        {
          name: 'SkiErg',
          sets: 1,
          reps: '1000m',
          rest: '0:30',
          cues: 'Full body pull. Hinge at the hips, drive with the lats. Pace it — it\'s early.',
        },
        {
          name: '1km Run',
          sets: 1,
          reps: '1',
          rest: '0:30',
          cues: 'Get back to pace quickly after the ski. Smooth turnover.',
        },
        {
          name: 'Sled Push',
          sets: 1,
          reps: '50m',
          rest: '0:30',
          cues: 'Low and fast. Arms locked, drive through the ground.',
        },
        {
          name: '1km Run',
          sets: 1,
          reps: '1',
          rest: '0:30',
          cues: 'Recover on the run. Legs are heavy — that\'s the point.',
        },
        {
          name: 'Sled Pull',
          sets: 1,
          reps: '50m',
          rest: '0:30',
          cues: 'Hand over hand. Stay low. Drive with the legs, not the arms.',
        },
        {
          name: 'Rowing Machine',
          sets: 1,
          reps: '1000m',
          rest: '0:30',
          cues: 'Legs are tired. That\'s race day. Strong strokes, efficient recovery.',
        },
        {
          name: 'Wall Ball',
          sets: 1,
          reps: '50',
          rest: '0:00',
          cues: 'Break it into sets of 10-15 if needed. Don\'t stop. Keep moving.',
        },
      ],
      cooldown: '10 min: walk, full body stretch. Recovery starts NOW.',
    },
    {
      day: 'Day 6',
      title: 'Recovery + Mobility',
      warmup: '5 min easy walk or light bike',
      duration: '35 min',
      exercises: [
        {
          name: 'Foam Roll — Full Body',
          sets: 1,
          reps: '90 sec each area',
          rest: '-',
          cues: 'Quads, hamstrings, glutes, IT band, calves, upper back, lats. Slow and thorough.',
        },
        {
          name: '90/90 Hip Stretch',
          sets: 2,
          reps: '60 sec each side',
          rest: '-',
          cues: 'Sit tall, lean into it. Your hips take a beating in Hyrox — give them love.',
        },
        {
          name: 'Pigeon Stretch',
          sets: 2,
          reps: '60 sec each side',
          rest: '-',
          cues: 'Front shin parallel to the body. Walk hands forward. Breathe into the stretch.',
        },
        {
          name: 'World\'s Greatest Stretch',
          sets: 2,
          reps: '5 each side',
          rest: '-',
          cues: 'Lunge, rotate, reach. Hit the hips, thoracic spine, and ankles all at once.',
        },
        {
          name: 'Calf + Achilles Stretch',
          sets: 2,
          reps: '45 sec each',
          rest: '-',
          cues: 'Wall lean — straight leg for gastroc, bent knee for soleus. Both matter.',
        },
        {
          name: 'Supine Spinal Twist',
          sets: 2,
          reps: '60 sec each side',
          rest: '-',
          cues: 'Knees stacked, arms out. Let gravity open you up.',
        },
        {
          name: 'Box Breathing',
          sets: 1,
          reps: '5 min',
          rest: '-',
          cues: '4 in, 4 hold, 4 out, 4 hold. Recovery is a skill. Train it.',
        },
      ],
    },
  ],
}

export const runningProgram: Program = {
  id: 'running',
  name: 'Running',
  weeks: 4,
  frequency: '3x / week',
  description: 'Speed work, threshold training, and long runs. Get faster, go farther.',
  category: 'running',
  days: [
    {
      day: 'Day 1',
      title: 'Speed + Track Work',
      warmup: '15 min: easy jog (1 mile), dynamic stretches, A-skips, B-skips, high knees, 4 × 100m strides building to 90%',
      duration: '55 min',
      exercises: [
        {
          name: '400m Repeat',
          sets: 6,
          reps: '1',
          rest: '1:30',
          cues: 'Run at your current mile pace. Relaxed shoulders, quick turnover. Each rep should feel controlled, not all-out.',
        },
        {
          name: '200m Sprint',
          sets: 4,
          reps: '1',
          rest: '1:00',
          cues: '90-95% effort. Drive your arms, stay tall. Focus on form even when tired.',
        },
        {
          name: '100m Stride',
          sets: 4,
          reps: '1',
          rest: '0:45',
          cues: 'Smooth acceleration to 85%. Feel the speed, don\'t force it. Walk back recovery.',
        },
        {
          name: 'Hill Sprint',
          sets: 4,
          reps: '60m',
          rest: '2:00',
          cues: 'Find a moderate hill. Drive the knees, pump the arms. Walk down for recovery. Power, not pace.',
        },
        {
          name: 'Core Circuit — Plank + Dead Bug + Bird Dog',
          sets: 2,
          reps: '30 sec each',
          rest: '0:30',
          cues: 'Running-specific core. Stable hips = faster legs. No rushing.',
        },
      ],
      cooldown: '10 min: easy jog (0.5 mile), calf stretch, hip flexor stretch, hamstring stretch, quad stretch',
    },
    {
      day: 'Day 2',
      title: 'Threshold + Tempo',
      warmup: '15 min: easy jog (1 mile), leg swings, hip circles, 4 × 100m strides at tempo effort',
      duration: '50 min',
      exercises: [
        {
          name: 'Tempo Run',
          sets: 1,
          reps: '20 min',
          rest: '-',
          cues: 'Comfortably hard — you can talk in short phrases but not full sentences. This is your lactate threshold pace. Stay steady, don\'t fade.',
        },
        {
          name: '1km Threshold Interval',
          sets: 3,
          reps: '1',
          rest: '2:00',
          cues: '10-15 seconds per mile faster than your tempo pace. Hold it steady through the full kilometer. Recovery is easy jogging.',
        },
        {
          name: 'Cruise Interval — 1 Mile',
          sets: 2,
          reps: '1',
          rest: '1:30',
          cues: 'Run at half-marathon effort. Controlled breathing. The goal is sustained speed, not a race. Jog the recovery.',
        },
        {
          name: 'Fartlek Finish',
          sets: 1,
          reps: '10 min',
          rest: '-',
          cues: 'Alternate 1 min hard / 1 min easy for 10 minutes. The hard portions should be faster than tempo. Finish strong.',
        },
      ],
      cooldown: '10 min: easy jog (0.5 mile), foam roll calves and quads, pigeon stretch, standing hamstring stretch',
    },
    {
      day: 'Day 3',
      title: 'Long Run + Endurance',
      warmup: '10 min: walk to easy jog, start slow and let the pace come to you. No stretching — warm up with the first mile.',
      duration: '60-90 min',
      exercises: [
        {
          name: 'Long Run',
          sets: 1,
          reps: '60-90 min',
          rest: '-',
          cues: 'Easy conversational pace for the first 75%. You should be able to hold a full conversation. The last 25%, pick it up to moderate effort. Finish stronger than you started.',
        },
        {
          name: 'Progression Miles (last 2 miles)',
          sets: 2,
          reps: '1 mile each',
          rest: '0:00',
          cues: 'Drop your pace by 15-20 seconds per mile for each of the last 2 miles. Simulate the end of a race. Practice closing hard.',
        },
        {
          name: 'Walking Cooldown',
          sets: 1,
          reps: '5 min',
          rest: '-',
          cues: 'Walk it out. Don\'t stop moving abruptly. Let your heart rate come down gradually.',
        },
        {
          name: 'Post-Run Stretch Routine',
          sets: 1,
          reps: '10 min',
          rest: '-',
          cues: 'Calves (30 sec each), hip flexors (30 sec each), hamstrings (30 sec each), quads (30 sec each), pigeon stretch (45 sec each). Hold each stretch — don\'t bounce.',
        },
        {
          name: 'Foam Roll — Legs',
          sets: 1,
          reps: '5 min',
          rest: '-',
          cues: 'Calves, IT band, quads, hamstrings, glutes. Slow passes. Spend extra time on tight spots. This is how you stay healthy.',
        },
      ],
      cooldown: 'Hydrate immediately. Refuel within 30 minutes — protein + carbs. Your next long run depends on today\'s recovery.',
    },
  ],
}

export const allPrograms: Program[] = [
  functionalFitnessProgram,
  runningProgram,
  hybridProgram,
  athleticProgram,
  strengthProgram,
  hyroxProgram,
  executiveProgram,
]

export function getProgram(identity: string): Program {
  return identity === 'athlete' ? athleticProgram : executiveProgram
}

export function getProgramById(id: string): Program | undefined {
  return allPrograms.find((p) => p.id === id)
}
