import type { Program } from './programs'

export const sprintProgram: Program = {
  id: 'sprint',
  name: 'CTC Speed',
  weeks: 6,
  frequency: '3x / week',
  description: '6-week sprint program. 40-yard dash to 400m — get faster, more explosive, and race-ready.',
  category: 'running',
  image: '/programs/sprint.jpg',
  days: [
    // ──────────────────────────────────────────────
    // WEEK 1 — MECHANICS & BASE SPEED
    // ──────────────────────────────────────────────
    {
      day: 'Day 1',
      title: 'W1 · Acceleration',
      warmup: '20 min dynamic warmup — cover 15 yards for each drill down and back.\n\nWALKING MOBILITY\nKnee pulls ×15 yards (hug one knee to your chest each step) · Quad pulls ×15 yards (grab your ankle behind you and pull heel to glute each step) · Scoops ×15 yards (scoop your leg up and across your body each step to open your hips) · Straight leg marches ×15 yards (kick one leg straight up and reach for your toes) · Figure 4 ×15 yards (pull your ankle to opposite knee and sit into a small squat each step) · Adductor stretch ×15 yards (wide steps, shifting side to side) · Walking lunges ×15 yards · Pogo hops — double leg ×15 yards, then single leg ×15 yards each\n\nRUNNING DRILLS — 15 yards each\nSkips with arm circles · Backwards run · High knees · Butt kicks · A-skips (drive one knee up with a skip) · B-skips (extend your leg out after the knee drive) · C-skips (sweeping leg motion) · D-skips (exaggerated bounding) · Lateral shuffles · Power lateral shuffles (explosive push-off) · Karaoke (grapevine)\n\nSPEED PREP — 15 yards each\nAnkle-calf-knee dribbles (quick choppy steps focusing on each joint) · Strikes short and long (snap your foot down under your hip with a paw-back motion) · Fast leg right and left (rapid single-leg turnover)\n\nGROUND ACTIVATION\n10 scorpions on your back (lie face up, swing one leg across to touch the opposite hand) · 10 scorpions on your stomach (lie face down, swing one leg across behind you) · 10 hip thrusts (bridge up squeezing glutes) · 10 fire hydrants each leg (on all fours, lift knee out to the side) · 10 squat jumps · 10 head-hip-trunk rotations (standing, rotate through each segment)\n\nBUILD-UPS\n3 sprints at 70-80%\n\nCORRECTIONAL BAND WORK — 2×10 each\nBanded lateral walks · Monster walks · Backwards walks',
      duration: '45 min',
      sections: [{'name':'Sprints','start':0}],
      exercises: [
        { name: '10-Yard Starts', sets: 6, reps: '10 yards', rest: '1:00 walk back', cues: 'This is your explosive first step. Start in a 2-point stance: feet staggered (one forward, one back), weight on the balls of your feet, lean forward slightly. On "go," drive your back knee forward and push hard off the ground. Stay low for the first 3-4 steps — don\'t stand up right away. Think "push the ground behind you." Walk back to rest. These teach you to accelerate out of a dead stop.' },
        { name: '20-Yard Sprint', sets: 6, reps: '20 yards', rest: '1:30 walk back', cues: 'Same explosive start, but now hold the acceleration for 20 yards. Your body should gradually rise from the low start position to full upright by about 15 yards. Pump your arms hard — your arms drive your legs. Keep your hands relaxed (don\'t clench your fists) and swing them from your hip to your chin. Walk back for full recovery between each rep.' },
        { name: '40-Yard Dash', sets: 4, reps: '40 yards', rest: '2:00 walk back', cues: 'The full 40. Explode out of your start, stay low for the first 10 yards, transition to upright sprinting by 20 yards, and hold top speed through 40. Focus on driving your knees up and striking the ground directly under your hips — not out in front of you (that\'s like hitting the brakes every step). Walk back and rest fully — speed training only works when you\'re fresh.' },
      ],
      cooldown: '5 min easy jog. Stretch your hip flexors (big lunge, push hips forward — 30 sec each), hamstrings (foot on a bench, lean forward — 30 sec each), quads (grab ankle behind you — 30 sec each), and calves (wall lean — 30 sec each).',
    },
    {
      day: 'Day 2',
      title: 'W1 · Speed Endurance',
      warmup: '20 min dynamic warmup — cover 15 yards for each drill down and back.\n\nWALKING MOBILITY\nKnee pulls ×15 yards (hug one knee to your chest each step) · Quad pulls ×15 yards (grab your ankle behind you and pull heel to glute each step) · Scoops ×15 yards (scoop your leg up and across your body each step to open your hips) · Straight leg marches ×15 yards (kick one leg straight up and reach for your toes) · Figure 4 ×15 yards (pull your ankle to opposite knee and sit into a small squat each step) · Adductor stretch ×15 yards (wide steps, shifting side to side) · Walking lunges ×15 yards · Pogo hops — double leg ×15 yards, then single leg ×15 yards each\n\nRUNNING DRILLS — 15 yards each\nSkips with arm circles · Backwards run · High knees · Butt kicks · A-skips (drive one knee up with a skip) · B-skips (extend your leg out after the knee drive) · C-skips (sweeping leg motion) · D-skips (exaggerated bounding) · Lateral shuffles · Power lateral shuffles (explosive push-off) · Karaoke (grapevine)\n\nSPEED PREP — 15 yards each\nAnkle-calf-knee dribbles (quick choppy steps focusing on each joint) · Strikes short and long (snap your foot down under your hip with a paw-back motion) · Fast leg right and left (rapid single-leg turnover)\n\nGROUND ACTIVATION\n10 scorpions on your back (lie face up, swing one leg across to touch the opposite hand) · 10 scorpions on your stomach (lie face down, swing one leg across behind you) · 10 hip thrusts (bridge up squeezing glutes) · 10 fire hydrants each leg (on all fours, lift knee out to the side) · 10 squat jumps · 10 head-hip-trunk rotations (standing, rotate through each segment)\n\nBUILD-UPS\n3 sprints at 70-80%\n\nCORRECTIONAL BAND WORK — 2×10 each\nBanded lateral walks · Monster walks · Backwards walks',
      duration: '45 min',
      sections: [{'name':'Speed Endurance','start':0}],
      exercises: [
        { name: '100m Sprint', sets: 4, reps: '100m (one straight of a track)', rest: '2:00 walk back', cues: '100 meters is one straight section of a track — takes about 13-18 seconds depending on your speed. The first 30m is acceleration (stay low, drive hard). The middle 40m is top speed (stand tall, fast arms, knees high). The last 30m is about holding your form when your body wants to tighten up — stay relaxed, especially in your face and shoulders. Walk the curve back to start for full recovery.' },
        { name: '200m Sprint', sets: 3, reps: '200m (half a lap)', rest: '3:00 walk', cues: '200 meters is half a lap — the full curve plus one straight. This is where you learn to hold speed when your muscles start burning. Run the curve by leaning slightly inward (like a motorcycle in a turn). When you hit the straight, open up your stride and drive hard to the finish. The last 50m will feel tough — don\'t let your form fall apart. Stay tall, keep pumping your arms. Walk for 3 full minutes between reps.' },
        { name: '4 × 50m Fly Sprint', sets: 4, reps: '50m at top speed', rest: '1:30 walk back', cues: '"Fly" means you jog in for 20m to build speed, then sprint the next 50m at your absolute maximum. This removes the acceleration phase and lets you practice pure top-end speed. Think: tall posture, fast arms, knees driving up, feet striking directly under your body. Your goal is to feel smooth at top speed, not tense. Fast looks easy — if you\'re grimacing, relax your face.' },
      ],
      cooldown: '5 min easy jog. Full stretch — hip flexors, hamstrings, quads, calves, glutes (sit on the ground, cross one ankle over the opposite knee, pull toward your chest — 30 sec each). Drink water.',
    },
    {
      day: 'Day 3',
      title: 'W1 · Power & Agility',
      warmup: '20 min dynamic warmup — cover 15 yards for each drill down and back.\n\nWALKING MOBILITY\nKnee pulls ×15 yards (hug one knee to your chest each step) · Quad pulls ×15 yards (grab your ankle behind you and pull heel to glute each step) · Scoops ×15 yards (scoop your leg up and across your body each step to open your hips) · Straight leg marches ×15 yards (kick one leg straight up and reach for your toes) · Figure 4 ×15 yards (pull your ankle to opposite knee and sit into a small squat each step) · Adductor stretch ×15 yards (wide steps, shifting side to side) · Walking lunges ×15 yards · Pogo hops — double leg ×15 yards, then single leg ×15 yards each\n\nRUNNING DRILLS — 15 yards each\nSkips with arm circles · Backwards run · High knees · Butt kicks · A-skips (drive one knee up with a skip) · B-skips (extend your leg out after the knee drive) · C-skips (sweeping leg motion) · D-skips (exaggerated bounding) · Lateral shuffles · Power lateral shuffles (explosive push-off) · Karaoke (grapevine)\n\nSPEED PREP — 15 yards each\nAnkle-calf-knee dribbles (quick choppy steps focusing on each joint) · Strikes short and long (snap your foot down under your hip with a paw-back motion) · Fast leg right and left (rapid single-leg turnover)\n\nGROUND ACTIVATION\n10 scorpions on your back (lie face up, swing one leg across to touch the opposite hand) · 10 scorpions on your stomach (lie face down, swing one leg across behind you) · 10 hip thrusts (bridge up squeezing glutes) · 10 fire hydrants each leg (on all fours, lift knee out to the side) · 10 squat jumps · 10 head-hip-trunk rotations (standing, rotate through each segment)\n\nBUILD-UPS\n3 sprints at 70-80%\n\nCORRECTIONAL BAND WORK — 2×10 each\nBanded lateral walks · Monster walks · Backwards walks',
      duration: '45 min',
      sections: [{'name':'Power','start':0},{'name':'Agility','start':1},{'name':'Conditioning','start':3}],
      exercises: [
        { name: 'Standing Broad Jump', sets: 5, reps: '3 jumps', rest: '1:00', cues: 'Stand with feet shoulder-width apart. Swing your arms back, bend your knees, then explode forward and upward — throw your arms forward as you jump. Land softly on both feet (bend your knees to absorb the landing). This builds the explosive power that makes you faster off the line. Try to jump a little farther each rep.' },
        { name: 'Lateral Shuffle Sprint', sets: 4, reps: '10 yards shuffle + 20 yards sprint', rest: '1:30', cues: 'Start in an athletic position (knees bent, weight on the balls of your feet). Shuffle sideways for 10 yards (don\'t cross your feet — push off with the trailing foot), then immediately turn and sprint 20 yards straight ahead. This trains your body to change direction and accelerate — exactly what you need in sports. Walk back to rest.' },
        { name: '3-Cone Drill (L-Drill)', sets: 4, reps: '1 full rep', rest: '2:00', cues: 'Set up 3 cones in an L-shape, each 5 yards apart. Start at cone 1: sprint to cone 2, touch the ground, sprint back to cone 1, touch the ground. Sprint back to cone 2, turn around it, sprint to cone 3, turn around cone 3, sprint back through cone 2 and finish at cone 1. Stay low on the turns, plant hard, and explode out. This drill tests and builds your ability to change direction at speed.' },
        { name: '60-Yard Shuttle', sets: 3, reps: '1 full rep (down and back × 3)', rest: '2:00', cues: 'Set two cones 10 yards apart. Sprint to the far cone and back — that\'s one trip (20 yards). Do 3 trips without stopping (60 yards total). Touch the ground at each cone. The key is your turns — get low, plant your outside foot hard, and push off explosively. Your lungs will burn — that\'s your body building the ability to recover between sprints.' },
      ],
      cooldown: '5 min walk. Full stretch — hip flexors, hamstrings, quads, calves, groin/adductors (sit with soles of your feet together, push knees toward the ground — 30 sec). Foam roll if available.',
    },

    // ──────────────────────────────────────────────
    // WEEK 2 — BUILD SPEED
    // ──────────────────────────────────────────────
    {
      day: 'Day 4',
      title: 'W2 · Acceleration',
      warmup: '20 min dynamic warmup — cover 15 yards for each drill down and back.\n\nWALKING MOBILITY\nKnee pulls ×15 yards (hug one knee to your chest each step) · Quad pulls ×15 yards (grab your ankle behind you and pull heel to glute each step) · Scoops ×15 yards (scoop your leg up and across your body each step to open your hips) · Straight leg marches ×15 yards (kick one leg straight up and reach for your toes) · Figure 4 ×15 yards (pull your ankle to opposite knee and sit into a small squat each step) · Adductor stretch ×15 yards (wide steps, shifting side to side) · Walking lunges ×15 yards · Pogo hops — double leg ×15 yards, then single leg ×15 yards each\n\nRUNNING DRILLS — 15 yards each\nSkips with arm circles · Backwards run · High knees · Butt kicks · A-skips (drive one knee up with a skip) · B-skips (extend your leg out after the knee drive) · C-skips (sweeping leg motion) · D-skips (exaggerated bounding) · Lateral shuffles · Power lateral shuffles (explosive push-off) · Karaoke (grapevine)\n\nSPEED PREP — 15 yards each\nAnkle-calf-knee dribbles (quick choppy steps focusing on each joint) · Strikes short and long (snap your foot down under your hip with a paw-back motion) · Fast leg right and left (rapid single-leg turnover)\n\nGROUND ACTIVATION\n10 scorpions on your back (lie face up, swing one leg across to touch the opposite hand) · 10 scorpions on your stomach (lie face down, swing one leg across behind you) · 10 hip thrusts (bridge up squeezing glutes) · 10 fire hydrants each leg (on all fours, lift knee out to the side) · 10 squat jumps · 10 head-hip-trunk rotations (standing, rotate through each segment)\n\nBUILD-UPS\n3 sprints at 70-80%\n\nCORRECTIONAL BAND WORK — 2×10 each\nBanded lateral walks · Monster walks · Backwards walks',
      duration: '48 min',
      sections: [{'name':'Sprints','start':0}],
      exercises: [
        { name: '10-Yard Starts — 3-Point Stance', sets: 6, reps: '10 yards', rest: '1:00 walk back', cues: 'This week, try a 3-point stance: one hand on the ground (same side as your back foot), other arm cocked back. Weight forward over your hand. On "go," drive out low and hard. The hand on the ground lets you lean further forward, which means more explosive acceleration. Stay low for the first 4 steps. Power comes from pushing backward against the ground, not reaching forward with your feet.' },
        { name: '30-Yard Sprint', sets: 6, reps: '30 yards', rest: '1:30 walk back', cues: '10 yards longer than last week. Focus on the transition from low acceleration (first 10 yards) to upright sprinting (last 20 yards). This transition should feel smooth, not sudden — your body gradually rises as you build speed. Pump your arms the entire time. Each rep should feel faster and smoother than the last. Full recovery between reps.' },
        { name: '40-Yard Dash', sets: 5, reps: '40 yards', rest: '2:00 walk back', cues: 'One more rep than last week. By now your start should feel more natural. Focus on two things: explosive first 3 steps, and holding your speed through the last 10 yards. If you have a stopwatch, time yourself — but don\'t sacrifice form for time. A smooth 40 is always faster than a sloppy one.' },
      ],
      cooldown: '5 min easy jog. Full stretch — hip flexors, hamstrings, quads, calves (30 sec each side).',
    },
    {
      day: 'Day 5',
      title: 'W2 · Speed Endurance',
      warmup: '20 min dynamic warmup — cover 15 yards for each drill down and back.\n\nWALKING MOBILITY\nKnee pulls ×15 yards (hug one knee to your chest each step) · Quad pulls ×15 yards (grab your ankle behind you and pull heel to glute each step) · Scoops ×15 yards (scoop your leg up and across your body each step to open your hips) · Straight leg marches ×15 yards (kick one leg straight up and reach for your toes) · Figure 4 ×15 yards (pull your ankle to opposite knee and sit into a small squat each step) · Adductor stretch ×15 yards (wide steps, shifting side to side) · Walking lunges ×15 yards · Pogo hops — double leg ×15 yards, then single leg ×15 yards each\n\nRUNNING DRILLS — 15 yards each\nSkips with arm circles · Backwards run · High knees · Butt kicks · A-skips (drive one knee up with a skip) · B-skips (extend your leg out after the knee drive) · C-skips (sweeping leg motion) · D-skips (exaggerated bounding) · Lateral shuffles · Power lateral shuffles (explosive push-off) · Karaoke (grapevine)\n\nSPEED PREP — 15 yards each\nAnkle-calf-knee dribbles (quick choppy steps focusing on each joint) · Strikes short and long (snap your foot down under your hip with a paw-back motion) · Fast leg right and left (rapid single-leg turnover)\n\nGROUND ACTIVATION\n10 scorpions on your back (lie face up, swing one leg across to touch the opposite hand) · 10 scorpions on your stomach (lie face down, swing one leg across behind you) · 10 hip thrusts (bridge up squeezing glutes) · 10 fire hydrants each leg (on all fours, lift knee out to the side) · 10 squat jumps · 10 head-hip-trunk rotations (standing, rotate through each segment)\n\nBUILD-UPS\n3 sprints at 70-80%\n\nCORRECTIONAL BAND WORK — 2×10 each\nBanded lateral walks · Monster walks · Backwards walks',
      duration: '50 min',
      sections: [{'name':'Speed Endurance','start':0}],
      exercises: [
        { name: '100m Sprint', sets: 5, reps: '100m', rest: '2:00 walk back', cues: 'One more rep than last week. By now you should notice the 3 phases more clearly: acceleration (first 30m — stay low), top speed (middle 40m — tall and fast), and speed maintenance (last 30m — hold form). The third phase is where races are won and lost. When you feel yourself tightening up, consciously relax your shoulders and hands. Speed comes from relaxation, not tension.' },
        { name: '200m Sprint', sets: 3, reps: '200m', rest: '3:00 walk', cues: 'Half a lap. Same as last week but it should feel more controlled. On the curve, shorten your stride slightly and lean in. On the straight, open up and drive. The last 50m is about mental toughness — your legs will want to slow down but you decide when to stop pushing. Hold your form all the way through the finish line.' },
        { name: '4 × 60m Fly Sprint', sets: 4, reps: '60m at top speed', rest: '2:00 walk back', cues: 'Jog in for 20m to build up speed, then sprint 60m at maximum effort (10m longer than last week). The extra distance forces you to hold top speed a little longer. Focus on feeling smooth and effortless at max speed. If your head is bouncing up and down, you\'re wasting energy — try to glide forward. Walk back for full recovery.' },
      ],
      cooldown: '5 min easy jog. Full stretch — hip flexors, hamstrings, quads, calves, glutes (30 sec each). Hydrate.',
    },
    {
      day: 'Day 6',
      title: 'W2 · Power & Agility',
      warmup: '20 min dynamic warmup — cover 15 yards for each drill down and back.\n\nWALKING MOBILITY\nKnee pulls ×15 yards (hug one knee to your chest each step) · Quad pulls ×15 yards (grab your ankle behind you and pull heel to glute each step) · Scoops ×15 yards (scoop your leg up and across your body each step to open your hips) · Straight leg marches ×15 yards (kick one leg straight up and reach for your toes) · Figure 4 ×15 yards (pull your ankle to opposite knee and sit into a small squat each step) · Adductor stretch ×15 yards (wide steps, shifting side to side) · Walking lunges ×15 yards · Pogo hops — double leg ×15 yards, then single leg ×15 yards each\n\nRUNNING DRILLS — 15 yards each\nSkips with arm circles · Backwards run · High knees · Butt kicks · A-skips (drive one knee up with a skip) · B-skips (extend your leg out after the knee drive) · C-skips (sweeping leg motion) · D-skips (exaggerated bounding) · Lateral shuffles · Power lateral shuffles (explosive push-off) · Karaoke (grapevine)\n\nSPEED PREP — 15 yards each\nAnkle-calf-knee dribbles (quick choppy steps focusing on each joint) · Strikes short and long (snap your foot down under your hip with a paw-back motion) · Fast leg right and left (rapid single-leg turnover)\n\nGROUND ACTIVATION\n10 scorpions on your back (lie face up, swing one leg across to touch the opposite hand) · 10 scorpions on your stomach (lie face down, swing one leg across behind you) · 10 hip thrusts (bridge up squeezing glutes) · 10 fire hydrants each leg (on all fours, lift knee out to the side) · 10 squat jumps · 10 head-hip-trunk rotations (standing, rotate through each segment)\n\nBUILD-UPS\n3 sprints at 70-80%\n\nCORRECTIONAL BAND WORK — 2×10 each\nBanded lateral walks · Monster walks · Backwards walks',
      duration: '48 min',
      sections: [{'name':'Power','start':0},{'name':'Agility','start':1},{'name':'Speed Endurance','start':3}],
      exercises: [
        { name: 'Single Leg Bound', sets: 4, reps: '5 bounds each leg', rest: '1:00', cues: 'Stand on one leg. Jump forward as far as you can, landing on the SAME foot. That\'s 1 bound — do 5 in a row on each leg. Swing your arms to help propel you forward. This builds single-leg explosive power, which is exactly what sprinting is — you\'re only ever on one foot at a time. Land softly by bending your knee on each landing.' },
        { name: 'Pro Agility (5-10-5)', sets: 5, reps: '1 full rep', rest: '2:00', cues: 'Set 3 cones in a line, 5 yards apart. Start at the middle cone in an athletic stance. Sprint 5 yards to one side, touch the ground. Sprint 10 yards to the other side, touch the ground. Sprint 5 yards back through the middle. Stay low on the turns — the lower you are, the faster you can change direction. Your first step out of each turn is the most important — explode out of it.' },
        { name: 'Box Jump', sets: 4, reps: '5 jumps', rest: '1:30', cues: 'Stand facing a sturdy box, bench, or step (start with a height that feels challenging but safe — 12-20 inches). Swing your arms back, bend your knees, then jump up and land on top of the box with both feet. Stand up fully at the top. Step down (don\'t jump down — protects your joints). These build the explosive hip and leg power that drives your sprint speed.' },
        { name: '150m Sprint', sets: 3, reps: '150m', rest: '2:30 walk', cues: 'This is 3/8 of a lap — longer than 100m but shorter than 200m. It\'s the "in-between" distance that builds your ability to hold speed. Sprint at about 90% effort. The last 50m should feel hard but controlled. Don\'t let your form break down — if you start hunching over or flailing your arms, focus on standing tall and driving your knees. Walk for 2.5 minutes between reps.' },
      ],
      cooldown: '5 min walk. Full stretch — hip flexors, hamstrings, quads, calves, groin, glutes (30 sec each). Foam roll if available.',
    },

    // ──────────────────────────────────────────────
    // WEEK 3 — REFINE & PUSH
    // ──────────────────────────────────────────────
    {
      day: 'Day 7',
      title: 'W3 · Acceleration',
      warmup: '20 min dynamic warmup — cover 15 yards for each drill down and back.\n\nWALKING MOBILITY\nKnee pulls ×15 yards (hug one knee to your chest each step) · Quad pulls ×15 yards (grab your ankle behind you and pull heel to glute each step) · Scoops ×15 yards (scoop your leg up and across your body each step to open your hips) · Straight leg marches ×15 yards (kick one leg straight up and reach for your toes) · Figure 4 ×15 yards (pull your ankle to opposite knee and sit into a small squat each step) · Adductor stretch ×15 yards (wide steps, shifting side to side) · Walking lunges ×15 yards · Pogo hops — double leg ×15 yards, then single leg ×15 yards each\n\nRUNNING DRILLS — 15 yards each\nSkips with arm circles · Backwards run · High knees · Butt kicks · A-skips (drive one knee up with a skip) · B-skips (extend your leg out after the knee drive) · C-skips (sweeping leg motion) · D-skips (exaggerated bounding) · Lateral shuffles · Power lateral shuffles (explosive push-off) · Karaoke (grapevine)\n\nSPEED PREP — 15 yards each\nAnkle-calf-knee dribbles (quick choppy steps focusing on each joint) · Strikes short and long (snap your foot down under your hip with a paw-back motion) · Fast leg right and left (rapid single-leg turnover)\n\nGROUND ACTIVATION\n10 scorpions on your back (lie face up, swing one leg across to touch the opposite hand) · 10 scorpions on your stomach (lie face down, swing one leg across behind you) · 10 hip thrusts (bridge up squeezing glutes) · 10 fire hydrants each leg (on all fours, lift knee out to the side) · 10 squat jumps · 10 head-hip-trunk rotations (standing, rotate through each segment)\n\nBUILD-UPS\n3 sprints at 70-80%\n\nCORRECTIONAL BAND WORK — 2×10 each\nBanded lateral walks · Monster walks · Backwards walks',
      duration: '50 min',
      sections: [{'name':'Sprints','start':0}],
      exercises: [
        { name: 'Block Start or 3-Point Start', sets: 6, reps: '10 yards', rest: '1:00 walk back', cues: 'If you have access to starting blocks, use them. If not, use the 3-point stance from last week. Focus on your first 3 steps — they should be short, powerful, and low to the ground. Your shin angle should match the angle of your body lean (about 45 degrees). Think about driving your knees forward and pushing the ground behind you. Power from the hips, not the ankles.' },
        { name: '30-Yard Sprint — Timed', sets: 5, reps: '30 yards', rest: '1:30 walk back', cues: 'Time these if you can (phone stopwatch or a friend). Knowing your time gives you a target to beat. Focus on an explosive start and smooth transition to upright sprinting. Don\'t look at your phone mid-sprint — have someone else time you or check it after. Every rep is a chance to get faster.' },
        { name: '40-Yard Dash — Timed', sets: 5, reps: '40 yards', rest: '2:00 walk back', cues: 'Time these too. Your best 40 from today is your baseline for the rest of the program. Focus on the things you\'ve learned: explosive start, stay low for 10 yards, smooth transition to upright, hold speed through 40. Relax your jaw, relax your hands, pump your arms. The fastest sprinters look the most relaxed.' },
      ],
      cooldown: '5 min easy jog. Full stretch (30 sec each side). Write down your best 40 time — you\'re going to beat it.',
    },
    {
      day: 'Day 8',
      title: 'W3 · Speed Endurance',
      warmup: '20 min dynamic warmup — cover 15 yards for each drill down and back.\n\nWALKING MOBILITY\nKnee pulls ×15 yards (hug one knee to your chest each step) · Quad pulls ×15 yards (grab your ankle behind you and pull heel to glute each step) · Scoops ×15 yards (scoop your leg up and across your body each step to open your hips) · Straight leg marches ×15 yards (kick one leg straight up and reach for your toes) · Figure 4 ×15 yards (pull your ankle to opposite knee and sit into a small squat each step) · Adductor stretch ×15 yards (wide steps, shifting side to side) · Walking lunges ×15 yards · Pogo hops — double leg ×15 yards, then single leg ×15 yards each\n\nRUNNING DRILLS — 15 yards each\nSkips with arm circles · Backwards run · High knees · Butt kicks · A-skips (drive one knee up with a skip) · B-skips (extend your leg out after the knee drive) · C-skips (sweeping leg motion) · D-skips (exaggerated bounding) · Lateral shuffles · Power lateral shuffles (explosive push-off) · Karaoke (grapevine)\n\nSPEED PREP — 15 yards each\nAnkle-calf-knee dribbles (quick choppy steps focusing on each joint) · Strikes short and long (snap your foot down under your hip with a paw-back motion) · Fast leg right and left (rapid single-leg turnover)\n\nGROUND ACTIVATION\n10 scorpions on your back (lie face up, swing one leg across to touch the opposite hand) · 10 scorpions on your stomach (lie face down, swing one leg across behind you) · 10 hip thrusts (bridge up squeezing glutes) · 10 fire hydrants each leg (on all fours, lift knee out to the side) · 10 squat jumps · 10 head-hip-trunk rotations (standing, rotate through each segment)\n\nBUILD-UPS\n3 sprints at 70-80%\n\nCORRECTIONAL BAND WORK — 2×10 each\nBanded lateral walks · Monster walks · Backwards walks',
      duration: '50 min',
      sections: [{'name':'Speed Endurance','start':0}],
      exercises: [
        { name: '150m Sprint', sets: 4, reps: '150m', rest: '2:30 walk', cues: 'One more rep than last week. 150 meters at 90-95% effort. This distance is long enough to build endurance but short enough that you should be sprinting, not jogging. Focus on the last 50m — that\'s where you win. Stay tall, keep your arms pumping, and don\'t let your stride get sloppy. When it burns, push through it.' },
        { name: '200m Sprint', sets: 3, reps: '200m', rest: '3:00 walk', cues: 'Half a lap. Run the curve with a slight inward lean, then attack the straight. By Week 3, your body should be more efficient at this distance. Pay attention to how you feel in the last 50m compared to Week 1 — you should be holding your form better. That\'s fitness.' },
        { name: '60m Fly Sprint', sets: 4, reps: '60m at max', rest: '2:00 walk back', cues: 'Jog 20m to build speed, then give 100% effort for 60m. These are your top-speed reps. Focus on feeling fast AND smooth. Quick arm pumps, high knee drive, feet striking under your hips. If you feel like you\'re straining, you\'re trying too hard with the wrong muscles — speed is about coordination, not brute force. Relax and let it flow.' },
      ],
      cooldown: '5 min easy jog. Full stretch. Hydrate well — speed work takes more out of you than you think.',
    },
    {
      day: 'Day 9',
      title: 'W3 · Power & Agility',
      warmup: '20 min dynamic warmup — cover 15 yards for each drill down and back.\n\nWALKING MOBILITY\nKnee pulls ×15 yards (hug one knee to your chest each step) · Quad pulls ×15 yards (grab your ankle behind you and pull heel to glute each step) · Scoops ×15 yards (scoop your leg up and across your body each step to open your hips) · Straight leg marches ×15 yards (kick one leg straight up and reach for your toes) · Figure 4 ×15 yards (pull your ankle to opposite knee and sit into a small squat each step) · Adductor stretch ×15 yards (wide steps, shifting side to side) · Walking lunges ×15 yards · Pogo hops — double leg ×15 yards, then single leg ×15 yards each\n\nRUNNING DRILLS — 15 yards each\nSkips with arm circles · Backwards run · High knees · Butt kicks · A-skips (drive one knee up with a skip) · B-skips (extend your leg out after the knee drive) · C-skips (sweeping leg motion) · D-skips (exaggerated bounding) · Lateral shuffles · Power lateral shuffles (explosive push-off) · Karaoke (grapevine)\n\nSPEED PREP — 15 yards each\nAnkle-calf-knee dribbles (quick choppy steps focusing on each joint) · Strikes short and long (snap your foot down under your hip with a paw-back motion) · Fast leg right and left (rapid single-leg turnover)\n\nGROUND ACTIVATION\n10 scorpions on your back (lie face up, swing one leg across to touch the opposite hand) · 10 scorpions on your stomach (lie face down, swing one leg across behind you) · 10 hip thrusts (bridge up squeezing glutes) · 10 fire hydrants each leg (on all fours, lift knee out to the side) · 10 squat jumps · 10 head-hip-trunk rotations (standing, rotate through each segment)\n\nBUILD-UPS\n3 sprints at 70-80%\n\nCORRECTIONAL BAND WORK — 2×10 each\nBanded lateral walks · Monster walks · Backwards walks',
      duration: '50 min',
      sections: [{'name':'Power','start':0},{'name':'Agility','start':1},{'name':'Speed Endurance','start':3}],
      exercises: [
        { name: 'Depth Jump to Sprint', sets: 4, reps: '3 reps', rest: '2:00', cues: 'Stand on a low box or step (12-18 inches). Step off (don\'t jump off) and land on both feet. The instant your feet hit the ground, explode into a 10-yard sprint. The point is to spend as little time on the ground as possible after landing — touch and go. This trains your muscles to react explosively, which is exactly what happens during the start of a sprint. Walk back to rest.' },
        { name: 'T-Drill', sets: 4, reps: '1 full rep', rest: '2:00', cues: 'Set 4 cones in a T-shape: one at the start, one 10 yards ahead, one 5 yards to the left of that, one 5 yards to the right. Sprint from start to the center cone, shuffle left to the left cone, shuffle right all the way to the right cone, shuffle back to center, then backpedal to the start. Stay low on every change of direction. This builds the multi-directional speed that makes you dangerous in any sport.' },
        { name: 'Bounding', sets: 4, reps: '30 yards', rest: '1:30', cues: 'Bounding is exaggerated running — big, powerful strides where you drive your knee high and push hard off the ground. Think of it as running in slow motion but with maximum power on every step. Swing your arms big to match your legs. This builds the explosive stride power that makes your sprint longer and more powerful. 30 yards is about 10-12 bounds.' },
        { name: '300m Sprint', sets: 2, reps: '300m (3/4 of a lap)', rest: '3:00 walk', cues: 'This is the longest sprint in the program this week. 300m at about 85% effort — fast but not all-out. This builds the endurance to hold your speed over longer distances. The last 100m will be the hardest part. Focus on maintaining your form: tall posture, arm drive, knee lift. Don\'t let yourself jog the finish — sprint through it. Walk for 3 full minutes between reps.' },
      ],
      cooldown: '5 min walk. Full stretch — hip flexors, hamstrings, quads, calves, groin, glutes (30 sec each). This was a tough day — rest well tonight.',
    },

    // ──────────────────────────────────────────────
    // WEEK 4 — PEAK SPEED
    // ──────────────────────────────────────────────
    {
      day: 'Day 10',
      title: 'W4 · Acceleration',
      warmup: '20 min dynamic warmup — cover 15 yards for each drill down and back.\n\nWALKING MOBILITY\nKnee pulls ×15 yards (hug one knee to your chest each step) · Quad pulls ×15 yards (grab your ankle behind you and pull heel to glute each step) · Scoops ×15 yards (scoop your leg up and across your body each step to open your hips) · Straight leg marches ×15 yards (kick one leg straight up and reach for your toes) · Figure 4 ×15 yards (pull your ankle to opposite knee and sit into a small squat each step) · Adductor stretch ×15 yards (wide steps, shifting side to side) · Walking lunges ×15 yards · Pogo hops — double leg ×15 yards, then single leg ×15 yards each\n\nRUNNING DRILLS — 15 yards each\nSkips with arm circles · Backwards run · High knees · Butt kicks · A-skips (drive one knee up with a skip) · B-skips (extend your leg out after the knee drive) · C-skips (sweeping leg motion) · D-skips (exaggerated bounding) · Lateral shuffles · Power lateral shuffles (explosive push-off) · Karaoke (grapevine)\n\nSPEED PREP — 15 yards each\nAnkle-calf-knee dribbles (quick choppy steps focusing on each joint) · Strikes short and long (snap your foot down under your hip with a paw-back motion) · Fast leg right and left (rapid single-leg turnover)\n\nGROUND ACTIVATION\n10 scorpions on your back (lie face up, swing one leg across to touch the opposite hand) · 10 scorpions on your stomach (lie face down, swing one leg across behind you) · 10 hip thrusts (bridge up squeezing glutes) · 10 fire hydrants each leg (on all fours, lift knee out to the side) · 10 squat jumps · 10 head-hip-trunk rotations (standing, rotate through each segment)\n\nBUILD-UPS\n3 sprints at 70-80%\n\nCORRECTIONAL BAND WORK — 2×10 each\nBanded lateral walks · Monster walks · Backwards walks',
      duration: '50 min',
      sections: [{'name':'Sprints','start':0}],
      exercises: [
        { name: '10-Yard Starts — Reaction', sets: 6, reps: '10 yards', rest: '1:00 walk back', cues: 'This week, add a reaction element. Have a friend clap or shout "go" at a random time (don\'t count down). Start from your 3-point stance and explode when you hear the signal. In real competition, you don\'t get to go when you\'re ready — you go when the signal fires. Reacting quickly is a skill you can train. Stay loaded and ready. First step wins.' },
        { name: '40-Yard Dash — Timed', sets: 6, reps: '40 yards', rest: '2:00 walk back', cues: 'Your peak 40-yard session. 6 reps — each one is a chance to set your best time. Compare to your Week 3 times. Focus on the things that make the biggest difference: explosive first step, stay low through 10 yards, drive your arms hard, and hold your speed through the finish. Don\'t slow down before the line — sprint through it like the line is 5 yards past the actual cone.' },
        { name: '60-Yard Sprint', sets: 4, reps: '60 yards', rest: '2:00 walk back', cues: '60 yards extends the 40 — now you need to accelerate AND hold top speed for an extra 20 yards. The first 40 yards should feel like your regular 40-yard dash. The last 20 yards are about maintaining that speed without decelerating. This is what separates fast starters from truly fast athletes. Stay relaxed, stay tall, keep driving.' },
      ],
      cooldown: '5 min easy jog. Full stretch (30 sec each side). Record your best 40 time — is it faster than Week 3?',
    },
    {
      day: 'Day 11',
      title: 'W4 · Speed Endurance',
      warmup: '20 min dynamic warmup — cover 15 yards for each drill down and back.\n\nWALKING MOBILITY\nKnee pulls ×15 yards (hug one knee to your chest each step) · Quad pulls ×15 yards (grab your ankle behind you and pull heel to glute each step) · Scoops ×15 yards (scoop your leg up and across your body each step to open your hips) · Straight leg marches ×15 yards (kick one leg straight up and reach for your toes) · Figure 4 ×15 yards (pull your ankle to opposite knee and sit into a small squat each step) · Adductor stretch ×15 yards (wide steps, shifting side to side) · Walking lunges ×15 yards · Pogo hops — double leg ×15 yards, then single leg ×15 yards each\n\nRUNNING DRILLS — 15 yards each\nSkips with arm circles · Backwards run · High knees · Butt kicks · A-skips (drive one knee up with a skip) · B-skips (extend your leg out after the knee drive) · C-skips (sweeping leg motion) · D-skips (exaggerated bounding) · Lateral shuffles · Power lateral shuffles (explosive push-off) · Karaoke (grapevine)\n\nSPEED PREP — 15 yards each\nAnkle-calf-knee dribbles (quick choppy steps focusing on each joint) · Strikes short and long (snap your foot down under your hip with a paw-back motion) · Fast leg right and left (rapid single-leg turnover)\n\nGROUND ACTIVATION\n10 scorpions on your back (lie face up, swing one leg across to touch the opposite hand) · 10 scorpions on your stomach (lie face down, swing one leg across behind you) · 10 hip thrusts (bridge up squeezing glutes) · 10 fire hydrants each leg (on all fours, lift knee out to the side) · 10 squat jumps · 10 head-hip-trunk rotations (standing, rotate through each segment)\n\nBUILD-UPS\n3 sprints at 70-80%\n\nCORRECTIONAL BAND WORK — 2×10 each\nBanded lateral walks · Monster walks · Backwards walks',
      duration: '55 min',
      sections: [{'name':'Speed Endurance','start':0}],
      exercises: [
        { name: '200m Sprint', sets: 4, reps: '200m', rest: '3:00 walk', cues: 'One more rep than previous weeks. By now, 200m should feel like a distance you know well. Attack the curve, open up on the straight. Your goal this week: the last 50m should look as smooth as the first 50m. That\'s the real test — not how fast you start, but how well you finish.' },
        { name: '300m Sprint', sets: 3, reps: '300m', rest: '3:30 walk', cues: '300m at 85-90% effort. This is the toughest speed endurance distance. Break it into thirds mentally: the first 100m is building speed, the middle 100m is holding, the last 100m is competing against the voice in your head that says slow down. Don\'t listen to it. Push through with good form. Walk for 3.5 minutes between reps — you need the full recovery.' },
        { name: '400m Sprint', sets: 2, reps: '400m (1 full lap)', rest: '4:00 walk', cues: 'One full lap — the longest sprint distance. This is a controlled effort: go out at 85% for the first 200m, then push harder for the second 200m. The last 100m will burn. Your legs will feel heavy. THIS is where mental toughness is built. Hold your form: tall posture, drive your arms, keep your knees up. Don\'t let your stride get short and shuffly. Walk for 4 full minutes between reps.' },
      ],
      cooldown: '5 min easy jog. Full stretch — spend extra time on hamstrings and hip flexors. Drink water. This was a big session.',
    },
    {
      day: 'Day 12',
      title: 'W4 · Power & Agility',
      warmup: '20 min dynamic warmup — cover 15 yards for each drill down and back.\n\nWALKING MOBILITY\nKnee pulls ×15 yards (hug one knee to your chest each step) · Quad pulls ×15 yards (grab your ankle behind you and pull heel to glute each step) · Scoops ×15 yards (scoop your leg up and across your body each step to open your hips) · Straight leg marches ×15 yards (kick one leg straight up and reach for your toes) · Figure 4 ×15 yards (pull your ankle to opposite knee and sit into a small squat each step) · Adductor stretch ×15 yards (wide steps, shifting side to side) · Walking lunges ×15 yards · Pogo hops — double leg ×15 yards, then single leg ×15 yards each\n\nRUNNING DRILLS — 15 yards each\nSkips with arm circles · Backwards run · High knees · Butt kicks · A-skips (drive one knee up with a skip) · B-skips (extend your leg out after the knee drive) · C-skips (sweeping leg motion) · D-skips (exaggerated bounding) · Lateral shuffles · Power lateral shuffles (explosive push-off) · Karaoke (grapevine)\n\nSPEED PREP — 15 yards each\nAnkle-calf-knee dribbles (quick choppy steps focusing on each joint) · Strikes short and long (snap your foot down under your hip with a paw-back motion) · Fast leg right and left (rapid single-leg turnover)\n\nGROUND ACTIVATION\n10 scorpions on your back (lie face up, swing one leg across to touch the opposite hand) · 10 scorpions on your stomach (lie face down, swing one leg across behind you) · 10 hip thrusts (bridge up squeezing glutes) · 10 fire hydrants each leg (on all fours, lift knee out to the side) · 10 squat jumps · 10 head-hip-trunk rotations (standing, rotate through each segment)\n\nBUILD-UPS\n3 sprints at 70-80%\n\nCORRECTIONAL BAND WORK — 2×10 each\nBanded lateral walks · Monster walks · Backwards walks',
      duration: '50 min',
      sections: [{'name':'Power','start':0},{'name':'Agility','start':1},{'name':'Speed Endurance','start':2}],
      exercises: [
        { name: 'Sprint—Backpedal—Sprint', sets: 5, reps: '10 yd sprint + 5 yd backpedal + 10 yd sprint', rest: '1:30', cues: 'Sprint 10 yards forward, immediately transition to a 5-yard backpedal (run backward — stay on the balls of your feet, keep your hips low), then immediately sprint forward 10 more yards. The transitions are the key — how fast can you stop, reverse, and accelerate again? Stay low during the direction changes. This is pure sport speed.' },
        { name: 'Single Leg Hop (Distance)', sets: 4, reps: '3 hops each leg', rest: '1:30', cues: 'Stand on one foot. Hop forward for distance — 3 big hops in a row, each one as far as you can go, landing on the same foot each time. Swing your arms hard to help. This builds single-leg power and stability. If you lose your balance on landing, that tells you where to improve. Do all 3 on one leg, then switch.' },
        { name: 'Flying 40-Yard Sprint', sets: 4, reps: '40 yards at top speed', rest: '2:00 walk back', cues: 'Jog for 20 yards to build speed, then sprint 40 yards at your absolute maximum. Because you\'re already moving when you hit the sprint zone, you reach top speed faster. This is pure speed training — no acceleration phase to worry about. Focus on being smooth, relaxed, and fast. Your best sprint should feel effortless.' },
        { name: '150m Sprint', sets: 3, reps: '150m', rest: '2:30 walk', cues: 'Sprint 150m at 90-95% effort. By Week 4, this distance should feel more manageable than Week 2. If you\'re holding your form better in the last 50m, your speed endurance is improving. Keep pushing.' },
      ],
      cooldown: '5 min walk. Full stretch (30 sec each). Foam roll hamstrings and quads if available.',
    },

    // ──────────────────────────────────────────────
    // WEEK 5 — PEAK PERFORMANCE
    // ──────────────────────────────────────────────
    {
      day: 'Day 13',
      title: 'W5 · Acceleration',
      warmup: '20 min dynamic warmup — cover 15 yards for each drill down and back.\n\nWALKING MOBILITY\nKnee pulls ×15 yards (hug one knee to your chest each step) · Quad pulls ×15 yards (grab your ankle behind you and pull heel to glute each step) · Scoops ×15 yards (scoop your leg up and across your body each step to open your hips) · Straight leg marches ×15 yards (kick one leg straight up and reach for your toes) · Figure 4 ×15 yards (pull your ankle to opposite knee and sit into a small squat each step) · Adductor stretch ×15 yards (wide steps, shifting side to side) · Walking lunges ×15 yards · Pogo hops — double leg ×15 yards, then single leg ×15 yards each\n\nRUNNING DRILLS — 15 yards each\nSkips with arm circles · Backwards run · High knees · Butt kicks · A-skips (drive one knee up with a skip) · B-skips (extend your leg out after the knee drive) · C-skips (sweeping leg motion) · D-skips (exaggerated bounding) · Lateral shuffles · Power lateral shuffles (explosive push-off) · Karaoke (grapevine)\n\nSPEED PREP — 15 yards each\nAnkle-calf-knee dribbles (quick choppy steps focusing on each joint) · Strikes short and long (snap your foot down under your hip with a paw-back motion) · Fast leg right and left (rapid single-leg turnover)\n\nGROUND ACTIVATION\n10 scorpions on your back (lie face up, swing one leg across to touch the opposite hand) · 10 scorpions on your stomach (lie face down, swing one leg across behind you) · 10 hip thrusts (bridge up squeezing glutes) · 10 fire hydrants each leg (on all fours, lift knee out to the side) · 10 squat jumps · 10 head-hip-trunk rotations (standing, rotate through each segment)\n\nBUILD-UPS\n3 sprints at 70-80%\n\nCORRECTIONAL BAND WORK — 2×10 each\nBanded lateral walks · Monster walks · Backwards walks',
      duration: '50 min',
      sections: [{'name':'Sprints','start':0}],
      exercises: [
        { name: '10-Yard Starts — Competition', sets: 6, reps: '10 yards', rest: '1:00 walk back', cues: 'If you can, race someone on these. Competition brings out speed you didn\'t know you had. From your 3-point stance, explode on the signal. These 10-yard starts should feel automatic by now — low, powerful, aggressive. If you\'re training alone, imagine someone next to you and try to beat them every rep.' },
        { name: '40-Yard Dash — Best Effort', sets: 6, reps: '40 yards', rest: '2:30 walk back', cues: 'This is your peak 40-yard session. Extra rest between reps so you can give 100% on every one. At least one of these 6 reps should be your fastest 40 ever. Everything you\'ve trained — starts, acceleration, arm drive, relaxation — put it all together. Time every rep. Your body is at its peak speed this week.' },
        { name: '60-Yard Sprint', sets: 4, reps: '60 yards', rest: '2:00 walk back', cues: 'Explode through 40 yards, then hold top speed for another 20. The 60 is where true speed shows. If you can hold your 40-yard speed through 60 yards, you are genuinely fast. Focus on relaxing at top speed — loose hands, relaxed face, smooth arm swings.' },
      ],
      cooldown: '5 min easy jog. Full stretch. Record your times — these are your benchmarks.',
    },
    {
      day: 'Day 14',
      title: 'W5 · Speed Endurance',
      warmup: '20 min dynamic warmup — cover 15 yards for each drill down and back.\n\nWALKING MOBILITY\nKnee pulls ×15 yards (hug one knee to your chest each step) · Quad pulls ×15 yards (grab your ankle behind you and pull heel to glute each step) · Scoops ×15 yards (scoop your leg up and across your body each step to open your hips) · Straight leg marches ×15 yards (kick one leg straight up and reach for your toes) · Figure 4 ×15 yards (pull your ankle to opposite knee and sit into a small squat each step) · Adductor stretch ×15 yards (wide steps, shifting side to side) · Walking lunges ×15 yards · Pogo hops — double leg ×15 yards, then single leg ×15 yards each\n\nRUNNING DRILLS — 15 yards each\nSkips with arm circles · Backwards run · High knees · Butt kicks · A-skips (drive one knee up with a skip) · B-skips (extend your leg out after the knee drive) · C-skips (sweeping leg motion) · D-skips (exaggerated bounding) · Lateral shuffles · Power lateral shuffles (explosive push-off) · Karaoke (grapevine)\n\nSPEED PREP — 15 yards each\nAnkle-calf-knee dribbles (quick choppy steps focusing on each joint) · Strikes short and long (snap your foot down under your hip with a paw-back motion) · Fast leg right and left (rapid single-leg turnover)\n\nGROUND ACTIVATION\n10 scorpions on your back (lie face up, swing one leg across to touch the opposite hand) · 10 scorpions on your stomach (lie face down, swing one leg across behind you) · 10 hip thrusts (bridge up squeezing glutes) · 10 fire hydrants each leg (on all fours, lift knee out to the side) · 10 squat jumps · 10 head-hip-trunk rotations (standing, rotate through each segment)\n\nBUILD-UPS\n3 sprints at 70-80%\n\nCORRECTIONAL BAND WORK — 2×10 each\nBanded lateral walks · Monster walks · Backwards walks',
      duration: '55 min',
      sections: [{'name':'Speed Endurance','start':0}],
      exercises: [
        { name: '200m Sprint — Best Effort', sets: 4, reps: '200m', rest: '3:30 walk', cues: 'Peak 200m session. Time these if possible. Attack the curve, explode down the straight. By now you should feel confident over this distance. Each rep is a chance to prove how much faster you\'ve gotten over 5 weeks. Run through the finish line, not to it.' },
        { name: '300m Sprint', sets: 3, reps: '300m', rest: '3:30 walk', cues: 'The 300 is your endurance test. 85-90% effort. The first 200m should feel controlled, the last 100m is where you compete. Against the clock, against the pain, against the voice telling you to slow down. Hold your form. Drive your arms. You\'re almost through the hardest training of the program.' },
        { name: '400m Sprint — Best Effort', sets: 2, reps: '400m', rest: '4:00 walk', cues: 'Peak 400m session. Full lap. Go out controlled for the first 200m (don\'t sprint all-out from the start — that\'s a common mistake that kills your finish). The second 200m is where you race. The last 100m will test everything you\'ve built. When your legs feel like concrete, your arms do the work — pump them hard and your legs will follow. Time these and remember the feeling. This is what competing feels like.' },
      ],
      cooldown: '5 min easy jog. Full stretch. Record your times. Hydrate and eat well — next week is taper.',
    },
    {
      day: 'Day 15',
      title: 'W5 · Power & Agility',
      warmup: '20 min dynamic warmup — cover 15 yards for each drill down and back.\n\nWALKING MOBILITY\nKnee pulls ×15 yards (hug one knee to your chest each step) · Quad pulls ×15 yards (grab your ankle behind you and pull heel to glute each step) · Scoops ×15 yards (scoop your leg up and across your body each step to open your hips) · Straight leg marches ×15 yards (kick one leg straight up and reach for your toes) · Figure 4 ×15 yards (pull your ankle to opposite knee and sit into a small squat each step) · Adductor stretch ×15 yards (wide steps, shifting side to side) · Walking lunges ×15 yards · Pogo hops — double leg ×15 yards, then single leg ×15 yards each\n\nRUNNING DRILLS — 15 yards each\nSkips with arm circles · Backwards run · High knees · Butt kicks · A-skips (drive one knee up with a skip) · B-skips (extend your leg out after the knee drive) · C-skips (sweeping leg motion) · D-skips (exaggerated bounding) · Lateral shuffles · Power lateral shuffles (explosive push-off) · Karaoke (grapevine)\n\nSPEED PREP — 15 yards each\nAnkle-calf-knee dribbles (quick choppy steps focusing on each joint) · Strikes short and long (snap your foot down under your hip with a paw-back motion) · Fast leg right and left (rapid single-leg turnover)\n\nGROUND ACTIVATION\n10 scorpions on your back (lie face up, swing one leg across to touch the opposite hand) · 10 scorpions on your stomach (lie face down, swing one leg across behind you) · 10 hip thrusts (bridge up squeezing glutes) · 10 fire hydrants each leg (on all fours, lift knee out to the side) · 10 squat jumps · 10 head-hip-trunk rotations (standing, rotate through each segment)\n\nBUILD-UPS\n3 sprints at 70-80%\n\nCORRECTIONAL BAND WORK — 2×10 each\nBanded lateral walks · Monster walks · Backwards walks',
      duration: '50 min',
      sections: [{'name':'Power','start':0},{'name':'Agility','start':1},{'name':'Speed Endurance','start':2}],
      exercises: [
        { name: 'Depth Jump to 20-Yard Sprint', sets: 5, reps: '1 rep', rest: '2:00', cues: 'Step off a box (12-18 inches), land on both feet, and instantly explode into a 20-yard sprint. Spend as little time on the ground as possible after landing. Your muscles store energy during the landing and release it during the sprint — like a coiled spring. This is peak reactive power training. Walk back to rest fully.' },
        { name: 'Pro Agility (5-10-5) — Timed', sets: 5, reps: '1 full rep', rest: '2:00', cues: 'Time these and compare to Week 2. Same drill: start at the middle cone, sprint 5 yards, touch, sprint 10 yards, touch, sprint 5 yards back. Stay low on every cut. Plant hard and explode out. Your change-of-direction speed should be noticeably better than Week 2.' },
        { name: 'Flying 40-Yard Sprint', sets: 5, reps: '40 yards at max', rest: '2:00 walk back', cues: 'Jog 20 yards, then hit your absolute top speed for 40 yards. One more rep than Week 4. These should feel fast and effortless. If sprinting is starting to feel natural and smooth, that means the training is working. You\'re faster than when you started.' },
      ],
      cooldown: '5 min walk. Full stretch. Foam roll if available. Last hard week is done — taper week is next.',
    },

    // ──────────────────────────────────────────────
    // WEEK 6 — TAPER & TEST
    // ──────────────────────────────────────────────
    {
      day: 'Day 16',
      title: 'W6 · Speed Sharpening',
      warmup: '20 min dynamic warmup — cover 15 yards for each drill down and back.\n\nWALKING MOBILITY\nKnee pulls ×15 yards (hug one knee to your chest each step) · Quad pulls ×15 yards (grab your ankle behind you and pull heel to glute each step) · Scoops ×15 yards (scoop your leg up and across your body each step to open your hips) · Straight leg marches ×15 yards (kick one leg straight up and reach for your toes) · Figure 4 ×15 yards (pull your ankle to opposite knee and sit into a small squat each step) · Adductor stretch ×15 yards (wide steps, shifting side to side) · Walking lunges ×15 yards · Pogo hops — double leg ×15 yards, then single leg ×15 yards each\n\nRUNNING DRILLS — 15 yards each\nSkips with arm circles · Backwards run · High knees · Butt kicks · A-skips (drive one knee up with a skip) · B-skips (extend your leg out after the knee drive) · C-skips (sweeping leg motion) · D-skips (exaggerated bounding) · Lateral shuffles · Power lateral shuffles (explosive push-off) · Karaoke (grapevine)\n\nSPEED PREP — 15 yards each\nAnkle-calf-knee dribbles (quick choppy steps focusing on each joint) · Strikes short and long (snap your foot down under your hip with a paw-back motion) · Fast leg right and left (rapid single-leg turnover)\n\nGROUND ACTIVATION\n10 scorpions on your back (lie face up, swing one leg across to touch the opposite hand) · 10 scorpions on your stomach (lie face down, swing one leg across behind you) · 10 hip thrusts (bridge up squeezing glutes) · 10 fire hydrants each leg (on all fours, lift knee out to the side) · 10 squat jumps · 10 head-hip-trunk rotations (standing, rotate through each segment)\n\nBUILD-UPS\n3 sprints at 70-80%\n\nCORRECTIONAL BAND WORK — 2×10 each\nBanded lateral walks · Monster walks · Backwards walks',
      duration: '40 min',
      sections: [{'name':'Sprints','start':0}],
      exercises: [
        { name: '10-Yard Starts', sets: 4, reps: '10 yards', rest: '1:00 walk back', cues: 'Just 4 reps — keep the starts feeling explosive and sharp. This is taper week: your muscles have recovered from 5 weeks of hard training and you should feel springy and powerful. Don\'t overthink it — just explode.' },
        { name: '40-Yard Dash', sets: 3, reps: '40 yards', rest: '2:30 walk back', cues: 'Only 3 reps with generous rest. These should feel fast — possibly your fastest ever. Your body has been training for 5 weeks and is at its peak right now. Enjoy how smooth and powerful your sprinting feels. If you\'re testing for a combine, tryout, or race, this is what peak performance feels like.' },
        { name: 'Flying 60-Yard Sprint', sets: 3, reps: '60 yards at max', rest: '2:00 walk back', cues: 'Jog 20 yards in, then 60 yards at top speed. Fewer reps, maximum quality. Every stride should feel smooth and effortless. This is the speed you built over 6 weeks. Trust it.' },
      ],
      cooldown: '5 min easy jog. Gentle stretch (20-30 sec each). Save your legs.',
    },
    {
      day: 'Day 17',
      title: 'W6 · Speed Endurance Tune-Up',
      warmup: '20 min dynamic warmup — cover 15 yards for each drill down and back.\n\nWALKING MOBILITY\nKnee pulls ×15 yards (hug one knee to your chest each step) · Quad pulls ×15 yards (grab your ankle behind you and pull heel to glute each step) · Scoops ×15 yards (scoop your leg up and across your body each step to open your hips) · Straight leg marches ×15 yards (kick one leg straight up and reach for your toes) · Figure 4 ×15 yards (pull your ankle to opposite knee and sit into a small squat each step) · Adductor stretch ×15 yards (wide steps, shifting side to side) · Walking lunges ×15 yards · Pogo hops — double leg ×15 yards, then single leg ×15 yards each\n\nRUNNING DRILLS — 15 yards each\nSkips with arm circles · Backwards run · High knees · Butt kicks · A-skips (drive one knee up with a skip) · B-skips (extend your leg out after the knee drive) · C-skips (sweeping leg motion) · D-skips (exaggerated bounding) · Lateral shuffles · Power lateral shuffles (explosive push-off) · Karaoke (grapevine)\n\nSPEED PREP — 15 yards each\nAnkle-calf-knee dribbles (quick choppy steps focusing on each joint) · Strikes short and long (snap your foot down under your hip with a paw-back motion) · Fast leg right and left (rapid single-leg turnover)\n\nGROUND ACTIVATION\n10 scorpions on your back (lie face up, swing one leg across to touch the opposite hand) · 10 scorpions on your stomach (lie face down, swing one leg across behind you) · 10 hip thrusts (bridge up squeezing glutes) · 10 fire hydrants each leg (on all fours, lift knee out to the side) · 10 squat jumps · 10 head-hip-trunk rotations (standing, rotate through each segment)\n\nBUILD-UPS\n3 sprints at 70-80%\n\nCORRECTIONAL BAND WORK — 2×10 each\nBanded lateral walks · Monster walks · Backwards walks',
      duration: '38 min',
      sections: [{'name':'Speed Endurance','start':0}],
      exercises: [
        { name: '200m Sprint', sets: 2, reps: '200m', rest: '3:00 walk', cues: 'Just 2 reps. Run with confidence — the hard training is done. These are about reminding your body what 200m speed feels like. Should feel surprisingly smooth and fast. Don\'t strain — let the speed come to you.' },
        { name: '100m Sprint', sets: 3, reps: '100m', rest: '2:00 walk back', cues: '3 reps at 95% effort. Short, sharp, fast. Your 100m should feel completely different than Week 1 — more powerful, more controlled, more confident. That\'s the result of 6 weeks of training. Enjoy it.' },
      ],
      cooldown: '5 min walk. Gentle stretch. Focus on sleep this week — 8+ hours.',
    },
    {
      day: 'Day 18',
      title: 'W6 · Test Day',
      warmup: '20 min dynamic warmup — cover 15 yards for each drill down and back.\n\nWALKING MOBILITY\nKnee pulls ×15 yards (hug one knee to your chest each step) · Quad pulls ×15 yards (grab your ankle behind you and pull heel to glute each step) · Scoops ×15 yards (scoop your leg up and across your body each step to open your hips) · Straight leg marches ×15 yards (kick one leg straight up and reach for your toes) · Figure 4 ×15 yards (pull your ankle to opposite knee and sit into a small squat each step) · Adductor stretch ×15 yards (wide steps, shifting side to side) · Walking lunges ×15 yards · Pogo hops — double leg ×15 yards, then single leg ×15 yards each\n\nRUNNING DRILLS — 15 yards each\nSkips with arm circles · Backwards run · High knees · Butt kicks · A-skips (drive one knee up with a skip) · B-skips (extend your leg out after the knee drive) · C-skips (sweeping leg motion) · D-skips (exaggerated bounding) · Lateral shuffles · Power lateral shuffles (explosive push-off) · Karaoke (grapevine)\n\nSPEED PREP — 15 yards each\nAnkle-calf-knee dribbles (quick choppy steps focusing on each joint) · Strikes short and long (snap your foot down under your hip with a paw-back motion) · Fast leg right and left (rapid single-leg turnover)\n\nGROUND ACTIVATION\n10 scorpions on your back (lie face up, swing one leg across to touch the opposite hand) · 10 scorpions on your stomach (lie face down, swing one leg across behind you) · 10 hip thrusts (bridge up squeezing glutes) · 10 fire hydrants each leg (on all fours, lift knee out to the side) · 10 squat jumps · 10 head-hip-trunk rotations (standing, rotate through each segment)\n\nBUILD-UPS\n3 sprints at 70-80%\n\nCORRECTIONAL BAND WORK — 2×10 each\nBanded lateral walks · Monster walks · Backwards walks',
      duration: '40 min',
      sections: [{'name':'Testing','start':0}],
      exercises: [
        { name: '40-Yard Dash — Final Test', sets: 3, reps: '40 yards', rest: '3:00 walk back', cues: 'This is it. 3 reps, full rest, best effort. Time every single one. Your fastest rep today is your result — compare it to your Week 3 baseline. You are faster than when you started. Everything you trained — starts, acceleration, top speed, arm drive, relaxation — put it all together one last time. Run with confidence. Sprint through the finish.' },
        { name: '100m Sprint — Final Test', sets: 2, reps: '100m', rest: '3:00 walk back', cues: 'Full 100m test. 2 reps, best effort. Accelerate hard, hit top speed, and hold it through the line. Time it and own it. Compare to Week 1 if you have a time. 6 weeks of work just paid off.' },
        { name: '200m Sprint — Final Test', sets: 2, reps: '200m', rest: '3:00 walk', cues: 'Last test of the program. 2 reps, best effort. Attack the curve, explode down the straight, and finish strong. Time it. This is your showcase. You put in the work. You got faster. Now you have the numbers to prove it. Go compete.' },
      ],
      cooldown: 'Walk 5 min. Full stretch — celebrate. Record all your times. Compare to your earlier weeks. You\'re faster, more explosive, and more confident than when you started. That\'s what 6 weeks of sprint training does.',
    },
  ],
}
